-- Title: DNS Query To AzureWebsites.NET By Non-Browser Process
-- ID: e043f529-8514-4205-8ab0-7f7d2927b400
-- Status: test
-- Level: medium
-- Author: Nasreddine Bencherchali (Nextron Systems)
-- Date: 2024-06-24
-- Tags: attack.command-and-control, attack.t1219.002
-- Description: Detects a DNS query by a non browser process on the system to "azurewebsites.net". The latter was often used by threat actors as a malware hosting and exfiltration site.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE ((QueryName ILIKE '%azurewebsites.net') AND NOT ((((Image ILIKE 'C:\\Program Files (x86)\\Avant Browser\\%' OR Image ILIKE 'C:\\Program Files\\Avant Browser\\%') AND Image ILIKE '%\\avant.exe') OR (Image ILIKE '%\\brave.exe' AND Image ILIKE 'C:\\Program Files\\BraveSoftware\\%') OR ((Image = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' OR Image = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe')) OR ((Image ILIKE '%\\MsMpEng.exe' OR Image ILIKE '%\\MsSense.exe')) OR ((Image ILIKE 'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\%') OR (Image ILIKE '%\\WindowsApps\\MicrosoftEdge.exe') OR ((Image = 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe' OR Image = 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe'))) OR ((Image ILIKE 'C:\\Program Files (x86)\\Microsoft\\EdgeCore\\%' OR Image ILIKE 'C:\\Program Files\\Microsoft\\EdgeCore\\%') AND (Image ILIKE '%\\msedge.exe' OR Image ILIKE '%\\msedgewebview2.exe')) OR ((Image ILIKE 'C:\\Program Files\\Falkon\\%' OR Image ILIKE 'C:\\Program Files (x86)\\Falkon\\%') AND Image ILIKE '%\\falkon.exe') OR ((Image = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe' OR Image = 'C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe')) OR (Image ILIKE '%\\AppData\\Local\\Flock\\%' AND Image ILIKE '%\\Flock.exe') OR ((Image = 'C:\\Program Files (x86)\\Internet Explorer\\iexplore.exe' OR Image = 'C:\\Program Files\\Internet Explorer\\iexplore.exe')) OR (Image ILIKE '%\\AppData\\Local\\Maxthon\\%' AND Image ILIKE '%\\maxthon.exe') OR (Image ILIKE '%\\AppData\\Local\\Programs\\midori-ng\\%' AND Image ILIKE '%\\Midori Next Generation.exe') OR (Image ILIKE '%\\AppData\\Local\\Programs\\Opera\\%' AND Image ILIKE '%\\opera.exe') OR (Image ILIKE '%\\AppData\\Local\\Phoebe\\%' AND Image ILIKE '%\\Phoebe.exe') OR (Image ILIKE '%\\safari.exe') OR ((Image ILIKE 'C:\\Program Files\\SeaMonkey\\%' OR Image ILIKE 'C:\\Program Files (x86)\\SeaMonkey\\%') AND Image ILIKE '%\\seamonkey.exe') OR ((Image ILIKE 'C:\\Program Files\\SlimBrowser\\%' OR Image ILIKE 'C:\\Program Files (x86)\\SlimBrowser\\%') AND Image ILIKE '%\\slimbrowser.exe') OR (Image ILIKE '%\\Tor Browser\\%') OR (Image ILIKE '%\\AppData\\Local\\Vivaldi\\%' AND Image ILIKE '%\\vivaldi.exe') OR ((Image ILIKE 'C:\\Program Files\\Naver\\Naver Whale\\%' OR Image ILIKE 'C:\\Program Files (x86)\\Naver\\Naver Whale\\%') AND Image ILIKE '%\\whale.exe') OR ((Image ILIKE 'C:\\Program Files\\Waterfox\\%' OR Image ILIKE 'C:\\Program Files (x86)\\Waterfox\\%') AND Image ILIKE '%\\Waterfox.exe'))))
