-- Title: Suspicious DNS Query for IP Lookup Service APIs
-- ID: ec82e2a5-81ea-4211-a1f8-37a0286df2c2
-- Status: test
-- Level: medium
-- Author: Brandon George (blog post), Thomas Patzke
-- Date: 2021-07-08
-- Tags: attack.reconnaissance, attack.t1590
-- Description: Detects DNS queries for IP lookup services such as "api.ipify.org" originating from a non browser process.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE ((((QueryName = 'www.ip.cn' OR QueryName = 'l2.io')) OR ((QueryName ILIKE '%api.2ip.ua%' OR QueryName ILIKE '%api.bigdatacloud.net%' OR QueryName ILIKE '%api.ipify.org%' OR QueryName ILIKE '%bot.whatismyipaddress.com%' OR QueryName ILIKE '%canireachthe.net%' OR QueryName ILIKE '%checkip.amazonaws.com%' OR QueryName ILIKE '%checkip.dyndns.org%' OR QueryName ILIKE '%curlmyip.com%' OR QueryName ILIKE '%db-ip.com%' OR QueryName ILIKE '%edns.ip-api.com%' OR QueryName ILIKE '%eth0.me%' OR QueryName ILIKE '%freegeoip.app%' OR QueryName ILIKE '%geoipy.com%' OR QueryName ILIKE '%getip.pro%' OR QueryName ILIKE '%icanhazip.com%' OR QueryName ILIKE '%ident.me%' OR QueryName ILIKE '%ifconfig.io%' OR QueryName ILIKE '%ifconfig.me%' OR QueryName ILIKE '%ip-api.com%' OR QueryName ILIKE '%ip.360.cn%' OR QueryName ILIKE '%ip.anysrc.net%' OR QueryName ILIKE '%ip.taobao.com%' OR QueryName ILIKE '%ip.tyk.nu%' OR QueryName ILIKE '%ipaddressworld.com%' OR QueryName ILIKE '%ipapi.co%' OR QueryName ILIKE '%ipconfig.io%' OR QueryName ILIKE '%ipecho.net%' OR QueryName ILIKE '%ipinfo.io%' OR QueryName ILIKE '%ipip.net%' OR QueryName ILIKE '%ipof.in%' OR QueryName ILIKE '%ipv4.icanhazip.com%' OR QueryName ILIKE '%ipv4bot.whatismyipaddress.com%' OR QueryName ILIKE '%ipv6-test.com%' OR QueryName ILIKE '%ipwho.is%' OR QueryName ILIKE '%jsonip.com%' OR QueryName ILIKE '%myexternalip.com%' OR QueryName ILIKE '%seeip.org%' OR QueryName ILIKE '%wgetip.com%' OR QueryName ILIKE '%whatismyip.akamai.com%' OR QueryName ILIKE '%whois.pconline.com.cn%' OR QueryName ILIKE '%wtfismyip.com%'))) AND NOT (((Image ILIKE '%\\brave.exe') OR ((Image = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' OR Image = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe')) OR ((Image ILIKE 'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\%') OR (Image ILIKE '%\\WindowsApps\\MicrosoftEdge.exe') OR ((Image = 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe' OR Image = 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe'))) OR ((Image ILIKE 'C:\\Program Files (x86)\\Microsoft\\EdgeCore\\%' OR Image ILIKE 'C:\\Program Files\\Microsoft\\EdgeCore\\%') AND (Image ILIKE '%\\msedge.exe' OR Image ILIKE '%\\msedgewebview2.exe')) OR ((Image = 'C:\\Program Files\\Mozilla Firefox\\firefox.exe' OR Image = 'C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe')) OR ((Image = 'C:\\Program Files (x86)\\Internet Explorer\\iexplore.exe' OR Image = 'C:\\Program Files\\Internet Explorer\\iexplore.exe')) OR (Image ILIKE '%\\maxthon.exe') OR (Image ILIKE '%\\opera.exe') OR (Image ILIKE '%\\safari.exe') OR (Image ILIKE '%\\seamonkey.exe') OR (Image ILIKE '%\\vivaldi.exe') OR (Image ILIKE '%\\whale.exe'))))
