-- Title: PowerShell Core DLL Loaded By Non PowerShell Process
-- ID: 092bc4b9-3d1d-43b4-a6b4-8c8acd83522f
-- Status: test
-- Level: medium
-- Author: Tom Kern, oscd.community, Natalia Shornikova, Tim Shelton, Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
-- Date: 2019-11-14
-- Tags: attack.t1059.001, attack.execution
-- Description: Detects loading of essential DLLs used by PowerShell by non-PowerShell process.
-- Detects behavior similar to meterpreter's "load powershell" extension.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE (((Description = 'System.Management.Automation') OR (OriginalFileName = 'System.Management.Automation.dll') OR ((ImageLoaded ILIKE '%\\System.Management.Automation.dll' OR ImageLoaded ILIKE '%\\System.Management.Automation.ni.dll'))) AND NOT ((((Image ILIKE 'C:\\Windows\\Microsoft.NET\\Framework\\%' OR Image ILIKE 'C:\\Windows\\Microsoft.NET\\FrameworkArm\\%' OR Image ILIKE 'C:\\Windows\\Microsoft.NET\\FrameworkArm64\\%' OR Image ILIKE 'C:\\Windows\\Microsoft.NET\\Framework64\\%') AND Image ILIKE '%\\mscorsvw.exe') OR ((Image = 'C:\\Windows\\System32\\dsac.exe' OR Image = 'C:\\WINDOWS\\System32\\RemoteFXvGPUDisablement.exe' OR Image = 'C:\\Windows\\System32\\runscripthelper.exe' OR Image = 'C:\\WINDOWS\\System32\\sdiagnhost.exe' OR Image = 'C:\\Windows\\System32\\ServerManager.exe' OR Image = 'C:\\Windows\\System32\\SyncAppvPublishingServer.exe' OR Image = 'C:\\Windows\\System32\\winrshost.exe' OR Image = 'C:\\Windows\\System32\\wsmprovhost.exe' OR Image = 'C:\\Windows\\SysWOW64\\winrshost.exe' OR Image = 'C:\\Windows\\SysWOW64\\wsmprovhost.exe')) OR ((Image = 'C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe' OR Image = 'C:\\Program Files\\PowerShell\\7\\pwsh.exe' OR Image = 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe' OR Image = 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe' OR Image = 'C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell_ise.exe' OR Image = 'C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe')) OR ((Image ILIKE '%C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview%' OR Image ILIKE '%\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShellPreview%') AND Image ILIKE '%\\pwsh.exe'))) AND NOT (((Image IS NULL) OR (Image ILIKE 'C:\\ProgramData\\chocolatey\\choco.exe%') OR (Image ILIKE '%\\Citrix\\ConfigSync\\ConfigSyncRun.exe') OR (Image ILIKE 'C:\\Program Files\\WindowsApps\\Microsoft.GetHelp_%' AND Image ILIKE '%\\GetHelp.exe') OR (Image ILIKE 'C:\\Windows\\Temp\\asgard2-agent\\%' AND (Image ILIKE '%\\thor64.exe' OR Image ILIKE '%\\thor.exe')) OR ((Image ILIKE 'C:\\Program Files (x86)\\Microsoft SQL Server Management Studio%' OR Image ILIKE 'C:\\Program Files\\Microsoft SQL Server Management Studio%') AND Image ILIKE '%\\IDE\\Ssms.exe') OR ((Image ILIKE 'C:\\Program Files (x86)\\Microsoft SQL Server\\%' OR Image ILIKE 'C:\\Program Files\\Microsoft SQL Server\\%') AND Image ILIKE '%\\Tools\\Binn\\SQLPS.exe') OR ((Image ILIKE 'C:\\Program Files (x86)\\Microsoft Visual Studio\\%' OR Image ILIKE 'C:\\Program Files\\Microsoft Visual Studio\\%')))))
