-- Title: Network Communication Initiated To File Sharing Domains From Process Located In Suspicious Folder
-- ID: e0f8ab85-0ac9-423b-a73a-81b3c7b1aa97
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
-- Date: 2018-08-30
-- Tags: attack.command-and-control, attack.t1105
-- Description: Detects executables located in potentially suspicious directories initiating network connections towards file sharing domains.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE ((Initiated = 'true' AND (DestinationHostname ILIKE '%.githubusercontent.com' OR DestinationHostname ILIKE '%0x0.st' OR DestinationHostname ILIKE '%anonfiles.com' OR DestinationHostname ILIKE '%bashupload.com' OR DestinationHostname ILIKE '%cdn.discordapp.com' OR DestinationHostname ILIKE '%chunk.io' OR DestinationHostname ILIKE '%ddns.net' OR DestinationHostname ILIKE '%dl.dropboxusercontent.com' OR DestinationHostname ILIKE '%ghostbin.co' OR DestinationHostname ILIKE '%github.com' OR DestinationHostname ILIKE '%glitch.me' OR DestinationHostname ILIKE '%gofile.io' OR DestinationHostname ILIKE '%hastebin.com' OR DestinationHostname ILIKE '%mediafire.com' OR DestinationHostname ILIKE '%mega.co.nz' OR DestinationHostname ILIKE '%mega.nz' OR DestinationHostname ILIKE '%onrender.com' OR DestinationHostname ILIKE '%pages.dev' OR DestinationHostname ILIKE '%paste.ee' OR DestinationHostname ILIKE '%pastebin.com' OR DestinationHostname ILIKE '%pastebin.pl' OR DestinationHostname ILIKE '%pastetext.net' OR DestinationHostname ILIKE '%pixeldrain.com' OR DestinationHostname ILIKE '%privatlab.com' OR DestinationHostname ILIKE '%privatlab.net' OR DestinationHostname ILIKE '%send.exploit.in' OR DestinationHostname ILIKE '%sendspace.com' OR DestinationHostname ILIKE '%storage.googleapis.com' OR DestinationHostname ILIKE '%storjshare.io' OR DestinationHostname ILIKE '%supabase.co' OR DestinationHostname ILIKE '%temp.sh' OR DestinationHostname ILIKE '%transfer.sh' OR DestinationHostname ILIKE '%trycloudflare.com' OR DestinationHostname ILIKE '%ufile.io' OR DestinationHostname ILIKE '%w3spaces.com' OR DestinationHostname ILIKE '%workers.dev' OR DestinationHostname ILIKE '%x0.at')) AND ((Image ILIKE '%:\\$Recycle.bin%' OR Image ILIKE '%:\\Perflogs\\%' OR Image ILIKE '%:\\Temp\\%' OR Image ILIKE '%:\\Users\\Default\\%' OR Image ILIKE '%:\\Users\\Public\\%' OR Image ILIKE '%:\\Windows\\Fonts\\%' OR Image ILIKE '%:\\Windows\\IME\\%' OR Image ILIKE '%:\\Windows\\System32\\Tasks\\%' OR Image ILIKE '%:\\Windows\\Tasks\\%' OR Image ILIKE '%:\\Windows\\Temp\\%' OR Image ILIKE '%\\AppData\\Temp\\%' OR Image ILIKE '%\\config\\systemprofile\\%' OR Image ILIKE '%\\Windows\\addins\\%')))
