-- Title: Invoke-Obfuscation Obfuscated IEX Invocation - PowerShell Module
-- ID: 2f211361-7dce-442d-b78a-c04039677378
-- Status: test
-- Level: high
-- Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
-- Date: 2019-11-08
-- Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
-- Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the code block cited in the reference section below
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE ((REGEXP_LIKE(Payload, '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[')) OR (REGEXP_LIKE(Payload, '\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[')) OR (REGEXP_LIKE(Payload, '\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[')) OR (REGEXP_LIKE(Payload, '\$env:ComSpec\[(\s*\d{1,3}\s*,){2}')) OR (REGEXP_LIKE(Payload, '\*mdr\*\W\s*\)\.Name')) OR (REGEXP_LIKE(Payload, '\$VerbosePreference\.ToString\(')) OR (REGEXP_LIKE(Payload, '\[String\]\s*\$VerbosePreference')))
