-- Title: Potentially Suspicious EventLog Recon Activity Using Log Query Utilities
-- ID: beaa66d6-aa1b-4e3c-80f5-e0145369bfaf
-- Status: test
-- Level: medium
-- Author: Nasreddine Bencherchali (Nextron Systems), X__Junior (Nextron Systems)
-- Date: 2022-09-09
-- Tags: attack.credential-access, attack.discovery, attack.t1552, attack.t1087
-- Description: Detects execution of different log query utilities and commands to search and dump the content of specific event logs or look for specific event IDs.
-- This technique is used by threat actors in order to extract sensitive information from events logs such as usernames, IP addresses, hostnames, etc.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE ((((CommandLine ILIKE '%-InstanceId 462?%' OR CommandLine ILIKE '%.eventid -eq 462?%' OR CommandLine ILIKE '%.ID -eq 462?%' OR CommandLine ILIKE '%EventCode=?462?%' OR CommandLine ILIKE '%EventIdentifier=?462?%' OR CommandLine ILIKE '%System[EventID=462?]%' OR CommandLine ILIKE '%-InstanceId 4778%' OR CommandLine ILIKE '%.eventid -eq 4778%' OR CommandLine ILIKE '%.ID -eq 4778%' OR CommandLine ILIKE '%EventCode=?4778?%' OR CommandLine ILIKE '%EventIdentifier=?4778?%' OR CommandLine ILIKE '%System[EventID=4778]%' OR CommandLine ILIKE '%-InstanceId 25%' OR CommandLine ILIKE '%.eventid -eq 25%' OR CommandLine ILIKE '%.ID -eq 25%' OR CommandLine ILIKE '%EventCode=?25?%' OR CommandLine ILIKE '%EventIdentifier=?25?%' OR CommandLine ILIKE '%System[EventID=25]%' OR CommandLine ILIKE '%-InstanceId 1149%' OR CommandLine ILIKE '%.eventid -eq 1149%' OR CommandLine ILIKE '%.ID -eq 1149%' OR CommandLine ILIKE '%EventCode=?1149?%' OR CommandLine ILIKE '%EventIdentifier=?1149?%' OR CommandLine ILIKE '%System[EventID=1149]%' OR CommandLine ILIKE '%-InstanceId 21%' OR CommandLine ILIKE '%.eventid -eq 21%' OR CommandLine ILIKE '%.ID -eq 21%' OR CommandLine ILIKE '%EventCode=?21?%' OR CommandLine ILIKE '%EventIdentifier=?21?%' OR CommandLine ILIKE '%System[EventID=21]%' OR CommandLine ILIKE '%-InstanceId 22%' OR CommandLine ILIKE '%.eventid -eq 22%' OR CommandLine ILIKE '%.ID -eq 22%' OR CommandLine ILIKE '%EventCode=?22?%' OR CommandLine ILIKE '%EventIdentifier=?22?%' OR CommandLine ILIKE '%System[EventID=22]%')) OR ((CommandLine ILIKE '%Microsoft-Windows-PowerShell%' OR CommandLine ILIKE '%Microsoft-Windows-Security-Auditing%' OR CommandLine ILIKE '%Microsoft-Windows-TerminalServices-LocalSessionManager%' OR CommandLine ILIKE '%Microsoft-Windows-TerminalServices-RemoteConnectionManager%' OR CommandLine ILIKE '%Microsoft-Windows-Windows Defender%' OR CommandLine ILIKE '%PowerShellCore%' OR CommandLine ILIKE '%Security%' OR CommandLine ILIKE '%Windows PowerShell%'))) AND (((CommandLine ILIKE '%Select%' AND CommandLine ILIKE '%Win32_NTLogEvent%')) OR (((CommandLine ILIKE '% qe %' OR CommandLine ILIKE '% query-events %')) AND ((Image ILIKE '%\\wevtutil.exe') OR (OriginalFileName = 'wevtutil.exe'))) OR ((CommandLine ILIKE '% ntevent%') AND ((Image ILIKE '%\\wmic.exe') OR (OriginalFileName = 'wmic.exe'))) OR ((CommandLine ILIKE '%Get-WinEvent %' OR CommandLine ILIKE '%get-eventlog %'))))
