-- Title: Invoke-Obfuscation Obfuscated IEX Invocation
-- ID: 4bf943c6-5146-4273-98dd-e958fd1e3abf
-- Status: test
-- Level: high
-- Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
-- Date: 2019-11-08
-- Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
-- Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the following code block
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE ((REGEXP_LIKE(CommandLine, '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[')) OR (REGEXP_LIKE(CommandLine, '\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[')) OR (REGEXP_LIKE(CommandLine, '\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[')) OR (REGEXP_LIKE(CommandLine, '\$env:ComSpec\[(?:\s*\d{1,3}\s*,){2}')) OR (REGEXP_LIKE(CommandLine, '\*mdr\*\W\s*\)\.Name')) OR (REGEXP_LIKE(CommandLine, '\$VerbosePreference\.ToString\(')) OR (REGEXP_LIKE(CommandLine, '\[String\]\s*\$VerbosePreference')))
