-- Title: Windows Filtering Platform Blocked Connection From EDR Agent Binary
-- ID: bacf58c6-e199-4040-a94f-95dea0f1e45a
-- Status: test
-- Level: high
-- Author: @gott_cyber
-- Date: 2024-01-08
-- Tags: attack.defense-impairment, attack.t1685
-- Description: Detects a Windows Filtering Platform (WFP) blocked connection event involving common Endpoint Detection and Response (EDR) agents.
-- Adversaries may use WFP filters to prevent Endpoint Detection and Response (EDR) agents from reporting security events.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE (EventID = 5157 AND (Application ILIKE '%\\AmSvc.exe' OR Application ILIKE '%\\cb.exe' OR Application ILIKE '%\\CETASvc.exe' OR Application ILIKE '%\\CNTAoSMgr.exe' OR Application ILIKE '%\\CrAmTray.exe' OR Application ILIKE '%\\CrsSvc.exe' OR Application ILIKE '%\\CSFalconContainer.exe' OR Application ILIKE '%\\CSFalconService.exe' OR Application ILIKE '%\\CybereasonAV.exe' OR Application ILIKE '%\\CylanceSvc.exe' OR Application ILIKE '%\\cyserver.exe' OR Application ILIKE '%\\CyveraService.exe' OR Application ILIKE '%\\CyvrFsFlt.exe' OR Application ILIKE '%\\EIConnector.exe' OR Application ILIKE '%\\elastic-agent.exe' OR Application ILIKE '%\\elastic-endpoint.exe' OR Application ILIKE '%\\EndpointBasecamp.exe' OR Application ILIKE '%\\ExecutionPreventionSvc.exe' OR Application ILIKE '%\\filebeat.exe' OR Application ILIKE '%\\fortiedr.exe' OR Application ILIKE '%\\hmpalert.exe' OR Application ILIKE '%\\hurukai.exe' OR Application ILIKE '%\\LogProcessorService.exe' OR Application ILIKE '%\\mcsagent.exe' OR Application ILIKE '%\\mcsclient.exe' OR Application ILIKE '%\\MsMpEng.exe' OR Application ILIKE '%\\MsSense.exe' OR Application ILIKE '%\\Ntrtscan.exe' OR Application ILIKE '%\\PccNTMon.exe' OR Application ILIKE '%\\QualysAgent.exe' OR Application ILIKE '%\\RepMgr.exe' OR Application ILIKE '%\\RepUtils.exe' OR Application ILIKE '%\\RepUx.exe' OR Application ILIKE '%\\RepWAV.exe' OR Application ILIKE '%\\RepWSC.exe' OR Application ILIKE '%\\sedservice.exe' OR Application ILIKE '%\\SenseCncProxy.exe' OR Application ILIKE '%\\SenseIR.exe' OR Application ILIKE '%\\SenseNdr.exe' OR Application ILIKE '%\\SenseSampleUploader.exe' OR Application ILIKE '%\\SentinelAgent.exe' OR Application ILIKE '%\\SentinelAgentWorker.exe' OR Application ILIKE '%\\SentinelBrowserNativeHost.exe' OR Application ILIKE '%\\SentinelHelperService.exe' OR Application ILIKE '%\\SentinelServiceHost.exe' OR Application ILIKE '%\\SentinelStaticEngine.exe' OR Application ILIKE '%\\SentinelStaticEngineScanner.exe' OR Application ILIKE '%\\sfc.exe' OR Application ILIKE '%\\sophos ui.exe' OR Application ILIKE '%\\sophosfilescanner.exe' OR Application ILIKE '%\\sophosfs.exe' OR Application ILIKE '%\\sophoshealth.exe' OR Application ILIKE '%\\sophosips.exe' OR Application ILIKE '%\\sophosLivequeryservice.exe' OR Application ILIKE '%\\sophosnetfilter.exe' OR Application ILIKE '%\\sophosntpservice.exe' OR Application ILIKE '%\\sophososquery.exe' OR Application ILIKE '%\\sspservice.exe' OR Application ILIKE '%\\TaniumClient.exe' OR Application ILIKE '%\\TaniumCX.exe' OR Application ILIKE '%\\TaniumDetectEngine.exe' OR Application ILIKE '%\\TMBMSRV.exe' OR Application ILIKE '%\\TmCCSF.exe' OR Application ILIKE '%\\TmListen.exe' OR Application ILIKE '%\\TmWSCSvc.exe' OR Application ILIKE '%\\Traps.exe' OR Application ILIKE '%\\winlogbeat.exe' OR Application ILIKE '%\\WSCommunicator.exe' OR Application ILIKE '%\\xagt.exe'))
