-- Title: Invoke-Obfuscation Obfuscated IEX Invocation - Security
-- ID: fd0f5778-d3cb-4c9a-9695-66759d04702a
-- Status: test
-- Level: high
-- Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
-- Date: 2019-11-08
-- Tags: attack.stealth, attack.t1027
-- Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the code block linked in the references
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM security_logs WHERE ((EventID = 4697) AND ((REGEXP_LIKE(ServiceFileName, '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[')) OR (REGEXP_LIKE(ServiceFileName, '\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[')) OR (REGEXP_LIKE(ServiceFileName, '\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[')) OR (REGEXP_LIKE(ServiceFileName, '\$env:ComSpec\[(\s*\d{1,3}\s*,){2}')) OR (REGEXP_LIKE(ServiceFileName, '\\*mdr\*\W\s*\)\.Name')) OR (REGEXP_LIKE(ServiceFileName, '\$VerbosePreference\.ToString\(')) OR (REGEXP_LIKE(ServiceFileName, '\String\]\s*\$VerbosePreference'))))
