-- Title: PSScriptPolicyTest Creation By Uncommon Process
-- ID: 1027d292-dd87-4a1a-8701-2abe04d7783c
-- Status: test
-- Level: medium
-- Author: Nasreddine Bencherchali (Nextron Systems)
-- Date: 2023-06-01
-- Tags: attack.stealth
-- Description: Detects the creation of the "PSScriptPolicyTest" PowerShell script by an uncommon process. This file is usually generated by Microsoft Powershell to test against Applocker.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM file WHERE ((TargetFilename LIKE '%__PSScriptPolicyTest_%') AND NOT ((((Image = 'C:\\Windows\\System32\\dsac.exe' OR Image = 'C:\\Windows\\System32\\sdiagnhost.exe' OR Image = 'C:\\Windows\\System32\\ServerManager.exe' OR Image = 'C:\\Windows\\System32\\wsmprovhost.exe' OR Image = 'C:\\Windows\\SysWOW64\\sdiagnhost.exe')) OR ((Image = 'C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe' OR Image = 'C:\\Program Files\\PowerShell\\7\\pwsh.exe' OR Image = 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe' OR Image = 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe' OR Image = 'C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell_ise.exe' OR Image = 'C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe')) OR ((Image LIKE '%C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview%' OR Image LIKE '%\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShellPreview%') AND Image="*\\pwsh.exe"))) AND NOT ((Image="C:\\Program Files\\WindowsApps\\Microsoft.GetHelp_*" AND Image="*\\GetHelp.exe")))
