-- Title: HackTool - SafetyKatz Dump Indicator
-- ID: e074832a-eada-4fd7-94a1-10642b130e16
-- Status: test
-- Level: high
-- Author: Markus Neis
-- Date: 2018-07-24
-- Tags: attack.credential-access, attack.t1003.001
-- Description: Detects default lsass dump filename generated by SafetyKatz.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM file WHERE (TargetFilename="*\\Temp\\debug.bin")
