-- Title: Network Connection Initiated From Process Located In Potentially Suspicious Or Uncommon Location
-- ID: 7b434893-c57d-4f41-908d-6a17bf1ae98f
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
-- Date: 2017-03-19
-- Tags: attack.command-and-control, attack.t1105
-- Description: Detects a network connection initiated by programs or processes running from suspicious or uncommon files system locations.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM file WHERE ((Initiated = 'true' AND (Image LIKE '%:\\$Recycle.bin%' OR Image LIKE '%:\\Perflogs\\%' OR Image LIKE '%:\\Temp\\%' OR Image LIKE '%:\\Users\\Default\\%' OR Image LIKE '%:\\Users\\Public\\%' OR Image LIKE '%:\\Windows\\Fonts\\%' OR Image LIKE '%:\\Windows\\IME\\%' OR Image LIKE '%:\\Windows\\System32\\Tasks\\%' OR Image LIKE '%:\\Windows\\Tasks\\%' OR Image LIKE '%\\config\\systemprofile\\%' OR Image LIKE '%\\Contacts\\%' OR Image LIKE '%\\Favorites\\%' OR Image LIKE '%\\Favourites\\%' OR Image LIKE '%\\Music\\%' OR Image LIKE '%\\Pictures\\%' OR Image LIKE '%\\Videos\\%' OR Image LIKE '%\\Windows\\addins\\%')) AND NOT (((DestinationHostname="*.githubusercontent.com" OR DestinationHostname="*0x0.st" OR DestinationHostname="*anonfiles.com" OR DestinationHostname="*bashupload.com" OR DestinationHostname="*cdn.discordapp.com" OR DestinationHostname="*chunk.io" OR DestinationHostname="*ddns.net" OR DestinationHostname="*dl.dropboxusercontent.com" OR DestinationHostname="*ghostbin.co" OR DestinationHostname="*github.com" OR DestinationHostname="*glitch.me" OR DestinationHostname="*gofile.io" OR DestinationHostname="*hastebin.com" OR DestinationHostname="*mediafire.com" OR DestinationHostname="*mega.co.nz" OR DestinationHostname="*mega.nz" OR DestinationHostname="*onrender.com" OR DestinationHostname="*pages.dev" OR DestinationHostname="*paste.ee" OR DestinationHostname="*pastebin.com" OR DestinationHostname="*pastebin.pl" OR DestinationHostname="*pastetext.net" OR DestinationHostname="*portmap.io" OR DestinationHostname="*privatlab.com" OR DestinationHostname="*privatlab.net" OR DestinationHostname="*send.exploit.in" OR DestinationHostname="*sendspace.com" OR DestinationHostname="*storage.googleapis.com" OR DestinationHostname="*storjshare.io" OR DestinationHostname="*supabase.co" OR DestinationHostname="*temp.sh" OR DestinationHostname="*transfer.sh" OR DestinationHostname="*trycloudflare.com" OR DestinationHostname="*ufile.io" OR DestinationHostname="*w3spaces.com" OR DestinationHostname="*workers.dev" OR DestinationHostname="*x0.at"))))
