-- Title: Tamper Windows Defender - ScriptBlockLogging
-- ID: 14c71865-6cd3-44ae-adaa-1db923fae5f2
-- Status: test
-- Level: high
-- Author: frack113, elhoim, Tim Shelton (fps, alias support), Swachchhanda Shrawan Poudel, Nasreddine Bencherchali (Nextron Systems)
-- Date: 2022-01-16
-- Tags: attack.defense-impairment, attack.t1685
-- Description: Detects PowerShell scripts attempting to disable scheduled scanning and other parts of Windows Defender ATP or set default actions to allow.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM file WHERE ((((ScriptBlockText LIKE '%-dbaf $true%' OR ScriptBlockText LIKE '%-dbaf 1%' OR ScriptBlockText LIKE '%-dbm $true%' OR ScriptBlockText LIKE '%-dbm 1%' OR ScriptBlockText LIKE '%-dips $true%' OR ScriptBlockText LIKE '%-dips 1%' OR ScriptBlockText LIKE '%-DisableArchiveScanning $true%' OR ScriptBlockText LIKE '%-DisableArchiveScanning 1%' OR ScriptBlockText LIKE '%-DisableBehaviorMonitoring $true%' OR ScriptBlockText LIKE '%-DisableBehaviorMonitoring 1%' OR ScriptBlockText LIKE '%-DisableBlockAtFirstSeen $true%' OR ScriptBlockText LIKE '%-DisableBlockAtFirstSeen 1%' OR ScriptBlockText LIKE '%-DisableCatchupFullScan $true%' OR ScriptBlockText LIKE '%-DisableCatchupFullScan 1%' OR ScriptBlockText LIKE '%-DisableCatchupQuickScan $true%' OR ScriptBlockText LIKE '%-DisableCatchupQuickScan 1%' OR ScriptBlockText LIKE '%-DisableIntrusionPreventionSystem $true%' OR ScriptBlockText LIKE '%-DisableIntrusionPreventionSystem 1%' OR ScriptBlockText LIKE '%-DisableIOAVProtection $true%' OR ScriptBlockText LIKE '%-DisableIOAVProtection 1%' OR ScriptBlockText LIKE '%-DisableRealtimeMonitoring $true%' OR ScriptBlockText LIKE '%-DisableRealtimeMonitoring 1%' OR ScriptBlockText LIKE '%-DisableRemovableDriveScanning $true%' OR ScriptBlockText LIKE '%-DisableRemovableDriveScanning 1%' OR ScriptBlockText LIKE '%-DisableScanningMappedNetworkDrivesForFullScan $true%' OR ScriptBlockText LIKE '%-DisableScanningMappedNetworkDrivesForFullScan 1%' OR ScriptBlockText LIKE '%-DisableScanningNetworkFiles $true%' OR ScriptBlockText LIKE '%-DisableScanningNetworkFiles 1%' OR ScriptBlockText LIKE '%-DisableScriptScanning $true%' OR ScriptBlockText LIKE '%-DisableScriptScanning 1%' OR ScriptBlockText LIKE '%-MAPSReporting $false%' OR ScriptBlockText LIKE '%-MAPSReporting 0%' OR ScriptBlockText LIKE '%-drdsc $true%' OR ScriptBlockText LIKE '%-drdsc 1%' OR ScriptBlockText LIKE '%-drtm $true%' OR ScriptBlockText LIKE '%-drtm 1%' OR ScriptBlockText LIKE '%-dscrptsc $true%' OR ScriptBlockText LIKE '%-dscrptsc 1%' OR ScriptBlockText LIKE '%-dsmndf $true%' OR ScriptBlockText LIKE '%-dsmndf 1%' OR ScriptBlockText LIKE '%-dsnf $true%' OR ScriptBlockText LIKE '%-dsnf 1%' OR ScriptBlockText LIKE '%-dss $true%' OR ScriptBlockText LIKE '%-dss 1%')) AND (ScriptBlockText LIKE '%Set-MpPreference%')) OR ((ScriptBlockText LIKE '%Set-MpPreference%') AND ((ScriptBlockText LIKE '%HighThreatDefaultAction Allow%' OR ScriptBlockText LIKE '%htdefac Allow%' OR ScriptBlockText LIKE '%LowThreatDefaultAction Allow%' OR ScriptBlockText LIKE '%ltdefac Allow%' OR ScriptBlockText LIKE '%ModerateThreatDefaultAction Allow%' OR ScriptBlockText LIKE '%mtdefac Allow%' OR ScriptBlockText LIKE '%SevereThreatDefaultAction Allow%' OR ScriptBlockText LIKE '%stdefac Allow%'))))
