-- Title: Tamper Windows Defender - PSClassic
-- ID: ec19ebab-72dc-40e1-9728-4c0b805d722c
-- Status: test
-- Level: high
-- Author: frack113, Nasreddine Bencherchali (Nextron Systems)
-- Date: 2021-06-07
-- Tags: attack.defense-impairment, attack.t1685
-- Description: Attempting to disable scheduled scanning and other parts of Windows Defender ATP or set default actions to allow.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM file WHERE ((Data LIKE '%Set-MpPreference%') AND (((Data LIKE '%HighThreatDefaultAction Allow%' OR Data LIKE '%htdefac Allow%' OR Data LIKE '%LowThreatDefaultAction Allow%' OR Data LIKE '%ltdefac Allow%' OR Data LIKE '%ModerateThreatDefaultAction Allow%' OR Data LIKE '%mtdefac Allow%' OR Data LIKE '%SevereThreatDefaultAction Allow%' OR Data LIKE '%stdefac Allow%')) OR ((Data LIKE '%-dbaf $true%' OR Data LIKE '%-dbaf 1%' OR Data LIKE '%-dbm $true%' OR Data LIKE '%-dbm 1%' OR Data LIKE '%-dips $true%' OR Data LIKE '%-dips 1%' OR Data LIKE '%-DisableArchiveScanning $true%' OR Data LIKE '%-DisableArchiveScanning 1%' OR Data LIKE '%-DisableBehaviorMonitoring $true%' OR Data LIKE '%-DisableBehaviorMonitoring 1%' OR Data LIKE '%-DisableBlockAtFirstSeen $true%' OR Data LIKE '%-DisableBlockAtFirstSeen 1%' OR Data LIKE '%-DisableCatchupFullScan $true%' OR Data LIKE '%-DisableCatchupFullScan 1%' OR Data LIKE '%-DisableCatchupQuickScan $true%' OR Data LIKE '%-DisableCatchupQuickScan 1%' OR Data LIKE '%-DisableIntrusionPreventionSystem $true%' OR Data LIKE '%-DisableIntrusionPreventionSystem 1%' OR Data LIKE '%-DisableIOAVProtection $true%' OR Data LIKE '%-DisableIOAVProtection 1%' OR Data LIKE '%-DisableRealtimeMonitoring $true%' OR Data LIKE '%-DisableRealtimeMonitoring 1%' OR Data LIKE '%-DisableRemovableDriveScanning $true%' OR Data LIKE '%-DisableRemovableDriveScanning 1%' OR Data LIKE '%-DisableScanningMappedNetworkDrivesForFullScan $true%' OR Data LIKE '%-DisableScanningMappedNetworkDrivesForFullScan 1%' OR Data LIKE '%-DisableScanningNetworkFiles $true%' OR Data LIKE '%-DisableScanningNetworkFiles 1%' OR Data LIKE '%-DisableScriptScanning $true%' OR Data LIKE '%-DisableScriptScanning 1%' OR Data LIKE '%-MAPSReporting $false%' OR Data LIKE '%-MAPSReporting 0%' OR Data LIKE '%-drdsc $true%' OR Data LIKE '%-drdsc 1%' OR Data LIKE '%-drtm $true%' OR Data LIKE '%-drtm 1%' OR Data LIKE '%-dscrptsc $true%' OR Data LIKE '%-dscrptsc 1%' OR Data LIKE '%-dsmndf $true%' OR Data LIKE '%-dsmndf 1%' OR Data LIKE '%-dsnf $true%' OR Data LIKE '%-dsnf 1%' OR Data LIKE '%-dss $true%' OR Data LIKE '%-dss 1%'))))
