-- Title: Suspicious File Download From File Sharing Domain Via Curl.EXE
-- ID: 56454143-524f-49fb-b1c6-3fb8b1ad41fb
-- Status: test
-- Level: high
-- Author: Nasreddine Bencherchali (Nextron Systems)
-- Date: 2023-05-05
-- Tags: attack.execution
-- Description: Detects potentially suspicious file download from file sharing domains using curl.exe
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE (((CommandLine="*.ps1" OR CommandLine="*.ps1'" OR CommandLine="*.ps1\"" OR CommandLine="*.dat" OR CommandLine="*.dat'" OR CommandLine="*.dat\"" OR CommandLine="*.msi" OR CommandLine="*.msi'" OR CommandLine="*.msi\"" OR CommandLine="*.bat" OR CommandLine="*.bat'" OR CommandLine="*.bat\"" OR CommandLine="*.exe" OR CommandLine="*.exe'" OR CommandLine="*.exe\"" OR CommandLine="*.vbs" OR CommandLine="*.vbs'" OR CommandLine="*.vbs\"" OR CommandLine="*.vbe" OR CommandLine="*.vbe'" OR CommandLine="*.vbe\"" OR CommandLine="*.hta" OR CommandLine="*.hta'" OR CommandLine="*.hta\"" OR CommandLine="*.dll" OR CommandLine="*.dll'" OR CommandLine="*.dll\"" OR CommandLine="*.psm1" OR CommandLine="*.psm1'" OR CommandLine="*.psm1\"")) AND ((CommandLine LIKE '% -O%' OR CommandLine LIKE '%--remote-name%' OR CommandLine LIKE '%--output%')) AND (CommandLine LIKE '%http%') AND ((Image="*\\curl.exe") OR (OriginalFileName = 'curl.exe')) AND ((CommandLine LIKE '%.githubusercontent.com%' OR CommandLine LIKE '%0x0.st%' OR CommandLine LIKE '%anonfiles.com%' OR CommandLine LIKE '%bashupload.com%' OR CommandLine LIKE '%cdn.discordapp.com%' OR CommandLine LIKE '%chunk.io%' OR CommandLine LIKE '%ddns.net%' OR CommandLine LIKE '%dl.dropboxusercontent.com%' OR CommandLine LIKE '%ghostbin.co%' OR CommandLine LIKE '%github.com%' OR CommandLine LIKE '%glitch.me%' OR CommandLine LIKE '%gofile.io%' OR CommandLine LIKE '%hastebin.com%' OR CommandLine LIKE '%mediafire.com%' OR CommandLine LIKE '%mega.nz%' OR CommandLine LIKE '%onrender.com%' OR CommandLine LIKE '%pages.dev%' OR CommandLine LIKE '%paste.ee%' OR CommandLine LIKE '%pastebin.com%' OR CommandLine LIKE '%pastebin.pl%' OR CommandLine LIKE '%pastetext.net%' OR CommandLine LIKE '%pixeldrain.com%' OR CommandLine LIKE '%privatlab.com%' OR CommandLine LIKE '%privatlab.net%' OR CommandLine LIKE '%send.exploit.in%' OR CommandLine LIKE '%sendspace.com%' OR CommandLine LIKE '%storage.googleapis.com%' OR CommandLine LIKE '%storjshare.io%' OR CommandLine LIKE '%supabase.co%' OR CommandLine LIKE '%temp.sh%' OR CommandLine LIKE '%transfer.sh%' OR CommandLine LIKE '%trycloudflare.com%' OR CommandLine LIKE '%ufile.io%' OR CommandLine LIKE '%w3spaces.com%' OR CommandLine LIKE '%workers.dev%' OR CommandLine LIKE '%x0.at%')))
