-- Title: Suspicious Windows Defender Registry Key Tampering Via Reg.EXE
-- ID: 452bce90-6fb0-43cc-97a5-affc283139b3
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), Swachchhanda Shrawan Poudel, Nasreddine Bencherchali (Nextron Systems)
-- Date: 2022-03-22
-- Tags: attack.defense-impairment, attack.t1685
-- Description: Detects the usage of "reg.exe" to tamper with different Windows Defender registry keys in order to disable some important features related to protection and detection
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE ((((Image="*\\reg.exe") OR (OriginalFileName = 'reg.exe')) AND ((CommandLine LIKE '%SOFTWARE\\Microsoft\\Windows Defender\\%' OR CommandLine LIKE '%SOFTWARE\\Policies\\Microsoft\\Windows Defender Security Center%' OR CommandLine LIKE '%SOFTWARE\\Policies\\Microsoft\\Windows Defender\\%'))) AND (((CommandLine LIKE '% add %' AND CommandLine LIKE '%d 0%') AND (CommandLine LIKE '%DisallowExploitProtectionOverride%' OR CommandLine LIKE '%EnableControlledFolderAccess%' OR CommandLine LIKE '%MpEnablePus%' OR CommandLine LIKE '%PUAProtection%' OR CommandLine LIKE '%SpynetReporting%' OR CommandLine LIKE '%SubmitSamplesConsent%' OR CommandLine LIKE '%TamperProtection%')) OR ((CommandLine LIKE '% add %' AND CommandLine LIKE '%d 1%') AND (CommandLine LIKE '%DisableAccess%' OR CommandLine LIKE '%DisableAntiSpyware%' OR CommandLine LIKE '%DisableAntiSpywareRealtimeProtection%' OR CommandLine LIKE '%DisableAntiVirus%' OR CommandLine LIKE '%DisableAntiVirusSignatures%' OR CommandLine LIKE '%DisableArchiveScanning%' OR CommandLine LIKE '%DisableBehaviorMonitoring%' OR CommandLine LIKE '%DisableBlockAtFirstSeen%' OR CommandLine LIKE '%DisableCloudProtection%' OR CommandLine LIKE '%DisableConfig%' OR CommandLine LIKE '%DisableEnhancedNotifications%' OR CommandLine LIKE '%DisableIntrusionPreventionSystem%' OR CommandLine LIKE '%DisableIOAVProtection%' OR CommandLine LIKE '%DisableNetworkProtection%' OR CommandLine LIKE '%DisableOnAccessProtection%' OR CommandLine LIKE '%DisablePrivacyMode%' OR CommandLine LIKE '%DisableRealtimeMonitoring%' OR CommandLine LIKE '%DisableRoutinelyTakingAction%' OR CommandLine LIKE '%DisableScanOnRealtimeEnable%' OR CommandLine LIKE '%DisableScriptScanning%' OR CommandLine LIKE '%DisableSecurityCenter%' OR CommandLine LIKE '%Notification_Suppress%' OR CommandLine LIKE '%SignatureDisableUpdateOnStartupWithoutEngine%'))))
