-- Title: System File Execution Location Anomaly
-- ID: e4a6b256-3e47-40fc-89d2-7a477edd6915
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), Patrick Bareiss, Anton Kutepov, oscd.community, Nasreddine Bencherchali (Nextron Systems)
-- Date: 2017-11-27
-- Tags: attack.stealth, attack.t1036
-- Description: Detects the execution of a Windows system binary that is usually located in the system folder from an uncommon location.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE (((Image="*\\atbroker.exe" OR Image="*\\audiodg.exe" OR Image="*\\bcdedit.exe" OR Image="*\\bitsadmin.exe" OR Image="*\\certreq.exe" OR Image="*\\certutil.exe" OR Image="*\\cmstp.exe" OR Image="*\\conhost.exe" OR Image="*\\consent.exe" OR Image="*\\cscript.exe" OR Image="*\\csrss.exe" OR Image="*\\dashost.exe" OR Image="*\\defrag.exe" OR Image="*\\dfrgui.exe" OR Image="*\\dism.exe" OR Image="*\\dllhost.exe" OR Image="*\\dllhst3g.exe" OR Image="*\\dwm.exe" OR Image="*\\eventvwr.exe" OR Image="*\\fsquirt.exe" OR Image="*\\finger.exe" OR Image="*\\logonui.exe" OR Image="*\\LsaIso.exe" OR Image="*\\lsass.exe" OR Image="*\\lsm.exe" OR Image="*\\msiexec.exe" OR Image="*\\ntoskrnl.exe" OR Image="*\\powershell_ise.exe" OR Image="*\\powershell.exe" OR Image="*\\pwsh.exe" OR Image="*\\regsvr32.exe" OR Image="*\\rundll32.exe" OR Image="*\\runonce.exe" OR Image="*\\RuntimeBroker.exe" OR Image="*\\schtasks.exe" OR Image="*\\services.exe" OR Image="*\\sihost.exe" OR Image="*\\smartscreen.exe" OR Image="*\\smss.exe" OR Image="*\\spoolsv.exe" OR Image="*\\svchost.exe" OR Image="*\\taskhost.exe" OR Image="*\\taskhostw.exe" OR Image="*\\Taskmgr.exe" OR Image="*\\userinit.exe" OR Image="*\\werfault.exe" OR Image="*\\werfaultsecure.exe" OR Image="*\\wininit.exe" OR Image="*\\winlogon.exe" OR Image="*\\winver.exe" OR Image="*\\wlanext.exe" OR Image="*\\wmic.exe" OR Image="*\\wscript.exe" OR Image="*\\wsl.exe" OR Image="*\\wsmprovhost.exe")) AND NOT ((((Image="C:\\$WINDOWS.~BT\\*" OR Image="C:\\$WinREAgent\\*" OR Image="C:\\Windows\\SoftwareDistribution\\*" OR Image="C:\\Windows\\System32\\*" OR Image="C:\\Windows\\SystemTemp\\*" OR Image="C:\\Windows\\SysWOW64\\*" OR Image="C:\\Windows\\uus\\*" OR Image="C:\\Windows\\WinSxS\\*")) OR ((Image LIKE '%C:\\Program Files\\PowerShell\\7\\%' OR Image LIKE '%C:\\Program Files\\PowerShell\\7-preview\\%' OR Image LIKE '%C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview%' OR Image LIKE '%\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShellPreview%') AND Image="*\\pwsh.exe") OR (Image="C:\\Users\\*" AND Image LIKE '%\\AppData\\Local\\Microsoft\\WindowsApps\\%' AND Image="*\\wsl.exe") OR ((Image="C:\\Program Files\\WindowsApps\\MicrosoftCorporationII.WindowsSubsystemForLinux*" OR Image="C:\\Program Files\\WSL\\*") AND Image="*\\wsl.exe"))) AND NOT ((Image LIKE '%\\SystemRoot\\System32\\%')))
