-- Title: Potential Tampering With Security Products Via WMIC
-- ID: 847d5ff3-8a31-4737-a970-aeae8fe21765
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
-- Date: 2021-01-30
-- Tags: attack.defense-impairment, attack.t1685
-- Description: Detects uninstallation or termination of security products using the WMIC utility
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE ((((CommandLine LIKE '%wmic%' AND CommandLine LIKE '%product %' AND CommandLine LIKE '%uninstall%') AND (CommandLine LIKE '%/nointeractive%' OR CommandLine LIKE '%-nointeractive%')) OR ((CommandLine LIKE '%wmic%' AND CommandLine LIKE '%caption like %') AND (CommandLine LIKE '%call delete%' OR CommandLine LIKE '%call terminate%')) OR ((CommandLine LIKE '%process %' AND CommandLine LIKE '%where %' AND CommandLine LIKE '%delete%'))) AND ((CommandLine LIKE '%%carbon%%' OR CommandLine LIKE '%%cylance%%' OR CommandLine LIKE '%%endpoint%%' OR CommandLine LIKE '%%eset%%' OR CommandLine LIKE '%%malware%%' OR CommandLine LIKE '%%Sophos%%' OR CommandLine LIKE '%%symantec%%' OR CommandLine LIKE '%Antivirus%' OR CommandLine LIKE '%AVG %' OR CommandLine LIKE '%Carbon Black%' OR CommandLine LIKE '%CarbonBlack%' OR CommandLine LIKE '%Cb Defense Sensor 64-bit%' OR CommandLine LIKE '%Crowdstrike Sensor%' OR CommandLine LIKE '%Cylance %' OR CommandLine LIKE '%Dell Threat Defense%' OR CommandLine LIKE '%DLP Endpoint%' OR CommandLine LIKE '%Endpoint Detection%' OR CommandLine LIKE '%Endpoint Protection%' OR CommandLine LIKE '%Endpoint Security%' OR CommandLine LIKE '%Endpoint Sensor%' OR CommandLine LIKE '%ESET File Security%' OR CommandLine LIKE '%LogRhythm System Monitor Service%' OR CommandLine LIKE '%Malwarebytes%' OR CommandLine LIKE '%McAfee Agent%' OR CommandLine LIKE '%Microsoft Security Client%' OR CommandLine LIKE '%Sophos Anti-Virus%' OR CommandLine LIKE '%Sophos AutoUpdate%' OR CommandLine LIKE '%Sophos Credential Store%' OR CommandLine LIKE '%Sophos Management Console%' OR CommandLine LIKE '%Sophos Management Database%' OR CommandLine LIKE '%Sophos Management Server%' OR CommandLine LIKE '%Sophos Remote Management System%' OR CommandLine LIKE '%Sophos Update Manager%' OR CommandLine LIKE '%Threat Protection%' OR CommandLine LIKE '%VirusScan%' OR CommandLine LIKE '%Webroot SecureAnywhere%' OR CommandLine LIKE '%Windows Defender%')))
