-- Title: Malicious Base64 Encoded PowerShell Keywords in Command Lines
-- ID: f26c6093-6f14-4b12-800f-0fcb46f5ffd0
-- Status: test
-- Level: high
-- Author: John Lambert (rule)
-- Date: 2019-01-16
-- Tags: attack.execution, attack.t1059.001
-- Description: Detects base64 encoded strings used in hidden malicious PowerShell command lines
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE (((CommandLine LIKE '%AGkAdABzAGEAZABtAGkAbgAgAC8AdAByAGEAbgBzAGYAZQByA%' OR CommandLine LIKE '%aXRzYWRtaW4gL3RyYW5zZmVy%' OR CommandLine LIKE '%IAaQB0AHMAYQBkAG0AaQBuACAALwB0AHIAYQBuAHMAZgBlAHIA%' OR CommandLine LIKE '%JpdHNhZG1pbiAvdHJhbnNmZX%' OR CommandLine LIKE '%YgBpAHQAcwBhAGQAbQBpAG4AIAAvAHQAcgBhAG4AcwBmAGUAcg%' OR CommandLine LIKE '%Yml0c2FkbWluIC90cmFuc2Zlc%' OR CommandLine LIKE '%AGMAaAB1AG4AawBfAHMAaQB6AGUA%' OR CommandLine LIKE '%JABjAGgAdQBuAGsAXwBzAGkAegBlA%' OR CommandLine LIKE '%JGNodW5rX3Npem%' OR CommandLine LIKE '%QAYwBoAHUAbgBrAF8AcwBpAHoAZQ%' OR CommandLine LIKE '%RjaHVua19zaXpl%' OR CommandLine LIKE '%Y2h1bmtfc2l6Z%' OR CommandLine LIKE '%AE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4A%' OR CommandLine LIKE '%kATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8Abg%' OR CommandLine LIKE '%lPLkNvbXByZXNzaW9u%' OR CommandLine LIKE '%SQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuA%' OR CommandLine LIKE '%SU8uQ29tcHJlc3Npb2%' OR CommandLine LIKE '%Ty5Db21wcmVzc2lvb%' OR CommandLine LIKE '%AE8ALgBNAGUAbQBvAHIAeQBTAHQAcgBlAGEAbQ%' OR CommandLine LIKE '%kATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtA%' OR CommandLine LIKE '%lPLk1lbW9yeVN0cmVhb%' OR CommandLine LIKE '%SQBPAC4ATQBlAG0AbwByAHkAUwB0AHIAZQBhAG0A%' OR CommandLine LIKE '%SU8uTWVtb3J5U3RyZWFt%' OR CommandLine LIKE '%Ty5NZW1vcnlTdHJlYW%' OR CommandLine LIKE '%4ARwBlAHQAQwBoAHUAbgBrA%' OR CommandLine LIKE '%5HZXRDaHVua%' OR CommandLine LIKE '%AEcAZQB0AEMAaAB1AG4Aaw%' OR CommandLine LIKE '%LgBHAGUAdABDAGgAdQBuAGsA%' OR CommandLine LIKE '%LkdldENodW5r%' OR CommandLine LIKE '%R2V0Q2h1bm%' OR CommandLine LIKE '%AEgAUgBFAEEARABfAEkATgBGAE8ANgA0A%' OR CommandLine LIKE '%QASABSAEUAQQBEAF8ASQBOAEYATwA2ADQA%' OR CommandLine LIKE '%RIUkVBRF9JTkZPNj%' OR CommandLine LIKE '%SFJFQURfSU5GTzY0%' OR CommandLine LIKE '%VABIAFIARQBBAEQAXwBJAE4ARgBPADYANA%' OR CommandLine LIKE '%VEhSRUFEX0lORk82N%' OR CommandLine LIKE '%AHIAZQBhAHQAZQBSAGUAbQBvAHQAZQBUAGgAcgBlAGEAZA%' OR CommandLine LIKE '%cmVhdGVSZW1vdGVUaHJlYW%' OR CommandLine LIKE '%MAcgBlAGEAdABlAFIAZQBtAG8AdABlAFQAaAByAGUAYQBkA%' OR CommandLine LIKE '%NyZWF0ZVJlbW90ZVRocmVhZ%' OR CommandLine LIKE '%Q3JlYXRlUmVtb3RlVGhyZWFk%' OR CommandLine LIKE '%QwByAGUAYQB0AGUAUgBlAG0AbwB0AGUAVABoAHIAZQBhAGQA%' OR CommandLine LIKE '%0AZQBtAG0AbwB2AGUA%' OR CommandLine LIKE '%1lbW1vdm%' OR CommandLine LIKE '%AGUAbQBtAG8AdgBlA%' OR CommandLine LIKE '%bQBlAG0AbQBvAHYAZQ%' OR CommandLine LIKE '%bWVtbW92Z%' OR CommandLine LIKE '%ZW1tb3Zl%')) AND (CommandLine LIKE '% hidden %') AND (((Image="*\\powershell.exe" OR Image="*\\pwsh.exe")) OR ((OriginalFileName = 'PowerShell.EXE' OR OriginalFileName = 'pwsh.dll'))))
