-- Title: Suspicious SYSTEM User Process Creation
-- ID: 2617e7ed-adb7-40ba-b0f3-8f9945fe6c09
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), David ANDRE (additional keywords)
-- Date: 2021-12-20
-- Tags: attack.credential-access, attack.privilege-escalation, attack.stealth, attack.t1134, attack.t1003, attack.t1027
-- Description: Detects a suspicious process creation as SYSTEM user (suspicious program or command line parameter)
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE ((((IntegrityLevel = 'System' OR IntegrityLevel = 'S-1-16-16384') AND (User LIKE '%AUTHORI%' OR User LIKE '%AUTORI%')) AND (((Image="*\\calc.exe" OR Image="*\\cscript.exe" OR Image="*\\forfiles.exe" OR Image="*\\hh.exe" OR Image="*\\mshta.exe" OR Image="*\\ping.exe" OR Image="*\\wscript.exe")) OR (CommandLine=regex("net\\s+user\\s+")) OR ((CommandLine LIKE '% -NoP %' OR CommandLine LIKE '% -W Hidden %' OR CommandLine LIKE '% -decode %' OR CommandLine LIKE '% /decode %' OR CommandLine LIKE '% /urlcache %' OR CommandLine LIKE '% -urlcache %' OR CommandLine LIKE '% -e* JAB%' OR CommandLine LIKE '% -e* SUVYI%' OR CommandLine LIKE '% -e* SQBFAFgA%' OR CommandLine LIKE '% -e* aWV4I%' OR CommandLine LIKE '% -e* IAB%' OR CommandLine LIKE '% -e* PAA%' OR CommandLine LIKE '% -e* aQBlAHgA%' OR CommandLine LIKE '%vssadmin delete shadows%' OR CommandLine LIKE '%reg SAVE HKLM%' OR CommandLine LIKE '% -ma %' OR CommandLine LIKE '%Microsoft\\Windows\\CurrentVersion\\Run%' OR CommandLine LIKE '%.downloadstring(%' OR CommandLine LIKE '%.downloadfile(%' OR CommandLine LIKE '% /ticket:%' OR CommandLine LIKE '%dpapi::%' OR CommandLine LIKE '%event::clear%' OR CommandLine LIKE '%event::drop%' OR CommandLine LIKE '%id::modify%' OR CommandLine LIKE '%kerberos::%' OR CommandLine LIKE '%lsadump::%' OR CommandLine LIKE '%misc::%' OR CommandLine LIKE '%privilege::%' OR CommandLine LIKE '%rpc::%' OR CommandLine LIKE '%sekurlsa::%' OR CommandLine LIKE '%sid::%' OR CommandLine LIKE '%token::%' OR CommandLine LIKE '%vault::cred%' OR CommandLine LIKE '%vault::list%' OR CommandLine LIKE '% p::d %' OR CommandLine LIKE '%;iex(%' OR CommandLine LIKE '%MiniDump%')))) AND NOT (((ParentImage LIKE '%:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\%') OR ((ParentImage LIKE '%:\\Program Files (x86)\\Java\\%' OR ParentImage LIKE '%:\\Program Files\\Java\\%') AND ParentImage="*\\bin\\javaws.exe" AND (Image LIKE '%:\\Program Files (x86)\\Java\\%' OR Image LIKE '%:\\Program Files\\Java\\%') AND Image="*\\bin\\jp2launcher.exe" AND CommandLine LIKE '% -ma %') OR ((CommandLine LIKE '%ping%' AND CommandLine LIKE '%127.0.0.1%' AND CommandLine LIKE '% -n %')) OR (Image="*\\PING.EXE" AND ParentCommandLine LIKE '%\\DismFoDInstall.cmd%'))))
