-- Title: Potential WinAPI Calls Via CommandLine
-- ID: ba3f5c1b-6272-4119-9dbd-0bc8d21c2702
-- Status: test
-- Level: high
-- Author: Nasreddine Bencherchali (Nextron Systems)
-- Date: 2022-09-06
-- Tags: attack.execution, attack.t1106
-- Description: Detects the use of WinAPI Functions via the commandline. As seen used by threat actors via the tool winapiexec
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE (((CommandLine LIKE '%AddSecurityPackage%' OR CommandLine LIKE '%AdjustTokenPrivileges%' OR CommandLine LIKE '%Advapi32%' OR CommandLine LIKE '%CloseHandle%' OR CommandLine LIKE '%CreateProcessWithToken%' OR CommandLine LIKE '%CreatePseudoConsole%' OR CommandLine LIKE '%CreateRemoteThread%' OR CommandLine LIKE '%CreateThread%' OR CommandLine LIKE '%CreateUserThread%' OR CommandLine LIKE '%DangerousGetHandle%' OR CommandLine LIKE '%DuplicateTokenEx%' OR CommandLine LIKE '%EnumerateSecurityPackages%' OR CommandLine LIKE '%FreeHGlobal%' OR CommandLine LIKE '%FreeLibrary%' OR CommandLine LIKE '%GetDelegateForFunctionPointer%' OR CommandLine LIKE '%GetLogonSessionData%' OR CommandLine LIKE '%GetModuleHandle%' OR CommandLine LIKE '%GetProcAddress%' OR CommandLine LIKE '%GetProcessHandle%' OR CommandLine LIKE '%GetTokenInformation%' OR CommandLine LIKE '%ImpersonateLoggedOnUser%' OR CommandLine LIKE '%kernel32%' OR CommandLine LIKE '%LoadLibrary%' OR CommandLine LIKE '%memcpy%' OR CommandLine LIKE '%MiniDumpWriteDump%' OR CommandLine LIKE '%ntdll%' OR CommandLine LIKE '%OpenDesktop%' OR CommandLine LIKE '%OpenProcess%' OR CommandLine LIKE '%OpenProcessToken%' OR CommandLine LIKE '%OpenThreadToken%' OR CommandLine LIKE '%OpenWindowStation%' OR CommandLine LIKE '%PtrToString%' OR CommandLine LIKE '%QueueUserApc%' OR CommandLine LIKE '%ReadProcessMemory%' OR CommandLine LIKE '%RevertToSelf%' OR CommandLine LIKE '%RtlCreateUserThread%' OR CommandLine LIKE '%secur32%' OR CommandLine LIKE '%SetThreadToken%' OR CommandLine LIKE '%VirtualAlloc%' OR CommandLine LIKE '%VirtualFree%' OR CommandLine LIKE '%VirtualProtect%' OR CommandLine LIKE '%WaitForSingleObject%' OR CommandLine LIKE '%WriteInt32%' OR CommandLine LIKE '%WriteProcessMemory%' OR CommandLine LIKE '%ZeroFreeGlobalAllocUnicode%')) AND NOT (((ParentImage="*\\CompatTelRunner.exe" AND (CommandLine LIKE '%FreeHGlobal%' OR CommandLine LIKE '%PtrToString%' OR CommandLine LIKE '%kernel32%' OR CommandLine LIKE '%CloseHandle%')) OR (Image="*\\MpCmdRun.exe" AND CommandLine LIKE '%GetLoadLibraryWAddress32%'))))
