-- Title: PUA - PingCastle Execution From Potentially Suspicious Parent
-- ID: b37998de-a70b-4f33-b219-ec36bf433dc0
-- Status: test
-- Level: high
-- Author: Nasreddine Bencherchali (Nextron Systems), X__Junior (Nextron Systems)
-- Date: 2024-01-11
-- Tags: attack.reconnaissance, attack.t1595
-- Description: Detects the execution of PingCastle, a tool designed to quickly assess the Active Directory security level via a script located in a potentially suspicious or uncommon location.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE ((((ParentCommandLine LIKE '%.bat%' OR ParentCommandLine LIKE '%.chm%' OR ParentCommandLine LIKE '%.cmd%' OR ParentCommandLine LIKE '%.hta%' OR ParentCommandLine LIKE '%.htm%' OR ParentCommandLine LIKE '%.html%' OR ParentCommandLine LIKE '%.js%' OR ParentCommandLine LIKE '%.lnk%' OR ParentCommandLine LIKE '%.ps1%' OR ParentCommandLine LIKE '%.vbe%' OR ParentCommandLine LIKE '%.vbs%' OR ParentCommandLine LIKE '%.wsf%')) OR ((ParentCommandLine LIKE '%:\\Perflogs\\%' OR ParentCommandLine LIKE '%:\\Temp\\%' OR ParentCommandLine LIKE '%:\\Users\\Public\\%' OR ParentCommandLine LIKE '%:\\Windows\\Temp\\%' OR ParentCommandLine LIKE '%\\AppData\\Local\\Temp%' OR ParentCommandLine LIKE '%\\AppData\\Roaming\\%' OR ParentCommandLine LIKE '%\\Temporary Internet%')) OR (((ParentCommandLine LIKE '%:\\Users\\%' AND ParentCommandLine LIKE '%\\Favorites\\%')) OR ((ParentCommandLine LIKE '%:\\Users\\%' AND ParentCommandLine LIKE '%\\Favourites\\%')) OR ((ParentCommandLine LIKE '%:\\Users\\%' AND ParentCommandLine LIKE '%\\Contacts\\%')))) AND ((ParentCommandLine LIKE '%.bat%' OR ParentCommandLine LIKE '%.chm%' OR ParentCommandLine LIKE '%.cmd%' OR ParentCommandLine LIKE '%.hta%' OR ParentCommandLine LIKE '%.htm%' OR ParentCommandLine LIKE '%.html%' OR ParentCommandLine LIKE '%.js%' OR ParentCommandLine LIKE '%.lnk%' OR ParentCommandLine LIKE '%.ps1%' OR ParentCommandLine LIKE '%.vbe%' OR ParentCommandLine LIKE '%.vbs%' OR ParentCommandLine LIKE '%.wsf%')) AND ((Image="*\\PingCastle.exe") OR (OriginalFileName = 'PingCastle.exe') OR (Product = 'Ping Castle') OR ((CommandLine LIKE '%--scanner aclcheck%' OR CommandLine LIKE '%--scanner antivirus%' OR CommandLine LIKE '%--scanner computerversion%' OR CommandLine LIKE '%--scanner foreignusers%' OR CommandLine LIKE '%--scanner laps_bitlocker%' OR CommandLine LIKE '%--scanner localadmin%' OR CommandLine LIKE '%--scanner nullsession%' OR CommandLine LIKE '%--scanner nullsession-trust%' OR CommandLine LIKE '%--scanner oxidbindings%' OR CommandLine LIKE '%--scanner remote%' OR CommandLine LIKE '%--scanner share%' OR CommandLine LIKE '%--scanner smb%' OR CommandLine LIKE '%--scanner smb3querynetwork%' OR CommandLine LIKE '%--scanner spooler%' OR CommandLine LIKE '%--scanner startup%' OR CommandLine LIKE '%--scanner zerologon%')) OR (CommandLine LIKE '%--no-enum-limit%') OR ((CommandLine LIKE '%--healthcheck%' AND CommandLine LIKE '%--level Full%')) OR ((CommandLine LIKE '%--healthcheck%' AND CommandLine LIKE '%--server %'))))
