-- Title: Invoke-Obfuscation Obfuscated IEX Invocation
-- ID: 4bf943c6-5146-4273-98dd-e958fd1e3abf
-- Status: test
-- Level: high
-- Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
-- Date: 2019-11-08
-- Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
-- Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the following code block
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE ((CommandLine=regex("\\$PSHome\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$PSHome\\[")) OR (CommandLine=regex("\\$ShellId\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$ShellId\\[")) OR (CommandLine=regex("\\$env:Public\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$env:Public\\[")) OR (CommandLine=regex("\\$env:ComSpec\\[(?:\\s*\\d{1,3}\\s*,){2}")) OR (CommandLine=regex("\\*mdr\\*\\W\\s*\\)\\.Name")) OR (CommandLine=regex("\\$VerbosePreference\\.ToString\\(")) OR (CommandLine=regex("\\[String\\]\\s*\\$VerbosePreference")))
