-- Title: Potentially Suspicious Rundll32 Activity
-- ID: e593cf51-88db-4ee1-b920-37e89012a3c9
-- Status: test
-- Level: medium
-- Author: juju4, Jonhnathan Ribeiro, oscd.community, Nasreddine Bencherchali (Nextron Systems)
-- Date: 2019-01-16
-- Tags: attack.stealth, attack.t1218.011
-- Description: Detects suspicious execution of rundll32, with specific calls to some DLLs with known LOLBIN functionalities
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE ((((CommandLine LIKE '%javascript:%' AND CommandLine LIKE '%.RegisterXLL%')) OR ((CommandLine LIKE '%url.dll%' AND CommandLine LIKE '%OpenURL%')) OR ((CommandLine LIKE '%url.dll%' AND CommandLine LIKE '%OpenURLA%')) OR ((CommandLine LIKE '%url.dll%' AND CommandLine LIKE '%FileProtocolHandler%')) OR ((CommandLine LIKE '%zipfldr.dll%' AND CommandLine LIKE '%RouteTheCall%')) OR ((CommandLine LIKE '%shell32.dll%' AND CommandLine LIKE '%Control_RunDLL%')) OR ((CommandLine LIKE '%shell32.dll%' AND CommandLine LIKE '%ShellExec_RunDLL%')) OR ((CommandLine LIKE '%mshtml.dll%' AND CommandLine LIKE '%PrintHTML%')) OR ((CommandLine LIKE '%advpack.dll%' AND CommandLine LIKE '%LaunchINFSection%')) OR ((CommandLine LIKE '%advpack.dll%' AND CommandLine LIKE '%RegisterOCX%')) OR ((CommandLine LIKE '%ieadvpack.dll%' AND CommandLine LIKE '%LaunchINFSection%')) OR ((CommandLine LIKE '%ieadvpack.dll%' AND CommandLine LIKE '%RegisterOCX%')) OR ((CommandLine LIKE '%ieframe.dll%' AND CommandLine LIKE '%OpenURL%')) OR ((CommandLine LIKE '%shdocvw.dll%' AND CommandLine LIKE '%OpenURL%')) OR ((CommandLine LIKE '%syssetup.dll%' AND CommandLine LIKE '%SetupInfObjectInstallAction%')) OR ((CommandLine LIKE '%setupapi.dll%' AND CommandLine LIKE '%InstallHinfSection%')) OR ((CommandLine LIKE '%pcwutl.dll%' AND CommandLine LIKE '%LaunchApplication%')) OR ((CommandLine LIKE '%dfshim.dll%' AND CommandLine LIKE '%ShOpenVerbApplication%')) OR ((CommandLine LIKE '%dfshim.dll%' AND CommandLine LIKE '%ShOpenVerbShortcut%')) OR ((CommandLine LIKE '%scrobj.dll%' AND CommandLine LIKE '%GenerateTypeLib%' AND CommandLine LIKE '%http%')) OR ((CommandLine LIKE '%shimgvw.dll%' AND CommandLine LIKE '%ImageView_Fullscreen%' AND CommandLine LIKE '%http%')) OR ((CommandLine LIKE '%comsvcs.dll%' AND CommandLine LIKE '%MiniDump%'))) AND NOT (((ParentImage = 'C:\\Windows\\System32\\control.exe' AND ParentCommandLine LIKE '%.cpl%' AND (CommandLine LIKE '%Shell32.dll%' AND CommandLine LIKE '%Control_RunDLL%' AND CommandLine LIKE '%.cpl%')) OR (CommandLine LIKE '%shell32.dll,Control_RunDLL desk.cpl,screensaver,@screensaver%') OR (ParentImage = 'C:\\Windows\\System32\\control.exe' AND CommandLine="\"C:\\Windows\\system32\\rundll32.exe\" Shell32.dll,Control_RunDLL \"C:\\Windows\\System32\\*" AND CommandLine="*.cpl\","))))
