-- Title: Potentially Suspicious EventLog Recon Activity Using Log Query Utilities
-- ID: beaa66d6-aa1b-4e3c-80f5-e0145369bfaf
-- Status: test
-- Level: medium
-- Author: Nasreddine Bencherchali (Nextron Systems), X__Junior (Nextron Systems)
-- Date: 2022-09-09
-- Tags: attack.credential-access, attack.discovery, attack.t1552, attack.t1087
-- Description: Detects execution of different log query utilities and commands to search and dump the content of specific event logs or look for specific event IDs.
-- This technique is used by threat actors in order to extract sensitive information from events logs such as usernames, IP addresses, hostnames, etc.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM processes WHERE ((((CommandLine LIKE '%-InstanceId 462?%' OR CommandLine LIKE '%.eventid -eq 462?%' OR CommandLine LIKE '%.ID -eq 462?%' OR CommandLine LIKE '%EventCode=?462?%' OR CommandLine LIKE '%EventIdentifier=?462?%' OR CommandLine LIKE '%System[EventID=462?]%' OR CommandLine LIKE '%-InstanceId 4778%' OR CommandLine LIKE '%.eventid -eq 4778%' OR CommandLine LIKE '%.ID -eq 4778%' OR CommandLine LIKE '%EventCode=?4778?%' OR CommandLine LIKE '%EventIdentifier=?4778?%' OR CommandLine LIKE '%System[EventID=4778]%' OR CommandLine LIKE '%-InstanceId 25%' OR CommandLine LIKE '%.eventid -eq 25%' OR CommandLine LIKE '%.ID -eq 25%' OR CommandLine LIKE '%EventCode=?25?%' OR CommandLine LIKE '%EventIdentifier=?25?%' OR CommandLine LIKE '%System[EventID=25]%' OR CommandLine LIKE '%-InstanceId 1149%' OR CommandLine LIKE '%.eventid -eq 1149%' OR CommandLine LIKE '%.ID -eq 1149%' OR CommandLine LIKE '%EventCode=?1149?%' OR CommandLine LIKE '%EventIdentifier=?1149?%' OR CommandLine LIKE '%System[EventID=1149]%' OR CommandLine LIKE '%-InstanceId 21%' OR CommandLine LIKE '%.eventid -eq 21%' OR CommandLine LIKE '%.ID -eq 21%' OR CommandLine LIKE '%EventCode=?21?%' OR CommandLine LIKE '%EventIdentifier=?21?%' OR CommandLine LIKE '%System[EventID=21]%' OR CommandLine LIKE '%-InstanceId 22%' OR CommandLine LIKE '%.eventid -eq 22%' OR CommandLine LIKE '%.ID -eq 22%' OR CommandLine LIKE '%EventCode=?22?%' OR CommandLine LIKE '%EventIdentifier=?22?%' OR CommandLine LIKE '%System[EventID=22]%')) OR ((CommandLine LIKE '%Microsoft-Windows-PowerShell%' OR CommandLine LIKE '%Microsoft-Windows-Security-Auditing%' OR CommandLine LIKE '%Microsoft-Windows-TerminalServices-LocalSessionManager%' OR CommandLine LIKE '%Microsoft-Windows-TerminalServices-RemoteConnectionManager%' OR CommandLine LIKE '%Microsoft-Windows-Windows Defender%' OR CommandLine LIKE '%PowerShellCore%' OR CommandLine LIKE '%Security%' OR CommandLine LIKE '%Windows PowerShell%'))) AND (((CommandLine LIKE '%Select%' AND CommandLine LIKE '%Win32_NTLogEvent%')) OR (((CommandLine LIKE '% qe %' OR CommandLine LIKE '% query-events %')) AND ((Image="*\\wevtutil.exe") OR (OriginalFileName = 'wevtutil.exe'))) OR ((CommandLine LIKE '% ntevent%') AND ((Image="*\\wmic.exe") OR (OriginalFileName = 'wmic.exe'))) OR ((CommandLine LIKE '%Get-WinEvent %' OR CommandLine LIKE '%get-eventlog %'))))
