-- Title: Scheduled TaskCache Change by Uncommon Program
-- ID: 4720b7df-40c3-48fd-bbdf-fd4b3c464f0d
-- Status: test
-- Level: high
-- Author: Syed Hasan (@syedhasan009)
-- Date: 2021-06-18
-- Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053, attack.t1053.005
-- Description: Monitor the creation of a new key under 'TaskCache' when a new scheduled task is registered by a process that is not svchost.exe, which is suspicious
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM file WHERE ((TargetObject LIKE '%SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\%') AND NOT (((Details = '(Empty)') OR (Image = 'C:\\Windows\\explorer.exe' AND TargetObject LIKE '%\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree\\Microsoft\\Windows\\PLA\\Server Manager Performance Monitor\\%') OR (Image="*C:\\Windows\\System32\\MoUsoCoreWorker.exe") OR (Image = 'C:\\Windows\\System32\\msiexec.exe') OR (Image="C:\\Windows\\Microsoft.NET\\Framework*" AND Image="*\\ngen.exe" AND (TargetObject LIKE '%\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tasks\\{B66B135D-DA06-4FC4-95F8-7458E1D10129}%' OR TargetObject LIKE '%\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree\\Microsoft\\Windows\\.NET Framework\\.NET Framework NGEN%')) OR (NOT Details=*) OR ((Image = 'C:\\Program Files\\Microsoft Office\\root\\Integration\\Integrator.exe' OR Image = 'C:\\Program Files (x86)\\Microsoft Office\\root\\Integration\\Integrator.exe' OR Image = 'C:\\Program Files\\Common Files\\microsoft shared\\ClickToRun\\OfficeC2RClient.exe' OR Image = 'C:\\Program Files (x86)\\Common Files\\microsoft shared\\ClickToRun\\OfficeC2RClient.exe')) OR ((TargetObject LIKE '%Microsoft\\Windows\\UpdateOrchestrator%' OR TargetObject LIKE '%Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask\\Index%' OR TargetObject LIKE '%Microsoft\\Windows\\Flighting\\OneSettings\\RefreshCache\\Index%')) OR (Image = 'C:\\Windows\\System32\\RuntimeBroker.exe') OR (Image="*C:\\Windows\\System32\\services.exe") OR (Image = 'C:\\WINDOWS\\system32\\svchost.exe') OR (Image = 'System') OR (Image="C:\\Windows\\*" AND Image="*\\TiWorker.exe"))) AND NOT ((((Image = 'C:\\Program Files (x86)\\Dropbox\\Update\\DropboxUpdate.exe' OR Image = 'C:\\Program Files\\Dropbox\\Update\\DropboxUpdate.exe')) OR ((Image="*C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\MicrosoftEdgeUpdate.exe" OR Image="*C:\\Program Files\\Microsoft\\EdgeUpdate\\MicrosoftEdgeUpdate.exe")) OR ((Image="*C:\\Program Files (x86)\\Microsoft OneDrive\\OneDrive.exe" OR Image="*C:\\Program Files\\Microsoft OneDrive\\OneDrive.exe")))))
