-- Title: Common Autorun Keys Modification
-- ID: f59c3faf-50f3-464b-9f4c-1b67ab512d99
-- Status: test
-- Level: medium
-- Author: Victor Sergeev, Daniil Yugoslavskiy, Gleb Sukhodolskiy, Timur Zinniatullin, oscd.community, Tim Shelton, frack113 (split), wagga (name)
-- Date: 2019-10-25
-- Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
-- Description: Detects modification of autostart extensibility point (ASEP) in registry.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM file WHERE (((TargetObject LIKE '%\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows CE Services\\AutoStart%' OR TargetObject LIKE '%\\Software\\Wow6432Node\\Microsoft\\Command Processor\\Autorun%' OR TargetObject LIKE '%\\SOFTWARE\\Wow6432Node\\Microsoft\\Active Setup\\Installed Components%' OR TargetObject LIKE '%\\SOFTWARE\\Microsoft\\Windows CE Services\\AutoStartOnDisconnect%' OR TargetObject LIKE '%\\SOFTWARE\\Microsoft\\Windows CE Services\\AutoStartOnConnect%' OR TargetObject LIKE '%\\SYSTEM\\Setup\\CmdLine%' OR TargetObject LIKE '%\\Software\\Microsoft\\Ctf\\LangBarAddin%' OR TargetObject LIKE '%\\Software\\Microsoft\\Command Processor\\Autorun%' OR TargetObject LIKE '%\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components%' OR TargetObject LIKE '%\\SOFTWARE\\Classes\\Protocols\\Handler%' OR TargetObject LIKE '%\\SOFTWARE\\Classes\\Protocols\\Filter%' OR TargetObject LIKE '%\\SOFTWARE\\Classes\\Htmlfile\\Shell\\Open\\Command\\(Default)%' OR TargetObject LIKE '%\\Environment\\UserInitMprLogonScript%' OR TargetObject LIKE '%\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\\Scrnsave.exe%' OR TargetObject LIKE '%\\Software\\Microsoft\\Internet Explorer\\UrlSearchHooks%' OR TargetObject LIKE '%\\SOFTWARE\\Microsoft\\Internet Explorer\\Desktop\\Components%' OR TargetObject LIKE '%\\Software\\Classes\\Clsid\\{AB8902B4-09CA-4bb6-B78D-A8F59079A8D5}\\Inprocserver32%' OR TargetObject LIKE '%\\Control Panel\\Desktop\\Scrnsave.exe%')) AND NOT (((Details = '(Empty)') OR (NOT Details=*) OR (Image = 'C:\\Windows\\System32\\poqexec.exe'))) AND NOT (((TargetObject LIKE '%\\Software\\Microsoft\\Active Setup\\Installed Components\\{89820200-ECBD-11cf-8B85-00AA005B4383}%') OR (TargetObject LIKE '%\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components\\{8A69D345-D564-463c-AFF1-A69D9E530F96}%') OR (TargetObject LIKE '%\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components\\{9459C573-B17A-45AE-9F64-1857B5D58CEE}%') OR ((Image = 'C:\\Program Files (x86)\\Microsoft Office\\root\\integration\\integrator.exe' OR Image = 'C:\\Program Files\\Microsoft Office\\root\\integration\\integrator.exe')) OR (((TargetObject LIKE '%\\Office\\ClickToRun\\REGISTRY\\MACHINE\\Software\\Classes\\PROTOCOLS\\Handler\\%' OR TargetObject LIKE '%\\ClickToRunStore\\HKMU\\SOFTWARE\\Classes\\PROTOCOLS\\Handler\\%')) OR ((Details = '{314111c7-a502-11d2-bbca-00c04f8ec294}' OR Details = '{3459B272-CC19-4448-86C9-DDC3B4B2FAD3}' OR Details = '{42089D2D-912D-4018-9087-2B87803E93FB}' OR Details = '{5504BE45-A83B-4808-900A-3A5C36E7F77A}' OR Details = '{807583E5-5146-11D5-A672-00B0D022E945}'))) OR ((Image="C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\*" OR Image="C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\Updates\\*") AND Image="*\\OfficeClickToRun.exe"))))
