// Title: PowerView PowerShell Cmdlets - ScriptBlock
// ID: dcd74b95-3f36-4ed9-9598-0490951643aa
// Status: test
// Level: high
// Author: Bhabesh Raj
// Date: 2021-05-18
// Tags: attack.execution, attack.t1059.001
// Description: Detects Cmdlet names from PowerView of the PowerSploit exploitation framework.
// Converted by: Sigma Universal SIEM/EDR CLI

((ScriptBlockText contains "Export-PowerViewCSV" OR ScriptBlockText contains "Find-DomainLocalGroupMember" OR ScriptBlockText contains "Find-DomainObjectPropertyOutlier" OR ScriptBlockText contains "Find-DomainProcess" OR ScriptBlockText contains "Find-DomainShare" OR ScriptBlockText contains "Find-DomainUserEvent" OR ScriptBlockText contains "Find-DomainUserLocation" OR ScriptBlockText contains "Find-ForeignGroup" OR ScriptBlockText contains "Find-ForeignUser" OR ScriptBlockText contains "Find-GPOComputerAdmin" OR ScriptBlockText contains "Find-GPOLocation" OR ScriptBlockText contains "Find-InterestingDomain" OR ScriptBlockText contains "Find-InterestingFile" OR ScriptBlockText contains "Find-LocalAdminAccess" OR ScriptBlockText contains "Find-ManagedSecurityGroups" OR ScriptBlockText contains "Get-CachedRDPConnection" OR ScriptBlockText contains "Get-DFSshare" OR ScriptBlockText contains "Get-DomainDFSShare" OR ScriptBlockText contains "Get-DomainDNSRecord" OR ScriptBlockText contains "Get-DomainDNSZone" OR ScriptBlockText contains "Get-DomainFileServer" OR ScriptBlockText contains "Get-DomainGPOComputerLocalGroupMapping" OR ScriptBlockText contains "Get-DomainGPOLocalGroup" OR ScriptBlockText contains "Get-DomainGPOUserLocalGroupMapping" OR ScriptBlockText contains "Get-LastLoggedOn" OR ScriptBlockText contains "Get-LoggedOnLocal" OR ScriptBlockText contains "Get-NetFileServer" OR ScriptBlockText contains "Get-NetForest" OR ScriptBlockText contains "Get-NetGPOGroup" OR ScriptBlockText contains "Get-NetProcess" OR ScriptBlockText contains "Get-NetRDPSession" OR ScriptBlockText contains "Get-RegistryMountedDrive" OR ScriptBlockText contains "Get-RegLoggedOn" OR ScriptBlockText contains "Get-WMIRegCachedRDPConnection" OR ScriptBlockText contains "Get-WMIRegLastLoggedOn" OR ScriptBlockText contains "Get-WMIRegMountedDrive" OR ScriptBlockText contains "Get-WMIRegProxy" OR ScriptBlockText contains "Invoke-ACLScanner" OR ScriptBlockText contains "Invoke-CheckLocalAdminAccess" OR ScriptBlockText contains "Invoke-EnumerateLocalAdmin" OR ScriptBlockText contains "Invoke-EventHunter" OR ScriptBlockText contains "Invoke-FileFinder" OR ScriptBlockText contains "Invoke-Kerberoast" OR ScriptBlockText contains "Invoke-MapDomainTrust" OR ScriptBlockText contains "Invoke-ProcessHunter" OR ScriptBlockText contains "Invoke-RevertToSelf" OR ScriptBlockText contains "Invoke-ShareFinder" OR ScriptBlockText contains "Invoke-UserHunter" OR ScriptBlockText contains "Invoke-UserImpersonation" OR ScriptBlockText contains "Remove-RemoteConnection" OR ScriptBlockText contains "Request-SPNTicket" OR ScriptBlockText contains "Resolve-IPAddress"))
