// Title: Malicious Base64 Encoded PowerShell Keywords in Command Lines
// ID: f26c6093-6f14-4b12-800f-0fcb46f5ffd0
// Status: test
// Level: high
// Author: John Lambert (rule)
// Date: 2019-01-16
// Tags: attack.execution, attack.t1059.001
// Description: Detects base64 encoded strings used in hidden malicious PowerShell command lines
// Converted by: Sigma Universal SIEM/EDR CLI

(((CommandLine contains "AGkAdABzAGEAZABtAGkAbgAgAC8AdAByAGEAbgBzAGYAZQByA" OR CommandLine contains "aXRzYWRtaW4gL3RyYW5zZmVy" OR CommandLine contains "IAaQB0AHMAYQBkAG0AaQBuACAALwB0AHIAYQBuAHMAZgBlAHIA" OR CommandLine contains "JpdHNhZG1pbiAvdHJhbnNmZX" OR CommandLine contains "YgBpAHQAcwBhAGQAbQBpAG4AIAAvAHQAcgBhAG4AcwBmAGUAcg" OR CommandLine contains "Yml0c2FkbWluIC90cmFuc2Zlc" OR CommandLine contains "AGMAaAB1AG4AawBfAHMAaQB6AGUA" OR CommandLine contains "JABjAGgAdQBuAGsAXwBzAGkAegBlA" OR CommandLine contains "JGNodW5rX3Npem" OR CommandLine contains "QAYwBoAHUAbgBrAF8AcwBpAHoAZQ" OR CommandLine contains "RjaHVua19zaXpl" OR CommandLine contains "Y2h1bmtfc2l6Z" OR CommandLine contains "AE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4A" OR CommandLine contains "kATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8Abg" OR CommandLine contains "lPLkNvbXByZXNzaW9u" OR CommandLine contains "SQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuA" OR CommandLine contains "SU8uQ29tcHJlc3Npb2" OR CommandLine contains "Ty5Db21wcmVzc2lvb" OR CommandLine contains "AE8ALgBNAGUAbQBvAHIAeQBTAHQAcgBlAGEAbQ" OR CommandLine contains "kATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtA" OR CommandLine contains "lPLk1lbW9yeVN0cmVhb" OR CommandLine contains "SQBPAC4ATQBlAG0AbwByAHkAUwB0AHIAZQBhAG0A" OR CommandLine contains "SU8uTWVtb3J5U3RyZWFt" OR CommandLine contains "Ty5NZW1vcnlTdHJlYW" OR CommandLine contains "4ARwBlAHQAQwBoAHUAbgBrA" OR CommandLine contains "5HZXRDaHVua" OR CommandLine contains "AEcAZQB0AEMAaAB1AG4Aaw" OR CommandLine contains "LgBHAGUAdABDAGgAdQBuAGsA" OR CommandLine contains "LkdldENodW5r" OR CommandLine contains "R2V0Q2h1bm" OR CommandLine contains "AEgAUgBFAEEARABfAEkATgBGAE8ANgA0A" OR CommandLine contains "QASABSAEUAQQBEAF8ASQBOAEYATwA2ADQA" OR CommandLine contains "RIUkVBRF9JTkZPNj" OR CommandLine contains "SFJFQURfSU5GTzY0" OR CommandLine contains "VABIAFIARQBBAEQAXwBJAE4ARgBPADYANA" OR CommandLine contains "VEhSRUFEX0lORk82N" OR CommandLine contains "AHIAZQBhAHQAZQBSAGUAbQBvAHQAZQBUAGgAcgBlAGEAZA" OR CommandLine contains "cmVhdGVSZW1vdGVUaHJlYW" OR CommandLine contains "MAcgBlAGEAdABlAFIAZQBtAG8AdABlAFQAaAByAGUAYQBkA" OR CommandLine contains "NyZWF0ZVJlbW90ZVRocmVhZ" OR CommandLine contains "Q3JlYXRlUmVtb3RlVGhyZWFk" OR CommandLine contains "QwByAGUAYQB0AGUAUgBlAG0AbwB0AGUAVABoAHIAZQBhAGQA" OR CommandLine contains "0AZQBtAG0AbwB2AGUA" OR CommandLine contains "1lbW1vdm" OR CommandLine contains "AGUAbQBtAG8AdgBlA" OR CommandLine contains "bQBlAG0AbQBvAHYAZQ" OR CommandLine contains "bWVtbW92Z" OR CommandLine contains "ZW1tb3Zl")) AND (CommandLine contains " hidden ") AND (((Image="*\\powershell.exe" OR Image="*\\pwsh.exe")) OR ((OriginalFileName == "PowerShell.EXE" OR OriginalFileName == "pwsh.dll"))))
