// Title: Webshell Detection With Command Line Keywords
// ID: bed2a484-9348-4143-8a8a-b801c979301c
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro, Anton Kutepov, oscd.community, Chad Hudson, Matt Anderson
// Date: 2017-01-01
// Tags: attack.persistence, attack.discovery, attack.t1505.003, attack.t1018, attack.t1033, attack.t1087
// Description: Detects certain command line parameters often used during reconnaissance activity via web shells
// Converted by: Sigma Universal SIEM/EDR CLI

((((ParentImage="*\\java.exe" OR ParentImage="*\\javaw.exe") AND (ParentImage contains "-tomcat-" OR ParentImage contains "\\tomcat")) OR ((ParentImage="*\\java.exe" OR ParentImage="*\\javaw.exe") AND (CommandLine contains "catalina.jar" OR CommandLine contains "CATALINA_HOME")) OR ((ParentImage="*\\w3wp.exe" OR ParentImage="*\\php-cgi.exe" OR ParentImage="*\\nginx.exe" OR ParentImage="*\\httpd.exe" OR ParentImage="*\\caddy.exe" OR ParentImage="*\\ws_tomcatservice.exe"))) AND (((CommandLine contains "&cd&echo" OR CommandLine contains "cd /d ")) OR (((Image="*\\dsquery.exe" OR Image="*\\find.exe" OR Image="*\\findstr.exe" OR Image="*\\ipconfig.exe" OR Image="*\\netstat.exe" OR Image="*\\nslookup.exe" OR Image="*\\pathping.exe" OR Image="*\\quser.exe" OR Image="*\\schtasks.exe" OR Image="*\\systeminfo.exe" OR Image="*\\tasklist.exe" OR Image="*\\tracert.exe" OR Image="*\\wevtutil.exe" OR Image="*\\whoami.exe")) OR ((OriginalFileName == "dsquery.exe" OR OriginalFileName == "find.exe" OR OriginalFileName == "findstr.exe" OR OriginalFileName == "ipconfig.exe" OR OriginalFileName == "netstat.exe" OR OriginalFileName == "nslookup.exe" OR OriginalFileName == "pathping.exe" OR OriginalFileName == "quser.exe" OR OriginalFileName == "schtasks.exe" OR OriginalFileName == "sysinfo.exe" OR OriginalFileName == "tasklist.exe" OR OriginalFileName == "tracert.exe" OR OriginalFileName == "VSSADMIN.EXE" OR OriginalFileName == "wevtutil.exe" OR OriginalFileName == "whoami.exe"))) OR ((CommandLine contains " Test-NetConnection " OR CommandLine contains "dir \\")) OR ((OriginalFileName == "net.exe" OR OriginalFileName == "net1.exe") AND (CommandLine contains " user " OR CommandLine contains " use " OR CommandLine contains " group ")) OR (OriginalFileName == "ping.exe" AND CommandLine contains " -n ") OR ((Image="*\\cmd.exe" OR Image="*\\powershell.exe" OR Image="*\\pwsh.exe") AND (CommandLine contains " -enc " OR CommandLine contains " -EncodedCommand " OR CommandLine contains " -w hidden " OR CommandLine contains " -windowstyle hidden" OR CommandLine contains ".WebClient).Download")) OR (OriginalFileName == "wmic.exe" AND CommandLine contains " /node:")))
