// Title: PUA - PingCastle Execution From Potentially Suspicious Parent
// ID: b37998de-a70b-4f33-b219-ec36bf433dc0
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), X__Junior (Nextron Systems)
// Date: 2024-01-11
// Tags: attack.reconnaissance, attack.t1595
// Description: Detects the execution of PingCastle, a tool designed to quickly assess the Active Directory security level via a script located in a potentially suspicious or uncommon location.
// Converted by: Sigma Universal SIEM/EDR CLI

((((ParentCommandLine contains ".bat" OR ParentCommandLine contains ".chm" OR ParentCommandLine contains ".cmd" OR ParentCommandLine contains ".hta" OR ParentCommandLine contains ".htm" OR ParentCommandLine contains ".html" OR ParentCommandLine contains ".js" OR ParentCommandLine contains ".lnk" OR ParentCommandLine contains ".ps1" OR ParentCommandLine contains ".vbe" OR ParentCommandLine contains ".vbs" OR ParentCommandLine contains ".wsf")) OR ((ParentCommandLine contains ":\\Perflogs\\" OR ParentCommandLine contains ":\\Temp\\" OR ParentCommandLine contains ":\\Users\\Public\\" OR ParentCommandLine contains ":\\Windows\\Temp\\" OR ParentCommandLine contains "\\AppData\\Local\\Temp" OR ParentCommandLine contains "\\AppData\\Roaming\\" OR ParentCommandLine contains "\\Temporary Internet")) OR (((ParentCommandLine contains ":\\Users\\" AND ParentCommandLine contains "\\Favorites\\")) OR ((ParentCommandLine contains ":\\Users\\" AND ParentCommandLine contains "\\Favourites\\")) OR ((ParentCommandLine contains ":\\Users\\" AND ParentCommandLine contains "\\Contacts\\")))) AND ((ParentCommandLine contains ".bat" OR ParentCommandLine contains ".chm" OR ParentCommandLine contains ".cmd" OR ParentCommandLine contains ".hta" OR ParentCommandLine contains ".htm" OR ParentCommandLine contains ".html" OR ParentCommandLine contains ".js" OR ParentCommandLine contains ".lnk" OR ParentCommandLine contains ".ps1" OR ParentCommandLine contains ".vbe" OR ParentCommandLine contains ".vbs" OR ParentCommandLine contains ".wsf")) AND ((Image="*\\PingCastle.exe") OR (OriginalFileName == "PingCastle.exe") OR (Product == "Ping Castle") OR ((CommandLine contains "--scanner aclcheck" OR CommandLine contains "--scanner antivirus" OR CommandLine contains "--scanner computerversion" OR CommandLine contains "--scanner foreignusers" OR CommandLine contains "--scanner laps_bitlocker" OR CommandLine contains "--scanner localadmin" OR CommandLine contains "--scanner nullsession" OR CommandLine contains "--scanner nullsession-trust" OR CommandLine contains "--scanner oxidbindings" OR CommandLine contains "--scanner remote" OR CommandLine contains "--scanner share" OR CommandLine contains "--scanner smb" OR CommandLine contains "--scanner smb3querynetwork" OR CommandLine contains "--scanner spooler" OR CommandLine contains "--scanner startup" OR CommandLine contains "--scanner zerologon")) OR (CommandLine contains "--no-enum-limit") OR ((CommandLine contains "--healthcheck" AND CommandLine contains "--level Full")) OR ((CommandLine contains "--healthcheck" AND CommandLine contains "--server "))))
