// Title: PowerShell Base64 Encoded WMI Classes
// ID: 1816994b-42e1-4fb1-afd2-134d88184f71
// Status: test
// Level: high
// Author: Christian Burkard (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-30
// Tags: attack.execution, attack.stealth, attack.t1059.001, attack.t1027
// Description: Detects calls to base64 encoded WMI class such as "Win32_ShadowCopy", "Win32_ScheduledJob", etc.
// Converted by: Sigma Universal SIEM/EDR CLI

((((Image="*\\powershell.exe" OR Image="*\\pwsh.exe")) OR ((OriginalFileName == "PowerShell.EXE" OR OriginalFileName == "pwsh.dll"))) AND (((CommandLine contains "VwBpAG4AMwAyAF8ATABvAGcAZwBlAGQATwBuAFUAcwBlAHIA" OR CommandLine contains "cAaQBuADMAMgBfAEwAbwBnAGcAZQBkAE8AbgBVAHMAZQByA" OR CommandLine contains "XAGkAbgAzADIAXwBMAG8AZwBnAGUAZABPAG4AVQBzAGUAcg" OR CommandLine contains "V2luMzJfTG9nZ2VkT25Vc2Vy" OR CommandLine contains "dpbjMyX0xvZ2dlZE9uVXNlc" OR CommandLine contains "XaW4zMl9Mb2dnZWRPblVzZX")) OR ((CommandLine contains "VwBpAG4AMwAyAF8AUAByAG8AYwBlAHMAcw" OR CommandLine contains "cAaQBuADMAMgBfAFAAcgBvAGMAZQBzAHMA" OR CommandLine contains "XAGkAbgAzADIAXwBQAHIAbwBjAGUAcwBzA" OR CommandLine contains "V2luMzJfUHJvY2Vzc" OR CommandLine contains "dpbjMyX1Byb2Nlc3" OR CommandLine contains "XaW4zMl9Qcm9jZXNz")) OR ((CommandLine contains "VwBpAG4AMwAyAF8AUwBjAGgAZQBkAHUAbABlAGQASgBvAGIA" OR CommandLine contains "cAaQBuADMAMgBfAFMAYwBoAGUAZAB1AGwAZQBkAEoAbwBiA" OR CommandLine contains "XAGkAbgAzADIAXwBTAGMAaABlAGQAdQBsAGUAZABKAG8AYg" OR CommandLine contains "V2luMzJfU2NoZWR1bGVkSm9i" OR CommandLine contains "dpbjMyX1NjaGVkdWxlZEpvY" OR CommandLine contains "XaW4zMl9TY2hlZHVsZWRKb2")) OR ((CommandLine contains "VwBpAG4AMwAyAF8AUwBoAGEAZABvAHcAYwBvAHAAeQ" OR CommandLine contains "cAaQBuADMAMgBfAFMAaABhAGQAbwB3AGMAbwBwAHkA" OR CommandLine contains "XAGkAbgAzADIAXwBTAGgAYQBkAG8AdwBjAG8AcAB5A" OR CommandLine contains "V2luMzJfU2hhZG93Y29we" OR CommandLine contains "dpbjMyX1NoYWRvd2NvcH" OR CommandLine contains "XaW4zMl9TaGFkb3djb3B5")) OR ((CommandLine contains "VwBpAG4AMwAyAF8AVQBzAGUAcgBBAGMAYwBvAHUAbgB0A" OR CommandLine contains "cAaQBuADMAMgBfAFUAcwBlAHIAQQBjAGMAbwB1AG4AdA" OR CommandLine contains "XAGkAbgAzADIAXwBVAHMAZQByAEEAYwBjAG8AdQBuAHQA" OR CommandLine contains "V2luMzJfVXNlckFjY291bn" OR CommandLine contains "dpbjMyX1VzZXJBY2NvdW50" OR CommandLine contains "XaW4zMl9Vc2VyQWNjb3Vud"))))
