// Title: DSInternals Suspicious PowerShell Cmdlets
// ID: 43d91656-a9b2-4541-b7e2-6a9bd3a13f4e
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), Nounou Mbeiri
// Date: 2024-06-26
// Tags: attack.execution, attack.t1059.001
// Description: Detects execution and usage of the DSInternals PowerShell module. Which can be used to perform what might be considered as suspicious activity such as dumping DPAPI backup keys or manipulating NTDS.DIT files.
// The DSInternals PowerShell Module exposes several internal features of Active Directory and Azure Active Directory. These include FIDO2 and NGC key auditing, offline ntds.dit file manipulation, password auditing, DC recovery from IFM backups and password hash calculation.
// Converted by: Sigma Universal SIEM/EDR CLI

((CommandLine contains "Add-ADDBSidHistory" OR CommandLine contains "Add-ADNgcKey" OR CommandLine contains "Add-ADReplNgcKey" OR CommandLine contains "ConvertFrom-ADManagedPasswordBlob" OR CommandLine contains "ConvertFrom-GPPrefPassword" OR CommandLine contains "ConvertFrom-ManagedPasswordBlob" OR CommandLine contains "ConvertFrom-UnattendXmlPassword" OR CommandLine contains "ConvertFrom-UnicodePassword" OR CommandLine contains "ConvertTo-AADHash" OR CommandLine contains "ConvertTo-GPPrefPassword" OR CommandLine contains "ConvertTo-KerberosKey" OR CommandLine contains "ConvertTo-LMHash" OR CommandLine contains "ConvertTo-MsoPasswordHash" OR CommandLine contains "ConvertTo-NTHash" OR CommandLine contains "ConvertTo-OrgIdHash" OR CommandLine contains "ConvertTo-UnicodePassword" OR CommandLine contains "Disable-ADDBAccount" OR CommandLine contains "Enable-ADDBAccount" OR CommandLine contains "Get-ADDBAccount" OR CommandLine contains "Get-ADDBBackupKey" OR CommandLine contains "Get-ADDBDomainController" OR CommandLine contains "Get-ADDBGroupManagedServiceAccount" OR CommandLine contains "Get-ADDBKdsRootKey" OR CommandLine contains "Get-ADDBSchemaAttribute" OR CommandLine contains "Get-ADDBServiceAccount" OR CommandLine contains "Get-ADDefaultPasswordPolicy" OR CommandLine contains "Get-ADKeyCredential" OR CommandLine contains "Get-ADPasswordPolicy" OR CommandLine contains "Get-ADReplAccount" OR CommandLine contains "Get-ADReplBackupKey" OR CommandLine contains "Get-ADReplicationAccount" OR CommandLine contains "Get-ADSIAccount" OR CommandLine contains "Get-AzureADUserEx" OR CommandLine contains "Get-BootKey" OR CommandLine contains "Get-KeyCredential" OR CommandLine contains "Get-LsaBackupKey" OR CommandLine contains "Get-LsaPolicy" OR CommandLine contains "Get-SamPasswordPolicy" OR CommandLine contains "Get-SysKey" OR CommandLine contains "Get-SystemKey" OR CommandLine contains "New-ADDBRestoreFromMediaScript" OR CommandLine contains "New-ADKeyCredential" OR CommandLine contains "New-ADNgcKey" OR CommandLine contains "New-NTHashSet" OR CommandLine contains "Remove-ADDBObject" OR CommandLine contains "Save-DPAPIBlob" OR CommandLine contains "Set-ADAccountPasswordHash" OR CommandLine contains "Set-ADDBAccountPassword" OR CommandLine contains "Set-ADDBBootKey" OR CommandLine contains "Set-ADDBDomainController" OR CommandLine contains "Set-ADDBPrimaryGroup" OR CommandLine contains "Set-ADDBSysKey" OR CommandLine contains "Set-AzureADUserEx" OR CommandLine contains "Set-LsaPolicy" OR CommandLine contains "Set-SamAccountPasswordHash" OR CommandLine contains "Set-WinUserPasswordHash" OR CommandLine contains "Test-ADDBPasswordQuality" OR CommandLine contains "Test-ADPasswordQuality" OR CommandLine contains "Test-ADReplPasswordQuality" OR CommandLine contains "Test-PasswordQuality" OR CommandLine contains "Unlock-ADDBAccount" OR CommandLine contains "Write-ADNgcKey" OR CommandLine contains "Write-ADReplNgcKey"))
