// Title: Suspicious SQL Error Messages
// ID: 8a670c6d-7189-4b1c-8017-a417ca84a086
// Status: test
// Level: high
// Author: Bjoern Kimminich
// Date: 2017-11-27
// Tags: attack.initial-access, attack.t1190
// Description: Detects SQL error messages that indicate probing for an injection attack
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "quoted string not properly terminated" or * has "You have an error in your SQL syntax" or * has "Unclosed quotation mark" or * has "near \"*\": syntax error" or * has "SELECTs to the left and right of UNION do not have the same number of result columns")
