// Title: Django Framework Exceptions
// ID: fd435618-981e-4a7c-81f8-f78ce480d616
// Status: stable
// Level: medium
// Author: Thomas Patzke
// Date: 2017-08-05
// Tags: attack.initial-access, attack.t1190
// Description: Detects suspicious Django web application framework exceptions that could indicate exploitation attempts
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "SuspiciousOperation" or * has "DisallowedHost" or * has "DisallowedModelAdminLookup" or * has "DisallowedModelAdminToField" or * has "DisallowedRedirect" or * has "InvalidSessionKey" or * has "RequestDataTooBig" or * has "SuspiciousFileOperation" or * has "SuspiciousMultipartForm" or * has "SuspiciousSession" or * has "TooManyFieldsSent" or * has "PermissionDenied")
