// Title: Ingress/Egress Security Group Modification
// ID: 6fb77778-040f-4015-9440-572aa9b6b580
// Status: test
// Level: medium
// Author: jamesc-grafana
// Date: 2024-07-11
// Tags: attack.initial-access, attack.t1190
// Description: Detects when an account makes changes to the ingress or egress rules of a security group.
// This can indicate that an attacker is attempting to open up new attack vectors in the account, that they are trying to exfiltrate data over the network, or that they are trying to allow machines in that VPC/Subnet to contact a C&C server.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (eventSource == "ec2.amazonaws.com" and (eventName == "AuthorizeSecurityGroupEgress" or eventName == "AuthorizeSecurityGroupIngress" or eventName == "RevokeSecurityGroupEgress" or eventName == "RevokeSecurityGroupIngress"))
