// Title: Azure Container Registry Created or Deleted
// ID: 93e0ef48-37c8-49ed-a02c-038aab23628e
// Status: test
// Level: low
// Author: Austin Songer @austinsonger
// Date: 2021-08-07
// Tags: attack.impact, attack.t1485, attack.t1496, attack.t1489
// Description: Detects when a Container Registry is created or deleted.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((operationName == "MICROSOFT.CONTAINERREGISTRY/REGISTRIES/WRITE" or operationName == "MICROSOFT.CONTAINERREGISTRY/REGISTRIES/DELETE"))
