// Title: Azure Virtual Network Device Modified or Deleted
// ID: 15ef3fac-f0f0-4dc4-ada0-660aa72980b3
// Status: test
// Level: medium
// Author: Austin Songer @austinsonger
// Date: 2021-08-08
// Tags: attack.impact
// Description: Identifies when a virtual network device is being modified or deleted.
// This can be a network interface, network virtual appliance, virtual hub, or virtual router.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((operationName == "MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/WRITE" or operationName == "MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/DELETE" or operationName == "MICROSOFT.NETWORK/NETWORKINTERFACES/WRITE" or operationName == "MICROSOFT.NETWORK/NETWORKINTERFACES/JOIN/ACTION" or operationName == "MICROSOFT.NETWORK/NETWORKINTERFACES/DELETE" or operationName == "MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/DELETE" or operationName == "MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/WRITE" or operationName == "MICROSOFT.NETWORK/VIRTUALHUBS/DELETE" or operationName == "MICROSOFT.NETWORK/VIRTUALHUBS/WRITE" or operationName == "MICROSOFT.NETWORK/VIRTUALROUTERS/WRITE" or operationName == "MICROSOFT.NETWORK/VIRTUALROUTERS/DELETE"))
