// Title: Azure Network Firewall Policy Modified or Deleted
// ID: 83c17918-746e-4bd9-920b-8e098bf88c23
// Status: test
// Level: medium
// Author: Austin Songer @austinsonger
// Date: 2021-09-02
// Tags: attack.impact, attack.defense-impairment, attack.t1686.001
// Description: Identifies when a Firewall Policy is Modified or Deleted.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((operationName == "MICROSOFT.NETWORK/FIREWALLPOLICIES/WRITE" or operationName == "MICROSOFT.NETWORK/FIREWALLPOLICIES/JOIN/ACTION" or operationName == "MICROSOFT.NETWORK/FIREWALLPOLICIES/CERTIFICATES/ACTION" or operationName == "MICROSOFT.NETWORK/FIREWALLPOLICIES/DELETE"))
