// Title: Azure Application Deleted
// ID: 410d2a41-1e6d-452f-85e5-abdd8257a823
// Status: test
// Level: medium
// Author: Austin Songer @austinsonger
// Date: 2021-09-03
// Tags: attack.impact, attack.t1489
// Description: Identifies when a application is deleted in Azure.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((operationName == "Delete application" or operationName == "Hard Delete application" or operationName == "Delete administrative unit"))
