// Title: Too Many Global Admins
// ID: 7bbc309f-e2b1-4eb1-8369-131a367d67d3
// Status: test
// Level: high
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-14
// Tags: attack.initial-access, attack.stealth, attack.t1078, attack.persistence, attack.privilege-escalation
// Description: Identifies an event where there are there are too many accounts assigned the Global Administrator role.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (riskEventType == "tooManyGlobalAdminsAssignedToTenantAlertIncident")
