// Title: Suspicious Browser Activity
// ID: 944f6adb-7a99-4c69-80c1-b712579e93e6
// Status: test
// Level: high
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-03
// Tags: attack.stealth, attack.t1078, attack.persistence, attack.privilege-escalation, attack.initial-access
// Description: Indicates anomalous behavior based on suspicious sign-in activity across multiple tenants from different countries in the same browser
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (riskEventType == "suspiciousBrowser")
