// Title: Malicious IP Address Sign-In Failure Rate
// ID: a3f55ebd-0c01-4ed6-adc0-8fb76d8cd3cd
// Status: test
// Level: high
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-07
// Tags: attack.t1090, attack.command-and-control
// Description: Indicates sign-in from a malicious IP address based on high failure rates.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (riskEventType == "maliciousIPAddress")
