// Title: Anomalous User Activity
// ID: 258b6593-215d-4a26-a141-c8e31c1299a6
// Status: test
// Level: high
// Author: Mark Morowczynski '@markmorow', Gloria Lee, '@gleeiamglo'
// Date: 2023-09-03
// Tags: attack.privilege-escalation, attack.t1098, attack.persistence
// Description: Indicates that there are anomalous patterns of behavior like suspicious changes to the directory.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (riskEventType == "anomalousUserActivity")
