// Title: Bitbucket Secret Scanning Exempt Repository Added
// ID: b91e8d5e-0033-44fe-973f-b730316f23a1
// Status: test
// Level: high
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects when a repository is exempted from secret scanning feature.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (auditType.category == "Repositories" and auditType.action == "Secret scanning exempt repository added")
