// Title: Bitbucket Full Data Export Triggered
// ID: 195e1b9d-bfc2-4ffa-ab4e-35aef69815f8
// Status: test
// Level: high
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-02-25
// Tags: attack.collection, attack.t1213.003
// Description: Detects when full data export is attempted.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (auditType.category == "Data pipeline" and auditType.action == "Full data export triggered")
