// Title: Cisco Modify Configuration
// ID: 671ffc77-50a7-464f-9e3d-9ea2b493b26b
// Status: test
// Level: medium
// Author: Austin Clark
// Date: 2019-08-12
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.impact, attack.t1490, attack.t1505, attack.t1565.002, attack.t1053
// Description: Modifications to a config that will serve an adversary's impacts or persistence
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "ip http server" or * has "ip https server" or * has "kron policy-list" or * has "kron occurrence" or * has "policy-list" or * has "access-list" or * has "ip access-group" or * has "archive maximum" or * has "ntp server")
