// Title: Cisco LDP Authentication Failures
// ID: 50e606bf-04ce-4ca7-9d54-3449494bbd4b
// Status: test
// Level: low
// Author: Tim Brown
// Date: 2023-01-09
// Tags: attack.initial-access, attack.persistence, attack.privilege-escalation, attack.credential-access, attack.collection, attack.stealth, attack.t1078, attack.t1110, attack.t1557
// Description: Detects LDP failures which may be indicative of brute force attacks to manipulate MPLS labels
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((* has "LDP") and (* has "SOCKET_TCP_PACKET_MD5_AUTHEN_FAIL" or * has "TCPMD5AuthenFail"))
