// Title: Cisco Local Accounts
// ID: 6d844f0f-1c18-41af-8f19-33e7654edfc3
// Status: test
// Level: high
// Author: Austin Clark
// Date: 2019-08-12
// Tags: attack.privilege-escalation, attack.persistence, attack.t1136.001, attack.t1098
// Description: Find local accounts being created or modified as well as remote authentication configurations
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "username" or * has "aaa")
