// Title: Cisco Discovery
// ID: 9705a6a1-6db6-4a16-a987-15b7151e299b
// Status: test
// Level: low
// Author: Austin Clark
// Date: 2019-08-12
// Tags: attack.discovery, attack.t1083, attack.t1201, attack.t1057, attack.t1018, attack.t1082, attack.t1016, attack.t1049, attack.t1033, attack.t1124
// Description: Find information about network devices that is not stored in config files
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "dir" or * has "show arp" or * has "show cdp" or * has "show clock" or * has "show ip interface" or * has "show ip route" or * has "show ip sockets" or * has "show processes" or * has "show ssh" or * has "show users" or * has "show version")
