// Title: Unusual File Download from Direct IP Address
// ID: 025bd229-fd1f-4fdb-97ab-20006e1a5368
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), Florian Roth (Nextron Systems)
// Date: 2022-09-07
// Tags: attack.stealth, attack.t1564.004
// Description: Detects the download of suspicious file type from URLs with IP
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Contents matches regex @"http[s]?://[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}" and (FileName contains ".ps1:Zone" or FileName contains ".bat:Zone" or FileName contains ".exe:Zone" or FileName contains ".vbe:Zone" or FileName contains ".vbs:Zone" or FileName contains ".dll:Zone" or FileName contains ".one:Zone" or FileName contains ".cmd:Zone" or FileName contains ".hta:Zone" or FileName contains ".xll:Zone" or FileName contains ".lnk:Zone"))
