// Title: Potentially Suspicious File Download From ZIP TLD
// ID: 0bb4bbeb-fe52-4044-b40c-430a04577ebe
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2023-05-18
// Tags: attack.stealth
// Description: Detects the download of a file with a potentially suspicious extension from a .zip top level domain.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Contents contains ".zip/" and (FileName contains ".bat:Zone" or FileName contains ".dat:Zone" or FileName contains ".dll:Zone" or FileName contains ".doc:Zone" or FileName contains ".docm:Zone" or FileName contains ".exe:Zone" or FileName contains ".hta:Zone" or FileName contains ".pptm:Zone" or FileName contains ".ps1:Zone" or FileName contains ".rar:Zone" or FileName contains ".rtf:Zone" or FileName contains ".sct:Zone" or FileName contains ".vbe:Zone" or FileName contains ".vbs:Zone" or FileName contains ".ws:Zone" or FileName contains ".wsf:Zone" or FileName contains ".xll:Zone" or FileName contains ".xls:Zone" or FileName contains ".xlsm:Zone" or FileName contains ".zip:Zone"))
