// Title: DNS Server Discovery Via LDAP Query
// ID: a21bcd7e-38ec-49ad-b69a-9ea17e69509e
// Status: test
// Level: low
// Author: frack113
// Date: 2022-08-20
// Tags: attack.discovery, attack.t1482
// Description: Detects DNS server discovery via LDAP query requests from uncommon applications
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((QueryName startswith "_ldap.") and not(((FolderPath contains ":\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" and FolderPath endswith "\\MsMpEng.exe") or ((FolderPath contains ":\\Program Files\\" or FolderPath contains ":\\Program Files (x86)\\" or FolderPath contains ":\\Windows\\")) or ((isempty(FolderPath) or isnull(FolderPath))) or (FolderPath == "<unknown process>"))) and not(((FolderPath startswith "C:\\WindowsAzure\\GuestAgent") or ((FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\firefox.exe" or FolderPath endswith "\\opera.exe")))))
