// Title: Desktop.INI Created by Uncommon Process
// ID: 81315b50-6b60-4d8f-9928-3466e1022515
// Status: test
// Level: medium
// Author: Maxime Thiebaut (@0xThiebaut), Tim Shelton (HAWK.IO)
// Date: 2020-03-19
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.009
// Description: Detects unusual processes accessing desktop.ini, which can be leveraged to alter how Explorer displays a folder's content (i.e. renaming files) without changing them on disk.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FileName endswith "\\desktop.ini") and not((((FolderPath startswith "C:\\Windows\\" or FolderPath startswith "C:\\Program Files\\" or FolderPath startswith "C:\\Program Files (x86)\\")) or (FileName startswith "C:\\$WINDOWS.~BT\\NewOS\\"))) and not(((FolderPath startswith "C:\\Users\\" and FolderPath endswith "\\AppData\\Local\\JetBrains\\Toolbox\\bin\\7z.exe" and FileName contains "\\JetBrains\\apps\\") or (FolderPath startswith "C:\\Users\\" and FolderPath contains "\\AppData\\Local\\Microsoft\\OneDrive\\"))))
