// Title: Legitimate Application Dropped Archive
// ID: 654fcc6d-840d-4844-9b07-2c3300e54a26
// Status: test
// Level: high
// Author: frack113, Florian Roth
// Date: 2022-08-21
// Tags: attack.stealth, attack.t1218
// Description: Detects programs on a Windows system that should not write an archive to disk
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\winword.exe" or FolderPath endswith "\\excel.exe" or FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\msaccess.exe" or FolderPath endswith "\\mspub.exe" or FolderPath endswith "\\eqnedt32.exe" or FolderPath endswith "\\visio.exe" or FolderPath endswith "\\wordpad.exe" or FolderPath endswith "\\wordview.exe" or FolderPath endswith "\\certutil.exe" or FolderPath endswith "\\certoc.exe" or FolderPath endswith "\\CertReq.exe" or FolderPath endswith "\\Desktopimgdownldr.exe" or FolderPath endswith "\\esentutl.exe" or FolderPath endswith "\\finger.exe" or FolderPath endswith "\\notepad.exe" or FolderPath endswith "\\AcroRd32.exe" or FolderPath endswith "\\RdrCEF.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\hh.exe") and (FileName endswith ".zip" or FileName endswith ".rar" or FileName endswith ".7z" or FileName endswith ".diagcab" or FileName endswith ".appx"))
