// Title: Legitimate Application Dropped Executable
// ID: f0540f7e-2db3-4432-b9e0-3965486744bc
// Status: test
// Level: high
// Author: frack113, Florian Roth (Nextron Systems)
// Date: 2022-08-21
// Tags: attack.stealth, attack.t1218
// Description: Detects LOLBINs and applications that should not legitimately drop executable or executable-equivalent files to disk.
// This may indicate malware staging, process injection, or abuse of a trusted binary for payload delivery.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\eqnedt32.exe" or FolderPath endswith "\\wordpad.exe" or FolderPath endswith "\\wordview.exe" or FolderPath endswith "\\certutil.exe" or FolderPath endswith "\\certoc.exe" or FolderPath endswith "\\CertReq.exe" or FolderPath endswith "\\Desktopimgdownldr.exe" or FolderPath endswith "\\esentutl.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\AcroRd32.exe" or FolderPath endswith "\\RdrCEF.exe" or FolderPath endswith "\\hh.exe" or FolderPath endswith "\\finger.exe") and (FileName endswith ".com" or FileName endswith ".dll" or FileName endswith ".exe" or FileName endswith ".jar" or FileName endswith ".ocx" or FileName endswith ".pyc"))
