// Title: OneNote Attachment File Dropped In Suspicious Location
// ID: 7fd164ba-126a-4d9c-9392-0d4f7c243df0
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-22
// Tags: attack.stealth
// Description: Detects creation of files with the ".one"/".onepkg" extension in suspicious or uncommon locations. This could be a sign of attackers abusing OneNote attachments
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName contains "\\AppData\\Local\\Temp\\" or FileName contains "\\Users\\Public\\" or FileName contains "\\Windows\\Temp\\" or FileName contains ":\\Temp\\") and (FileName endswith ".one" or FileName endswith ".onepkg")) and not((FolderPath contains ":\\Program Files\\Microsoft Office\\" and FolderPath endswith "\\ONENOTE.EXE")))
