// Title: Suspicious Binaries and Scripts in Public Folder
// ID: b447f7de-1e53-4cbf-bfb4-f1f6d0b04e4e
// Status: experimental
// Level: high
// Author: The DFIR Report
// Date: 2025-01-23
// Tags: attack.execution, attack.t1204
// Description: Detects the creation of a file with a suspicious extension in the public folder, which could indicate potential malicious activity.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FileName contains ":\\Users\\Public\\" and (FileName endswith ".bat" or FileName endswith ".dll" or FileName endswith ".exe" or FileName endswith ".hta" or FileName endswith ".js" or FileName endswith ".ps1" or FileName endswith ".vbe" or FileName endswith ".vbs"))
