// Title: Suspicious DotNET CLR Usage Log Artifact
// ID: e0b06658-7d1d-4cd3-bf15-03467507ff7c
// Status: test
// Level: high
// Author: frack113, omkar72, oscd.community, Wojciech Lesicki
// Date: 2022-11-18
// Tags: attack.stealth, attack.t1218
// Description: Detects the creation of Usage Log files by the CLR (clr.dll). These files are named after the executing process once the assembly is finished executing for the first time in the (user) session context.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith "\\UsageLogs\\cmstp.exe.log" or FileName endswith "\\UsageLogs\\cscript.exe.log" or FileName endswith "\\UsageLogs\\mshta.exe.log" or FileName endswith "\\UsageLogs\\msxsl.exe.log" or FileName endswith "\\UsageLogs\\regsvr32.exe.log" or FileName endswith "\\UsageLogs\\rundll32.exe.log" or FileName endswith "\\UsageLogs\\svchost.exe.log" or FileName endswith "\\UsageLogs\\wscript.exe.log" or FileName endswith "\\UsageLogs\\wmic.exe.log")) and not((InitiatingProcessFolderPath endswith "\\MsiExec.exe" and InitiatingProcessCommandLine contains " -Embedding" and FolderPath endswith "\\rundll32.exe" and (ProcessCommandLine contains "Temp" and ProcessCommandLine contains "zzzzInvokeManagedCustomActionOutOfProc"))))
