// Title: Suspicious File Created In PerfLogs
// ID: bbb7e38c-0b41-4a11-b306-d2a457b7ac2b
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-05
// Tags: attack.execution, attack.t1059
// Description: Detects suspicious file based on their extension being created in "C:\PerfLogs\". Note that this directory mostly contains ".etl" files
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FileName startswith "C:\\PerfLogs\\" and (FileName endswith ".7z" or FileName endswith ".bat" or FileName endswith ".bin" or FileName endswith ".chm" or FileName endswith ".dll" or FileName endswith ".exe" or FileName endswith ".hta" or FileName endswith ".lnk" or FileName endswith ".ps1" or FileName endswith ".psm1" or FileName endswith ".py" or FileName endswith ".scr" or FileName endswith ".sys" or FileName endswith ".vbe" or FileName endswith ".vbs" or FileName endswith ".zip"))
