// Title: HackTool - Inveigh Execution Artefacts
// ID: bb09dd3e-2b78-4819-8e35-a7c1b874e449
// Status: test
// Level: critical
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-24
// Tags: attack.command-and-control, attack.t1219.002
// Description: Detects the presence and execution of Inveigh via dropped artefacts
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FileName endswith "\\Inveigh-Log.txt" or FileName endswith "\\Inveigh-Cleartext.txt" or FileName endswith "\\Inveigh-NTLMv1Users.txt" or FileName endswith "\\Inveigh-NTLMv2Users.txt" or FileName endswith "\\Inveigh-NTLMv1.txt" or FileName endswith "\\Inveigh-NTLMv2.txt" or FileName endswith "\\Inveigh-FormInput.txt" or FileName endswith "\\Inveigh.dll" or FileName endswith "\\Inveigh.exe" or FileName endswith "\\Inveigh.ps1" or FileName endswith "\\Inveigh-Relay.ps1"))
