// Title: Suspicious File Created Via OneNote Application
// ID: fcc6d700-68d9-4241-9a1a-06874d621b06
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-09
// Tags: attack.stealth
// Description: Detects suspicious files created via the OneNote application. This could indicate a potential malicious ".one"/".onepkg" file was executed as seen being used in malware activity in the wild
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\onenote.exe" or FolderPath endswith "\\onenotem.exe" or FolderPath endswith "\\onenoteim.exe") and FileName contains "\\AppData\\Local\\Temp\\OneNote\\" and (FileName endswith ".bat" or FileName endswith ".chm" or FileName endswith ".cmd" or FileName endswith ".dll" or FileName endswith ".exe" or FileName endswith ".hta" or FileName endswith ".htm" or FileName endswith ".html" or FileName endswith ".js" or FileName endswith ".lnk" or FileName endswith ".ps1" or FileName endswith ".vbe" or FileName endswith ".vbs" or FileName endswith ".wsf"))
