// Title: UAC Bypass Using EventVwr
// ID: 63e4f530-65dc-49cc-8f80-ccfa95c69d43
// Status: test
// Level: high
// Author: Antonio Cocomazzi (idea), Florian Roth (Nextron Systems)
// Date: 2022-04-27
// Tags: attack.privilege-escalation, attack.stealth
// Description: Detects the pattern of a UAC bypass using Windows Event Viewer
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith "\\Microsoft\\Event Viewer\\RecentViews" or FileName endswith "\\Microsoft\\EventV~1\\RecentViews")) and not(((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\"))))
