// Title: Potential SAM Database Dump
// ID: 4e87b8e2-2ee9-4b2a-a715-4727d297ece0
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-02-11
// Tags: attack.credential-access, attack.t1003.002
// Description: Detects the creation of files that look like exports of the local SAM (Security Account Manager)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith "\\Temp\\sam" or FileName endswith "\\sam.sav" or FileName endswith "\\Intel\\sam" or FileName endswith "\\sam.hive" or FileName endswith "\\Perflogs\\sam" or FileName endswith "\\ProgramData\\sam" or FileName endswith "\\Users\\Public\\sam" or FileName endswith "\\AppData\\Local\\sam" or FileName endswith "\\AppData\\Roaming\\sam" or FileName endswith "_ShadowSteal.zip" or FileName endswith "\\Documents\\SAM.export" or FileName endswith ":\\sam")) or ((FileName contains "\\hive_sam_" or FileName contains "\\sam.save" or FileName contains "\\sam.export" or FileName contains "\\~reg_sam.save" or FileName contains "\\sam_backup" or FileName contains "\\sam.bck" or FileName contains "\\sam.backup")))
