// Title: .RDP File Created By Uncommon Application
// ID: fccfb43e-09a7-4bd2-8b37-a5a7df33386d
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-18
// Tags: attack.stealth
// Description: Detects creation of a file with an ".rdp" extension by an application that doesn't commonly create such files.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FileName endswith ".rdp" and (FolderPath endswith "\\brave.exe" or FolderPath endswith "\\CCleaner Browser\\Application\\CCleanerBrowser.exe" or FolderPath endswith "\\chromium.exe" or FolderPath endswith "\\firefox.exe" or FolderPath endswith "\\Google\\Chrome\\Application\\chrome.exe" or FolderPath endswith "\\iexplore.exe" or FolderPath endswith "\\microsoftedge.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\Opera.exe" or FolderPath endswith "\\Vivaldi.exe" or FolderPath endswith "\\Whale.exe" or FolderPath endswith "\\olk.exe" or FolderPath endswith "\\Outlook.exe" or FolderPath endswith "\\RuntimeBroker.exe" or FolderPath endswith "\\Thunderbird.exe" or FolderPath endswith "\\Discord.exe" or FolderPath endswith "\\Keybase.exe" or FolderPath endswith "\\msteams.exe" or FolderPath endswith "\\Slack.exe" or FolderPath endswith "\\teams.exe"))
