// Title: Potential File Extension Spoofing Using Right-to-Left Override
// ID: 979baf41-ca44-4540-9d0c-4fcef3b5a3a4
// Status: test
// Level: high
// Author: Jonathan Peters (Nextron Systems), Florian Roth (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2024-11-17
// Tags: attack.execution, attack.stealth, attack.t1036.002
// Description: Detects suspicious filenames that contain a right-to-left override character and a potentially spoofed file extensions.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName contains "3pm." or FileName contains "4pm." or FileName contains "cod." or FileName contains "fdp." or FileName contains "ftr." or FileName contains "gepj." or FileName contains "gnp." or FileName contains "gpj." or FileName contains "ism." or FileName contains "lmth." or FileName contains "nls." or FileName contains "piz." or FileName contains "slx." or FileName contains "tdo." or FileName contains "vsc." or FileName contains "vwm." or FileName contains "xcod." or FileName contains "xslx." or FileName contains "xtpp.")) and ((FileName contains "\\u202e" or FileName contains "[U+202E]" or FileName contains "‮")))
