// Title: VHD Image Download Via Browser
// ID: 8468111a-ef07-4654-903b-b863a80bbc95
// Status: test
// Level: medium
// Author: frack113, Christopher Peacock '@securepeacock', SCYTHE '@scythe_io'
// Date: 2021-10-25
// Tags: attack.resource-development, attack.t1587.001
// Description: Detects creation of ".vhd"/".vhdx" files by browser processes.
// Malware can use mountable Virtual Hard Disk ".vhd" files to encapsulate payloads and evade security controls.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\firefox.exe" or FolderPath endswith "\\iexplore.exe" or FolderPath endswith "\\maxthon.exe" or FolderPath endswith "\\MicrosoftEdge.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\msedgewebview2.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\safari.exe" or FolderPath endswith "\\seamonkey.exe" or FolderPath endswith "\\vivaldi.exe" or FolderPath endswith "\\whale.exe") and FileName contains ".vhd")
