// Title: Potential Persistence Via Microsoft Office Add-In
// ID: 8e1cb247-6cf6-42fa-b440-3f27d57e9936
// Status: test
// Level: high
// Author: NVISO
// Date: 2020-05-11
// Tags: attack.persistence, attack.t1137.006
// Description: Detects potential persistence activity via startup add-ins that load when Microsoft Office starts (.wll/.xll are simply .dll fit for Word or Excel).
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FileName contains "\\Microsoft\\Addins\\" and (FileName endswith ".xlam" or FileName endswith ".xla" or FileName endswith ".ppam")) or (FileName contains "\\Microsoft\\Word\\Startup\\" and FileName endswith ".wll") or (FileName contains "Microsoft\\Excel\\XLSTART\\" and FileName endswith ".xlam") or (FileName contains "\\Microsoft\\Excel\\Startup\\" and FileName endswith ".xll"))
