// Title: BloodHound Collection Files
// ID: 02773bed-83bf-469f-b7ff-e676e7d78bab
// Status: test
// Level: high
// Author: C.J. May
// Date: 2022-08-09
// Tags: attack.discovery, attack.t1087.001, attack.t1087.002, attack.t1482, attack.t1069.001, attack.t1069.002, attack.execution, attack.t1059.001
// Description: Detects default file names outputted by the BloodHound collection tool SharpHound
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith "BloodHound.zip" or FileName endswith "_computers.json" or FileName endswith "_containers.json" or FileName endswith "_gpos.json" or FileName endswith "_groups.json" or FileName endswith "_ous.json" or FileName endswith "_users.json")) and not((FolderPath endswith "\\svchost.exe" and FileName startswith "C:\\Program Files\\WindowsApps\\Microsoft." and FileName endswith "\\pocket_containers.json")))
