// Title: Potential WSL Binary Modification from Installed Location
// ID: 2f400434-01e1-416b-b52c-bb5bfbb9eb78
// Status: experimental
// Level: medium
// Author: Liran Ravich, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-05-05
// Tags: attack.stealth, attack.t1036.005, attack.t1218
// Description: Detects the modification of the wsl.exe binary from its installed location.
// Attackers can replace the legitimate wsl.exe binary with a malicious payload in its place, which is then executed when the user runs WSL, acting as a proxy execution and defense evasion technique.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith "\\wsl.exe") and (((FileName contains ":\\Program files\\wsl\\" or FileName contains ":\\Program files\\WindowsApps\\MicrosoftCorporationII.WindowsSubsystemForLinux_")) or ((FileName contains ":\\Users\\" and FileName contains "\\AppData\\Local\\Microsoft\\WindowsApps\\")))) and not((((FolderPath == "C:\\Windows\\System32\\msiexec.exe" or FolderPath == "C:\\Windows\\SysWOW64\\msiexec.exe")) or (FolderPath == "C:\\Windows\\System32\\svchost.exe" and FileName contains "\\WindowsApps\\"))))
