// Title: Suspicious File Created in Outlook Temporary Directory
// ID: fabb0e80-030c-4e3e-a104-d09676991ac3
// Status: experimental
// Level: high
// Author: Florian Roth (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-07-22
// Tags: attack.initial-access, attack.t1566.001
// Description: Detects the creation of files with suspicious file extensions in the temporary directory that Outlook uses when opening attachments.
// This can be used to detect spear-phishing campaigns that use suspicious files as attachments, which may contain malicious code.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith ".cpl" or FileName endswith ".hta" or FileName endswith ".iso" or FileName endswith ".rdp" or FileName endswith ".svg" or FileName endswith ".vba" or FileName endswith ".vbe" or FileName endswith ".vbs")) and (((FileName contains "\\AppData\\Local\\Packages\\Microsoft.Outlook_" or FileName contains "\\AppData\\Local\\Microsoft\\Olk\\Attachments\\")) or ((FileName contains "\\AppData\\Local\\Microsoft\\Windows\\" and FileName contains "\\Content.Outlook\\"))))
