// Title: Office Macro File Creation From Suspicious Process
// ID: b1c50487-1967-4315-a026-6491686d860e
// Status: test
// Level: high
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-23
// Tags: attack.initial-access, attack.t1566.001
// Description: Detects the creation of a office macro file from a a suspicious process
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\wscript.exe")) or ((InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\regsvr32.exe" or InitiatingProcessFolderPath endswith "\\rundll32.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe"))) and ((FileName endswith ".docm" or FileName endswith ".dotm" or FileName endswith ".xlsm" or FileName endswith ".xltm" or FileName endswith ".potm" or FileName endswith ".pptm")))
