// Title: Suspicious ASPX File Drop by Exchange
// ID: bd1212e5-78da-431e-95fa-c58e3237a8e6
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), MSTI (query, idea)
// Date: 2022-10-01
// Tags: attack.persistence, attack.t1505.003
// Description: Detects suspicious file type dropped by an Exchange component in IIS into a suspicious folder
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\w3wp.exe" and ProcessCommandLine contains "MSExchange" and (FileName contains "FrontEnd\\HttpProxy\\" or FileName contains "\\inetpub\\wwwroot\\aspnet_client\\")) and ((FileName endswith ".aspx" or FileName endswith ".asp" or FileName endswith ".ashx")))
