// Title: Startup Folder File Write
// ID: 2aa0a6b4-a865-495b-ab51-c28249537b75
// Status: test
// Level: medium
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
// Description: A General detection for files being created in the Windows startup directory. This could be an indicator of persistence.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FileName contains "\\Microsoft\\Windows\\Start Menu\\Programs\\StartUp") and not((((FolderPath == "C:\\Windows\\System32\\wuauclt.exe" or FolderPath == "C:\\Windows\\uus\\ARM64\\wuaucltcore.exe")) or ((FileName startswith "C:\\$WINDOWS.~BT\\NewOS\\" or FileName startswith "C:\\$WinREAgent\\Scratch\\Mount\\")))) and not((FolderPath endswith "\\ONENOTE.EXE" and FileName endswith "\\Send to OneNote.lnk")))
