// Title: Suspicious File Drop by Exchange
// ID: 6b269392-9eba-40b5-acb6-55c882b20ba6
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2022-10-04
// Tags: attack.persistence, attack.t1190, attack.initial-access, attack.t1505.003
// Description: Detects suspicious file type dropped by an Exchange component in IIS
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\w3wp.exe" and ProcessCommandLine contains "MSExchange") and ((FileName endswith ".aspx" or FileName endswith ".asp" or FileName endswith ".ashx" or FileName endswith ".ps1" or FileName endswith ".bat" or FileName endswith ".exe" or FileName endswith ".dll" or FileName endswith ".vbs")))
