// Title: Office Macro File Creation
// ID: 91174a41-dc8f-401b-be89-7bfc140612a0
// Status: test
// Level: low
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-23
// Tags: attack.initial-access, attack.t1566.001
// Description: Detects the creation of a new office macro files on the systems
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith ".docm" or FileName endswith ".dotm" or FileName endswith ".xlsm" or FileName endswith ".xltm" or FileName endswith ".potm" or FileName endswith ".pptm")) and not(((FolderPath startswith "C:\\Program Files\\Microsoft Office\\" or FolderPath startswith "C:\\Program Files (x86)\\Microsoft Office\\") and (FolderPath endswith "\\WINWORD.EXE" or FolderPath endswith "\\EXCEL.EXE" or FolderPath endswith "\\POWERPNT.EXE") and FileName contains "\\~$")))
