// Title: Suspicious Executable File Creation
// ID: 74babdd6-a758-4549-9632-26535279e654
// Status: test
// Level: high
// Author: frack113
// Date: 2022-09-05
// Tags: attack.stealth, attack.t1564
// Description: Detect creation of suspicious executable file names.
// Some strings look for suspicious file extensions, others look for filenames that exploit unquoted service paths.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FileName endswith ":\\$Recycle.Bin.exe" or FileName endswith ":\\Documents and Settings.exe" or FileName endswith ":\\MSOCache.exe" or FileName endswith ":\\PerfLogs.exe" or FileName endswith ":\\Recovery.exe" or FileName endswith ".bat.exe" or FileName endswith ".sys.exe"))
