// Title: Creation of WerFault.exe/Wer.dll in Unusual Folder
// ID: 28a452f3-786c-4fd8-b8f2-bddbe9d616d1
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-05-09
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.stealth, attack.t1574.001
// Description: Detects the creation of a file named "WerFault.exe" or "wer.dll" in an uncommon folder, which could be a sign of WerFault DLL hijacking.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FileName endswith "\\WerFault.exe" or FileName endswith "\\wer.dll")) and not((((FileName startswith "C:\\Windows\\SoftwareDistribution\\" or FileName startswith "C:\\Windows\\System32\\" or FileName startswith "C:\\Windows\\SysWOW64\\" or FileName startswith "C:\\Windows\\WinSxS\\" or FileName startswith "C:\\Windows\\UUS\\")) or (FolderPath endswith "\\wuaucltcore.exe"))))
