// Title: Uncommon File Created by Notepad++ Updater Gup.EXE
// ID: 3b8f4c92-6a51-4d7e-9c3a-8e2d1f5a7b09
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-02-03
// Tags: attack.collection, attack.credential-access, attack.t1195.002, attack.initial-access, attack.t1557
// Description: Detects when the Notepad++ updater (gup.exe) creates files in suspicious or uncommon locations.
// This could indicate potential exploitation of the updater component to deliver unwanted malware or unwarranted files.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\gup.exe") and not((((FileName startswith "C:\\Program Files\\Notepad++\\" or FileName startswith "C:\\Program Files (x86)\\Notepad++\\")) or (((FileName contains "\\plugins\\JsonTools\\testfiles\\" or FileName contains "\\Notepad++\\plugins\\ComparePlugin\\")) or ((FileName contains "npp." and FileName contains ".portable." and FileName contains "\\plugins\\"))) or (FileName startswith "C:\\$Recycle.Bin\\S-1-5-21") or (FileName startswith "C:\\Users\\" and (FileName contains "\\AppData\\Local\\Temp\\" and FileName contains ".zip")) or (FileName startswith "C:\\Users\\" and (FileName contains "\\AppData\\Local\\Temp\\" and FileName contains "npp." and FileName contains ".Installer." and FileName contains ".exe")))))
