// Title: Suspicious File Creation In Uncommon AppData Folder
// ID: d7b50671-d1ad-4871-aa60-5aa5b331fe04
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-05
// Tags: attack.execution, attack.stealth
// Description: Detects the creation of suspicious files and folders inside the user's AppData folder but not inside any of the common and well known directories (Local, Romaing, LocalLow). This method could be used as a method to bypass detection who exclude the AppData folder in fear of FPs
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FileName startswith "C:\\Users\\" and FileName contains "\\AppData\\" and (FileName endswith ".bat" or FileName endswith ".cmd" or FileName endswith ".cpl" or FileName endswith ".dll" or FileName endswith ".exe" or FileName endswith ".hta" or FileName endswith ".iso" or FileName endswith ".lnk" or FileName endswith ".msi" or FileName endswith ".ps1" or FileName endswith ".psm1" or FileName endswith ".scr" or FileName endswith ".vbe" or FileName endswith ".vbs")) and not((FileName startswith "C:\\Users\\" and (FileName contains "\\AppData\\Local\\" or FileName contains "\\AppData\\LocalLow\\" or FileName contains "\\AppData\\Roaming\\"))))
