// Title: Potential Webshell Creation On Static Website
// ID: 39f1f9f2-9636-45de-98f6-a4046aa8e4b9
// Status: test
// Level: medium
// Author: Beyu Denis, oscd.community, Tim Shelton, Thurein Oo
// Date: 2019-10-22
// Tags: attack.persistence, attack.t1505.003
// Description: Detects the creation of files with certain extensions on a static web site. This can be indicative of potential uploads of a web shell.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((FileName contains ".ashx" or FileName contains ".asp" or FileName contains ".ph" or FileName contains ".soap")) and (FileName contains "\\inetpub\\wwwroot\\")) or ((FileName contains ".ph") and ((FileName contains "\\www\\" or FileName contains "\\htdocs\\" or FileName contains "\\html\\")))) and not(((FileName contains "\\xampp") or (FolderPath == "System") or ((FileName contains "\\AppData\\Local\\Temp\\" or FileName contains "\\Windows\\Temp\\")))))
