// Title: EventLog EVTX File Deleted
// ID: 63c779ba-f638-40a0-a593-ddd45e8b1ddc
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-15
// Tags: attack.stealth, attack.t1070
// Description: Detects the deletion of the event log files which may indicate an attempt to destroy forensic evidence
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FileName startswith "C:\\Windows\\System32\\winevt\\Logs\\" and FileName endswith ".evtx")
