// Title: PowerShell Core DLL Loaded Via Office Application
// ID: bb2ba6fb-95d4-4a25-89fc-30bb736c021a
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-01
// Tags: attack.stealth
// Description: Detects PowerShell core DLL being loaded by an Office Product
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\excel.exe" or FolderPath endswith "\\mspub.exe" or FolderPath endswith "\\outlook.exe" or FolderPath endswith "\\onenote.exe" or FolderPath endswith "\\onenoteim.exe" or FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\winword.exe") and (ImageLoaded contains "\\System.Management.Automation.Dll" or ImageLoaded contains "\\System.Management.Automation.ni.Dll"))
