// Title: Potential Chrome Frame Helper DLL Sideloading
// ID: 72ca7c75-bf85-45cd-aca7-255d360e423c
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Wietze Beukema (project and research)
// Date: 2022-08-17
// Tags: attack.persistence, attack.privilege-escalation, attack.execution, attack.stealth, attack.t1574.001
// Description: Detects potential DLL sideloading of "chrome_frame_helper.dll"
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ImageLoaded endswith "\\chrome_frame_helper.dll") and not(((ImageLoaded startswith "C:\\Program Files\\Google\\Chrome\\Application\\" or ImageLoaded startswith "C:\\Program Files (x86)\\Google\\Chrome\\Application\\"))) and not((ImageLoaded contains "\\AppData\\local\\Google\\Chrome\\Application\\")))
