// Title: VBA DLL Loaded Via Office Application
// ID: e6ce8457-68b1-485b-9bdd-3c2b5d679aa9
// Status: test
// Level: high
// Author: Antonlovesdnb
// Date: 2020-02-19
// Tags: attack.execution, attack.t1204.002
// Description: Detects VB DLL's loaded by an office application. Which could indicate the presence of VBA Macros.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\excel.exe" or FolderPath endswith "\\mspub.exe" or FolderPath endswith "\\onenote.exe" or FolderPath endswith "\\onenoteim.exe" or FolderPath endswith "\\outlook.exe" or FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\winword.exe") and (ImageLoaded endswith "\\VBE7.DLL" or ImageLoaded endswith "\\VBEUI.DLL" or ImageLoaded endswith "\\VBE7INTL.DLL"))
