// Title: DotNET Assembly DLL Loaded Via Office Application
// ID: ff0f2b05-09db-4095-b96d-1b75ca24894a
// Status: test
// Level: medium
// Author: Antonlovesdnb
// Date: 2020-02-19
// Tags: attack.execution, attack.t1204.002
// Description: Detects any assembly DLL being loaded by an Office Product
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\excel.exe" or FolderPath endswith "\\mspub.exe" or FolderPath endswith "\\onenote.exe" or FolderPath endswith "\\onenoteim.exe" or FolderPath endswith "\\outlook.exe" or FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\winword.exe") and ImageLoaded startswith "C:\\Windows\\assembly\\")
