// Title: Potential DLL Sideloading Of DbgModel.DLL
// ID: fef394cd-f44d-4040-9b18-95d92fe278c0
// Status: test
// Level: medium
// Author: Gary Lobermier
// Date: 2024-07-11
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.stealth, attack.t1574.001
// Description: Detects potential DLL sideloading of "DbgModel.dll"
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ImageLoaded endswith "\\dbgmodel.dll") and not(((ImageLoaded startswith "C:\\Windows\\System32\\" or ImageLoaded startswith "C:\\Windows\\SysWOW64\\" or ImageLoaded startswith "C:\\Windows\\WinSxS\\"))) and not(((ImageLoaded startswith "C:\\Program Files\\WindowsApps\\Microsoft.WinDbg_") or ((ImageLoaded startswith "C:\\Program Files (x86)\\Windows Kits\\" or ImageLoaded startswith "C:\\Program Files\\Windows Kits\\")))))
