// Title: Microsoft Excel Add-In Loaded From Uncommon Location
// ID: af4c4609-5755-42fe-8075-4effb49f5d44
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-12
// Tags: attack.execution, attack.t1204.002
// Description: Detects Microsoft Excel loading an Add-In (.xll) file from an uncommon location
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FolderPath endswith "\\excel.exe" and (ImageLoaded contains "\\Desktop\\" or ImageLoaded contains "\\Downloads\\" or ImageLoaded contains "\\Perflogs\\" or ImageLoaded contains "\\Temp\\" or ImageLoaded contains "\\Users\\Public\\" or ImageLoaded contains "\\Windows\\Tasks\\") and ImageLoaded endswith ".xll")
