// Title: Python Image Load By Non-Python Process
// ID: cbb56d62-4060-40f7-9466-d8aaf3123f83
// Status: test
// Level: low
// Author: Patrick St. John, OTR (Open Threat Research)
// Date: 2020-05-03
// Tags: attack.stealth, attack.t1027.002
// Description: Detects the image load of "Python Core" by a non-Python process. This might be indicative of a execution of executable that has been bundled from Python code.
// Various tools like Py2Exe, PyInstaller, and cx_Freeze are used to bundle Python code into standalone executables.
// Threat actors often use these tools to bundle malicious Python scripts into executables, sometimes to obfuscate the code or to bypass security measures.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Description == "Python Core") and not(((FolderPath contains "Python") or ((FolderPath startswith "C:\\Program Files\\" or FolderPath startswith "C:\\Program Files (x86)\\" or FolderPath startswith "C:\\ProgramData\\Anaconda3\\")))) and not(((isempty(FolderPath) or isnull(FolderPath)))))
