// Title: Potential Python DLL SideLoading
// ID: d36f7c12-14a3-4d48-b6b8-774b9c66f44d
// Status: test
// Level: medium
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-10-06
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.stealth, attack.t1574.001
// Description: Detects potential DLL sideloading of Python DLL files.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ImageLoaded endswith "\\python39.dll" or ImageLoaded endswith "\\python310.dll" or ImageLoaded endswith "\\python311.dll" or ImageLoaded endswith "\\python312.dll")) and not(((((ImageLoaded startswith "C:\\Program Files\\Python3" or ImageLoaded startswith "C:\\Program Files (x86)\\Python3")) or (ImageLoaded contains "\\AppData\\Local\\Programs\\Python\\Python3")) or (Product == "Python" and Signed == "true" and Description == "Python" and Company == "Python Software Foundation"))) and not(((ImageLoaded startswith "C:\\ProgramData\\Anaconda3\\") or ((ImageLoaded contains "\\cpython\\externals\\" or ImageLoaded contains "\\cpython\\PCbuild\\")) or (ImageLoaded startswith "C:\\Users" and ImageLoaded contains "\\AppData\\Local\\Temp\\_MEI") or (ImageLoaded startswith "C:\\Program Files\\Microsoft Visual Studio\\"))))
