// Title: DotNet CLR DLL Loaded By Scripting Applications
// ID: 4508a70e-97ef-4300-b62b-ff27992990ea
// Status: test
// Level: high
// Author: omkar72, oscd.community
// Date: 2020-10-14
// Tags: attack.execution, attack.privilege-escalation, attack.stealth, attack.t1055
// Description: Detects .NET CLR DLLs being loaded by scripting applications such as wscript or cscript. This could be an indication of potential suspicious execution.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\cmstp.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\msxsl.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\wmic.exe" or FolderPath endswith "\\wscript.exe") and (ImageLoaded endswith "\\clr.dll" or ImageLoaded endswith "\\mscoree.dll" or ImageLoaded endswith "\\mscorlib.dll"))
