// Title: CLR DLL Loaded Via Office Applications
// ID: d13c43f0-f66b-4279-8b2c-5912077c1780
// Status: test
// Level: medium
// Author: Antonlovesdnb
// Date: 2020-02-19
// Tags: attack.execution, attack.t1204.002
// Description: Detects CLR DLL being loaded by an Office Product
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\excel.exe" or FolderPath endswith "\\mspub.exe" or FolderPath endswith "\\outlook.exe" or FolderPath endswith "\\onenote.exe" or FolderPath endswith "\\onenoteim.exe" or FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\winword.exe") and ImageLoaded contains "\\clr.dll")
