// Title: Potentially Suspicious Volume Shadow Copy Vsstrace.dll Load
// ID: 48bfd177-7cf2-412b-ad77-baf923489e82
// Status: test
// Level: medium
// Author: frack113
// Date: 2023-02-17
// Tags: attack.impact, attack.t1490
// Description: Detects the image load of VSS DLL by uncommon executables
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ImageLoaded endswith "\\vsstrace.dll") and not((((isempty(FolderPath) or isnull(FolderPath))) or ((FolderPath startswith "C:\\Program Files\\" or FolderPath startswith "C:\\Program Files (x86)\\")) or (((FolderPath == "C:\\Windows\\explorer.exe" or FolderPath == "C:\\Windows\\ImmersiveControlPanel\\SystemSettings.exe" or FolderPath == "C:\\Windows\\servicing\\TrustedInstaller.exe")) or ((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\" or FolderPath startswith "C:\\Windows\\Temp\\{" or FolderPath startswith "C:\\Windows\\WinSxS\\" or FolderPath startswith "C:\\ProgramData\\Package Cache\\{"))))) and not((((FolderPath contains "\\temp\\is-" and FolderPath contains "\\avira_system_speedup.tmp")) or (FolderPath startswith "C:\\$WinREAgent\\Scratch\\"))))
