// Title: Suspicious Use of /dev/tcp
// ID: 6cc5fceb-9a71-4c23-aeeb-963abe0b279c
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-12-10
// Tags: attack.reconnaissance
// Description: Detects suspicious command with /dev/tcp
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "cat </dev/tcp/" or * has "exec 3<>/dev/tcp/" or * has "echo >/dev/tcp/" or * has "bash -i >& /dev/tcp/" or * has "sh -i >& /dev/udp/" or * has "0<&196;exec 196<>/dev/tcp/" or * has "exec 5<>/dev/tcp/" or * has "(sh)0>/dev/tcp/" or * has "bash -c 'bash -i >& /dev/tcp/" or * has "echo -e '#!/bin/bash\\nbash -i >& /dev/tcp/")
