// Title: Suspicious Commands Linux
// ID: 1543ae20-cbdf-4ec1-8d12-7664d667a825
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2017-12-12
// Tags: attack.execution, attack.t1059.004
// Description: Detects relevant commands often related to malware or hacking activity
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((type == "EXECVE" and a0 == "chmod" and a1 == 777) or (type == "EXECVE" and a0 == "chmod" and a1 == "u+s") or (type == "EXECVE" and a0 == "cp" and a1 == "/bin/ksh") or (type == "EXECVE" and a0 == "cp" and a1 == "/bin/sh"))
