// Title: Suspicious OpenSSH Daemon Error
// ID: e76b413a-83d0-4b94-8e4c-85db4a5b8bdc
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2017-06-30
// Tags: attack.initial-access, attack.t1190
// Description: Detects suspicious SSH / SSHD error messages that indicate a fatal or suspicious error that could be caused by exploiting attempts
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "unexpected internal error" or * has "unknown or unsupported key type" or * has "invalid certificate signing key" or * has "invalid elliptic curve value" or * has "incorrect signature" or * has "error in libcrypto" or * has "unexpected bytes remain after decoding" or * has "fatal: buffer_get_string: bad string" or * has "Local: crc32 compensation attack" or * has "bad client public DH value" or * has "Corrupted MAC on input")
