// Title: Relevant ClamAV Message
// ID: 36aa86ca-fd9d-4456-814e-d3b1b8e1e0bb
// Status: stable
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2017-03-01
// Tags: attack.resource-development, attack.t1588.001
// Description: Detects relevant ClamAV messages
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "Trojan*FOUND" or * has "VirTool*FOUND" or * has "Webshell*FOUND" or * has "Rootkit*FOUND" or * has "Htran*FOUND")
