// Title: Modify System Firewall
// ID: 323ff3f5-0013-4847-bbd4-250b5edb62cc
// Status: test
// Level: medium
// Author: IAI
// Date: 2023-03-06
// Tags: attack.defense-impairment, attack.t1686
// Description: Detects the removal of system firewall rules. Adversaries may only delete or modify a specific system firewall rule to bypass controls limiting network usage or access.
// Detection rules that match only on the disabling of firewalls will miss this.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((type == "EXECVE" and a0 == "iptables" and a1 contains "DROP") or (type == "EXECVE" and a0 == "firewall-cmd" and a1 contains "remove") or (type == "EXECVE" and a0 == "ufw" and a1 contains "delete") or (type == "EXECVE" and a0 == "nft" and (a1 contains "delete" or a1 contains "flush")))
