// Title: Suspicious Activity in Shell Commands
// ID: 2aa1440c-9ae9-4d92-84a7-a9e5f5e31695
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2017-08-21
// Tags: attack.execution, attack.t1059.004
// Description: Detects suspicious shell commands used in various exploit codes (see references)
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "wget * - http* | perl" or * has "wget * - http* | sh" or * has "wget * - http* | bash" or * has "python -m SimpleHTTPServer" or * has "-m http.server" or * has "import pty; pty.spawn*" or * has "socat exec:*" or * has "socat -O /tmp/*" or * has "socat tcp-connect*" or * has "*echo binary >>*" or * has "*wget *; chmod +x*" or * has "*wget *; chmod 777 *" or * has "*cd /tmp || cd /var/run || cd /mnt*" or * has "*stop;service iptables stop;*" or * has "*stop;SuSEfirewall2 stop;*" or * has "chmod 777 2020*" or * has "*>>/etc/rc.local" or * has "*base64 -d /tmp/*" or * has "* | base64 -d *" or * has "*/chmod u+s *" or * has "*chmod +s /tmp/*" or * has "*chmod u+s /tmp/*" or * has "* /tmp/haxhax*" or * has "* /tmp/ns_sploit*" or * has "nc -l -p *" or * has "cp /bin/ksh *" or * has "cp /bin/sh *" or * has "* /tmp/*.b64 *" or * has "*/tmp/ysocereal.jar*" or * has "*/tmp/x *" or * has "*; chmod +x /tmp/*" or * has "*;chmod +x /tmp/*")
