// Title: Suspicious History File Operations - Linux
// ID: eae8ce9f-bde9-47a6-8e79-f20d18419910
// Status: test
// Level: medium
// Author: Mikhail Larin, oscd.community
// Date: 2020-10-17
// Tags: attack.credential-access, attack.t1552.003
// Description: Detects commandline operations on shell history files
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((type == "EXECVE") and (* has ".bash_history" or * has ".zsh_history" or * has ".zhistory" or * has ".history" or * has ".sh_history" or * has "fish_history"))
