// Title: Suspicious VSFTPD Error Messages
// ID: 377f33a1-4b36-4ee1-acee-1dbe4b43cfbe
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2017-07-05
// Tags: attack.initial-access, attack.t1190
// Description: Detects suspicious VSFTPD error messages that indicate a fatal or suspicious error that could be caused by exploiting attempts
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "Connection refused: too many sessions for this address." or * has "Connection refused: tcp_wrappers denial." or * has "Bad HTTP verb." or * has "port and pasv both active" or * has "pasv and port both active" or * has "Transfer done (but failed to open directory)." or * has "Could not set file modification time." or * has "bug: pid active in ptrace_sandbox_free" or * has "PTRACE_SETOPTIONS failure" or * has "weird status:" or * has "couldn't handle sandbox event" or * has "syscall * out of bounds" or * has "syscall not permitted:" or * has "syscall validate failed:" or * has "Input line too long." or * has "poor buffer accounting in str_netfd_alloc" or * has "vsf_sysutil_read_loop")
