// Title: Disabling Security Tools - Builtin
// ID: 49f5dfc1-f92e-4d34-96fa-feba3f6acf36
// Status: test
// Level: medium
// Author: Ömer Günal, Alejandro Ortuno, oscd.community
// Date: 2020-06-17
// Tags: attack.defense-impairment, attack.t1686
// Description: Detects disabling security tools
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "stopping iptables" or * has "stopping ip6tables" or * has "stopping firewalld" or * has "stopping cbdaemon" or * has "stopping falcon-sensor")
