// Title: Communication To Ngrok Tunneling Service Initiated
// ID: 1d08ac94-400d-4469-a82f-daee9a908849
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-11-03
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567, attack.t1568.002, attack.t1572, attack.t1090, attack.t1102, attack.s0508
// Description: Detects an executable initiating a network connection to "ngrok" tunneling domains.
// Attackers were seen using this "ngrok" in order to store their second stage payloads and malware.
// While communication with such domains can be legitimate, often times is a sign of either data exfiltration by malicious actors or additional download.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((DestinationHostname contains "tunnel.us.ngrok.com" or DestinationHostname contains "tunnel.eu.ngrok.com" or DestinationHostname contains "tunnel.ap.ngrok.com" or DestinationHostname contains "tunnel.au.ngrok.com" or DestinationHostname contains "tunnel.sa.ngrok.com" or DestinationHostname contains "tunnel.jp.ngrok.com" or DestinationHostname contains "tunnel.in.ngrok.com"))
