// Title: Outbound Network Connection Initiated By Script Interpreter
// ID: 992a6cae-db6a-43c8-9cec-76d7195c96fc
// Status: test
// Level: high
// Author: frack113, Florian Roth (Nextron Systems)
// Date: 2022-08-28
// Tags: attack.command-and-control, attack.t1105
// Description: Detects a script interpreter wscript/cscript opening a network connection to a non-local network. Adversaries may use script to download malicious payloads.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Initiated == "true" and (FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe")) and not((((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7"))) or (ipv4_is_in_range(RemoteIP, "20.0.0.0/11")))))
