// Title: Suspicious Outbound SMTP Connections
// ID: 9976fa64-2804-423c-8a5b-646ade840773
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-01-07
// Tags: attack.exfiltration, attack.t1048.003
// Description: Adversaries may steal data by exfiltrating it over an un-encrypted network protocol other than that of the existing command and control channel.
// The data may also be sent to an alternate network location from the main command and control server.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RemotePort == 25 or RemotePort == 587 or RemotePort == 465 or RemotePort == 2525) and Initiated == "true") and not((((FolderPath endswith "\\thunderbird.exe" or FolderPath endswith "\\outlook.exe")) or (FolderPath startswith "C:\\Program Files\\Microsoft\\Exchange Server\\") or (FolderPath startswith "C:\\Program Files\\WindowsApps\\microsoft.windowscommunicationsapps_" and FolderPath endswith "\\HxTsr.exe"))))
