// Title: Potential Remote PowerShell Session Initiated
// ID: c539afac-c12a-46ed-b1bd-5a5567c9f045
// Status: test
// Level: high
// Author: Roberto Rodriguez @Cyb3rWard0g
// Date: 2019-09-12
// Tags: attack.execution, attack.t1059.001, attack.lateral-movement, attack.t1021.006
// Description: Detects a process that initiated a network connection over ports 5985 or 5986 from a non-network service account.
// This could potentially indicates a remote PowerShell connection.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RemotePort == 5985 or RemotePort == 5986) and Initiated == "true" and SourceIsIpv6 == "false") and not((((LocalIP == "::1" or LocalIP == "127.0.0.1") and (RemoteIP == "::1" or RemoteIP == "127.0.0.1")) or (((AccountName contains "NETWORK SERVICE" or AccountName contains "NETZWERKDIENST" or AccountName contains "SERVICIO DE RED" or AccountName contains "SERVIZIO DI RETE")) or ((AccountName contains "SERVICE R" and AccountName contains "SEAU"))))) and not(((FolderPath == "C:\\Program Files\\Avast Software\\Avast\\AvastSvc.exe" or FolderPath == "C:\\Program Files (x86)\\Avast Software\\Avast\\AvastSvc.exe"))))
