// Title: Suspicious Network Connection Binary No CommandLine
// ID: 20384606-a124-4fec-acbb-8bd373728613
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-03
// Tags: attack.stealth
// Description: Detects suspicious network connections made by a well-known Windows binary run with no command line parameters
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Initiated == "true" and (FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\dllhost.exe") and (ProcessCommandLine endswith "\\regsvr32.exe" or ProcessCommandLine endswith "\\rundll32.exe" or ProcessCommandLine endswith "\\dllhost.exe")) and not(((ProcessCommandLine == "") or ((isempty(ProcessCommandLine) or isnull(ProcessCommandLine))))))
