// Title: Local Network Connection Initiated By Script Interpreter
// ID: 08249dc0-a28d-4555-8ba5-9255a198e08c
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-08-28
// Tags: attack.command-and-control, attack.t1105
// Description: Detects a script interpreter (Wscript/Cscript) initiating a local network connection to download or execute a script hosted on a shared folder.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Initiated == "true" and (FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe") and (ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7")))
