// Title: Cobalt Strike DNS Beaconing
// ID: 2975af79-28c4-4d2f-a951-9095f229df29
// Status: test
// Level: critical
// Author: Florian Roth (Nextron Systems)
// Date: 2018-05-10
// Tags: attack.command-and-control, attack.t1071.004
// Description: Detects suspicious DNS queries known from Cobalt Strike beacons
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (((query startswith "aaa.stage." or query startswith "post.1")) or (query contains ".stage.123456."))
