// Title: Microsoft Sync Center Suspicious Network Connections
// ID: 9f2cc74d-78af-4eb2-bb64-9cd1d292b87b
// Status: test
// Level: medium
// Author: elhoim
// Date: 2022-04-28
// Tags: attack.privilege-escalation, attack.stealth, attack.t1055, attack.t1218, attack.execution
// Description: Detects suspicious connections from Microsoft Sync Center to non-private IPs.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\mobsync.exe") and not(((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7")))))
