// Title: Rundll32 Internet Connection
// ID: cdc8da7d-c303-42f8-b08c-b4ab47230263
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2017-11-04
// Tags: attack.stealth, attack.t1218.011, attack.execution
// Description: Detects a rundll32 that communicates with public IP addresses
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\rundll32.exe" and Initiated == "true") and not(((ProcessCommandLine endswith "\\system32\\PcaSvc.dll,PcaPatchSdbTask") or (SourceHostname endswith ".internal.cloudapp.net") or ((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7"))) or ((ipv4_is_in_range(RemoteIP, "20.0.0.0/8") or ipv4_is_in_range(RemoteIP, "51.103.0.0/16") or ipv4_is_in_range(RemoteIP, "51.104.0.0/16") or ipv4_is_in_range(RemoteIP, "51.105.0.0/16"))) or (InitiatingProcessFolderPath == "C:\\Windows\\System32\\svchost.exe" and RemotePort == 443))))
