// Title: Python Initiated Connection
// ID: bef0bc5a-b9ae-425d-85c6-7b2d705980c6
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-12-10
// Tags: attack.discovery, attack.t1046
// Description: Detects a Python process initiating a network connection. While this often relates to package installation, it can also indicate a potential malicious script communicating with a C&C server.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Initiated == "true" and (FolderPath contains "\\python" and FolderPath contains ".exe")) and not(((RemoteIP == "127.0.0.1" and LocalIP == "127.0.0.1") or ((ProcessCommandLine contains "pip.exe" and ProcessCommandLine contains "install")))) and not(((InitiatingProcessFolderPath == "C:\\ProgramData\\Anaconda3\\Scripts\\conda.exe" and (ProcessCommandLine contains ":\\ProgramData\\Anaconda3\\Scripts\\conda-script.py" and ProcessCommandLine contains "update")) or (InitiatingProcessFolderPath == "C:\\ProgramData\\Anaconda3\\python.exe" and ProcessCommandLine contains "C:\\ProgramData\\Anaconda3\\Scripts\\jupyter-notebook-script.py"))))
