// Title: RDP Over Reverse SSH Tunnel
// ID: 5f699bc5-5446-4a4a-a0b7-5ef2885a3eb4
// Status: test
// Level: high
// Author: Samir Bousseaden
// Date: 2019-02-16
// Tags: attack.command-and-control, attack.t1572, attack.lateral-movement, attack.t1021.001, car.2013-07-002
// Description: Detects svchost hosting RDP termsvcs communicating with the loopback address and on TCP port 3389
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "::1/128"))) and (FolderPath endswith "\\svchost.exe" and Initiated == "true" and LocalPort == 3389))
