// Title: RegAsm.EXE Initiating Network Connection To Public IP
// ID: 0531e43a-d77d-47c2-b89f-5fe50321c805
// Status: test
// Level: medium
// Author: frack113
// Date: 2024-04-25
// Tags: attack.stealth, attack.t1218.009
// Description: Detects "RegAsm.exe" initiating a network connection to public IP adresses
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Initiated == "true" and FolderPath endswith "\\regasm.exe") and not(((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7")))))
