// Title: Outbound Network Connection To Public IP Via Winlogon
// ID: 7610a4ea-c06d-495f-a2ac-0a696abcfd3b
// Status: test
// Level: medium
// Author: Christopher Peacock @securepeacock, SCYTHE @scythe_io
// Date: 2023-04-28
// Tags: attack.execution, attack.command-and-control, attack.stealth, attack.t1218.011
// Description: Detects a "winlogon.exe" process that initiate network communications with public IP addresses
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\winlogon.exe" and Initiated == "true") and not(((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7")))))
