// Title: OpenCanary - VNC Connection Attempt
// ID: 9db5446c-b44a-4291-8b89-fcab5609c3b3
// Status: test
// Level: high
// Author: Security Onion Solutions
// Date: 2024-03-08
// Tags: attack.lateral-movement, attack.t1021
// Description: Detects instances where a VNC service on an OpenCanary node has had a connection attempt.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (logtype == 12001)
