// Title: PUA - RemCom Default Named Pipe
// ID: d36f87ea-c403-44d2-aa79-1a0ac7c24456
// Status: test
// Level: medium
// Author: Nikita Nazarov, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-07
// Tags: attack.lateral-movement, attack.t1021.002, attack.execution, attack.t1569.002
// Description: Detects default RemCom pipe creation
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (PipeName contains "\\RemCom")
