// Title: Malicious Named Pipe Created
// ID: fe3ac066-98bb-432a-b1e7-a5229cb39d4a
// Status: test
// Level: critical
// Author: Florian Roth (Nextron Systems), blueteam0ps, elhoim
// Date: 2017-11-06
// Tags: attack.privilege-escalation, attack.stealth, attack.t1055
// Description: Detects the creation of a named pipe seen used by known APTs or malware.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((PipeName == "\\46a676ab7f179e511e30dd2dc41bd388" or PipeName == "\\583da945-62af-10e8-4902-a8f205c72b2e" or PipeName == "\\6e7645c4-32c5-4fe3-aabf-e94c2f4370e7" or PipeName == "\\9f81f59bc58452127884ce513865ed20" or PipeName == "\\adschemerpc" or PipeName == "\\ahexec" or PipeName == "\\AnonymousPipe" or PipeName == "\\bc31a7" or PipeName == "\\bc367" or PipeName == "\\bizkaz" or PipeName == "\\csexecsvc" or PipeName == "\\dce_3d" or PipeName == "\\e710f28d59aa529d6792ca6ff0ca1b34" or PipeName == "\\gruntsvc" or PipeName == "\\isapi_dg" or PipeName == "\\isapi_dg2" or PipeName == "\\isapi_http" or PipeName == "\\jaccdpqnvbrrxlaf" or PipeName == "\\lsassw" or PipeName == "\\NamePipe_MoreWindows" or PipeName == "\\pcheap_reuse" or PipeName == "\\Posh*" or PipeName == "\\rpchlp_3" or PipeName == "\\sdlrpc" or PipeName == "\\svcctl" or PipeName == "\\testPipe" or PipeName == "\\winsession"))
