// Title: Potentially Suspicious Call To Win32_NTEventlogFile Class - PSScript
// ID: e2812b49-bae0-4b21-b366-7c142eafcde2
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-13
// Tags: attack.defense-impairment
// Description: Detects usage of the WMI class "Win32_NTEventlogFile" in a potentially suspicious way (delete, backup, change permissions, etc.) from a PowerShell script
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ScriptBlockText contains "Win32_NTEventlogFile") and ((ScriptBlockText contains ".BackupEventlog(" or ScriptBlockText contains ".ChangeSecurityPermissions(" or ScriptBlockText contains ".ChangeSecurityPermissionsEx(" or ScriptBlockText contains ".ClearEventLog(" or ScriptBlockText contains ".Delete(" or ScriptBlockText contains ".DeleteEx(" or ScriptBlockText contains ".Rename(" or ScriptBlockText contains ".TakeOwnerShip(" or ScriptBlockText contains ".TakeOwnerShipEx(")))
