// Title: Clear PowerShell History - PowerShell Module
// ID: f99276ad-d122-4989-a09a-d00904a5f9d2
// Status: test
// Level: medium
// Author: Ilyas Ochkov, Jonhnathan Ribeiro, Daniil Yugoslavskiy, oscd.community
// Date: 2019-10-25
// Tags: attack.stealth, attack.t1070.003
// Description: Detects keywords that could indicate clearing PowerShell history
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((Payload contains "Set-PSReadlineOption" and Payload contains "–HistorySaveStyle" and Payload contains "SaveNothing")) or ((Payload contains "Set-PSReadlineOption" and Payload contains "-HistorySaveStyle" and Payload contains "SaveNothing"))) or (((Payload contains "del" or Payload contains "Remove-Item" or Payload contains "rm")) and (Payload contains "(Get-PSReadlineOption).HistorySavePath")))
