// Title: Powershell DNSExfiltration
// ID: d59d7842-9a21-4bc6-ba98-64bfe0091355
// Status: test
// Level: high
// Author: frack113
// Date: 2022-01-07
// Tags: attack.exfiltration, attack.t1048
// Description: DNSExfiltrator allows for transferring (exfiltrate) a file over a DNS request covert channel
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ScriptBlockText contains "Invoke-DNSExfiltrator") or ((ScriptBlockText contains " -i " and ScriptBlockText contains " -d " and ScriptBlockText contains " -p " and ScriptBlockText contains " -doh " and ScriptBlockText contains " -t ")))
