// Title: PowerShell Downgrade Attack - PowerShell
// ID: 6331d09b-4785-4c13-980f-f96661356249
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), Lee Holmes (idea), Harish Segar (improvements)
// Date: 2017-03-22
// Tags: attack.execution, attack.t1059.001
// Description: Detects PowerShell downgrade attack by comparing the host versions with the actually used engine version 2.0
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Data contains "EngineVersion=2.") and not((Data contains "HostVersion=2.")))
