// Title: Powershell Timestomp
// ID: c6438007-e081-42ce-9483-b067fbef33c3
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-08-03
// Tags: attack.stealth, attack.t1070.006
// Description: Adversaries may modify file time attributes to hide new or changes to existing files.
// Timestomping is a technique that modifies the timestamps of a file (the modify, access, create, and change times), often to mimic files that are in the same folder.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ScriptBlockText contains ".CreationTime =" or ScriptBlockText contains ".LastWriteTime =" or ScriptBlockText contains ".LastAccessTime =" or ScriptBlockText contains "[IO.File]::SetCreationTime" or ScriptBlockText contains "[IO.File]::SetLastAccessTime" or ScriptBlockText contains "[IO.File]::SetLastWriteTime"))
