// Title: Silence.EDA Detection
// ID: 3ceb2083-a27f-449a-be33-14ec1b7cc973
// Status: test
// Level: critical
// Author: Alina Stepchenkova, Group-IB, oscd.community
// Date: 2019-11-01
// Tags: attack.execution, attack.t1059.001, attack.command-and-control, attack.t1071.004, attack.t1572, attack.impact, attack.t1529, attack.g0091, attack.s0363
// Description: Detects Silence EmpireDNSAgent as described in the Group-IP report
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ScriptBlockText contains "System.Diagnostics.Process" and ScriptBlockText contains "Stop-Computer" and ScriptBlockText contains "Restart-Computer" and ScriptBlockText contains "Exception in execution" and ScriptBlockText contains "$cmdargs" and ScriptBlockText contains "Close-Dnscat2Tunnel")) and ((ScriptBlockText contains "set type=$LookupType`nserver" and ScriptBlockText contains "$Command | nslookup 2>&1 | Out-String" and ScriptBlockText contains "New-RandomDNSField" and ScriptBlockText contains "[Convert]::ToString($SYNOptions, 16)" and ScriptBlockText contains "$Session.Dead = $True" and ScriptBlockText contains "$Session[\"Driver\"] -eq")))
