// Title: Operator Bloopers Cobalt Strike Modules
// ID: 4f154fb6-27d1-4813-a759-78b93e0b9c48
// Status: test
// Level: high
// Author: _pete_0, TheDFIRReport
// Date: 2022-05-06
// Tags: attack.execution, attack.t1059.003
// Description: Detects Cobalt Strike module/commands accidentally entered in CMD shell
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Invoke-UserHunter" or ProcessCommandLine contains "Invoke-ShareFinder" or ProcessCommandLine contains "Invoke-Kerberoast" or ProcessCommandLine contains "Invoke-SMBAutoBrute" or ProcessCommandLine contains "Invoke-Nightmare" or ProcessCommandLine contains "zerologon" or ProcessCommandLine contains "av_query")) and ((ProcessVersionInfoOriginalFileName == "Cmd.Exe") or (FolderPath endswith "\\cmd.exe")))
