// Title: Potentially Suspicious Execution Of Regasm/Regsvcs From Uncommon Location
// ID: cc368ed0-2411-45dc-a222-510ace303cb2
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-25
// Tags: attack.stealth, attack.t1218.009
// Description: Detects potentially suspicious execution of the Regasm/Regsvcs utilities from a potentially suspicious location
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\" or ProcessCommandLine contains "\\PerfLogs\\" or ProcessCommandLine contains "\\Users\\Public\\" or ProcessCommandLine contains "\\Windows\\Temp\\")) and (((FolderPath endswith "\\Regsvcs.exe" or FolderPath endswith "\\Regasm.exe")) or ((ProcessVersionInfoOriginalFileName == "RegSvcs.exe" or ProcessVersionInfoOriginalFileName == "RegAsm.exe"))))
