// Title: 7Zip Compressing Dump Files
// ID: ec570e53-4c76-45a9-804d-dc3f355ff7a7
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-27
// Tags: attack.collection, attack.t1560.001
// Description: Detects execution of 7z in order to compress a file with a ".dmp"/".dump" extension, which could be a step in a process of dump file exfiltration.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ".dmp" or ProcessCommandLine contains ".dump" or ProcessCommandLine contains ".hdmp")) and ((Description contains "7-Zip") or ((FolderPath endswith "\\7z.exe" or FolderPath endswith "\\7zr.exe" or FolderPath endswith "\\7za.exe")) or ((ProcessVersionInfoOriginalFileName == "7z.exe" or ProcessVersionInfoOriginalFileName == "7za.exe" or ProcessVersionInfoOriginalFileName == "7zr.exe"))))
