// Title: Linux Shell Pipe to Shell
// ID: 880973f3-9708-491c-a77b-2a35a1921158
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-14
// Tags: attack.stealth, attack.t1140
// Description: Detects suspicious process command line that starts with a shell that executes something and finally gets piped into another shell
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine startswith "sh -c " or ProcessCommandLine startswith "bash -c ")) and (((ProcessCommandLine contains "| bash " or ProcessCommandLine contains "| sh " or ProcessCommandLine contains "|bash " or ProcessCommandLine contains "|sh ")) or ((ProcessCommandLine endswith "| bash" or ProcessCommandLine endswith "| sh" or ProcessCommandLine endswith "|bash" or ProcessCommandLine endswith " |sh"))))
