// Title: Suspicious Svchost Process Access
// ID: 166e9c50-8cd9-44af-815d-d1f0c0e90dde
// Status: test
// Level: high
// Author: Tim Burrell
// Date: 2020-01-02
// Tags: attack.defense-impairment, attack.t1685.001
// Description: Detects suspicious access to the "svchost" process such as that used by Invoke-Phantom to kill the thread of the Windows event logging service.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((TargetImage endswith ":\\Windows\\System32\\svchost.exe" and GrantedAccess == "0x1F3FFF" and CallTrace contains "UNKNOWN") and not((SourceImage contains ":\\Program Files\\Microsoft Visual Studio\\" and SourceImage endswith "\\MSBuild\\Current\\Bin\\MSBuild.exe" and (CallTrace contains "Microsoft.Build.ni.dll" or CallTrace contains "System.ni.dll"))))
