// Title: PowerShell SAM Copy
// ID: 1af57a4b-460a-4738-9034-db68b880c665
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2021-07-29
// Tags: attack.credential-access, attack.t1003.002
// Description: Detects suspicious PowerShell scripts accessing SAM hives
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "\\HarddiskVolumeShadowCopy" and ProcessCommandLine contains "System32\\config\\sam")) and ((ProcessCommandLine contains "Copy-Item" or ProcessCommandLine contains "cp $_." or ProcessCommandLine contains "cpi $_." or ProcessCommandLine contains "copy $_." or ProcessCommandLine contains ".File]::Copy(")))
