// Title: Registry Modification of MS-settings Protocol Handler
// ID: dd3ee8cc-f751-41c9-ba53-5a32ed47e563
// Status: test
// Level: medium
// Author: frack113, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2021-12-20
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-impairment, attack.t1548.002, attack.t1546.001, attack.t1112
// Description: Detects registry modifications to the 'ms-settings' protocol handler, which is frequently targeted for UAC bypass or persistence.
// Attackers can modify this registry to execute malicious code with elevated privileges by hijacking the command execution path.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "add") and ((FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName == "reg.exe"))) or (((ProcessCommandLine contains "New-ItemProperty" or ProcessCommandLine contains "Set-ItemProperty" or ProcessCommandLine contains "ni " or ProcessCommandLine contains "sp ")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "powershell.exe" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))))) and (ProcessCommandLine contains "\\ms-settings\\shell\\open\\command"))
