// Title: Suspicious File Downloaded From Direct IP Via Certutil.EXE
// ID: 13e6fe51-d478-4c7e-b0f2-6da9b400a829
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-15
// Tags: attack.stealth, attack.t1027, attack.command-and-control, attack.t1105
// Description: Detects the execution of certutil with certain flags that allow the utility to download files from direct IPs.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "urlcache " or ProcessCommandLine contains "verifyctl " or ProcessCommandLine contains "URL ")) and ((ProcessCommandLine contains "://1" or ProcessCommandLine contains "://2" or ProcessCommandLine contains "://3" or ProcessCommandLine contains "://4" or ProcessCommandLine contains "://5" or ProcessCommandLine contains "://6" or ProcessCommandLine contains "://7" or ProcessCommandLine contains "://8" or ProcessCommandLine contains "://9")) and ((FolderPath endswith "\\certutil.exe") or (ProcessVersionInfoOriginalFileName == "CertUtil.exe"))) and not((ProcessCommandLine contains "://7-")))
