// Title: Computer Discovery And Export Via Get-ADComputer Cmdlet
// ID: 435e10e4-992a-4281-96f3-38b11106adde
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-11-10
// Tags: attack.discovery, attack.t1033
// Description: Detects usage of the Get-ADComputer cmdlet to collect computer information and output it to a file
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Get-ADComputer " and ProcessCommandLine contains " -Filter \\*") and (ProcessCommandLine contains " > " or ProcessCommandLine contains " | Select " or ProcessCommandLine contains "Out-File" or ProcessCommandLine contains "Set-Content" or ProcessCommandLine contains "Add-Content")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))))
