// Title: Script Event Consumer Spawning Process
// ID: f6d1dd2f-b8ce-40ca-bc23-062efb686b34
// Status: test
// Level: high
// Author: Sittikorn S
// Date: 2021-06-21
// Tags: attack.execution, attack.t1047
// Description: Detects a suspicious child process of Script Event Consumer (scrcons.exe).
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (InitiatingProcessFolderPath endswith "\\scrcons.exe" and (FolderPath endswith "\\svchost.exe" or FolderPath endswith "\\dllhost.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\schtasks.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\msiexec.exe" or FolderPath endswith "\\msbuild.exe"))
