// Title: Renamed Visual Studio Code Tunnel Execution
// ID: 2cf29f11-e356-4f61-98c0-1bdb9393d6da
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-28
// Tags: attack.command-and-control, attack.t1071.001, attack.t1219
// Description: Detects renamed Visual Studio Code tunnel execution. Attackers can abuse this functionality to establish a C2 channel
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((isempty(ProcessVersionInfoOriginalFileName) or isnull(ProcessVersionInfoOriginalFileName)) and ProcessCommandLine endswith ".exe tunnel") or ((ProcessCommandLine contains ".exe tunnel" and ProcessCommandLine contains "--accept-server-license-terms")) or ((ProcessCommandLine contains "tunnel " and ProcessCommandLine contains "service" and ProcessCommandLine contains "internal-run" and ProcessCommandLine contains "tunnel-service.log"))) and not(((FolderPath endswith "\\code-tunnel.exe" or FolderPath endswith "\\code.exe")))) or ((InitiatingProcessCommandLine endswith " tunnel" and FolderPath endswith "\\cmd.exe" and (ProcessCommandLine contains "/d /c " and ProcessCommandLine contains "\\servers\\Stable-" and ProcessCommandLine contains "code-server.cmd")) and not(((InitiatingProcessFolderPath endswith "\\code-tunnel.exe" or InitiatingProcessFolderPath endswith "\\code.exe")))))
