// Title: Suspicious Rundll32 Execution With Image Extension
// ID: 4aa6040b-3f28-44e3-a769-9208e5feb5ec
// Status: test
// Level: high
// Author: Hieu Tran
// Date: 2023-03-13
// Tags: attack.stealth, attack.t1218.011
// Description: Detects the execution of Rundll32.exe with DLL files masquerading as image files
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ".bmp" or ProcessCommandLine contains ".cr2" or ProcessCommandLine contains ".eps" or ProcessCommandLine contains ".gif" or ProcessCommandLine contains ".ico" or ProcessCommandLine contains ".jpeg" or ProcessCommandLine contains ".jpg" or ProcessCommandLine contains ".nef" or ProcessCommandLine contains ".orf" or ProcessCommandLine contains ".png" or ProcessCommandLine contains ".raw" or ProcessCommandLine contains ".sr2" or ProcessCommandLine contains ".tif" or ProcessCommandLine contains ".tiff")) and ((FolderPath endswith "\\rundll32.exe") or (ProcessVersionInfoOriginalFileName == "RUNDLL32.exe")))
