// Title: PowerShell Download Pattern
// ID: 3b6ab547-8ec2-4991-b9d2-2b06702a48d7
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), oscd.community, Jonhnathan Ribeiro
// Date: 2019-01-16
// Tags: attack.execution, attack.t1059.001
// Description: Detects a Powershell process that contains download commands in its command line string
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "new-object" and ProcessCommandLine contains "net.webclient)." and ProcessCommandLine contains "download") and (ProcessCommandLine contains "string(" or ProcessCommandLine contains "file(")) and (((FolderPath endswith "\\powershell_ise.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell_ISE.EXE" or ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))))
