// Title: Powershell Token Obfuscation - Process Creation
// ID: deb9b646-a508-44ee-b7c9-d8965921c6b6
// Status: test
// Level: high
// Author: frack113
// Date: 2022-12-27
// Tags: attack.stealth, attack.t1027.009
// Description: Detects TOKEN OBFUSCATION technique from Invoke-Obfuscation
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine matches regex @"\\w+`(?:\\w+|-|.)`[\\w+|\\s]") or (ProcessCommandLine matches regex @"\"(?:\\{\\d\\})+\"\\s*-f") or (ProcessCommandLine matches regex @"(?i)\\$\\{`?e`?n`?v`?:`?p`?a`?t`?h`?\\}")) and not((ProcessCommandLine contains "${env:path}")))
