// Title: Potentially Suspicious WebDAV LNK Execution
// ID: 1412aa78-a24c-4abd-83df-767dfb2c5bbe
// Status: test
// Level: medium
// Author: Micah Babinski
// Date: 2023-08-21
// Tags: attack.execution, attack.t1059.001, attack.t1204
// Description: Detects possible execution via LNK file accessed on a WebDAV server.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (InitiatingProcessFolderPath endswith "\\explorer.exe" and (FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\wscript.exe") and ProcessCommandLine contains "\\DavWWWRoot\\")
