// Title: Gatekeeper Bypass via Xattr
// ID: f5141b6d-9f42-41c6-a7bf-2a780678b29b
// Status: test
// Level: low
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Tags: attack.defense-impairment, attack.t1553.001
// Description: Detects macOS Gatekeeper bypass via xattr utility
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FolderPath endswith "/xattr" and (ProcessCommandLine contains "-d" and ProcessCommandLine contains "com.apple.quarantine"))
