// Title: System Network Connections Discovery - Linux
// ID: 4c519226-f0cd-4471-bd2f-6fbb2bb68a79
// Status: test
// Level: low
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Tags: attack.discovery, attack.t1049
// Description: Detects usage of system utilities to discover system network connections
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "/who" or FolderPath endswith "/w" or FolderPath endswith "/last" or FolderPath endswith "/lsof" or FolderPath endswith "/netstat")) and not((InitiatingProcessCommandLine contains "/usr/bin/landscape-sysinfo" and FolderPath endswith "/who")))
