// Title: Registry Manipulation via WMI Stdregprov
// ID: c453ab7a-1f5c-4716-a3b4-dea8135fb43a
// Status: experimental
// Level: medium
// Author: Daniel Koifman (KoifSec)
// Date: 2025-07-30
// Tags: attack.execution, attack.t1047, attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects the usage of wmic.exe to modify Windows registry via the WMI StdRegProv class write methods (CreateKey, DeleteKey, SetStringValue, etc.).
// This behaviour could be potentially suspicious because it uses an alternative method to modify registry keys instead of legitimate registry tools like reg.exe or regedit.exe.
// Attackers specifically choose this technique to evade detection and bypass security monitoring focused on traditional registry modification commands.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "stdregprov" and ProcessCommandLine contains "call") and (ProcessCommandLine contains "CreateKey" or ProcessCommandLine contains "DeleteKey" or ProcessCommandLine contains "DeleteValue" or ProcessCommandLine contains "SetBinaryValue" or ProcessCommandLine contains "SetDWORDValue" or ProcessCommandLine contains "SetExpandedStringValue" or ProcessCommandLine contains "SetMultiStringValue" or ProcessCommandLine contains "SetQWORDValue" or ProcessCommandLine contains "SetSecurityDescriptor" or ProcessCommandLine contains "SetStringValue")) and ((FolderPath endswith "\\wmic.exe") or (ProcessVersionInfoOriginalFileName == "wmic.exe")))
