// Title: CodePage Modification Via MODE.COM To Russian Language
// ID: 12fbff88-16b5-4b42-9754-cd001a789fb3
// Status: test
// Level: medium
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-01-17
// Tags: attack.stealth, attack.t1036
// Description: Detects a CodePage modification using the "mode.com" utility to Russian language.
// This behavior has been used by threat actors behind Dharma ransomware.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " con " and ProcessCommandLine contains " cp " and ProcessCommandLine contains " select=") and (ProcessCommandLine endswith "=1251" or ProcessCommandLine endswith "=866")) and ((FolderPath endswith "\\mode.com") or (ProcessVersionInfoOriginalFileName == "MODE.COM")))
