// Title: Bypass UAC via CMSTP
// ID: e66779cc-383e-4224-a3a4-267eeb585c40
// Status: test
// Level: high
// Author: E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
// Date: 2019-10-24
// Tags: attack.privilege-escalation, attack.stealth, attack.t1548.002, attack.t1218.003
// Description: Detect commandline usage of Microsoft Connection Manager Profile Installer (cmstp.exe) to install specially formatted local .INF files
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "/s" or ProcessCommandLine contains "-s" or ProcessCommandLine contains "/au" or ProcessCommandLine contains "-au" or ProcessCommandLine contains "/ni" or ProcessCommandLine contains "-ni")) and ((FolderPath endswith "\\cmstp.exe") or (ProcessVersionInfoOriginalFileName == "CMSTP.EXE")))
