// Title: User Discovery And Export Via Get-ADUser Cmdlet
// ID: 1114e048-b69c-4f41-bc20-657245ae6e3f
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-09
// Tags: attack.discovery, attack.t1033
// Description: Detects usage of the Get-ADUser cmdlet to collect user information and output it to a file
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Get-ADUser " and ProcessCommandLine contains " -Filter \\*") and (ProcessCommandLine contains " > " or ProcessCommandLine contains " | Select " or ProcessCommandLine contains "Out-File" or ProcessCommandLine contains "Set-Content" or ProcessCommandLine contains "Add-Content")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))))
