// Title: Potential Arbitrary File Download Using Office Application
// ID: 4ae3e30b-b03f-43aa-87e3-b622f4048eed
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), Beyu Denis, oscd.community
// Date: 2022-05-17
// Tags: attack.stealth, attack.t1202
// Description: Detects potential arbitrary file download using a Microsoft Office application
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://")) and (((FolderPath endswith "\\EXCEL.EXE" or FolderPath endswith "\\MSOXMLED.EXE" or FolderPath endswith "\\POWERPNT.EXE" or FolderPath endswith "\\WINWORD.exe")) or ((ProcessVersionInfoOriginalFileName == "Excel.exe" or ProcessVersionInfoOriginalFileName == "msoxmled.exe" or ProcessVersionInfoOriginalFileName == "POWERPNT.EXE" or ProcessVersionInfoOriginalFileName == "WinWord.exe"))))
