// Title: HackTool - RemoteKrbRelay Execution
// ID: a7664b14-75fb-4a50-a223-cb9bc0afbacf
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-06-27
// Tags: attack.credential-access, attack.t1558.003
// Description: Detects the use of RemoteKrbRelay, a Kerberos relaying tool via CommandLine flags and PE metadata.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\RemoteKrbRelay.exe") or (ProcessVersionInfoOriginalFileName == "RemoteKrbRelay.exe")) or ((ProcessCommandLine contains " -clsid " and ProcessCommandLine contains " -target " and ProcessCommandLine contains " -victim ")) or ((ProcessCommandLine contains "-rbcd ") and ((ProcessCommandLine contains "-cn " or ProcessCommandLine contains "--computername "))) or (ProcessCommandLine contains "-chp " and (ProcessCommandLine contains "-chpPass " and ProcessCommandLine contains "-chpUser ")) or ((ProcessCommandLine contains "-addgroupmember " and ProcessCommandLine contains "-group " and ProcessCommandLine contains "-groupuser ")) or ((ProcessCommandLine contains "-smb " and ProcessCommandLine contains "--smbkeyword ") and (ProcessCommandLine contains "interactive" or ProcessCommandLine contains "secrets" or ProcessCommandLine contains "service-add")))
