// Title: System Restore Registry Modification via CommandLine
// ID: 7c06ab9b-b1d2-4ba9-b06e-09491ded20d9
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-03-11
// Tags: attack.impact, attack.t1490
// Description: Detects system restore registry modification via command line, which can be used by adversaries to disable system restore on the computer.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " add " or ProcessCommandLine contains "Set-ItemProperty" or ProcessCommandLine contains "New-ItemProperty")) and ((ProcessCommandLine contains "DisableConfig" or ProcessCommandLine contains "DisableSR")) and ((ProcessCommandLine contains "\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\SystemRestore" or ProcessCommandLine contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\SystemRestore")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\reg.exe")) or ((ProcessVersionInfoOriginalFileName == "powershell.exe" or ProcessVersionInfoOriginalFileName == "pwsh.dll" or ProcessVersionInfoOriginalFileName == "reg.exe"))))
