// Title: Capture Credentials with Rpcping.exe
// ID: 93671f99-04eb-4ab4-a161-70d446a84003
// Status: test
// Level: medium
// Author: Julia Fomina, oscd.community
// Date: 2020-10-09
// Tags: attack.credential-access, attack.t1003
// Description: Detects using Rpcping.exe to send a RPC test connection to the target server (-s) and force the NTLM hash to be sent in the process.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "-s" or ProcessCommandLine contains "/s")) and ((FolderPath endswith "\\RpcPing.exe") or (ProcessVersionInfoOriginalFileName == "\\RpcPing.exe"))) and (((ProcessCommandLine contains "-t" or ProcessCommandLine contains "/t") and ProcessCommandLine contains "ncacn_np") or ((ProcessCommandLine contains "-u" or ProcessCommandLine contains "/u") and ProcessCommandLine contains "NTLM")))
