// Title: Execution Of Non-Existing File
// ID: 71158e3f-df67-472b-930e-7d287acaa3e1
// Status: test
// Level: high
// Author: Max Altgelt (Nextron Systems)
// Date: 2021-12-09
// Tags: attack.stealth, attack.privilege-escalation, attack.t1055
// Description: Detects process creation events where the Image field lacks an absolute path,
// which occurs when the backing file no longer exists on disk at the time of
// logging - commonly caused by Process Ghosting or other unorthodox process creation techniques.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (not((FolderPath contains "\\")) and not(((((FolderPath == "MemCompression" or FolderPath == "Registry" or FolderPath == "System" or FolderPath == "vmmem" or FolderPath == "vmmemWSL")) or ((ProcessCommandLine == "MemCompression" or ProcessCommandLine == "Registry" or ProcessCommandLine == "vmmem" or ProcessCommandLine == "vmmemWSL"))) or ((FolderPath == "-" or FolderPath == "")) or ((isempty(FolderPath) or isnull(FolderPath))))))
