// Title: Linux Logs Clearing Attempts
// ID: 80915f59-9b56-4616-9de0-fd0dea6c12fe
// Status: stable
// Level: medium
// Author: Ömer Günal, oscd.community
// Date: 2020-10-07
// Tags: attack.defense-impairment, attack.t1685.006
// Description: Detects logs clearing attempts on Linux systems via utilities such as 'rm', 'rmdir', 'shred', and 'unlink' targeting log files and directories.
// Adversaries often try to clear logs to cover their tracks after performing malicious activities.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "/rm" or FolderPath endswith "/rmdir" or FolderPath endswith "/shred" or FolderPath endswith "/unlink") and (ProcessCommandLine contains "/var/log" or ProcessCommandLine contains "/var/spool/mail")) and not(((FolderPath endswith "/rm" and ProcessCommandLine startswith "rm -f -- /var/log//dmesg") or (FolderPath endswith "/rm" and ProcessCommandLine startswith "rm -f /var/log/sysstat/"))))
