// Title: Renamed Gpg.EXE Execution
// ID: ec0722a3-eb5c-4a56-8ab2-bf6f20708592
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2023-08-09
// Tags: attack.impact, attack.t1486
// Description: Detects the execution of a renamed "gpg.exe". Often used by ransomware and loaders to decrypt/encrypt data.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessVersionInfoOriginalFileName == "gpg.exe") and not(((FolderPath endswith "\\gpg.exe" or FolderPath endswith "\\gpg2.exe"))))
