// Title: Suspicious BitLocker Access Agent Update Utility Execution
// ID: 9f38c1db-e2ae-40bf-81d0-5b68f73fb512
// Status: experimental
// Level: high
// Author: andrewdanis, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-10-18
// Tags: attack.stealth, attack.t1218, attack.lateral-movement, attack.t1021.003
// Description: Detects the execution of the BitLocker Access Agent Update Utility (baaupdate.exe) which is not a common parent process for other processes.
// Suspicious child processes spawned by baaupdate.exe could indicate an attempt at lateral movement via BitLocker DCOM & COM Hijacking.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (InitiatingProcessFolderPath endswith "\\baaupdate.exe" and (FolderPath endswith "\\bitsadmin.exe" or FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell_ise.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\schtasks.exe" or FolderPath endswith "\\wmic.exe" or FolderPath endswith "\\wscript.exe"))
