// Title: Potential Suspicious Registry File Imported Via Reg.EXE
// ID: 62e0298b-e994-4189-bc87-bc699aa62d97
// Status: test
// Level: medium
// Author: frack113, Nasreddine Bencherchali
// Date: 2022-08-01
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects the import of '.reg' files from suspicious paths using the 'reg.exe' utility
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains " import ") and ((FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName == "reg.exe")) and ((ProcessCommandLine contains "C:\\Users\\" or ProcessCommandLine contains "%temp%" or ProcessCommandLine contains "%tmp%" or ProcessCommandLine contains "%appdata%" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "C:\\Windows\\Temp\\" or ProcessCommandLine contains "C:\\ProgramData\\")))
