// Title: Potential Process Injection Via Msra.EXE
// ID: 744a188b-0415-4792-896f-11ddb0588dbc
// Status: test
// Level: high
// Author: Alexander McDonald
// Date: 2022-06-24
// Tags: attack.privilege-escalation, attack.stealth, attack.t1055
// Description: Detects potential process injection via Microsoft Remote Asssistance (Msra.exe) by looking at suspicious child processes spawned from the aforementioned process. It has been a target used by many threat actors and used for discovery and persistence tactics
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (InitiatingProcessFolderPath endswith "\\msra.exe" and InitiatingProcessCommandLine endswith "msra.exe" and (FolderPath endswith "\\arp.exe" or FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\net.exe" or FolderPath endswith "\\netstat.exe" or FolderPath endswith "\\nslookup.exe" or FolderPath endswith "\\route.exe" or FolderPath endswith "\\schtasks.exe" or FolderPath endswith "\\whoami.exe"))
