// Title: File Encryption Using Gpg4win
// ID: 550bbb84-ce5d-4e61-84ad-e590f0024dcd
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-09
// Tags: attack.execution
// Description: Detects usage of Gpg4win to encrypt files
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " -c " and ProcessCommandLine contains "passphrase")) and (((FolderPath endswith "\\gpg.exe" or FolderPath endswith "\\gpg2.exe")) or (Description == "GnuPG’s OpenPGP tool")))
