// Title: Suspicious Child Process of AspNetCompiler
// ID: 9ccba514-7cb6-4c5c-b377-700758f2f120
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-14
// Tags: attack.execution, attack.stealth, attack.t1127
// Description: Detects potentially suspicious child processes of "aspnet_compiler.exe".
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\calc.exe" or FolderPath endswith "\\notepad.exe")) or ((FolderPath contains "\\Users\\Public\\" or FolderPath contains "\\AppData\\Local\\Temp\\" or FolderPath contains "\\AppData\\Local\\Roaming\\" or FolderPath contains ":\\Temp\\" or FolderPath contains ":\\Windows\\Temp\\" or FolderPath contains ":\\Windows\\System32\\Tasks\\" or FolderPath contains ":\\Windows\\Tasks\\"))) and (InitiatingProcessFolderPath endswith "\\aspnet_compiler.exe"))
