// Title: Filter Driver Unloaded Via Fltmc.EXE
// ID: 4931188c-178e-4ee7-a348-39e8a7a56821
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-13
// Tags: attack.stealth, attack.defense-impairment, attack.t1070, attack.t1685, attack.t1685.001
// Description: Detect filter driver unloading activity via fltmc.exe
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "unload") and ((FolderPath endswith "\\fltMC.exe") or (ProcessVersionInfoOriginalFileName == "fltMC.exe"))) and not((((InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" or InitiatingProcessFolderPath contains ":\\Windows\\Temp\\") and InitiatingProcessFolderPath endswith "\\endpoint-protection-installer-x64.tmp" and (ProcessCommandLine endswith "unload rtp_filesystem_filter" or ProcessCommandLine endswith "unload rtp_filter")) or (InitiatingProcessFolderPath == "C:\\Program Files (x86)\\ManageEngine\\uems_agent\\bin\\dcfaservice64.exe" and ProcessCommandLine endswith "unload DFMFilter"))))
