// Title: Potentially Suspicious CMD Shell Output Redirect
// ID: 8e0bb260-d4b2-4fff-bb8d-3f82118e6892
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-12
// Tags: attack.stealth, attack.t1218
// Description: Detects inline Windows shell commands redirecting output via the ">" symbol to a suspicious location.
// This technique is sometimes used by malicious actors in order to redirect the output of reconnaissance commands such as "hostname" and "dir" to files for future exfiltration.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\cmd.exe") or (ProcessVersionInfoOriginalFileName == "Cmd.Exe")) and (((ProcessCommandLine contains ">?%APPDATA%\\" or ProcessCommandLine contains ">?%TEMP%\\" or ProcessCommandLine contains ">?%TMP%\\" or ProcessCommandLine contains ">?%USERPROFILE%\\" or ProcessCommandLine contains ">?C:\\ProgramData\\" or ProcessCommandLine contains ">?C:\\Temp\\" or ProcessCommandLine contains ">?C:\\Users\\Public\\" or ProcessCommandLine contains ">?C:\\Windows\\Temp\\")) or ((ProcessCommandLine contains " >" or ProcessCommandLine contains "\">" or ProcessCommandLine contains "'>") and (ProcessCommandLine contains "C:\\Users\\" and ProcessCommandLine contains "\\AppData\\Local\\"))))
