// Title: PUA - CleanWipe Execution
// ID: f44800ac-38ec-471f-936e-3fa7d9c53100
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-18
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects the use of CleanWipe a tool usually used to delete Symantec antivirus.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\SepRemovalToolNative_x64.exe") or (FolderPath endswith "\\CATClean.exe" and ProcessCommandLine contains "--uninstall") or (FolderPath endswith "\\NetInstaller.exe" and ProcessCommandLine contains "-r") or (FolderPath endswith "\\WFPUnins.exe" and (ProcessCommandLine contains "/uninstall" and ProcessCommandLine contains "/enterprise")))
