// Title: PktMon.EXE Execution
// ID: f956c7c1-0f60-4bc5-b7d7-b39ab3c08908
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-03-17
// Tags: attack.discovery, attack.credential-access, attack.t1040
// Description: Detects execution of PktMon, a tool that captures network packets.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\pktmon.exe") or (ProcessVersionInfoOriginalFileName == "PktMon.exe"))
