// Title: CobaltStrike Load by Rundll32
// ID: ae9c6a7c-9521-42a6-915e-5aaa8689d529
// Status: test
// Level: high
// Author: Wojciech Lesicki
// Date: 2021-06-01
// Tags: attack.stealth, attack.t1218.011
// Description: Rundll32 can be use by Cobalt Strike with StartW function to load DLLs from the command line.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains ".dll" and (ProcessCommandLine endswith " StartW" or ProcessCommandLine endswith ",StartW")) and ((FolderPath endswith "\\rundll32.exe") or (ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE") or ((ProcessCommandLine contains "rundll32.exe" or ProcessCommandLine contains "rundll32 "))))
