// Title: ETW Logging Tamper In .NET Processes Via CommandLine
// ID: 41421f44-58f9-455d-838a-c398859841d4
// Status: test
// Level: high
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects changes to environment variables related to ETW logging via the CommandLine.
// This could indicate potential adversaries stopping ETW providers recording loaded .NET assemblies.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "COMPlus_ETWEnabled" or ProcessCommandLine contains "COMPlus_ETWFlags"))
