// Title: Execute From Alternate Data Streams
// ID: 7f43c430-5001-4f8b-aaa9-c3b88f18fa5c
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-09-01
// Tags: attack.stealth, attack.t1564.004
// Description: Detects execution from an Alternate Data Stream (ADS). Adversaries may use NTFS file attributes to hide their malicious data in order to evade detection
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "txt:") and (((ProcessCommandLine contains "esentutl " and ProcessCommandLine contains " /y " and ProcessCommandLine contains " /d " and ProcessCommandLine contains " /o ")) or ((ProcessCommandLine contains "makecab " and ProcessCommandLine contains ".cab")) or ((ProcessCommandLine contains "reg " and ProcessCommandLine contains " export ")) or ((ProcessCommandLine contains "regedit " and ProcessCommandLine contains " /E ")) or ((ProcessCommandLine contains "type " and ProcessCommandLine contains " > "))))
