// Title: Potential PowerShell Execution Via DLL
// ID: 6812a10b-60ea-420c-832f-dfcc33b646ba
// Status: test
// Level: high
// Author: Markus Neis, Nasreddine Bencherchali (Nextron Systems)
// Date: 2018-08-25
// Tags: attack.stealth, attack.t1218.011
// Description: Detects potential PowerShell execution from a DLL instead of the usual PowerShell process as seen used in PowerShdll.
// This detection assumes that PowerShell commands are passed via the CommandLine.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Default.GetString" or ProcessCommandLine contains "DownloadString" or ProcessCommandLine contains "FromBase64String" or ProcessCommandLine contains "ICM " or ProcessCommandLine contains "IEX " or ProcessCommandLine contains "Invoke-Command" or ProcessCommandLine contains "Invoke-Expression")) and (((FolderPath endswith "\\InstallUtil.exe" or FolderPath endswith "\\RegAsm.exe" or FolderPath endswith "\\RegSvcs.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe")) or ((ProcessVersionInfoOriginalFileName == "InstallUtil.exe" or ProcessVersionInfoOriginalFileName == "RegAsm.exe" or ProcessVersionInfoOriginalFileName == "RegSvcs.exe" or ProcessVersionInfoOriginalFileName == "REGSVR32.EXE" or ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE"))))
