// Title: Potential Process Hollowing Activity
// ID: c4b890e5-8d8c-4496-8c66-c805753817cd
// Status: test
// Level: medium
// Author: Christopher Peacock '@securepeacock', SCYTHE '@scythe_io', Sittikorn S
// Date: 2022-01-25
// Tags: attack.privilege-escalation, attack.stealth, attack.t1055.012
// Description: Detects when a memory process image does not match the disk image, indicative of process hollowing.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Type == "Image is replaced") and not(((FolderPath contains ":\\Program Files (x86)" or FolderPath contains ":\\Program Files\\" or FolderPath contains ":\\Windows\\System32\\wbem\\WMIADAP.exe" or FolderPath contains ":\\Windows\\SysWOW64\\wbem\\WMIADAP.exe"))) and not(((FolderPath endswith "\\WindowsApps\\MicrosoftEdge.exe") or (FolderPath contains "\\AppData\\Local\\Programs\\Opera\\" and FolderPath endswith "\\opera.exe"))))
