// Title: Use of W32tm as Timer
// ID: 6da2c9f5-7c53-401b-aacb-92c040ce1215
// Status: test
// Level: high
// Author: frack113
// Date: 2022-09-25
// Tags: attack.discovery, attack.t1124
// Description: When configured with suitable command line arguments, w32tm can act as a delay mechanism
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "/stripchart" and ProcessCommandLine contains "/computer:" and ProcessCommandLine contains "/period:" and ProcessCommandLine contains "/dataonly" and ProcessCommandLine contains "/samples:")) and ((FolderPath endswith "\\w32tm.exe") or (ProcessVersionInfoOriginalFileName == "w32time.dll")))
