// Title: Potential PowerShell Downgrade Attack
// ID: b3512211-c67e-4707-bedc-66efc7848863
// Status: test
// Level: medium
// Author: Harish Segar (rule)
// Date: 2020-03-20
// Tags: attack.execution, attack.t1059.001
// Description: Detects PowerShell downgrade attack by comparing the host versions with the actually used engine version 2.0
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FolderPath endswith "\\powershell.exe" and (ProcessCommandLine contains " -version 2 " or ProcessCommandLine contains " -versio 2 " or ProcessCommandLine contains " -versi 2 " or ProcessCommandLine contains " -vers 2 " or ProcessCommandLine contains " -ver 2 " or ProcessCommandLine contains " -ve 2 " or ProcessCommandLine contains " -v 2 "))
