// Title: WMIC Remote Command Execution
// ID: 7773b877-5abb-4a3e-b9c9-fd0369b59b00
// Status: test
// Level: medium
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-14
// Tags: attack.execution, attack.t1047
// Description: Detects the execution of WMIC to query information on a remote system
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "/node:" or ProcessCommandLine contains "-node:")) and ((FolderPath endswith "\\WMIC.exe") or (ProcessVersionInfoOriginalFileName == "wmic.exe"))) and not(((ProcessCommandLine contains "localhost" or ProcessCommandLine contains "127.0.0.1"))))
