// Title: Always Install Elevated MSI Spawned Cmd And Powershell
// ID: 1e53dd56-8d83-4eb4-a43e-b790a05510aa
// Status: test
// Level: medium
// Author: Teymur Kheirkhabarov (idea), Mangatas Tondang (rule), oscd.community
// Date: 2020-10-13
// Tags: attack.privilege-escalation, attack.t1548.002
// Description: Detects Windows Installer service (msiexec.exe) spawning "cmd" or "powershell"
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "Cmd.Exe" or ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))) and ((InitiatingProcessFolderPath contains "\\Windows\\Installer\\" and InitiatingProcessFolderPath contains "msi") and InitiatingProcessFolderPath endswith "tmp"))
