// Title: File Explorer Folder Opened Using Explorer Folder Shortcut Via Shell
// ID: c3d76afc-93df-461e-8e67-9b2bad3f2ac4
// Status: test
// Level: high
// Author: @Kostastsale
// Date: 2022-12-22
// Tags: attack.discovery, attack.t1135
// Description: Detects the initial execution of "cmd.exe" which spawns "explorer.exe" with the appropriate command line arguments for opening the "My Computer" folder.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and FolderPath endswith "\\explorer.exe" and ProcessCommandLine contains "shell:mycomputerfolder")
