// Title: Suspicious Execution of Powershell with Base64
// ID: fb843269-508c-4b76-8b8d-88679db22ce7
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-01-02
// Tags: attack.execution, attack.t1059.001
// Description: Commandline to launch powershell with a base64 payload
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and (ProcessCommandLine contains " -e " or ProcessCommandLine contains " -en " or ProcessCommandLine contains " -enc " or ProcessCommandLine contains " -enco" or ProcessCommandLine contains " -ec ")) and not((((InitiatingProcessFolderPath contains "C:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\" or InitiatingProcessFolderPath contains "\\gc_worker.exe")) or (ProcessCommandLine contains " -Encoding "))))
