// Title: Sdiagnhost Calling Suspicious Child Process
// ID: f3d39c45-de1a-4486-a687-ab126124f744
// Status: test
// Level: high
// Author: Nextron Systems, @Kostastsale
// Date: 2022-06-01
// Tags: attack.stealth, attack.t1036, attack.t1218
// Description: Detects sdiagnhost.exe calling a suspicious child process (e.g. used in exploits for Follina / CVE-2022-30190)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\sdiagnhost.exe" and (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\taskkill.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\calc.exe")) and not(((FolderPath endswith "\\cmd.exe" and ProcessCommandLine contains "bits") or (FolderPath endswith "\\powershell.exe" and (ProcessCommandLine endswith "-noprofile -" or ProcessCommandLine endswith "-noprofile")))))
