// Title: Suspicious Msbuild Execution By Uncommon Parent Process
// ID: 33be4333-2c6b-44f4-ae28-102cdbde0a31
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-11-17
// Tags: attack.stealth
// Description: Detects suspicious execution of 'Msbuild.exe' by a uncommon parent process
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\MSBuild.exe") or (ProcessVersionInfoOriginalFileName == "MSBuild.exe")) and not(((InitiatingProcessFolderPath endswith "\\devenv.exe" or InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\msbuild.exe" or InitiatingProcessFolderPath endswith "\\python.exe" or InitiatingProcessFolderPath endswith "\\explorer.exe" or InitiatingProcessFolderPath endswith "\\nuget.exe"))))
