// Title: Container Residence Discovery Via Proc Virtual FS
// ID: 746c86fb-ccda-4816-8997-01386263acc4
// Status: test
// Level: low
// Author: Seth Hanford
// Date: 2023-08-23
// Tags: attack.discovery, attack.t1082
// Description: Detects potential container discovery via listing of certain kernel features in the "/proc" virtual filesystem
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "awk" or FolderPath endswith "/cat" or FolderPath endswith "grep" or FolderPath endswith "/head" or FolderPath endswith "/less" or FolderPath endswith "/more" or FolderPath endswith "/nl" or FolderPath endswith "/tail")) and ((ProcessCommandLine contains "/proc/2/") or (ProcessCommandLine contains "/proc/" and (ProcessCommandLine endswith "/cgroup" or ProcessCommandLine endswith "/sched"))))
