// Title: DumpMinitool Execution
// ID: dee0a7a3-f200-4112-a99b-952196d81e42
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Florian Roth (Nextron Systems)
// Date: 2022-04-06
// Tags: attack.stealth, attack.t1036, attack.t1003.001, attack.credential-access
// Description: Detects the use of "DumpMinitool.exe" a tool that allows the dump of process memory via the use of the "MiniDumpWriteDump"
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " Full" or ProcessCommandLine contains " Mini" or ProcessCommandLine contains " WithHeap")) and (((FolderPath endswith "\\DumpMinitool.exe" or FolderPath endswith "\\DumpMinitool.x86.exe" or FolderPath endswith "\\DumpMinitool.arm64.exe")) or ((ProcessVersionInfoOriginalFileName == "DumpMinitool.exe" or ProcessVersionInfoOriginalFileName == "DumpMinitool.x86.exe" or ProcessVersionInfoOriginalFileName == "DumpMinitool.arm64.exe"))))
