// Title: Docker Container Discovery Via Dockerenv Listing
// ID: 11701de9-d5a5-44aa-8238-84252f131895
// Status: test
// Level: low
// Author: Seth Hanford
// Date: 2023-08-23
// Tags: attack.discovery, attack.t1082
// Description: Detects listing or file reading of ".dockerenv" which can be a sing of potential container discovery
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "/cat" or FolderPath endswith "/dir" or FolderPath endswith "/find" or FolderPath endswith "/ls" or FolderPath endswith "/stat" or FolderPath endswith "/test" or FolderPath endswith "grep") and ProcessCommandLine endswith ".dockerenv")
