// Title: Suspicious NTLM Authentication on the Printer Spooler Service
// ID: bb76d96b-821c-47cf-944b-7ce377864492
// Status: test
// Level: high
// Author: Elastic (idea), Tobias Michalski (Nextron Systems)
// Date: 2022-05-04
// Tags: attack.privilege-escalation, attack.credential-access, attack.t1212
// Description: Detects a privilege elevation attempt by coercing NTLM authentication on the Printer Spooler service
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "C:\\windows\\system32\\davclnt.dll,DavSetCookie" and ProcessCommandLine contains "http") and (ProcessCommandLine contains "spoolss" or ProcessCommandLine contains "srvsvc" or ProcessCommandLine contains "/print/pipe/")) and ((FolderPath endswith "\\rundll32.exe") or (ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE")))
