// Title: Compress Data and Lock With Password for Exfiltration With 7-ZIP
// ID: 9fbf5927-5261-4284-a71d-f681029ea574
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-07-27
// Tags: attack.collection, attack.t1560.001
// Description: An adversary may compress or encrypt data that is collected prior to exfiltration using 3rd party utilities
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " a " or ProcessCommandLine contains " u ")) and ((Description contains "7-Zip") or ((FolderPath endswith "\\7z.exe" or FolderPath endswith "\\7zr.exe" or FolderPath endswith "\\7za.exe")) or ((ProcessVersionInfoOriginalFileName == "7z.exe" or ProcessVersionInfoOriginalFileName == "7za.exe" or ProcessVersionInfoOriginalFileName == "7zr.exe"))) and (ProcessCommandLine contains " -p"))
