// Title: Private Keys Reconnaissance Via CommandLine Tools
// ID: 213d6a77-3d55-4ce8-ba74-fcfef741974e
// Status: test
// Level: medium
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-07-20
// Tags: attack.credential-access, attack.t1552.004
// Description: Adversaries may search for private key certificate files on compromised systems for insecurely stored credential
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ".key" or ProcessCommandLine contains ".pgp" or ProcessCommandLine contains ".gpg" or ProcessCommandLine contains ".ppk" or ProcessCommandLine contains ".p12" or ProcessCommandLine contains ".pem" or ProcessCommandLine contains ".pfx" or ProcessCommandLine contains ".cer" or ProcessCommandLine contains ".p7b" or ProcessCommandLine contains ".asc")) and (((ProcessCommandLine contains "dir ") and ((FolderPath endswith "\\cmd.exe") or (ProcessVersionInfoOriginalFileName == "Cmd.Exe"))) or ((ProcessCommandLine contains "Get-ChildItem ") and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll")))) or ((FolderPath endswith "\\findstr.exe") or (ProcessVersionInfoOriginalFileName == "FINDSTR.EXE"))))
