// Title: Weak or Abused Passwords In CLI
// ID: 91edcfb1-2529-4ac2-9ecc-7617f895c7e4
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-14
// Tags: attack.execution, attack.stealth
// Description: Detects weak passwords or often abused passwords (seen used by threat actors) via the CLI.
// An example would be a threat actor creating a new user via the net command and providing the password inline
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "123456789" or ProcessCommandLine contains "123123qwE" or ProcessCommandLine contains "Asd123.aaaa" or ProcessCommandLine contains "Decryptme" or ProcessCommandLine contains "P@ssw0rd!" or ProcessCommandLine contains "Pass8080" or ProcessCommandLine contains "password123" or ProcessCommandLine contains "test@202"))
