// Title: Renamed ProcDump Execution
// ID: 4a0b2c7e-7cb2-495d-8b63-5f268e7bfd67
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-11-18
// Tags: attack.stealth, attack.t1036.003
// Description: Detects the execution of a renamed ProcDump executable.
// This often done by attackers or malware in order to evade defensive mechanisms.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessVersionInfoOriginalFileName == "procdump") or (((ProcessCommandLine contains " -ma " or ProcessCommandLine contains " -mp ")) and (ProcessCommandLine contains " /accepteula"))) and not(((FolderPath endswith "\\procdump.exe" or FolderPath endswith "\\procdump64.exe" or FolderPath endswith "\\procdump64a.exe"))))
