// Title: PsExec/PAExec Escalation to LOCAL SYSTEM
// ID: 8834e2f7-6b4b-4f09-8906-d2276470ee23
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-11-23
// Tags: attack.resource-development, attack.t1587.001
// Description: Detects suspicious commandline flags used by PsExec and PAExec to escalate a command line to LOCAL_SYSTEM rights
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "psexec" or ProcessCommandLine contains "paexec" or ProcessCommandLine contains "accepteula")) and ((ProcessCommandLine contains " -s cmd" or ProcessCommandLine contains " -s -i cmd" or ProcessCommandLine contains " -i -s cmd" or ProcessCommandLine contains " -s pwsh" or ProcessCommandLine contains " -s -i pwsh" or ProcessCommandLine contains " -i -s pwsh" or ProcessCommandLine contains " -s powershell" or ProcessCommandLine contains " -s -i powershell" or ProcessCommandLine contains " -i -s powershell")))
