// Title: Suspicious MsiExec Embedding Parent
// ID: 4a2a2c3e-209f-4d01-b513-4155a540b469
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-04-16
// Tags: attack.stealth, attack.t1218.007
// Description: Adversaries may abuse msiexec.exe to proxy the execution of malicious payloads
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\cmd.exe") and (InitiatingProcessCommandLine contains "MsiExec.exe" and InitiatingProcessCommandLine contains "-Embedding ")) and not(((FolderPath endswith ":\\Windows\\System32\\cmd.exe" and ProcessCommandLine contains "C:\\Program Files\\SplunkUniversalForwarder\\bin\\") or ((ProcessCommandLine contains "\\DismFoDInstall.cmd") or ((InitiatingProcessCommandLine contains "\\MsiExec.exe -Embedding " and InitiatingProcessCommandLine contains "Global\\MSI0000"))))))
