// Title: Potentially Suspicious Child Process Of Regsvr32
// ID: 6f0947a4-1c5e-4e0d-8ac7-53159b8f23ca
// Status: test
// Level: high
// Author: elhoim, Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-05-05
// Tags: attack.stealth, attack.t1218.010
// Description: Detects potentially suspicious child processes of "regsvr32.exe".
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\regsvr32.exe" and (FolderPath endswith "\\calc.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\explorer.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe" or FolderPath endswith "\\nltest.exe" or FolderPath endswith "\\notepad.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\reg.exe" or FolderPath endswith "\\schtasks.exe" or FolderPath endswith "\\werfault.exe" or FolderPath endswith "\\wscript.exe")) and not((FolderPath endswith "\\werfault.exe" and ProcessCommandLine contains " -u -p ")))
