// Title: Microsoft IIS Service Account Password Dumped
// ID: 2d3cdeec-c0db-45b4-aa86-082f7eb75701
// Status: test
// Level: high
// Author: Tim Rauch, Janantha Marasinghe, Elastic (original idea)
// Date: 2022-11-08
// Tags: attack.credential-access, attack.t1003
// Description: Detects the Internet Information Services (IIS) command-line tool, AppCmd, being used to list passwords
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "list ") and ((FolderPath endswith "\\appcmd.exe") or (ProcessVersionInfoOriginalFileName == "appcmd.exe"))) and (((ProcessCommandLine contains " /config" or ProcessCommandLine contains " /xml" or ProcessCommandLine contains " -config" or ProcessCommandLine contains " -xml")) or (((ProcessCommandLine contains " /@t" or ProcessCommandLine contains " /text" or ProcessCommandLine contains " /show" or ProcessCommandLine contains " -@t" or ProcessCommandLine contains " -text" or ProcessCommandLine contains " -show")) and ((ProcessCommandLine contains ":\\*" or ProcessCommandLine contains "password")))))
