// Title: Renamed SysInternals DebugView Execution
// ID: cd764533-2e07-40d6-a718-cfeec7f2da7f
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2020-05-28
// Tags: attack.resource-development, attack.t1588.002
// Description: Detects suspicious renamed SysInternals DebugView execution
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Product == "Sysinternals DebugView") and not((ProcessVersionInfoOriginalFileName == "Dbgview.exe" and FolderPath endswith "\\Dbgview.exe")))
