// Title: Schtasks Creation Or Modification With SYSTEM Privileges
// ID: 89ca78fd-b37c-4310-b3d3-81a023f83936
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-28
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053.005
// Description: Detects the creation or update of a scheduled task to run with "NT AUTHORITY\SYSTEM" privileges
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\schtasks.exe" and (ProcessCommandLine contains " /change " or ProcessCommandLine contains " /create ")) and (ProcessCommandLine contains "/ru ") and ((ProcessCommandLine contains "NT AUT" or ProcessCommandLine contains " SYSTEM "))) and not((((ProcessCommandLine contains "/Create /F /RU System /SC WEEKLY /TN AviraSystemSpeedupVerify /TR " or ProcessCommandLine contains ":\\Program Files (x86)\\Avira\\System Speedup\\setup\\avira_speedup_setup.exe" or ProcessCommandLine contains "/VERIFY /VERYSILENT /NOSTART /NODOTNET /NORESTART\" /RL HIGHEST")) or ((ProcessCommandLine contains "Subscription Heartbeat" and ProcessCommandLine contains "\\HeartbeatConfig.xml" and ProcessCommandLine contains "\\Microsoft Shared\\OFFICE")) or (FolderPath endswith "\\schtasks.exe" and (ProcessCommandLine contains "/TN TVInstallRestore" and ProcessCommandLine contains "\\TeamViewer_.exe")))))
