// Title: Python Function Execution Security Warning Disabled In Excel
// ID: 023c654f-8f16-44d9-bb2b-00ff36a62af9
// Status: test
// Level: high
// Author: @Kostastsale
// Date: 2023-08-22
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects changes to the registry value "PythonFunctionWarnings" that would prevent any warnings or alerts from showing when Python functions are about to be executed.
// Threat actors could run malicious code through the new Microsoft Excel feature that allows Python to run within the spreadsheet.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "\\Microsoft\\Office\\" and ProcessCommandLine contains "\\Excel\\Security" and ProcessCommandLine contains "PythonFunctionWarnings") and ProcessCommandLine contains " 0")
