// Title: Chopper Webshell Process Pattern
// ID: fa3c117a-bc0d-416e-a31b-0c0e80653efb
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), MSTI (query)
// Date: 2022-10-01
// Tags: attack.persistence, attack.discovery, attack.t1505.003, attack.t1018, attack.t1033, attack.t1087
// Description: Detects patterns found in process executions cause by China Chopper like tiny (ASPX) webshells
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "&ipconfig&echo" or ProcessCommandLine contains "&quser&echo" or ProcessCommandLine contains "&whoami&echo" or ProcessCommandLine contains "&c:&echo" or ProcessCommandLine contains "&cd&echo" or ProcessCommandLine contains "&dir&echo" or ProcessCommandLine contains "&echo [E]" or ProcessCommandLine contains "&echo [S]")) and ((FolderPath endswith "\\w3wp.exe") or (InitiatingProcessFolderPath endswith "\\w3wp.exe")))
