// Title: Chromium Browser Instance Executed With Custom Extension
// ID: 88d6e60c-759d-4ac1-a447-c0f1466c2d21
// Status: test
// Level: medium
// Author: Aedan Russell, frack113, X__Junior (Nextron Systems)
// Date: 2022-06-19
// Tags: attack.persistence, attack.t1176.001
// Description: Detects a Chromium based browser process with the 'load-extension' flag to start a instance with a custom extension
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\vivaldi.exe") and ProcessCommandLine contains "--load-extension=")
