// Title: New User Created Via Net.EXE With Never Expire Option
// ID: b9f0e6f5-09b4-4358-bae4-08408705bd5c
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-12
// Tags: attack.persistence, attack.t1136.001
// Description: Detects creation of local users via the net.exe command with the option "never expire"
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "user" and ProcessCommandLine contains "add" and ProcessCommandLine contains "expires:never")) and (((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe")) or ((ProcessVersionInfoOriginalFileName == "net.exe" or ProcessVersionInfoOriginalFileName == "net1.exe"))))
