// Title: HackTool - Covenant PowerShell Launcher
// ID: c260b6db-48ba-4b4a-a76f-2f67644e99d2
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro, oscd.community
// Date: 2020-06-04
// Tags: attack.execution, attack.stealth, attack.t1059.001, attack.t1564.003
// Description: Detects suspicious command lines used in Covenant luanchers
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "-Sta" and ProcessCommandLine contains "-Nop" and ProcessCommandLine contains "-Window" and ProcessCommandLine contains "Hidden") and (ProcessCommandLine contains "-Command" or ProcessCommandLine contains "-EncodedCommand")) or ((ProcessCommandLine contains "sv o (New-Object IO.MemorySteam);sv d " or ProcessCommandLine contains "mshta file.hta" or ProcessCommandLine contains "GruntHTTP" or ProcessCommandLine contains "-EncodedCommand cwB2ACAAbwAgA")))
