// Title: ESXi Storage Information Discovery Via ESXCLI
// ID: f41dada5-3f56-4232-8503-3fb7f9cf2d60
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Cedric Maurugeon
// Date: 2023-09-04
// Tags: attack.discovery, attack.execution, attack.t1033, attack.t1007, attack.t1059.012
// Description: Detects execution of the "esxcli" command with the "storage" flag in order to retrieve information about the storage status and other related information. Seen used by malware such as DarkSide and LockBit.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " get" or ProcessCommandLine contains " list")) and (FolderPath endswith "/esxcli" and ProcessCommandLine contains "storage"))
