// Title: Msiexec Quiet Installation
// ID: 79a87aa6-e4bd-42fc-a5bb-5e6fbdcd62f5
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-01-16
// Tags: attack.stealth, attack.t1218.007
// Description: Adversaries may abuse msiexec.exe to proxy execution of malicious payloads.
// Msiexec.exe is the command-line utility for the Windows Installer and is thus commonly associated with executing installation packages (.msi)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "-i" or ProcessCommandLine contains "/i" or ProcessCommandLine contains "-package" or ProcessCommandLine contains "/package" or ProcessCommandLine contains "-a" or ProcessCommandLine contains "/a" or ProcessCommandLine contains "-j" or ProcessCommandLine contains "/j")) and ((FolderPath endswith "\\msiexec.exe") or (ProcessVersionInfoOriginalFileName == "msiexec.exe")) and ((ProcessCommandLine contains "-q" or ProcessCommandLine contains "/q"))) and not(((InitiatingProcessFolderPath == "C:\\Windows\\CCM\\Ccm32BitLauncher.exe" and (IntegrityLevel == "System" or IntegrityLevel == "S-1-16-16384")) or (InitiatingProcessFolderPath startswith "C:\\Windows\\Temp\\"))) and not(((InitiatingProcessFolderPath startswith "C:\\Users\\" and InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\") or (InitiatingProcessFolderPath endswith "C:\\Windows\\System32\\wsl.exe" and FolderPath endswith "C:\\Windows\\System32\\msiexec.exe"))))
