// Title: Tasks Folder Evasion
// ID: cc4e02ba-9c06-48e2-b09e-2500cace9ae0
// Status: test
// Level: high
// Author: Sreeman
// Date: 2020-01-13
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.stealth, attack.t1574.001
// Description: The Tasks folder in system32 and syswow64 are globally writable paths.
// Adversaries can take advantage of this and load or influence any script hosts or ANY .NET Application
// in Tasks to load and execute a custom assembly into cscript, wscript, regsvr32, mshta, eventvwr
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "echo " or ProcessCommandLine contains "copy " or ProcessCommandLine contains "type " or ProcessCommandLine contains "file createnew")) and ((ProcessCommandLine contains " C:\\Windows\\System32\\Tasks\\" or ProcessCommandLine contains " C:\\Windows\\SysWow64\\Tasks\\")))
