// Title: GUI Input Capture - macOS
// ID: 60f1ce20-484e-41bd-85f4-ac4afec2c541
// Status: test
// Level: low
// Author: remotephone, oscd.community
// Date: 2020-10-13
// Tags: attack.collection, attack.credential-access, attack.t1056.002
// Description: Detects attempts to use system dialog prompts to capture user credentials
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "-e" and ProcessCommandLine contains "display" and ProcessCommandLine contains "dialog" and ProcessCommandLine contains "answer")) and ((ProcessCommandLine contains "admin" or ProcessCommandLine contains "administrator" or ProcessCommandLine contains "authenticate" or ProcessCommandLine contains "authentication" or ProcessCommandLine contains "credentials" or ProcessCommandLine contains "pass" or ProcessCommandLine contains "password" or ProcessCommandLine contains "unlock")) and (FolderPath endswith "/osascript"))
