// Title: Suspicious Process Start Locations
// ID: 15b75071-74cc-47e0-b4c6-b43744a62a2b
// Status: test
// Level: medium
// Author: juju4, Jonhnathan Ribeiro, oscd.community
// Date: 2019-01-16
// Tags: attack.stealth, attack.t1036, car.2013-05-002
// Description: Detects suspicious process run from unusual locations
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath contains ":\\RECYCLER\\" or FolderPath contains ":\\SystemVolumeInformation\\")) or ((FolderPath startswith "C:\\Windows\\Tasks\\" or FolderPath startswith "C:\\Windows\\debug\\" or FolderPath startswith "C:\\Windows\\fonts\\" or FolderPath startswith "C:\\Windows\\help\\" or FolderPath startswith "C:\\Windows\\drivers\\" or FolderPath startswith "C:\\Windows\\addins\\" or FolderPath startswith "C:\\Windows\\cursors\\" or FolderPath startswith "C:\\Windows\\system32\\tasks\\")))
