// Title: HackTool - Bloodhound/Sharphound Execution
// ID: f376c8a7-a2d0-4ddc-aa0c-16c17236d962
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2019-12-20
// Tags: attack.discovery, attack.t1087.001, attack.t1087.002, attack.t1482, attack.t1069.001, attack.t1069.002, attack.execution, attack.t1059.001
// Description: Detects command line parameters used by Bloodhound and Sharphound hack tools
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " -CollectionMethod All " or ProcessCommandLine contains " --CollectionMethods Session " or ProcessCommandLine contains " --Loop --Loopduration " or ProcessCommandLine contains " --PortScanTimeout " or ProcessCommandLine contains ".exe -c All -d " or ProcessCommandLine contains "Invoke-Bloodhound" or ProcessCommandLine contains "Get-BloodHoundData")) or ((ProcessCommandLine contains " -JsonFolder " and ProcessCommandLine contains " -ZipFileName ")) or ((ProcessCommandLine contains " DCOnly " and ProcessCommandLine contains " --NoSaveCache ")) or ((Product contains "SharpHound") or (Description contains "SharpHound") or ((Company contains "SpecterOps" or Company contains "evil corp")) or ((FolderPath contains "\\Bloodhound.exe" or FolderPath contains "\\SharpHound.exe"))))
