// Title: Suspicious Extrac32 Execution
// ID: aa8e035d-7be4-48d3-a944-102aec04400d
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-11-26
// Tags: attack.command-and-control, attack.t1105
// Description: Download or Copy file with Extrac32
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains ".cab") and ((ProcessCommandLine contains "extrac32.exe") or (FolderPath endswith "\\extrac32.exe") or (ProcessVersionInfoOriginalFileName == "extrac32.exe")) and ((ProcessCommandLine contains "/C" or ProcessCommandLine contains "/Y" or ProcessCommandLine contains " \\\\\\\\")))
