// Title: Operator Bloopers Cobalt Strike Commands
// ID: 647c7b9e-d784-4fda-b9a0-45c565a7b729
// Status: test
// Level: high
// Author: _pete_0, TheDFIRReport
// Date: 2022-05-06
// Tags: attack.execution, attack.t1059.003, stp.1u
// Description: Detects use of Cobalt Strike commands accidentally entered in the CMD shell
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine startswith "cmd " or ProcessCommandLine startswith "cmd.exe" or ProcessCommandLine startswith "c:\\windows\\system32\\cmd.exe") and (ProcessCommandLine contains "psinject" or ProcessCommandLine contains "spawnas" or ProcessCommandLine contains "make_token" or ProcessCommandLine contains "remote-exec" or ProcessCommandLine contains "rev2self" or ProcessCommandLine contains "dcsync" or ProcessCommandLine contains "logonpasswords" or ProcessCommandLine contains "execute-assembly" or ProcessCommandLine contains "getsystem")) and ((ProcessVersionInfoOriginalFileName == "Cmd.Exe") or (FolderPath endswith "\\cmd.exe")))
