// Title: PUA - NSudo Execution
// ID: 771d1eb5-9587-4568-95fb-9ec44153a012
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali
// Date: 2022-01-24
// Tags: attack.execution, attack.t1569.002, attack.s0029
// Description: Detects the use of NSudo tool for command execution
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "-U:S " or ProcessCommandLine contains "-U:T " or ProcessCommandLine contains "-U:E " or ProcessCommandLine contains "-P:E " or ProcessCommandLine contains "-M:S " or ProcessCommandLine contains "-M:H " or ProcessCommandLine contains "-U=S " or ProcessCommandLine contains "-U=T " or ProcessCommandLine contains "-U=E " or ProcessCommandLine contains "-P=E " or ProcessCommandLine contains "-M=S " or ProcessCommandLine contains "-M=H " or ProcessCommandLine contains "-ShowWindowMode:Hide")) and (((FolderPath endswith "\\NSudo.exe" or FolderPath endswith "\\NSudoLC.exe" or FolderPath endswith "\\NSudoLG.exe")) or ((ProcessVersionInfoOriginalFileName == "NSudo.exe" or ProcessVersionInfoOriginalFileName == "NSudoLC.exe" or ProcessVersionInfoOriginalFileName == "NSudoLG.exe"))))
