// Title: Deny Service Access Using Security Descriptor Tampering Via Sc.EXE
// ID: 99cf1e02-00fb-4c0d-8375-563f978dfd37
// Status: test
// Level: high
// Author: Jonhnathan Ribeiro, oscd.community
// Date: 2020-10-16
// Tags: attack.privilege-escalation, attack.persistence, attack.t1543.003
// Description: Detects suspicious DACL modifications to deny access to a service that affects critical trustees. This can be used to hide services or make them unstoppable.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\sc.exe") or (ProcessVersionInfoOriginalFileName == "sc.exe")) and ((ProcessCommandLine contains "sdset" and ProcessCommandLine contains "D;")) and ((ProcessCommandLine contains ";IU" or ProcessCommandLine contains ";SU" or ProcessCommandLine contains ";BA" or ProcessCommandLine contains ";SY" or ProcessCommandLine contains ";WD")))
