// Title: HackTool - SharpLdapWhoami Execution
// ID: d9367cbb-c2e0-47ce-bdc0-128cb6da898d
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-29
// Tags: attack.discovery, attack.t1033, car.2016-03-001
// Description: Detects SharpLdapWhoami, a whoami alternative that queries the LDAP service on a domain controller
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine endswith " /method:ntlm" or ProcessCommandLine endswith " /method:kerb" or ProcessCommandLine endswith " /method:nego" or ProcessCommandLine endswith " /m:nego" or ProcessCommandLine endswith " /m:ntlm" or ProcessCommandLine endswith " /m:kerb")) or (FolderPath endswith "\\SharpLdapWhoami.exe") or ((ProcessVersionInfoOriginalFileName contains "SharpLdapWhoami") or (Product == "SharpLdapWhoami")))
