// Title: PUA - NirCmd Execution
// ID: 4e2ed651-1906-4a59-a78a-18220fca1b22
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-24
// Tags: attack.execution, attack.t1569.002, attack.s0029
// Description: Detects the use of NirCmd tool for command execution, which could be the result of legitimate administrative activity
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains " execmd " or ProcessCommandLine contains ".exe script " or ProcessCommandLine contains ".exe shexec " or ProcessCommandLine contains " runinteractive ")) or ((FolderPath endswith "\\NirCmd.exe") or (ProcessVersionInfoOriginalFileName == "NirCmd.exe"))) or (((ProcessCommandLine contains " exec " or ProcessCommandLine contains " exec2 ")) and ((ProcessCommandLine contains " show " or ProcessCommandLine contains " hide "))))
