// Title: HackTool - SharpLDAPmonitor Execution
// ID: 9f8fc146-1d1a-4dbf-b8fd-dfae15e08541
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-30
// Tags: attack.discovery
// Description: Detects execution of the SharpLDAPmonitor. Which can monitor the creation, deletion and changes to LDAP objects.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "/user:" and ProcessCommandLine contains "/pass:" and ProcessCommandLine contains "/dcip:")) or ((FolderPath endswith "\\SharpLDAPmonitor.exe") or (ProcessVersionInfoOriginalFileName == "SharpLDAPmonitor.exe")))
