// Title: Wlrmdr.EXE Uncommon Argument Or Child Process
// ID: 9cfc00b6-bfb7-49ce-9781-ef78503154bb
// Status: experimental
// Level: medium
// Author: frack113, manasmbellani
// Date: 2022-02-16
// Tags: attack.stealth, attack.t1218
// Description: Detects the execution of "Wlrmdr.exe" with the "-u" command line flag which allows anything passed to it to be an argument of the ShellExecute API, which would allow an attacker to execute arbitrary binaries.
// This detection also focuses on any uncommon child processes spawned from "Wlrmdr.exe" as a supplement for those that posses "ParentImage" telemetry.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\wlrmdr.exe") or ((((ProcessCommandLine contains "-a " or ProcessCommandLine contains "/a ")) and ((ProcessCommandLine contains "-f " or ProcessCommandLine contains "/f ")) and ((ProcessCommandLine contains "-m " or ProcessCommandLine contains "/m ")) and ((ProcessCommandLine contains "-s " or ProcessCommandLine contains "/s ")) and ((ProcessCommandLine contains "-t " or ProcessCommandLine contains "/t ")) and ((ProcessCommandLine contains "-u " or ProcessCommandLine contains "/u ")) and ((FolderPath endswith "\\wlrmdr.exe") or (ProcessVersionInfoOriginalFileName == "WLRMNDR.EXE"))) and not((((InitiatingProcessFolderPath == "" or InitiatingProcessFolderPath == "-")) or ((isempty(InitiatingProcessFolderPath) or isnull(InitiatingProcessFolderPath))) or (InitiatingProcessFolderPath == "C:\\Windows\\System32\\winlogon.exe")))))
