// Title: Potential Suspicious Change To Sensitive/Critical Files
// ID: 86157017-c2b1-4d4a-8c33-93b8e67e4af4
// Status: test
// Level: medium
// Author: @d4ns4n_ (Wuerth-Phoenix)
// Date: 2023-05-30
// Tags: attack.impact, attack.t1565.001
// Description: Detects changes of sensitive and critical files. Monitors files that you don't expect to change without planning on Linux system.
// These files include, but are not limited to, system configuration files, authentication files, and critical application files.
// Attackers often target these files to maintain persistence, escalate privileges, or disrupt system operations.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "/cat" or FolderPath endswith "/echo" or FolderPath endswith "/grep" or FolderPath endswith "/head" or FolderPath endswith "/more" or FolderPath endswith "/tail") and ProcessCommandLine contains ">") or ((FolderPath endswith "/emacs" or FolderPath endswith "/nano" or FolderPath endswith "/sed" or FolderPath endswith "/vi" or FolderPath endswith "/vim"))) and ((ProcessCommandLine contains "/bin/login" or ProcessCommandLine contains "/bin/passwd" or ProcessCommandLine contains "/boot/" or ProcessCommandLine contains "/etc/*.conf" or ProcessCommandLine contains "/etc/cron." or ProcessCommandLine contains "/etc/crontab" or ProcessCommandLine contains "/etc/hosts" or ProcessCommandLine contains "/etc/init.d" or ProcessCommandLine contains "/etc/sudoers" or ProcessCommandLine contains "/opt/bin/" or ProcessCommandLine contains "/sbin" or ProcessCommandLine contains "/usr/bin/" or ProcessCommandLine contains "/usr/local/bin/")) and not(1=1))
