// Title: RDP Port Forwarding Rule Added Via Netsh.EXE
// ID: 782d6f3e-4c5d-4b8c-92a3-1d05fed72e63
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), oscd.community
// Date: 2019-01-29
// Tags: attack.lateral-movement, attack.command-and-control, attack.t1090
// Description: Detects the execution of netsh to configure a port forwarding of port 3389 (RDP) rule
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " i" and ProcessCommandLine contains " p" and ProcessCommandLine contains "=3389" and ProcessCommandLine contains " c")) and ((FolderPath endswith "\\netsh.exe") or (ProcessVersionInfoOriginalFileName == "netsh.exe")))
