// Title: MacOS Scripting Interpreter AppleScript
// ID: 1bc2e6c5-0885-472b-bed6-be5ea8eace55
// Status: test
// Level: medium
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-21
// Tags: attack.execution, attack.t1059.002
// Description: Detects execution of AppleScript of the macOS scripting language AppleScript.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "/osascript" and (ProcessCommandLine contains " -e " or ProcessCommandLine contains ".scpt" or ProcessCommandLine contains ".js")) and not((InitiatingProcessFolderPath endswith "opencode" and (ProcessCommandLine contains "osascript" and ProcessCommandLine contains " -e " and ProcessCommandLine contains "set imageData to the clipboard" and ProcessCommandLine contains "set fileRef"))))
