// Title: Proxy Execution Via Wuauclt.EXE
// ID: af77cf95-c469-471c-b6a0-946c685c4798
// Status: test
// Level: high
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research), Florian Roth (Nextron Systems), Sreeman, FPT.EagleEye Team
// Date: 2020-10-12
// Tags: attack.stealth, attack.t1218, attack.execution
// Description: Detects the use of the Windows Update Client binary (wuauclt.exe) for proxy execution.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "UpdateDeploymentProvider" and ProcessCommandLine contains "RunHandlerComServer")) and ((FolderPath endswith "\\wuauclt.exe") or (ProcessVersionInfoOriginalFileName == "wuauclt.exe"))) and not(((ProcessCommandLine contains " /UpdateDeploymentProvider UpdateDeploymentProvider.dll ") or ((ProcessCommandLine contains ":\\Windows\\UUS\\Packages\\Preview\\amd64\\updatedeploy.dll /ClassId" or ProcessCommandLine contains ":\\Windows\\UUS\\amd64\\UpdateDeploy.dll /ClassId")) or ((ProcessCommandLine contains ":\\Windows\\WinSxS\\" and ProcessCommandLine contains "\\UpdateDeploy.dll /ClassId ")) or (ProcessCommandLine contains " wuaueng.dll "))))
