// Title: Local System Accounts Discovery - Linux
// ID: b45e3d6f-42c6-47d8-a478-df6bd6cf534c
// Status: test
// Level: low
// Author: Alejandro Ortuno, oscd.community, CheraghiMilad
// Date: 2020-10-08
// Tags: attack.discovery, attack.t1087.001
// Description: Detects enumeration of local system accounts. This information can help adversaries determine which local accounts exist on a system to aid in follow-on behavior.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "/lastlog") or (ProcessCommandLine contains "'x:0:'") or ((FolderPath endswith "/cat" or FolderPath endswith "/ed" or FolderPath endswith "/head" or FolderPath endswith "/more" or FolderPath endswith "/nano" or FolderPath endswith "/tail" or FolderPath endswith "/vi" or FolderPath endswith "/vim" or FolderPath endswith "/less" or FolderPath endswith "/emacs" or FolderPath endswith "/sqlite3" or FolderPath endswith "/makemap") and (ProcessCommandLine contains "/etc/passwd" or ProcessCommandLine contains "/etc/shadow" or ProcessCommandLine contains "/etc/sudoers" or ProcessCommandLine contains "/etc/spwd.db" or ProcessCommandLine contains "/etc/pwd.db" or ProcessCommandLine contains "/etc/master.passwd")) or (FolderPath endswith "/id") or (FolderPath endswith "/lsof" and ProcessCommandLine contains "-u"))
