// Title: Phishing Pattern ISO in Archive
// ID: fcdf69e5-a3d3-452a-9724-26f2308bf2b1
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-07
// Tags: attack.initial-access, attack.t1566
// Description: Detects cases in which an ISO files is opend within an archiver like 7Zip or Winrar, which is a sign of phishing as threat actors put small ISO files in archives as email attachments to bypass certain filters and protective measures (mark of web)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\Winrar.exe" or InitiatingProcessFolderPath endswith "\\7zFM.exe" or InitiatingProcessFolderPath endswith "\\peazip.exe") and (FolderPath endswith "\\isoburn.exe" or FolderPath endswith "\\PowerISO.exe" or FolderPath endswith "\\ImgBurn.exe"))
