// Title: Suspicious AddinUtil.EXE CommandLine Execution
// ID: 631b22a4-70f4-4e2f-9ea8-42f84d9df6d8
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), Michael McKinley (@McKinleyMike), Tony Latteri (@TheLatteri)
// Date: 2023-09-18
// Tags: attack.stealth, attack.t1218
// Description: Detects execution of the Add-In deployment cache updating utility (AddInutil.exe) with suspicious Addinroot or Pipelineroot paths. An adversary may execute AddinUtil.exe with uncommon Addinroot/Pipelineroot paths that point to the adversaries Addins.Store payload.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\addinutil.exe") or (ProcessVersionInfoOriginalFileName == "AddInUtil.exe")) and ((((ProcessCommandLine contains "-AddInRoot:" or ProcessCommandLine contains "-PipelineRoot:")) and ((ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Desktop\\" or ProcessCommandLine contains "\\Downloads\\" or ProcessCommandLine contains "\\Users\\Public\\" or ProcessCommandLine contains "\\Windows\\Temp\\"))) or ((ProcessCommandLine contains "-AddInRoot:." or ProcessCommandLine contains "-AddInRoot:\".\"" or ProcessCommandLine contains "-PipelineRoot:." or ProcessCommandLine contains "-PipelineRoot:\".\"") and (CurrentDirectory contains "\\AppData\\Local\\Temp\\" or CurrentDirectory contains "\\Desktop\\" or CurrentDirectory contains "\\Downloads\\" or CurrentDirectory contains "\\Users\\Public\\" or CurrentDirectory contains "\\Windows\\Temp\\"))))
