// Title: Hiding Files with Attrib.exe
// ID: 4281cb20-2994-4580-aa63-c8b86d019934
// Status: test
// Level: medium
// Author: Sami Ruohonen
// Date: 2019-01-16
// Tags: attack.stealth, attack.t1564.001
// Description: Detects usage of attrib.exe to hide files from users.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " +h ") and ((FolderPath endswith "\\attrib.exe") or (ProcessVersionInfoOriginalFileName == "ATTRIB.EXE"))) and not((ProcessCommandLine contains "\\desktop.ini ")) and not((InitiatingProcessFolderPath endswith "\\cmd.exe" and ProcessCommandLine == "+R +H +S +A \\\\\\*.cui" and InitiatingProcessCommandLine == "C:\\\\WINDOWS\\\\system32\\\\\\*.bat")))
