// Title: File and Directory Discovery - MacOS
// ID: 089dbdf6-b960-4bcc-90e3-ffc3480c20f6
// Status: test
// Level: informational
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Tags: attack.discovery, attack.t1083
// Description: Detects usage of system utilities to discover files and directories
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath == "/usr/bin/file" and ProcessCommandLine matches regex @"(.){200,}") or (FolderPath == "/usr/bin/find") or (FolderPath == "/usr/bin/mdfind") or (FolderPath == "/bin/ls" and ProcessCommandLine contains "-R") or 1=1)
