// Title: HackTool - Certify Execution
// ID: 762f2482-ff21-4970-8939-0aa317a886bb
// Status: test
// Level: high
// Author: pH-T (Nextron Systems)
// Date: 2023-04-17
// Tags: attack.discovery, attack.credential-access, attack.t1649
// Description: Detects Certify a tool for Active Directory certificate abuse based on PE metadata characteristics and common command line arguments.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\Certify.exe") or (ProcessVersionInfoOriginalFileName == "Certify.exe") or (Description contains "Certify")) or (((ProcessCommandLine contains ".exe cas " or ProcessCommandLine contains ".exe find " or ProcessCommandLine contains ".exe pkiobjects " or ProcessCommandLine contains ".exe request " or ProcessCommandLine contains ".exe download ")) and ((ProcessCommandLine contains " /vulnerable" or ProcessCommandLine contains " /template:" or ProcessCommandLine contains " /altname:" or ProcessCommandLine contains " /domain:" or ProcessCommandLine contains " /path:" or ProcessCommandLine contains " /ca:"))))
