// Title: Portable Gpg.EXE Execution
// ID: 77df53a5-1d78-4f32-bc5a-0e7465bd8f41
// Status: test
// Level: medium
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-06
// Tags: attack.impact, attack.t1486
// Description: Detects the execution of "gpg.exe" from uncommon location. Often used by ransomware and loaders to decrypt/encrypt data.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\gpg.exe" or FolderPath endswith "\\gpg2.exe")) or (ProcessVersionInfoOriginalFileName == "gpg.exe") or (Description == "GnuPG’s OpenPGP tool")) and not(((FolderPath contains ":\\Program Files (x86)\\GNU\\GnuPG\\bin\\" or FolderPath contains ":\\Program Files (x86)\\GnuPG VS-Desktop\\" or FolderPath contains ":\\Program Files (x86)\\GnuPG\\bin\\" or FolderPath contains ":\\Program Files (x86)\\Gpg4win\\bin\\"))))
