// Title: PowerShell Base64 Encoded Invoke Keyword
// ID: 6385697e-9f1b-40bd-8817-f4a91f40508e
// Status: test
// Level: high
// Author: pH-T (Nextron Systems), Harjot Singh, @cyb3rjy0t
// Date: 2022-05-20
// Tags: attack.execution, attack.stealth, attack.t1059.001, attack.t1027
// Description: Detects UTF-8 and UTF-16 Base64 encoded powershell 'Invoke-' calls
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains " -e") and ((ProcessCommandLine contains "SQBuAHYAbwBrAGUALQ" or ProcessCommandLine contains "kAbgB2AG8AawBlAC0A" or ProcessCommandLine contains "JAG4AdgBvAGsAZQAtA" or ProcessCommandLine contains "SW52b2tlL" or ProcessCommandLine contains "ludm9rZS" or ProcessCommandLine contains "JbnZva2Ut")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))))
