// Title: IIS Native-Code Module Command Line Installation
// ID: 9465ddf4-f9e4-4ebd-8d98-702df3a93239
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2019-12-11
// Tags: attack.persistence, attack.t1505.003
// Description: Detects suspicious IIS native-code module installations via command line
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "install" and ProcessCommandLine contains "module") and (ProcessCommandLine contains "-name:" or ProcessCommandLine contains "/name:")) and ((FolderPath endswith "\\appcmd.exe") or (ProcessVersionInfoOriginalFileName == "appcmd.exe"))) and not((InitiatingProcessFolderPath == "C:\\Windows\\System32\\inetsrv\\iissetup.exe")))
