// Title: Modify Group Policy Settings
// ID: ada4b0c4-758b-46ac-9033-9004613a150d
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-08-19
// Tags: attack.privilege-escalation, attack.defense-impairment, attack.t1484.001
// Description: Detect malicious GPO modifications can be used to implement many other malicious behaviors.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "GroupPolicyRefreshTimeDC" or ProcessCommandLine contains "GroupPolicyRefreshTimeOffsetDC" or ProcessCommandLine contains "GroupPolicyRefreshTime" or ProcessCommandLine contains "GroupPolicyRefreshTimeOffset" or ProcessCommandLine contains "EnableSmartScreen" or ProcessCommandLine contains "ShellSmartScreenLevel")) and (ProcessCommandLine contains "\\SOFTWARE\\Policies\\Microsoft\\Windows\\System") and ((FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName == "reg.exe")))
