// Title: Insecure Transfer Via Curl.EXE
// ID: cb9cc1d1-e84e-4bdc-b7ad-c31b1b7908ec
// Status: test
// Level: medium
// Author: X__Junior (Nextron Systems)
// Date: 2023-06-30
// Tags: attack.execution
// Description: Detects execution of "curl.exe" with the "--insecure" flag.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine matches regex @"\\s-k\\s") or (ProcessCommandLine contains "--insecure")) and ((FolderPath endswith "\\curl.exe") or (ProcessVersionInfoOriginalFileName == "curl.exe")))
