// Title: Suspicious Download From Direct IP Via Bitsadmin
// ID: 99c840f2-2012-46fd-9141-c761987550ef
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-28
// Tags: attack.persistence, attack.execution, attack.stealth, attack.t1197, attack.s0190, attack.t1036.003
// Description: Detects usage of bitsadmin downloading a file using an URL that contains an IP
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "://1" or ProcessCommandLine contains "://2" or ProcessCommandLine contains "://3" or ProcessCommandLine contains "://4" or ProcessCommandLine contains "://5" or ProcessCommandLine contains "://6" or ProcessCommandLine contains "://7" or ProcessCommandLine contains "://8" or ProcessCommandLine contains "://9")) and ((ProcessCommandLine contains " /transfer " or ProcessCommandLine contains " /create " or ProcessCommandLine contains " /addfile ")) and ((FolderPath endswith "\\bitsadmin.exe") or (ProcessVersionInfoOriginalFileName == "bitsadmin.exe"))) and not((ProcessCommandLine contains "://7-")))
