// Title: Nslookup PowerShell Download Cradle - ProcessCreation
// ID: 1b3b01c7-84e9-4072-86e5-fc285a41ff23
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-05
// Tags: attack.stealth
// Description: Detects suspicious powershell download cradle using nslookup. This cradle uses nslookup to extract payloads from DNS records
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and (ProcessCommandLine contains " -q=txt " or ProcessCommandLine contains " -querytype=txt ")) and ((FolderPath contains "\\nslookup.exe") or (ProcessVersionInfoOriginalFileName == "\\nslookup.exe")))
