// Title: Suspicious XOR Encoded PowerShell Command
// ID: bb780e0c-16cf-4383-8383-1e5471db6cf9
// Status: test
// Level: medium
// Author: Sami Ruohonen, Harish Segar, Tim Shelton, Teymur Kheirkhabarov, Vasiliy Burov, oscd.community, Nasreddine Bencherchali
// Date: 2018-09-05
// Tags: attack.execution, attack.stealth, attack.t1059.001, attack.t1140, attack.t1027
// Description: Detects presence of a potentially xor encoded powershell command
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "ForEach" or ProcessCommandLine contains "for(" or ProcessCommandLine contains "for " or ProcessCommandLine contains "-join " or ProcessCommandLine contains "-join'" or ProcessCommandLine contains "-join\"" or ProcessCommandLine contains "-join`" or ProcessCommandLine contains "::Join" or ProcessCommandLine contains "[char]")) and (ProcessCommandLine contains "bxor") and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll")) or (Description == "Windows PowerShell") or (Product == "PowerShell Core 6")))
