// Title: Suspicious Process Parents
// ID: cbec226f-63d9-4eca-9f52-dfb6652f24df
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-21
// Tags: attack.stealth, attack.t1036
// Description: Detects suspicious parent processes that should not have any children or should only have a single possible child program
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessFolderPath endswith "\\minesweeper.exe" or InitiatingProcessFolderPath endswith "\\winver.exe" or InitiatingProcessFolderPath endswith "\\bitsadmin.exe")) or (((InitiatingProcessFolderPath endswith "\\csrss.exe" or InitiatingProcessFolderPath endswith "\\certutil.exe" or InitiatingProcessFolderPath endswith "\\eventvwr.exe" or InitiatingProcessFolderPath endswith "\\calc.exe" or InitiatingProcessFolderPath endswith "\\notepad.exe")) and not((((isempty(FolderPath) or isnull(FolderPath))) or ((FolderPath endswith "\\WerFault.exe" or FolderPath endswith "\\wermgr.exe" or FolderPath endswith "\\conhost.exe" or FolderPath endswith "\\mmc.exe" or FolderPath endswith "\\win32calc.exe" or FolderPath endswith "\\notepad.exe"))))))
