// Title: WSL Kali-Linux Usage
// ID: 6f1a11aa-4b8a-4b7f-9e13-4d3e4ff0e0d4
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-10-10
// Tags: attack.stealth, attack.t1202
// Description: Detects the use of Kali Linux through Windows Subsystem for Linux
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((FolderPath contains ":\\Users\\" and FolderPath contains "\\AppData\\Local\\packages\\KaliLinux")) or ((FolderPath contains ":\\Users\\" and FolderPath contains "\\AppData\\Local\\Microsoft\\WindowsApps\\kali.exe"))) or (FolderPath contains ":\\Program Files\\WindowsApps\\KaliLinux." and FolderPath endswith "\\kali.exe")) or (((((FolderPath contains "\\kali.exe" or FolderPath contains "\\KaliLinux")) or ((ProcessCommandLine contains "Kali.exe" or ProcessCommandLine contains "Kali-linux" or ProcessCommandLine contains "kalilinux"))) and ((InitiatingProcessFolderPath endswith "\\wsl.exe" or InitiatingProcessFolderPath endswith "\\wslhost.exe"))) and not(((ProcessCommandLine contains " -i " or ProcessCommandLine contains " --install " or ProcessCommandLine contains " --unregister ")))))
