// Title: Suspicious Workstation Locking via Rundll32
// ID: 3b5b0213-0460-4e3f-8937-3abf98ff7dcc
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-06-04
// Tags: attack.stealth
// Description: Detects a suspicious call to the user32.dll function that locks the user workstation
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "user32.dll,") and ((FolderPath endswith "\\rundll32.exe") or (ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE")) and (InitiatingProcessFolderPath endswith "\\cmd.exe") and (ProcessCommandLine contains "LockWorkStation"))
