// Title: PUA - Advanced Port Scanner Execution
// ID: 54773c5f-f1cc-4703-9126-2f797d96a69d
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-18
// Tags: attack.discovery, attack.t1046, attack.t1135
// Description: Detects the use of Advanced Port Scanner.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "/portable" and ProcessCommandLine contains "/lng")) or ((FolderPath contains "\\advanced_port_scanner") or (ProcessVersionInfoOriginalFileName contains "advanced_port_scanner") or (Description contains "Advanced Port Scanner")))
