// Title: Recon Command Output Piped To Findstr.EXE
// ID: ccb5742c-c248-4982-8c5c-5571b9275ad3
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2023-07-06
// Tags: attack.discovery, attack.t1057
// Description: Detects the execution of a potential recon command where the results are piped to "findstr". This is meant to trigger on inline calls of "cmd.exe" via the "/c" or "/k" for example.
// Attackers often time use this technique to extract specific information they require in their reconnaissance phase.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "ipconfig*|*find" or ProcessCommandLine contains "net*|*find" or ProcessCommandLine contains "netstat*|*find" or ProcessCommandLine contains "ping*|*find" or ProcessCommandLine contains "systeminfo*|*find" or ProcessCommandLine contains "tasklist*|*find" or ProcessCommandLine contains "whoami*|*find")) and not(((ProcessCommandLine contains "cmd.exe /c TASKLIST /V |" and ProcessCommandLine contains "FIND /I" and ProcessCommandLine contains "\\xampp\\" and ProcessCommandLine contains "\\catalina_start.bat"))))
