// Title: Potential Perl Reverse Shell Execution
// ID: 259df6bc-003f-4306-9f54-4ff1a08fa38e
// Status: test
// Level: high
// Author: @d4ns4n_, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-07
// Tags: attack.execution
// Description: Detects execution of the perl binary with the "-e" flag and common strings related to potential reverse shell activity
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "fdopen(" and ProcessCommandLine contains "::Socket::INET")) or ((ProcessCommandLine contains "Socket" and ProcessCommandLine contains "connect" and ProcessCommandLine contains "open" and ProcessCommandLine contains "exec"))) and (FolderPath endswith "/perl" and ProcessCommandLine contains " -e "))
