// Title: UAC Bypass Using NTFS Reparse Point - Process
// ID: 39ed3c80-e6a1-431b-9df3-911ac53d08a7
// Status: test
// Level: high
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-30
// Tags: attack.privilege-escalation, attack.t1548.002
// Description: Detects the pattern of UAC Bypass using NTFS reparse point and wusa.exe DLL hijacking (UACMe 36)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine startswith "\"C:\\Windows\\system32\\wusa.exe\"  /quiet C:\\Users\\" and ProcessCommandLine endswith "\\AppData\\Local\\Temp\\update.msu" and (IntegrityLevel == "High" or IntegrityLevel == "System" or IntegrityLevel == "S-1-16-16384" or IntegrityLevel == "S-1-16-12288")) or (InitiatingProcessCommandLine == "\"C:\\Windows\\system32\\dism.exe\" /online /quiet /norestart /add-package /packagepath:\"C:\\Windows\\system32\\pe386\" /ignorecheck" and (IntegrityLevel == "High" or IntegrityLevel == "System") and (ProcessCommandLine contains "C:\\Users\\" and ProcessCommandLine contains "\\AppData\\Local\\Temp\\" and ProcessCommandLine contains "\\dismhost.exe {") and FolderPath endswith "\\DismHost.exe"))
