// Title: Firewall Rule Deleted Via Netsh.EXE
// ID: 1a5fefe6-734f-452e-a07d-fc1c35bce4b2
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-08-14
// Tags: attack.defense-impairment, attack.t1686.003
// Description: Detects the removal of a port or application rule in the Windows Firewall configuration using netsh
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "firewall" and ProcessCommandLine contains "delete ")) and ((FolderPath endswith "\\netsh.exe") or (ProcessVersionInfoOriginalFileName == "netsh.exe"))) and not(((InitiatingProcessFolderPath endswith "\\instup.exe" and ProcessCommandLine contains "advfirewall firewall delete rule name=\"Avast Antivirus Admin Client\"") or (InitiatingProcessFolderPath endswith "\\Dropbox.exe" and ProcessCommandLine contains "name=Dropbox"))))
