// Title: RDP Connection Allowed Via Netsh.EXE
// ID: 01aeb693-138d-49d2-9403-c4f52d7d3d62
// Status: test
// Level: high
// Author: Sander Wiebing
// Date: 2020-05-23
// Tags: attack.defense-impairment, attack.t1686.003
// Description: Detects usage of the netsh command to open and allow connections to port 3389 (RDP). As seen used by Sarwent Malware
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "firewall " and ProcessCommandLine contains "add " and ProcessCommandLine contains "tcp " and ProcessCommandLine contains "3389") and (ProcessCommandLine contains "portopening" or ProcessCommandLine contains "allow")) and ((FolderPath endswith "\\netsh.exe") or (ProcessVersionInfoOriginalFileName == "netsh.exe")))
