// Title: Shell32 DLL Execution in Suspicious Directory
// ID: 32b96012-7892-429e-b26c-ac2bf46066ff
// Status: test
// Level: high
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-11-24
// Tags: attack.execution, attack.stealth, attack.t1218.011
// Description: Detects shell32.dll executing a DLL in a suspicious directory
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "shell32.dll" and ProcessCommandLine contains "Control_RunDLL") and (ProcessCommandLine contains "%AppData%" or ProcessCommandLine contains "%LocalAppData%" or ProcessCommandLine contains "%Temp%" or ProcessCommandLine contains "%tmp%" or ProcessCommandLine contains "\\AppData\\" or ProcessCommandLine contains "\\Temp\\" or ProcessCommandLine contains "\\Users\\Public\\")) and ((FolderPath endswith "\\rundll32.exe") or (ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE")))
