// Title: Linux Package Uninstall
// ID: 95d61234-7f56-465c-6f2d-b562c6fedbc4
// Status: test
// Level: low
// Author: Tuan Le (NCSGroup), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-09
// Tags: attack.stealth, attack.t1070
// Description: Detects linux package removal using builtin tools such as "yum", "apt", "apt-get" or "dpkg".
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "/apt" or FolderPath endswith "/apt-get") and (ProcessCommandLine contains "remove" or ProcessCommandLine contains "purge")) or (FolderPath endswith "/dpkg" and (ProcessCommandLine contains "--remove " or ProcessCommandLine contains " -r ")) or (FolderPath endswith "/rpm" and ProcessCommandLine contains " -e ") or (FolderPath endswith "/yum" and (ProcessCommandLine contains "erase" or ProcessCommandLine contains "remove")))
