// Title: Suspicious Network Command
// ID: a29c1813-ab1f-4dde-b489-330b952e91ae
// Status: test
// Level: low
// Author: frack113, Christopher Peacock '@securepeacock', SCYTHE '@scythe_io'
// Date: 2021-12-07
// Tags: attack.discovery, attack.t1016
// Description: Adversaries may look for details about the network configuration and settings of systems they access or through information discovery of remote systems
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine matches regex @"ipconfig\\s+/all" or ProcessCommandLine matches regex @"netsh\\s+interface show interface" or ProcessCommandLine matches regex @"arp\\s+-a" or ProcessCommandLine matches regex @"nbtstat\\s+-n" or ProcessCommandLine matches regex @"net\\s+config" or ProcessCommandLine matches regex @"route\\s+print"))
