// Title: Suspicious Package Installed - Linux
// ID: 700fb7e8-2981-401c-8430-be58e189e741
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-03
// Tags: attack.defense-impairment, attack.t1553.004
// Description: Detects installation of suspicious packages using system installation utilities
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "/apt" or FolderPath endswith "/apt-get") and ProcessCommandLine contains "install") or (FolderPath endswith "/dpkg" and (ProcessCommandLine contains "--install" or ProcessCommandLine contains "-i")) or (FolderPath endswith "/rpm" and ProcessCommandLine contains "-i") or (FolderPath endswith "/yum" and (ProcessCommandLine contains "localinstall" or ProcessCommandLine contains "install"))) and ((ProcessCommandLine contains "nmap" or ProcessCommandLine contains " nc" or ProcessCommandLine contains "netcat" or ProcessCommandLine contains "wireshark" or ProcessCommandLine contains "tshark" or ProcessCommandLine contains "openconnect" or ProcessCommandLine contains "proxychains" or ProcessCommandLine contains "socat")))
