// Title: Shadow Copies Creation Using Operating Systems Utilities
// ID: b17ea6f7-6e90-447e-a799-e6c0a493d6ce
// Status: test
// Level: medium
// Author: Teymur Kheirkhabarov, Daniil Yugoslavskiy, oscd.community
// Date: 2019-10-22
// Tags: attack.credential-access, attack.t1003, attack.t1003.002, attack.t1003.003
// Description: Shadow Copies creation using operating systems utilities, possible credential access
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "shadow" and ProcessCommandLine contains "create")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\wmic.exe" or FolderPath endswith "\\vssadmin.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll" or ProcessVersionInfoOriginalFileName == "wmic.exe" or ProcessVersionInfoOriginalFileName == "VSSADMIN.EXE"))))
