// Title: Suspicious Powercfg Execution To Change Lock Screen Timeout
// ID: f8d6a15e-4bc8-4c27-8e5d-2b10f0b73e5b
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-11-18
// Tags: attack.stealth
// Description: Detects suspicious execution of 'Powercfg.exe' to change lock screen timeout
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\powercfg.exe") or (ProcessVersionInfoOriginalFileName == "PowerCfg.exe")) and (((ProcessCommandLine contains "/setacvalueindex " and ProcessCommandLine contains "SCHEME_CURRENT" and ProcessCommandLine contains "SUB_VIDEO" and ProcessCommandLine contains "VIDEOCONLOCK")) or ((ProcessCommandLine contains "-change " and ProcessCommandLine contains "-standby-timeout-"))))
