// Title: Linux Network Service Scanning Tools Execution
// ID: 3e102cd9-a70d-4a7a-9508-403963092f31
// Status: test
// Level: low
// Author: Alejandro Ortuno, oscd.community, Georg Lauenstein (sure[secure])
// Date: 2020-10-21
// Tags: attack.discovery, attack.t1046
// Description: Detects execution of network scanning and reconnaisance tools. These tools can be used for the enumeration of local or remote network services for example.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "/nc" or FolderPath endswith "/ncat" or FolderPath endswith "/netcat" or FolderPath endswith "/socat")) and not(((ProcessCommandLine contains " --listen " or ProcessCommandLine contains " -l ")))) or ((FolderPath endswith "/autorecon" or FolderPath endswith "/hping" or FolderPath endswith "/hping2" or FolderPath endswith "/hping3" or FolderPath endswith "/naabu" or FolderPath endswith "/nmap" or FolderPath endswith "/nping" or FolderPath endswith "/telnet" or FolderPath endswith "/zenmap")))
