// Title: Chmod Targeting Sensitive Directories
// ID: 6419afd1-3742-47a5-a7e6-b50386cd15f8
// Status: test
// Level: medium
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-03
// Tags: attack.defense-impairment, attack.t1222.002
// Description: Detects chmod targeting files in sensitive directory paths on Linux systems.
// Attackers may use chmod to change permissions of files in these directories to maintain persistence, escalate privileges, or disrupt system operations.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "/chmod" and (ProcessCommandLine contains "/tmp/" or ProcessCommandLine contains "/.Library/" or ProcessCommandLine contains "/etc/" or ProcessCommandLine contains "/opt/")) and not(((ProcessCommandLine startswith "chmod 700 /tmp/apt-key-gpghome.") or (ProcessCommandLine == "chmod 0775 /etc/landscape/") or (ProcessCommandLine startswith "chmod 755 /var/tmp/mkinitramfs") or (ProcessCommandLine contains "/etc/" and (InitiatingProcessCommandLine contains "/var/lib/dpkg/info/" and InitiatingProcessCommandLine contains ".postinst configure")) or (ProcessCommandLine == "chmod 644 /etc/apparmor.d/tunables/home.d/ubuntu") or (ProcessCommandLine contains "chmod --reference=/etc/shells" and InitiatingProcessCommandLine endswith "/update-shells"))))
