// Title: LSASS Process Reconnaissance Via Findstr.EXE
// ID: fe63010f-8823-4864-a96b-a7b4a0f7b929
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-12
// Tags: attack.credential-access, attack.t1552.006
// Description: Detects findstring commands that include the keyword lsass, which indicates recon actviity for the LSASS process PID
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "lsass") and (((FolderPath endswith "\\find.exe" or FolderPath endswith "\\findstr.exe")) or ((ProcessVersionInfoOriginalFileName == "FIND.EXE" or ProcessVersionInfoOriginalFileName == "FINDSTR.EXE")))) or ((ProcessCommandLine contains " /i \"lsass" or ProcessCommandLine contains " /i lsass.exe" or ProcessCommandLine contains "findstr \"lsass" or ProcessCommandLine contains "findstr lsass" or ProcessCommandLine contains "findstr.exe \"lsass" or ProcessCommandLine contains "findstr.exe lsass")))
