// Title: Vim GTFOBin Abuse - Linux
// ID: 7ab8f73a-fcff-428b-84aa-6a5ff7877dea
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), Luc Génaux
// Date: 2022-12-28
// Tags: attack.execution, attack.discovery, attack.t1059, attack.t1083
// Description: Detects the use of "vim" and it's siblings commands to execute a shell or proxy commands.
// Such behavior may be associated with privilege escalation, unauthorized command execution, or to break out from restricted environments.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ":!/" or ProcessCommandLine contains ":!$" or ProcessCommandLine contains ":!.." or ProcessCommandLine contains ":lua " or ProcessCommandLine contains ":py " or ProcessCommandLine contains ":shell" or ProcessCommandLine contains "/bin/bash" or ProcessCommandLine contains "/bin/dash" or ProcessCommandLine contains "/bin/fish" or ProcessCommandLine contains "/bin/sh" or ProcessCommandLine contains "/bin/csh" or ProcessCommandLine contains "/bin/ksh" or ProcessCommandLine contains "/bin/zsh" or ProcessCommandLine contains "/bin/tmux")) and ((FolderPath endswith "/rvim" or FolderPath endswith "/vi" or FolderPath endswith "/vim" or FolderPath endswith "/vimdiff") and (ProcessCommandLine contains " --cmd " or ProcessCommandLine contains " -c")))
