// Title: HackTool - SysmonEnte Execution
// ID: d29ada0f-af45-4f27-8f32-f7b77c3dbc4e
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-09-07
// Tags: attack.defense-impairment, attack.t1685.001
// Description: Detects the use of SysmonEnte, a tool to attack the integrity of Sysmon
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((TargetImage contains ":\\Windows\\Sysmon.exe" or TargetImage contains ":\\Windows\\Sysmon64.exe" or TargetImage contains ":\\Windows\\Sysmon64a.exe") and GrantedAccess == "0x1400") and not((((SourceImage contains ":\\Program Files (x86)\\" or SourceImage contains ":\\Program Files\\" or SourceImage contains ":\\Windows\\System32\\" or SourceImage contains ":\\Windows\\SysWOW64\\")) or (SourceImage contains ":\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" and SourceImage endswith "\\MsMpEng.exe")))) or (CallTrace == "Ente"))
