// Title: Screen Capture - macOS
// ID: 0877ed01-da46-4c49-8476-d49cdd80dfa7
// Status: test
// Level: low
// Author: remotephone, oscd.community
// Date: 2020-10-13
// Tags: attack.collection, attack.t1113
// Description: Detects attempts to use screencapture to collect macOS screenshots
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FolderPath == "/usr/sbin/screencapture")
