// Title: Suspicious WSL InstallLocation Registry Key Modification Via CommandLine
// ID: f9f62824-de4e-40ca-afe7-8358f76a876d
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-05-05
// Tags: attack.stealth, attack.defense-impairment, attack.persistence, attack.t1112, attack.t1218
// Description: Detects the use of reg.exe or PowerShell to modify the WSL InstallLocation registry key via command-line arguments.
// Legitimate modifications to this key are performed exclusively by the Windows Installer (msiexec.exe) during WSL package installation or update.
// Manual use of reg.exe or PowerShell to set this value strongly indicates an attempt to redirect WSL execution to a malicious binary.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " add " or ProcessCommandLine contains "New-ItemProperty" or ProcessCommandLine contains "Set-ItemProperty" or ProcessCommandLine contains "sp ")) and ((ProcessCommandLine contains "\\Lxss\\MSI" or ProcessCommandLine contains "/Lxss/MSI")) and (ProcessCommandLine contains "InstallLocation") and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\reg.exe")) or ((ProcessVersionInfoOriginalFileName == "powershell.exe" or ProcessVersionInfoOriginalFileName == "pwsh.dll" or ProcessVersionInfoOriginalFileName == "reg.exe"))))
