// Title: Imports Registry Key From a File
// ID: 73bba97f-a82d-42ce-b315-9182e76c57b1
// Status: test
// Level: medium
// Author: Oddvar Moe, Sander Wiebing, oscd.community
// Date: 2020-10-07
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects the import of the specified file to the registry with regedit.exe.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains " /i " or ProcessCommandLine contains " /s " or ProcessCommandLine contains ".reg")) and ((FolderPath endswith "\\regedit.exe") or (ProcessVersionInfoOriginalFileName == "REGEDIT.EXE"))) and not((((ProcessCommandLine contains " -e " or ProcessCommandLine contains " -a " or ProcessCommandLine contains " -c ")) and (ProcessCommandLine matches regex @":[^ \\\\]"))))
