// Title: Execute Code with Pester.bat
// ID: 59e938ff-0d6d-4dc3-b13f-36cc28734d4e
// Status: test
// Level: medium
// Author: Julia Fomina, oscd.community
// Date: 2020-10-08
// Tags: attack.execution, attack.stealth, attack.t1059.001, attack.t1216
// Description: Detects code execution via Pester.bat (Pester - Powershell Modulte for testing)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and (ProcessCommandLine contains "Pester" and ProcessCommandLine contains "Get-Help")) or ((FolderPath endswith "\\cmd.exe" and (ProcessCommandLine contains "pester" and ProcessCommandLine contains ";")) and ((ProcessCommandLine contains "help" or ProcessCommandLine contains "\\?"))))
