// Title: Potential Credential Dumping Via WER
// ID: 9a4ccd1a-3526-4d99-b980-9f9c5d3a6ff3
// Status: test
// Level: high
// Author: @pbssubhash , Nasreddine Bencherchali
// Date: 2022-12-08
// Tags: attack.credential-access, attack.t1003.001
// Description: Detects potential credential dumping via Windows Error Reporting LSASS Shtinkering technique which uses the Windows Error Reporting to dump lsass
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ParentUser contains "AUTHORI" or ParentUser contains "AUTORI") and (AccountName contains "AUTHORI" or AccountName contains "AUTORI") and (ProcessCommandLine contains " -u -p " and ProcessCommandLine contains " -ip " and ProcessCommandLine contains " -s ")) and ((FolderPath endswith "\\Werfault.exe") or (ProcessVersionInfoOriginalFileName == "WerFault.exe"))) and not((InitiatingProcessFolderPath == "C:\\Windows\\System32\\lsass.exe")))
