// Title: Potential Discovery Activity Using Find - MacOS
// ID: 85de3a19-b675-4a51-bfc6-b11a5186c971
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-28
// Tags: attack.discovery, attack.t1083
// Description: Detects usage of "find" binary in a suspicious manner to perform discovery
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (FolderPath endswith "/find" and (ProcessCommandLine contains "-perm -4000" or ProcessCommandLine contains "-perm -2000" or ProcessCommandLine contains "-perm 0777" or ProcessCommandLine contains "-perm -222" or ProcessCommandLine contains "-perm -o w" or ProcessCommandLine contains "-perm -o x" or ProcessCommandLine contains "-perm -u=s" or ProcessCommandLine contains "-perm -g=s"))
