// Title: Mstsc.EXE Execution With Local RDP File
// ID: 5fdce3ac-e7f9-4ecd-a3aa-a4d78ebbf0af
// Status: test
// Level: low
// Author: Nasreddine Bencherchali (Nextron Systems), Christopher Peacock @securepeacock
// Date: 2023-04-18
// Tags: attack.command-and-control, attack.t1219.002
// Description: Detects potential RDP connection via Mstsc using a local ".rdp" file
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine endswith ".rdp" or ProcessCommandLine endswith ".rdp\"")) and ((FolderPath endswith "\\mstsc.exe") or (ProcessVersionInfoOriginalFileName == "mstsc.exe"))) and not((InitiatingProcessFolderPath == "C:\\Windows\\System32\\lxss\\wslhost.exe" and ProcessCommandLine contains "C:\\ProgramData\\Microsoft\\WSL\\wslg.rdp")))
