// Title: ImagingDevices Unusual Parent/Child Processes
// ID: f11f2808-adb4-46c0-802a-8660db50fa99
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-27
// Tags: attack.execution, attack.stealth
// Description: Detects unusual parent or children of the ImagingDevices.exe (Windows Contacts) process as seen being used with Bumblebee activity
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\ImagingDevices.exe") or ((InitiatingProcessFolderPath endswith "\\WmiPrvSE.exe" or InitiatingProcessFolderPath endswith "\\svchost.exe" or InitiatingProcessFolderPath endswith "\\dllhost.exe") and FolderPath endswith "\\ImagingDevices.exe"))
