// Title: PUA - Restic Backup Tool Execution
// ID: 6ddff2e8-ea1a-45d0-8938-93dfc1d67ae7
// Status: experimental
// Level: high
// Author: Nounou Mbeiri, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-10-17
// Tags: attack.exfiltration, attack.t1048, attack.t1567.002
// Description: Detects the execution of the Restic backup tool, which can be used for data exfiltration.
// Threat actors may leverage Restic to back up and exfiltrate sensitive data to remote storage locations, including cloud services.
// If not legitimately used in the enterprise environment, its presence may indicate malicious activity.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "sftp:" or ProcessCommandLine contains "rest:http" or ProcessCommandLine contains "s3:s3." or ProcessCommandLine contains "s3.http" or ProcessCommandLine contains "azure:" or ProcessCommandLine contains " gs:" or ProcessCommandLine contains "rclone:" or ProcessCommandLine contains "swift:" or ProcessCommandLine contains " b2:") and (ProcessCommandLine contains " init " and ProcessCommandLine contains " -r ")) or (((ProcessCommandLine contains "--password-file" and ProcessCommandLine contains "init" and ProcessCommandLine contains " -r ")) or ((ProcessCommandLine contains "--use-fs-snapshot" and ProcessCommandLine contains "backup" and ProcessCommandLine contains " -r "))))
