// Title: PUA - Chisel Tunneling Tool Execution
// ID: 8b0e12da-d3c3-49db-bb4f-256703f380e5
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-09-13
// Tags: attack.command-and-control, attack.t1090.001
// Description: Detects usage of the Chisel tunneling tool via the commandline arguments
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\chisel.exe") or (((ProcessCommandLine contains "exe client " or ProcessCommandLine contains "exe server ")) and ((ProcessCommandLine contains "-socks5" or ProcessCommandLine contains "-reverse" or ProcessCommandLine contains " r:" or ProcessCommandLine contains ":127.0.0.1:" or ProcessCommandLine contains "-tls-skip-verify " or ProcessCommandLine contains ":socks"))))
