// Title: Cscript/Wscript Potentially Suspicious Child Process
// ID: b6676963-0353-4f88-90f5-36c20d443c6a
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Alejandro Houspanossian ('@lekz86')
// Date: 2023-05-15
// Tags: attack.execution
// Description: Detects potentially suspicious child processes of Wscript/Cscript. These include processes such as rundll32 with uncommon exports or PowerShell spawning rundll32 or regsvr32.
// Malware such as Pikabot and Qakbot were seen using similar techniques as well as many others.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessFolderPath endswith "\\wscript.exe" or InitiatingProcessFolderPath endswith "\\cscript.exe")) and ((FolderPath endswith "\\rundll32.exe") or (((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) and (((ProcessCommandLine contains "mshta" and ProcessCommandLine contains "http")) or ((ProcessCommandLine contains "rundll32" or ProcessCommandLine contains "regsvr32" or ProcessCommandLine contains "msiexec"))))) and not((FolderPath endswith "\\rundll32.exe" and (ProcessCommandLine contains "UpdatePerUserSystemParameters" or ProcessCommandLine contains "PrintUIEntry" or ProcessCommandLine contains "ClearMyTracksByProcess"))))
