// Title: Process Creation Using Sysnative Folder
// ID: 3c1b5fb0-c72f-45ba-abd1-4d4c353144ab
// Status: test
// Level: medium
// Author: Max Altgelt (Nextron Systems)
// Date: 2022-08-23
// Tags: attack.privilege-escalation, attack.stealth, attack.t1055
// Description: Detects process creation events that use the Sysnative folder (common for CobaltStrike spawns)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ":\\Windows\\Sysnative\\") or (FolderPath contains ":\\Windows\\Sysnative\\")) and not(((FolderPath contains "C:\\Windows\\Microsoft.NET\\Framework64\\v" or FolderPath contains "C:\\Windows\\Microsoft.NET\\Framework\\v" or FolderPath contains "C:\\Windows\\Microsoft.NET\\FrameworkArm\\v" or FolderPath contains "C:\\Windows\\Microsoft.NET\\FrameworkArm64\\v") and FolderPath endswith "\\ngen.exe" and ProcessCommandLine contains "install")) and not(((ProcessCommandLine contains "\"C:\\Windows\\sysnative\\cmd.exe\"" and ProcessCommandLine contains "\\xampp\\" and ProcessCommandLine contains "\\catalina_start.bat"))))
