// Title: Schtasks From Suspicious Folders
// ID: 8a8379b8-780b-4dbf-b1e9-31c8d112fefb
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-04-15
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1053.005
// Description: Detects scheduled task creations that have suspicious action command and folder combinations
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "C:\\ProgramData\\" or ProcessCommandLine contains "%ProgramData%")) and ((ProcessCommandLine contains "powershell" or ProcessCommandLine contains "pwsh" or ProcessCommandLine contains "cmd /c " or ProcessCommandLine contains "cmd /k " or ProcessCommandLine contains "cmd /r " or ProcessCommandLine contains "cmd.exe /c " or ProcessCommandLine contains "cmd.exe /k " or ProcessCommandLine contains "cmd.exe /r ")) and (ProcessCommandLine contains " /create ") and ((FolderPath endswith "\\schtasks.exe") or (ProcessVersionInfoOriginalFileName == "schtasks.exe")))
