// Title: New Port Forwarding Rule Added Via Netsh.EXE
// ID: 322ed9ec-fcab-4f67-9a34-e7c6aef43614
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), omkar72, oscd.community, Swachchhanda Shrawan Poudel
// Date: 2019-01-29
// Tags: attack.lateral-movement, attack.command-and-control, attack.t1090
// Description: Detects the execution of netsh commands that configure a new port forwarding (PortProxy) rule
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\netsh.exe") or (ProcessVersionInfoOriginalFileName == "netsh.exe")) and (((ProcessCommandLine contains "interface" and ProcessCommandLine contains "portproxy" and ProcessCommandLine contains "add" and ProcessCommandLine contains "v4tov4")) or ((ProcessCommandLine contains "i " and ProcessCommandLine contains "p " and ProcessCommandLine contains "a " and ProcessCommandLine contains "v ")) or ((ProcessCommandLine contains "connectp" and ProcessCommandLine contains "listena" and ProcessCommandLine contains "c="))))
