// Title: MMC Spawning Windows Shell
// ID: 05a2ab7e-ce11-4b63-86db-ab32e763e11d
// Status: test
// Level: high
// Author: Karneades, Swisscom CSIRT
// Date: 2019-08-05
// Tags: attack.lateral-movement, attack.t1021.003
// Description: Detects a Windows command line executable started from MMC
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\mmc.exe") and (((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\sh.exe" or FolderPath endswith "\\bash.exe" or FolderPath endswith "\\reg.exe" or FolderPath endswith "\\regsvr32.exe")) or (FolderPath contains "\\BITSADMIN")))
