// Title: Psexec Execution
// ID: 730fc21b-eaff-474b-ad23-90fd265d4988
// Status: test
// Level: medium
// Author: omkar72
// Date: 2020-10-30
// Tags: attack.execution, attack.lateral-movement, attack.t1569, attack.t1021
// Description: Detects user accept agreement execution in psexec commandline
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\psexec.exe") or (ProcessVersionInfoOriginalFileName == "psexec.c"))
