// Title: Suspicious Uninstall of Windows Defender Feature via PowerShell
// ID: c443012c-7928-43bf-ac20-7eda5efe61ad
// Status: experimental
// Level: high
// Author: yxinmiracle
// Date: 2025-08-22
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects the use of PowerShell with Uninstall-WindowsFeature or Remove-WindowsFeature cmdlets to disable or remove the Windows Defender GUI feature, a common technique used by adversaries to evade defenses.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "Windows-Defender") and ((ProcessCommandLine contains "Uninstall-WindowsFeature" or ProcessCommandLine contains "Remove-WindowsFeature")) and (((FolderPath endswith "\\powershell_ise.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell_ISE.EXE" or ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))))
