// Title: PowerShell Execution With Potential Decryption Capabilities
// ID: 434c08ba-8406-4d15-8b24-782cb071a691
// Status: test
// Level: high
// Author: X__Junior (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-30
// Tags: attack.execution
// Description: Detects PowerShell commands that decrypt an ".LNK" "file to drop the next stage of the malware.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Get-ChildItem " or ProcessCommandLine contains "dir " or ProcessCommandLine contains "gci " or ProcessCommandLine contains "ls ")) and ((ProcessCommandLine contains "Get-Content " or ProcessCommandLine contains "gc " or ProcessCommandLine contains "cat " or ProcessCommandLine contains "type " or ProcessCommandLine contains "ReadAllBytes")) and (((ProcessCommandLine contains " ^| " and ProcessCommandLine contains "\\*.lnk" and ProcessCommandLine contains "-Recurse" and ProcessCommandLine contains "-Skip ")) or ((ProcessCommandLine contains " -ExpandProperty " and ProcessCommandLine contains "\\*.lnk" and ProcessCommandLine contains "WriteAllBytes" and ProcessCommandLine contains " .length "))) and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and (ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll")))
