// Title: Suspicious Group And Account Reconnaissance Activity Using Net.EXE
// ID: d95de845-b83c-4a9a-8a6a-4fc802ebf6c0
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), omkar72, @svch0st, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-01-16
// Tags: attack.discovery, attack.t1087.001, attack.t1087.002
// Description: Detects suspicious reconnaissance command line activity on Windows systems using Net.EXE
// Check if the user that executed the commands is suspicious (e.g. service accounts, LOCAL_SYSTEM)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe")) or ((ProcessVersionInfoOriginalFileName == "net.exe" or ProcessVersionInfoOriginalFileName == "net1.exe"))) and (((((ProcessCommandLine contains "domain admins" or ProcessCommandLine contains " administrator" or ProcessCommandLine contains " administrateur" or ProcessCommandLine contains "enterprise admins" or ProcessCommandLine contains "Exchange Trusted Subsystem" or ProcessCommandLine contains "Remote Desktop Users" or ProcessCommandLine contains "Utilisateurs du Bureau à distance" or ProcessCommandLine contains "Usuarios de escritorio remoto" or ProcessCommandLine contains " /do")) and ((ProcessCommandLine contains " group " or ProcessCommandLine contains " localgroup "))) and not((ProcessCommandLine contains " /add"))) or ((ProcessCommandLine contains " /do") and (ProcessCommandLine contains " accounts "))))
