// Title: Potentially Suspicious Child Process Of WinRAR.EXE
// ID: 146aace8-9bd6-42ba-be7a-0070d8027b76
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-31
// Tags: attack.execution, attack.t1203
// Description: Detects potentially suspicious child processes of WinRAR.exe.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\wscript.exe")) or ((ProcessVersionInfoOriginalFileName == "Cmd.Exe" or ProcessVersionInfoOriginalFileName == "cscript.exe" or ProcessVersionInfoOriginalFileName == "mshta.exe" or ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll" or ProcessVersionInfoOriginalFileName == "regsvr32.exe" or ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE" or ProcessVersionInfoOriginalFileName == "wscript.exe"))) and (InitiatingProcessFolderPath endswith "\\WinRAR.exe"))
