// Title: Indirect Command Execution From Script File Via Bash.EXE
// ID: 2d22a514-e024-4428-9dba-41505bd63a5b
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-15
// Tags: attack.stealth, attack.t1202
// Description: Detects execution of Microsoft bash launcher without any flags to execute the content of a bash script directly.
// This can be used to potentially bypass defenses and execute Linux or Windows-based binaries directly via bash.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith ":\\Windows\\System32\\bash.exe" or FolderPath endswith ":\\Windows\\SysWOW64\\bash.exe")) or (ProcessVersionInfoOriginalFileName == "Bash.exe")) and not((((ProcessCommandLine contains "bash.exe -" or ProcessCommandLine contains "bash -")) or (ProcessCommandLine == "") or ((isempty(ProcessCommandLine) or isnull(ProcessCommandLine))) or ((ProcessCommandLine == "bash.exe" or ProcessCommandLine == "bash")))))
