// Title: Recon Information for Export with Command Prompt
// ID: aa2efee7-34dd-446e-8a37-40790a66efd7
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-07-30
// Tags: attack.collection, attack.t1119
// Description: Once established within a system or network, an adversary may use automated techniques for collecting internal data.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\tree.com" or FolderPath endswith "\\WMIC.exe" or FolderPath endswith "\\doskey.exe" or FolderPath endswith "\\sc.exe")) or ((ProcessVersionInfoOriginalFileName == "wmic.exe" or ProcessVersionInfoOriginalFileName == "DOSKEY.EXE" or ProcessVersionInfoOriginalFileName == "sc.exe"))) and ((InitiatingProcessCommandLine contains " > %TEMP%\\" or InitiatingProcessCommandLine contains " > %TMP%\\")))
