// Title: Sensitive File Dump Via Wbadmin.EXE
// ID: 8b93a509-1cb8-42e1-97aa-ee24224cdc15
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2024-05-10
// Tags: attack.credential-access, attack.t1003.003
// Description: Detects the dump of highly sensitive files such as "NTDS.DIT" and "SECURITY" hive.
// Attackers can leverage the "wbadmin" utility in order to dump sensitive files that might contain credential or sensitive information.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "start" or ProcessCommandLine contains "backup")) and ((FolderPath endswith "\\wbadmin.exe") or (ProcessVersionInfoOriginalFileName == "WBADMIN.EXE")) and ((ProcessCommandLine contains "\\config\\SAM" or ProcessCommandLine contains "\\config\\SECURITY" or ProcessCommandLine contains "\\config\\SYSTEM" or ProcessCommandLine contains "\\Windows\\NTDS\\NTDS.dit")))
