// Title: LSASS Dump Keyword In CommandLine
// ID: ffa6861c-4461-4f59-8a41-578c39f3f23e
// Status: test
// Level: high
// Author: E.M. Anhaus, Tony Lambert, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-10-24
// Tags: attack.credential-access, attack.t1003.001
// Description: Detects the presence of the keywords "lsass" and ".dmp" in the commandline, which could indicate a potential attempt to dump or create a dump of the lsass process.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "lsass.dmp" or ProcessCommandLine contains "lsass.zip" or ProcessCommandLine contains "lsass.rar" or ProcessCommandLine contains "Andrew.dmp" or ProcessCommandLine contains "Coredump.dmp" or ProcessCommandLine contains "NotLSASS.zip" or ProcessCommandLine contains "lsass_2" or ProcessCommandLine contains "lsassdump" or ProcessCommandLine contains "lsassdmp")) or ((ProcessCommandLine contains "lsass" and ProcessCommandLine contains ".dmp")) or ((ProcessCommandLine contains "SQLDmpr" and ProcessCommandLine contains ".mdmp")) or ((ProcessCommandLine contains "nanodump" and ProcessCommandLine contains ".dmp")))
