// Title: Suspicious Mstsc.EXE Execution With Local RDP File
// ID: 6e22722b-dfb1-4508-a911-49ac840b40f8
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-18
// Tags: attack.command-and-control, attack.t1219.002
// Description: Detects potential RDP connection via Mstsc using a local ".rdp" file located in suspicious locations.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine endswith ".rdp" or ProcessCommandLine endswith ".rdp\"")) and ((FolderPath endswith "\\mstsc.exe") or (ProcessVersionInfoOriginalFileName == "mstsc.exe")) and ((ProcessCommandLine contains ":\\Users\\Public\\" or ProcessCommandLine contains ":\\Windows\\System32\\spool\\drivers\\color" or ProcessCommandLine contains ":\\Windows\\System32\\Tasks_Migrated " or ProcessCommandLine contains ":\\Windows\\Tasks\\" or ProcessCommandLine contains ":\\Windows\\Temp\\" or ProcessCommandLine contains ":\\Windows\\Tracing\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Downloads\\")))
