// Title: Potential Ransomware or Unauthorized MBR Tampering Via Bcdedit.EXE
// ID: c9fbe8e9-119d-40a6-9b59-dd58a5d84429
// Status: test
// Level: medium
// Author: @neu5ron
// Date: 2019-02-07
// Tags: attack.stealth, attack.t1070, attack.persistence, attack.t1542.003
// Description: Detects potential malicious and unauthorized usage of bcdedit.exe
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "delete" or ProcessCommandLine contains "deletevalue" or ProcessCommandLine contains "import" or ProcessCommandLine contains "safeboot" or ProcessCommandLine contains "network")) and ((FolderPath endswith "\\bcdedit.exe") or (ProcessVersionInfoOriginalFileName == "bcdedit.exe")))
