// Title: Automated Collection Command Prompt
// ID: f576a613-2392-4067-9d1a-9345fb58d8d1
// Status: test
// Level: medium
// Author: frack113
// Date: 2021-07-28
// Tags: attack.collection, attack.t1119, attack.credential-access, attack.t1552.001
// Description: Once established within a system or network, an adversary may use automated techniques for collecting internal data.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ".doc" or ProcessCommandLine contains ".docx" or ProcessCommandLine contains ".xls" or ProcessCommandLine contains ".xlsx" or ProcessCommandLine contains ".ppt" or ProcessCommandLine contains ".pptx" or ProcessCommandLine contains ".rtf" or ProcessCommandLine contains ".pdf" or ProcessCommandLine contains ".txt")) and (((ProcessCommandLine contains "dir " and ProcessCommandLine contains " /b " and ProcessCommandLine contains " /s ")) or (ProcessVersionInfoOriginalFileName == "FINDSTR.EXE" and (ProcessCommandLine contains " /e " or ProcessCommandLine contains " /si "))))
