// Title: Potential Obfuscated Ordinal Call Via Rundll32
// ID: 43fa5350-db63-4b8f-9a01-789a427074e1
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2023-05-17
// Tags: attack.stealth, attack.t1027.010
// Description: Detects execution of "rundll32" with potential obfuscated ordinal calls
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "#+" or ProcessCommandLine contains "#-" or ProcessCommandLine contains "#0" or ProcessCommandLine contains "#655" or ProcessCommandLine contains "#656")) and ((FolderPath endswith "\\rundll32.exe") or (ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE") or (ProcessCommandLine contains "rundll32")))
