// Title: Potential Meterpreter/CobaltStrike Activity
// ID: 15619216-e993-4721-b590-4c520615a67d
// Status: test
// Level: high
// Author: Teymur Kheirkhabarov, Ecco, Florian Roth
// Date: 2019-10-26
// Tags: attack.privilege-escalation, attack.stealth, attack.t1134.001, attack.t1134.002
// Description: Detects the use of getsystem Meterpreter/Cobalt Strike command by detecting a specific service starting
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\services.exe") and (((ProcessCommandLine contains "/c" and ProcessCommandLine contains "echo" and ProcessCommandLine contains "\\pipe\\") and (ProcessCommandLine contains "cmd" or ProcessCommandLine contains "%COMSPEC%")) or ((ProcessCommandLine contains "rundll32" and ProcessCommandLine contains ".dll,a" and ProcessCommandLine contains "/p:"))) and not((ProcessCommandLine contains "MpCmdRun")))
