// Title: Potential Product Reconnaissance Via Wmic.EXE
// ID: 15434e33-5027-4914-88d5-3d4145ec25a9
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali
// Date: 2023-02-14
// Tags: attack.execution, attack.t1047
// Description: Detects the execution of WMIC in order to get a list of firewall and antivirus products
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Product") and ((FolderPath endswith "\\wmic.exe") or (ProcessVersionInfoOriginalFileName == "wmic.exe"))) and not((((ProcessCommandLine contains " uninstall" or ProcessCommandLine contains " install")) or (ProcessCommandLine contains "csproduct"))))
