// Title: PUA - Nimgrab Execution
// ID: 74a12f18-505c-4114-8d0b-8448dd5485c6
// Status: test
// Level: high
// Author: frack113
// Date: 2022-08-28
// Tags: attack.command-and-control, attack.t1105
// Description: Detects the usage of nimgrab, a tool bundled with the Nim programming framework and used for downloading files.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((SHA256 contains "MD5=2DD44C3C29D667F5C0EF5F9D7C7FFB8B" or SHA256 contains "SHA256=F266609E91985F0FE3E31C5E8FAEEEC4FFA5E0322D8B6F15FE69F4C5165B9559" or SHA256 contains "IMPHASH=C07FDDD21D123EA9B3A08EEF44AAAC45")) or (FolderPath endswith "\\nimgrab.exe"))
