// Title: LSA PPL Protection Setting Modification via CommandLine
// ID: 8c0eca51-0f88-4db2-9183-fdfb10c703f9
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2022-03-22
// Tags: attack.defense-impairment, attack.t1689
// Description: Detects modification of LSA PPL protection settings via CommandLine.
// It may indicate an attempt to disable protection and enable credential dumping tools to access LSASS process memory.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "ControlSet" and ProcessCommandLine contains "\\Control\\Lsa") and (ProcessCommandLine contains "Set-ItemProperty" or ProcessCommandLine contains "New-ItemProperty" or ProcessCommandLine contains " add ")) and (((FolderPath endswith "\\reg.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "reg.exe" or ProcessVersionInfoOriginalFileName == "powershell.exe" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))) and ((ProcessCommandLine contains "IsPplAutoEnabled" or ProcessCommandLine contains "RunAsPPL" or ProcessCommandLine contains "RunAsPPLBoot")))
