// Title: PowerShell AppLocker Policy Discovery Via Get-AppLockerPolicy
// ID: f14b1e99-5e53-4598-98dc-6f20ad7b35e0
// Status: experimental
// Level: low
// Author: Tom3306
// Date: 2026-08-19
// Tags: attack.discovery, attack.t1518.001
// Description: Detects AppLocker policy enumeration attempts via PowerShell using the Get-AppLockerPolicy cmdlet and an policy scope of either Effective, LDAP, or Local.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "Get-AppLockerPolicy") and ((ProcessCommandLine contains " -Effective" or ProcessCommandLine contains " -Ldap " or ProcessCommandLine contains " -Local")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))))
