// Title: Potential Script Proxy Execution Via CL_Mutexverifiers.ps1
// ID: 1e0e1a81-e79b-44bc-935b-ddb9c8006b3d
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), oscd.community, Natalia Shornikova, frack113
// Date: 2022-05-21
// Tags: attack.stealth, attack.t1216
// Description: Detects the use of the Microsoft signed script "CL_mutexverifiers" to proxy the execution of additional PowerShell script commands
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and FolderPath endswith "\\powershell.exe" and ProcessCommandLine contains " -nologo -windowstyle minimized -file ") and ((ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Windows\\Temp\\")))
