// Title: Potentially Suspicious Child Process Of DiskShadow.EXE
// ID: 9f546b25-5f12-4c8d-8532-5893dcb1e4b8
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-15
// Tags: attack.stealth, attack.t1218
// Description: Detects potentially suspicious child processes of "Diskshadow.exe". This could be an attempt to bypass parent/child relationship detection or application whitelisting rules.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (InitiatingProcessFolderPath endswith "\\diskshadow.exe" and (FolderPath endswith "\\certutil.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\wscript.exe"))
