// Title: Visual Studio Code Tunnel Execution
// ID: 90d6bd71-dffb-4989-8d86-a827fedd6624
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), citron_ninja
// Date: 2023-10-25
// Tags: attack.command-and-control, attack.t1071.001, attack.t1219
// Description: Detects Visual Studio Code tunnel execution. Attackers can abuse this functionality to establish a C2 channel
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((isempty(ProcessVersionInfoOriginalFileName) or isnull(ProcessVersionInfoOriginalFileName)) and ProcessCommandLine endswith ".exe tunnel") or (InitiatingProcessCommandLine endswith " tunnel" and FolderPath endswith "\\cmd.exe" and (ProcessCommandLine contains "/d /c " and ProcessCommandLine contains "\\servers\\Stable-" and ProcessCommandLine contains "code-server.cmd")) or ((ProcessCommandLine contains ".exe tunnel" and ProcessCommandLine contains "--accept-server-license-terms")))
