// Title: HackTool - SOAPHound Execution
// ID: e92a4287-e072-4a40-9739-370c106bb750
// Status: test
// Level: high
// Author: @kostastsale
// Date: 2024-01-26
// Tags: attack.discovery, attack.t1087
// Description: Detects the execution of SOAPHound, a .NET tool for collecting Active Directory data, using specific command-line arguments that may indicate an attempt to extract sensitive AD information.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " --buildcache " or ProcessCommandLine contains " --bhdump " or ProcessCommandLine contains " --certdump " or ProcessCommandLine contains " --dnsdump ")) and ((ProcessCommandLine contains " -c " or ProcessCommandLine contains " --cachefilename " or ProcessCommandLine contains " -o " or ProcessCommandLine contains " --outputdirectory")))
