// Title: Renamed Schtasks Execution
// ID: f91e51c9-f344-4b32-969b-0b6f6b8537d4
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-11-27
// Tags: attack.execution, attack.persistence, attack.privilege-escalation, attack.stealth, attack.t1036.003, attack.t1053.005
// Description: Detects the execution of renamed schtasks.exe binary, which is a legitimate Windows utility used for scheduling tasks.
// One of the very common persistence techniques is schedule malicious tasks using schtasks.exe.
// Since, it is heavily abused, it is also heavily monitored by security products. To evade detection, threat actors may rename the schtasks.exe binary to schedule their malicious tasks.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((ProcessCommandLine contains " /tn " or ProcessCommandLine contains " /tr " or ProcessCommandLine contains " /sc " or ProcessCommandLine contains " /st " or ProcessCommandLine contains " /ru " or ProcessCommandLine contains " /fo ")) and ((ProcessCommandLine contains " /create " or ProcessCommandLine contains " /delete " or ProcessCommandLine contains " /query " or ProcessCommandLine contains " /change " or ProcessCommandLine contains " /run " or ProcessCommandLine contains " /end "))) and not((ProcessCommandLine contains "schtasks")) and not(((ProcessCommandLine contains "openfiles" and ProcessCommandLine contains " /query " and ProcessCommandLine contains " /fo")))) or ((ProcessVersionInfoOriginalFileName == "schtasks.exe") and not((FolderPath endswith "\\schtasks.exe"))))
