// Title: Hidden User Creation
// ID: b22a5b36-2431-493a-8be1-0bae56c28ef3
// Status: test
// Level: medium
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-10
// Tags: attack.stealth, attack.t1564.002
// Description: Detects creation of a hidden user account on macOS (UserID < 500) or with IsHidden option
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "/dscl" and ProcessCommandLine contains "create") and (ProcessCommandLine contains "UniqueID" and ProcessCommandLine matches regex @"([0-9]|[1-9][0-9]|[1-4][0-9]{2})")) or ((FolderPath endswith "/dscl" and ProcessCommandLine contains "create") and ((ProcessCommandLine contains "IsHidden") and ((ProcessCommandLine contains "true" or ProcessCommandLine contains "yes" or ProcessCommandLine contains "1")))))
