// Title: Firewall Disabled via Netsh.EXE
// ID: 57c4bf16-227f-4394-8ec7-1b745ee061c3
// Status: test
// Level: medium
// Author: Fatih Sirin
// Date: 2019-11-01
// Tags: attack.defense-impairment, attack.t1686.003, attack.s0108
// Description: Detects netsh commands that turns off the Windows firewall
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\netsh.exe") or (ProcessVersionInfoOriginalFileName == "netsh.exe")) and (((ProcessCommandLine contains "firewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "opmode" and ProcessCommandLine contains "disable")) or ((ProcessCommandLine contains "advfirewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "state" and ProcessCommandLine contains "off"))))
