// Title: Invoke-Obfuscation Via Stdin
// ID: 9c14c9fa-1a63-4a64-8e57-d19280559490
// Status: test
// Level: high
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-12
// Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
// Description: Detects Obfuscated Powershell via Stdin in Scripts
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (ProcessCommandLine matches regex @"(?i)(?:set).*&&\\s?set.*(?:environment|invoke|\\$\\{?input).*&&.*\"")
