// Title: Service Reconnaissance Via Wmic.EXE
// ID: 76f55eaa-d27f-4213-9d45-7b0e4b60bbae
// Status: test
// Level: medium
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-14
// Tags: attack.execution, attack.t1047
// Description: An adversary might use WMI to check if a certain remote service is running on a remote device.
// When the test completes, a service information will be displayed on the screen if it exists.
// A common feedback message is that "No instance(s) Available" if the service queried is not running.
// A common error message is "Node - (provided IP or default) ERROR Description =The RPC server is unavailable" if the provided remote host is unreachable
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "service") and ((FolderPath endswith "\\WMIC.exe") or (ProcessVersionInfoOriginalFileName == "wmic.exe"))) and not((((ProcessCommandLine contains "stopservice" or ProcessCommandLine contains "startservice")) or ((ProcessCommandLine contains "Change" or ProcessCommandLine contains "Create" or ProcessCommandLine contains "Delete" or ProcessCommandLine contains "PauseService" or ProcessCommandLine contains "ResumeService" or ProcessCommandLine contains "SetSecurityDescriptor" or ProcessCommandLine contains "StartService" or ProcessCommandLine contains "StopService" or ProcessCommandLine contains "UserControlService")))))
