// Title: Suspicious DLL Loaded via CertOC.EXE
// ID: 84232095-ecca-4015-b0d7-7726507ee793
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-15
// Tags: attack.stealth, attack.t1218
// Description: Detects when a user installs certificates by using CertOC.exe to load the target DLL file.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains " -LoadDLL ") and ((FolderPath endswith "\\certoc.exe") or (ProcessVersionInfoOriginalFileName == "CertOC.exe")) and ((ProcessCommandLine contains "\\Appdata\\Local\\Temp\\" or ProcessCommandLine contains "\\Desktop\\" or ProcessCommandLine contains "\\Downloads\\" or ProcessCommandLine contains "\\Users\\Public\\" or ProcessCommandLine contains "C:\\Windows\\Tasks\\" or ProcessCommandLine contains "C:\\Windows\\Temp\\")))
