// Title: ETW Trace Evasion Activity
// ID: a238b5d0-ce2d-4414-a676-7a531b3d13d6
// Status: test
// Level: high
// Author: @neu5ron, Florian Roth (Nextron Systems), Jonhnathan Ribeiro, oscd.community
// Date: 2019-03-22
// Tags: attack.stealth, attack.defense-impairment, attack.t1070, attack.t1685, car.2016-04-002
// Description: Detects command line activity that tries to clear or disable any ETW trace log which could be a sign of logging evasion.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "cl" and ProcessCommandLine contains "/Trace")) or ((ProcessCommandLine contains "clear-log" and ProcessCommandLine contains "/Trace")) or ((ProcessCommandLine contains "sl" and ProcessCommandLine contains "/e:false")) or ((ProcessCommandLine contains "set-log" and ProcessCommandLine contains "/e:false")) or ((ProcessCommandLine contains "logman" and ProcessCommandLine contains "update" and ProcessCommandLine contains "trace" and ProcessCommandLine contains "--p" and ProcessCommandLine contains "-ets")) or (ProcessCommandLine contains "Remove-EtwTraceProvider") or ((ProcessCommandLine contains "Set-EtwTraceProvider" and ProcessCommandLine contains "0x11")))
