// Title: Stop Windows Service Via Net.EXE
// ID: 88872991-7445-4a22-90b2-a3adadb0e827
// Status: test
// Level: low
// Author: Jakob Weinzettl, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-05
// Tags: attack.impact, attack.t1489
// Description: Detects the stopping of a Windows service via the "net" utility.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains " stop ") and (((ProcessVersionInfoOriginalFileName == "net.exe" or ProcessVersionInfoOriginalFileName == "net1.exe")) or ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe"))))
