// Title: Potentially Suspicious GoogleUpdate Child Process
// ID: 84b1ecf9-6eff-4004-bafb-bae5c0e251b2
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Tags: attack.stealth
// Description: Detects potentially suspicious child processes of "GoogleUpdate.exe"
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\GoogleUpdate.exe") and not((((isempty(FolderPath) or isnull(FolderPath))) or ((FolderPath contains "\\Google") or ((FolderPath endswith "\\setup.exe" or FolderPath endswith "chrome_updater.exe" or FolderPath endswith "chrome_installer.exe"))))))
