// Title: Suspicious Persistence Via VMwareToolBoxCmd.EXE VM State Change Script
// ID: 236d8e89-ed95-4789-a982-36f4643738ba
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-14
// Tags: attack.execution, attack.persistence, attack.t1059
// Description: Detects execution of the "VMwareToolBoxCmd.exe" with the "script" and "set" flag to setup a specific script that's located in a potentially suspicious location to run for a specific VM state
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " script " and ProcessCommandLine contains " set ")) and ((FolderPath endswith "\\VMwareToolBoxCmd.exe") or (ProcessVersionInfoOriginalFileName == "toolbox-cmd.exe")) and ((ProcessCommandLine contains ":\\PerfLogs\\" or ProcessCommandLine contains ":\\Temp\\" or ProcessCommandLine contains ":\\Windows\\System32\\Tasks\\" or ProcessCommandLine contains ":\\Windows\\Tasks\\" or ProcessCommandLine contains ":\\Windows\\Temp\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp")))
