// Title: Suspicious PowerShell Encoded Command Patterns
// ID: b9d9cc83-380b-4ba3-8d8f-60c0e7e2930c
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-05-24
// Tags: attack.execution, attack.t1059.001
// Description: Detects PowerShell command line patterns in combincation with encoded commands that often appear in malware infection chains
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains " JAB" or ProcessCommandLine contains " SUVYI" or ProcessCommandLine contains " SQBFAFgA" or ProcessCommandLine contains " aWV4I" or ProcessCommandLine contains " IAB" or ProcessCommandLine contains " PAA" or ProcessCommandLine contains " aQBlAHgA")) and ((ProcessCommandLine contains " -e " or ProcessCommandLine contains " -en " or ProcessCommandLine contains " -enc " or ProcessCommandLine contains " -enco")) and (((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.Exe" or ProcessVersionInfoOriginalFileName == "pwsh.dll")))) and not(((InitiatingProcessFolderPath contains "C:\\Packages\\Plugins\\Microsoft.GuestConfiguration.ConfigurationforWindows\\" or InitiatingProcessFolderPath contains "\\gc_worker.exe"))))
