// Title: Execution via stordiag.exe
// ID: 961e0abb-1b1e-4c84-a453-aafe56ad0d34
// Status: test
// Level: high
// Author: Austin Songer (@austinsonger)
// Date: 2021-10-21
// Tags: attack.stealth, attack.t1218
// Description: Detects the use of stordiag.exe to execute schtasks.exe systeminfo.exe and fltmc.exe
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\stordiag.exe" and (FolderPath endswith "\\schtasks.exe" or FolderPath endswith "\\systeminfo.exe" or FolderPath endswith "\\fltmc.exe")) and not(((InitiatingProcessFolderPath startswith "c:\\windows\\system32\\" or InitiatingProcessFolderPath startswith "c:\\windows\\syswow64\\"))))
