// Title: HackTool - XORDump Execution
// ID: 66e563f9-1cbd-4a22-a957-d8b7c0f44372
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-28
// Tags: attack.stealth, attack.t1036, attack.t1003.001, attack.credential-access
// Description: Detects suspicious use of XORDump process memory dumping utility
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\xordump.exe") or ((ProcessCommandLine contains " -process lsass.exe " or ProcessCommandLine contains " -m comsvcs " or ProcessCommandLine contains " -m dbghelp " or ProcessCommandLine contains " -m dbgcore ")))
