// Title: Rundll32 Registered COM Objects
// ID: f1edd233-30b5-4823-9e6a-c4171b24d316
// Status: test
// Level: high
// Author: frack113
// Date: 2022-02-13
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.015
// Description: load malicious registered COM objects
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "-sta " or ProcessCommandLine contains "-localserver ") and (ProcessCommandLine contains "{" and ProcessCommandLine contains "}")) and ((FolderPath endswith "\\rundll32.exe") or (ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE")))
