// Title: Enable BPF Kprobes Tracing
// ID: 7692f583-bd30-4008-8615-75dab3f08a99
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-25
// Tags: attack.execution, attack.stealth
// Description: Detects common command used to enable bpf kprobes tracing
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "echo 1 >" and ProcessCommandLine contains "/sys/kernel/debug/tracing/events/kprobes/") and (ProcessCommandLine contains "/myprobe/enable" or ProcessCommandLine contains "/myretprobe/enable"))
