// Title: Forfiles.EXE Child Process Masquerading
// ID: f53714ec-5077-420e-ad20-907ff9bb2958
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), Anish Bogati
// Date: 2024-01-05
// Tags: attack.stealth, attack.t1036
// Description: Detects the execution of "forfiles" from a non-default location, in order to potentially spawn a custom "cmd.exe" from the current working directory.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessCommandLine endswith ".exe" or InitiatingProcessCommandLine endswith ".exe\"") and FolderPath endswith "\\cmd.exe" and ProcessCommandLine startswith "/c echo \"") and not(((InitiatingProcessFolderPath contains ":\\Windows\\System32\\" or InitiatingProcessFolderPath contains ":\\Windows\\SysWOW64\\") and InitiatingProcessFolderPath endswith "\\forfiles.exe" and (FolderPath contains ":\\Windows\\System32\\" or FolderPath contains ":\\Windows\\SysWOW64\\") and FolderPath endswith "\\cmd.exe")))
