// Title: Remote Access Tool - Anydesk Execution From Suspicious Folder
// ID: 065b00ca-5d5c-4557-ac95-64a6d0b64d86
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-05-20
// Tags: attack.command-and-control, attack.t1219.002
// Description: An adversary may use legitimate desktop support and remote access software, such as Team Viewer, Go2Assist, LogMein, AmmyyAdmin, etc, to establish an interactive command and control channel to target systems within networks.
// These services are commonly used as legitimate technical support software, and may be allowed by application control within a target environment.
// Remote access tools like VNC, Ammyy, and Teamviewer are used frequently when compared with other legitimate software commonly used by adversaries. (Citation: Symantec Living off the Land)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\AnyDesk.exe" or FolderPath endswith "\\AnyDeskMSI.exe")) or (Description == "AnyDesk") or (Product == "AnyDesk") or (Company == "AnyDesk Software GmbH")) and not(((FolderPath contains "\\AppData\\" or FolderPath contains "Program Files (x86)\\AnyDesk" or FolderPath contains "Program Files\\AnyDesk"))))
