// Title: Renamed Microsoft Teams Execution
// ID: 88f46b67-14d4-4f45-ac2c-d66984f22191
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-07-12
// Tags: attack.stealth
// Description: Detects the execution of a renamed Microsoft Teams binary.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessVersionInfoOriginalFileName == "msteams.exe" or ProcessVersionInfoOriginalFileName == "teams.exe")) and not(((FolderPath endswith "\\msteams.exe" or FolderPath endswith "\\teams.exe"))))
