// Title: Non-privileged Usage of Reg or Powershell
// ID: 8f02c935-effe-45b3-8fc9-ef8696a9e41d
// Status: test
// Level: high
// Author: Teymur Kheirkhabarov (idea), Ryan Plas (rule), oscd.community
// Date: 2020-10-05
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Search for usage of reg or Powershell by non-privileged users to modify service configuration in registry
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "reg " and ProcessCommandLine contains "add")) or ((ProcessCommandLine contains "powershell" or ProcessCommandLine contains "set-itemproperty" or ProcessCommandLine contains " sp " or ProcessCommandLine contains "new-itemproperty"))) and ((IntegrityLevel == "Medium" or IntegrityLevel == "S-1-16-8192") and (ProcessCommandLine contains "ControlSet" and ProcessCommandLine contains "Services") and (ProcessCommandLine contains "ImagePath" or ProcessCommandLine contains "FailureCommand" or ProcessCommandLine contains "ServiceDLL")))
