// Title: Potential Suspicious Browser Launch From Document Reader Process
// ID: 1193d960-2369-499f-a158-7b50a31df682
// Status: test
// Level: medium
// Author: Joseph Kamau
// Date: 2024-05-27
// Tags: attack.execution, attack.t1204.002
// Description: Detects when a browser process or browser tab is launched from an application that handles document files such as Adobe, Microsoft Office, etc. And connects to a web application over http(s), this could indicate a possible phishing attempt.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessFolderPath contains "Acrobat Reader" or InitiatingProcessFolderPath contains "Microsoft Office" or InitiatingProcessFolderPath contains "PDF Reader") and (FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\firefox.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\maxthon.exe" or FolderPath endswith "\\seamonkey.exe" or FolderPath endswith "\\vivaldi.exe") and ProcessCommandLine contains "http") and not((ProcessCommandLine contains "https://go.microsoft.com/fwlink/")) and not(((ProcessCommandLine contains "http://ad.foxitsoftware.com/adlog.php?" or ProcessCommandLine contains "https://globe-map.foxitservice.com/go.php?do=redirect"))))
