// Title: HackTool - Quarks PwDump Execution
// ID: 0685b176-c816-4837-8e7b-1216f346636b
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-05
// Tags: attack.credential-access, attack.t1003.002
// Description: Detects usage of the Quarks PwDump tool via commandline arguments
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine == " -dhl" or ProcessCommandLine == " --dump-hash-local" or ProcessCommandLine == " -dhdc" or ProcessCommandLine == " --dump-hash-domain-cached" or ProcessCommandLine == " --dump-bitlocker" or ProcessCommandLine == " -dhd " or ProcessCommandLine == " --dump-hash-domain " or ProcessCommandLine == "--ntds-file")) or (FolderPath endswith "\\QuarksPwDump.exe"))
