// Title: Suspicious ArcSOC.exe Child Process
// ID: 8e95e73e-ba02-4a87-b4d7-0929b8053038
// Status: experimental
// Level: high
// Author: Micah Babinski
// Date: 2025-11-25
// Tags: attack.execution, attack.t1059, attack.t1203
// Description: Detects script interpreters, command-line tools, and similar suspicious child processes of ArcSOC.exe.
// ArcSOC.exe is the process name which hosts ArcGIS Server REST services. If an attacker compromises an ArcGIS
// Server system and uploads a malicious Server Object Extension (SOE), they can send crafted requests to the corresponding
// service endpoint and remotely execute code from the ArcSOC.exe process.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\ArcSOC.exe" and (FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\wmic.exe" or FolderPath endswith "\\wscript.exe")) and not((FolderPath endswith "\\cmd.exe" and ProcessCommandLine == "cmd.exe /c \"ver\"")))
