// Title: Suspicious Child Process Of Wermgr.EXE
// ID: 396f6630-f3ac-44e3-bfc8-1b161bc00c4e
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-10-14
// Tags: attack.privilege-escalation, attack.stealth, attack.t1055, attack.t1036
// Description: Detects suspicious Windows Error Reporting manager (wermgr.exe) child process
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\wermgr.exe" and (FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\ipconfig.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe" or FolderPath endswith "\\netstat.exe" or FolderPath endswith "\\nslookup.exe" or FolderPath endswith "\\powershell_ise.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\systeminfo.exe" or FolderPath endswith "\\whoami.exe" or FolderPath endswith "\\wscript.exe")) and not((FolderPath endswith "\\rundll32.exe" and (ProcessCommandLine contains "C:\\Windows\\system32\\WerConCpl.dll" and ProcessCommandLine contains "LaunchErcApp ") and (ProcessCommandLine contains "-queuereporting" or ProcessCommandLine contains "-responsepester"))))
