// Title: Arbitrary Binary Execution Using GUP Utility
// ID: d65aee4d-2292-4cea-b832-83accd6cfa43
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-10
// Tags: attack.execution
// Description: Detects execution of the Notepad++ updater (gup) to launch other commands or executables
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\gup.exe" and FolderPath endswith "\\explorer.exe") and not(((FolderPath endswith "\\explorer.exe" and ProcessCommandLine contains "\\Notepad++\\notepad++.exe") or ((isempty(ProcessCommandLine) or isnull(ProcessCommandLine))) or (InitiatingProcessFolderPath contains "\\Notepad++\\updater\\"))))
