// Title: SQLite Firefox Profile Data DB Access
// ID: 4833155a-4053-4c9c-a997-777fcea0baa7
// Status: test
// Level: high
// Author: frack113
// Date: 2022-04-08
// Tags: attack.credential-access, attack.t1539, attack.collection, attack.t1005
// Description: Detect usage of the "sqlite" binary to query databases in Firefox and other Gecko-based browsers for potential data stealing.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "cookies.sqlite" or ProcessCommandLine contains "places.sqlite")) and ((Product == "SQLite") or ((FolderPath endswith "\\sqlite.exe" or FolderPath endswith "\\sqlite3.exe"))))
