// Title: Netsh Allow Group Policy on Microsoft Defender Firewall
// ID: 347906f3-e207-4d18-ae5b-a9403d6bcdef
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-01-09
// Tags: attack.defense-impairment, attack.t1686.003
// Description: Adversaries may modify system firewalls in order to bypass controls limiting network usage
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "advfirewall" and ProcessCommandLine contains "firewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "rule" and ProcessCommandLine contains "group=" and ProcessCommandLine contains "new" and ProcessCommandLine contains "enable=Yes")) and ((FolderPath endswith "\\netsh.exe") or (ProcessVersionInfoOriginalFileName == "netsh.exe")))
