// Title: Renamed AutoHotkey.EXE Execution
// ID: 0f16d9cf-0616-45c8-8fad-becc11b5a41c
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali
// Date: 2023-02-07
// Tags: attack.stealth
// Description: Detects execution of a renamed autohotkey.exe binary based on PE metadata fields
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((Product contains "AutoHotkey") or (Description contains "AutoHotkey") or ((ProcessVersionInfoOriginalFileName == "AutoHotkey.exe" or ProcessVersionInfoOriginalFileName == "AutoHotkey.rc"))) and not((((FolderPath endswith "\\AutoHotkey.exe" or FolderPath endswith "\\AutoHotkey32.exe" or FolderPath endswith "\\AutoHotkey32_UIA.exe" or FolderPath endswith "\\AutoHotkey64.exe" or FolderPath endswith "\\AutoHotkey64_UIA.exe" or FolderPath endswith "\\AutoHotkeyA32.exe" or FolderPath endswith "\\AutoHotkeyA32_UIA.exe" or FolderPath endswith "\\AutoHotkeyU32.exe" or FolderPath endswith "\\AutoHotkeyU32_UIA.exe" or FolderPath endswith "\\AutoHotkeyU64.exe" or FolderPath endswith "\\AutoHotkeyU64_UIA.exe")) or (FolderPath contains "\\AutoHotkey"))))
