// Title: Suspicious RunAs-Like Flag Combination
// ID: 50d66fb0-03f8-4da0-8add-84e77d12a020
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2022-11-11
// Tags: attack.privilege-escalation
// Description: Detects suspicious command line flags that let the user set a target user and command as e.g. seen in PsExec-like tools
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " -c cmd" or ProcessCommandLine contains " -c \"cmd" or ProcessCommandLine contains " -c powershell" or ProcessCommandLine contains " -c \"powershell" or ProcessCommandLine contains " --command cmd" or ProcessCommandLine contains " --command powershell" or ProcessCommandLine contains " -c whoami" or ProcessCommandLine contains " -c wscript" or ProcessCommandLine contains " -c cscript")) and ((ProcessCommandLine contains " -u system " or ProcessCommandLine contains " --user system " or ProcessCommandLine contains " -u NT" or ProcessCommandLine contains " -u \"NT" or ProcessCommandLine contains " -u 'NT" or ProcessCommandLine contains " --system " or ProcessCommandLine contains " -u administrator ")))
