// Title: Suspicious Child Process Created as System
// ID: 590a5f4c-6c8c-4f10-8307-89afe9453a9d
// Status: test
// Level: high
// Author: Teymur Kheirkhabarov, Roberto Rodriguez (@Cyb3rWard0g), Open Threat Research (OTR)
// Date: 2019-10-26
// Tags: attack.privilege-escalation, attack.stealth, attack.t1134.002
// Description: Detection of child processes spawned with SYSTEM privileges by parents with LOCAL SERVICE or NETWORK SERVICE accounts
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ParentUser contains "AUTHORI" or ParentUser contains "AUTORI") and (ParentUser endswith "\\NETWORK SERVICE" or ParentUser endswith "\\LOCAL SERVICE") and (AccountName contains "AUTHORI" or AccountName contains "AUTORI") and (AccountName endswith "\\SYSTEM" or AccountName endswith "\\Système" or AccountName endswith "\\СИСТЕМА") and (IntegrityLevel == "System" or IntegrityLevel == "S-1-16-16384")) and not((FolderPath endswith "\\rundll32.exe" and ProcessCommandLine contains "DavSetCookie")))
