// Title: Uncommon One Time Only Scheduled Task At 00:00
// ID: 970823b7-273b-460a-8afc-3a6811998529
// Status: test
// Level: high
// Author: pH-T (Nextron Systems)
// Date: 2022-07-15
// Tags: attack.execution, attack.persistence, attack.privilege-escalation, attack.t1053.005
// Description: Detects scheduled task creation events that include suspicious actions, and is run once at 00:00
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "wscript" or ProcessCommandLine contains "vbscript" or ProcessCommandLine contains "cscript" or ProcessCommandLine contains "wmic " or ProcessCommandLine contains "wmic.exe" or ProcessCommandLine contains "regsvr32.exe" or ProcessCommandLine contains "powershell" or ProcessCommandLine contains "\\AppData\\")) and ((FolderPath contains "\\schtasks.exe") or (ProcessVersionInfoOriginalFileName == "schtasks.exe")) and ((ProcessCommandLine contains "once" and ProcessCommandLine contains "00:00")))
