// Title: Suspicious Binary In User Directory Spawned From Office Application
// ID: aa3a6f94-890e-4e22-b634-ffdfd54792cc
// Status: test
// Level: high
// Author: Jason Lynch
// Date: 2019-04-02
// Tags: attack.execution, attack.t1204.002, attack.g0046, car.2013-05-002
// Description: Detects an executable in the users directory started from one of the Microsoft Office suite applications (Word, Excel, PowerPoint, Publisher, Visio)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessFolderPath endswith "\\WINWORD.EXE" or InitiatingProcessFolderPath endswith "\\EXCEL.EXE" or InitiatingProcessFolderPath endswith "\\POWERPNT.exe" or InitiatingProcessFolderPath endswith "\\MSPUB.exe" or InitiatingProcessFolderPath endswith "\\VISIO.exe" or InitiatingProcessFolderPath endswith "\\MSACCESS.exe" or InitiatingProcessFolderPath endswith "\\EQNEDT32.exe") and FolderPath startswith "C:\\users\\" and FolderPath endswith ".exe") and not((FolderPath endswith "\\Teams.exe")))
