// Title: SQLite Chromium Profile Data DB Access
// ID: 24c77512-782b-448a-8950-eddb0785fc71
// Status: test
// Level: high
// Author: TropChaud
// Date: 2022-12-19
// Tags: attack.credential-access, attack.t1539, attack.t1555.003, attack.collection, attack.t1005
// Description: Detect usage of the "sqlite" binary to query databases in Chromium-based browsers for potential data stealing.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "\\User Data\\" or ProcessCommandLine contains "\\Opera Software\\" or ProcessCommandLine contains "\\ChromiumViewer\\")) and ((ProcessCommandLine contains "Login Data" or ProcessCommandLine contains "Cookies" or ProcessCommandLine contains "Web Data" or ProcessCommandLine contains "History" or ProcessCommandLine contains "Bookmarks")) and ((Product == "SQLite") or ((FolderPath endswith "\\sqlite.exe" or FolderPath endswith "\\sqlite3.exe"))))
