// Title: PUA - Wsudo Suspicious Execution
// ID: bdeeabc9-ff2a-4a51-be59-bb253aac7891
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-02
// Tags: attack.execution, attack.privilege-escalation, attack.t1059
// Description: Detects usage of wsudo (Windows Sudo Utility). Which is a tool that let the user execute programs with different permissions (System, Trusted Installer, Administrator...etc)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "-u System" or ProcessCommandLine contains "-uSystem" or ProcessCommandLine contains "-u TrustedInstaller" or ProcessCommandLine contains "-uTrustedInstaller" or ProcessCommandLine contains " --ti ")) or ((FolderPath endswith "\\wsudo.exe") or (ProcessVersionInfoOriginalFileName == "wsudo.exe") or (Description == "Windows sudo utility") or (InitiatingProcessFolderPath endswith "\\wsudo-bridge.exe")))
