// Title: Suspicious Userinit Child Process
// ID: b655a06a-31c0-477a-95c2-3726b83d649d
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), Samir Bousseaden (idea)
// Date: 2019-06-17
// Tags: attack.privilege-escalation, attack.stealth, attack.t1055
// Description: Detects a suspicious child process of userinit
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\userinit.exe") and not((((FolderPath endswith "\\explorer.exe") or (ProcessVersionInfoOriginalFileName == "explorer.exe") or (ProcessCommandLine == "C:\\Windows\\Explorer.EXE")) or (ProcessCommandLine contains "\\netlogon\\") or ((isempty(FolderPath) or isnull(FolderPath))))))
