// Title: Potential CommandLine Path Traversal Via Cmd.EXE
// ID: 087790e3-3287-436c-bccf-cbd0184a7db1
// Status: test
// Level: high
// Author: xknow @xknow_infosec, Tim Shelton
// Date: 2020-06-11
// Tags: attack.execution, attack.t1059.003
// Description: Detects potential path traversal attempt via cmd.exe. Could indicate possible command/argument confusion/hijacking
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((InitiatingProcessCommandLine contains "/c" or InitiatingProcessCommandLine contains "/k" or InitiatingProcessCommandLine contains "/r")) or ((ProcessCommandLine contains "/c" or ProcessCommandLine contains "/k" or ProcessCommandLine contains "/r"))) and ((InitiatingProcessFolderPath endswith "\\cmd.exe") or (FolderPath endswith "\\cmd.exe") or (ProcessVersionInfoOriginalFileName == "cmd.exe")) and ((InitiatingProcessCommandLine == "/../../") or (ProcessCommandLine contains "/../../"))) and not((ProcessCommandLine contains "\\Tasktop\\keycloak\\bin\\/../../jre\\bin\\java")))
