// Title: Potential Arbitrary Command Execution Using Msdt.EXE
// ID: 258fc8ce-8352-443a-9120-8a11e4857fa5
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-05-29
// Tags: attack.stealth, attack.t1202
// Description: Detects processes leveraging the "ms-msdt" handler or the "msdt.exe" binary to execute arbitrary commands as seen in the follina (CVE-2022-30190) vulnerability
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\msdt.exe") or (ProcessVersionInfoOriginalFileName == "msdt.exe")) and ((ProcessCommandLine contains "IT_BrowseForFile=") or ((ProcessCommandLine contains " PCWDiagnostic") and (ProcessCommandLine contains " -af "))))
