// Title: Password Set to Never Expire via WMI
// ID: 7864a175-3654-4824-9f0d-f0da18ab27c0
// Status: experimental
// Level: medium
// Author: Daniel Koifman (KoifSec)
// Date: 2025-07-30
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1047, attack.t1098
// Description: Detects the use of wmic.exe to modify user account settings and explicitly disable password expiration.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "useraccount" and ProcessCommandLine contains " set " and ProcessCommandLine contains "passwordexpires" and ProcessCommandLine contains "false")) and ((FolderPath endswith "\\wmic.exe") or (ProcessVersionInfoOriginalFileName == "wmic.exe")))
