// Title: PUA - NPS Tunneling Tool Execution
// ID: 68d37776-61db-42f5-bf54-27e87072d17e
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-10-08
// Tags: attack.command-and-control, attack.t1090
// Description: Detects the use of NPS, a port forwarding and intranet penetration proxy server
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " -server=" and ProcessCommandLine contains " -vkey=" and ProcessCommandLine contains " -password=")) or (ProcessCommandLine contains " -config=npc") or ((SHA256 contains "MD5=AE8ACF66BFE3A44148964048B826D005" or SHA256 contains "SHA1=CEA49E9B9B67F3A13AD0BE1C2655293EA3C18181" or SHA256 contains "SHA256=5A456283392FFCEEEACA3D3426C306EB470304637520D72FED1CC1FEBBBD6856")) or (FolderPath endswith "\\npc.exe"))
