// Title: Inline Python Execution - Spawn Shell Via OS System Library
// ID: 2d2f44ff-4611-4778-a8fc-323a0e9850cc
// Status: test
// Level: high
// Author: Li Ling, Andy Parkidomo, Robert Rakowski, Blake Hartstein (Bloomberg L.P.)
// Date: 2024-09-02
// Tags: attack.execution, attack.t1059
// Description: Detects execution of inline Python code via the "-c" in order to call the "system" function from the "os" library, and spawn a shell.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " -c " and ProcessCommandLine contains "os.system(") and (ProcessCommandLine contains "/bin/bash" or ProcessCommandLine contains "/bin/dash" or ProcessCommandLine contains "/bin/fish" or ProcessCommandLine contains "/bin/sh" or ProcessCommandLine contains "/bin/zsh")) and (((FolderPath endswith "/python" or FolderPath endswith "/python2" or FolderPath endswith "/python3")) or ((FolderPath contains "/python2." or FolderPath contains "/python3."))))
