// Title: Abused Debug Privilege by Arbitrary Parent Processes
// ID: d522eca2-2973-4391-a3e0-ef0374321dae
// Status: test
// Level: high
// Author: Semanur Guneysu @semanurtg, oscd.community
// Date: 2020-10-28
// Tags: attack.privilege-escalation, attack.t1548
// Description: Detection of unusual child processes by different system processes
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\cmd.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll" or ProcessVersionInfoOriginalFileName == "Cmd.Exe"))) and ((InitiatingProcessFolderPath endswith "\\winlogon.exe" or InitiatingProcessFolderPath endswith "\\services.exe" or InitiatingProcessFolderPath endswith "\\lsass.exe" or InitiatingProcessFolderPath endswith "\\csrss.exe" or InitiatingProcessFolderPath endswith "\\smss.exe" or InitiatingProcessFolderPath endswith "\\wininit.exe" or InitiatingProcessFolderPath endswith "\\spoolsv.exe" or InitiatingProcessFolderPath endswith "\\searchindexer.exe") and (AccountName contains "AUTHORI" or AccountName contains "AUTORI"))) and not(((ProcessCommandLine contains " route " and ProcessCommandLine contains " ADD "))))
