// Title: Terminal Service Process Spawn
// ID: 1012f107-b8f1-4271-af30-5aed2de89b39
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2019-05-22
// Tags: attack.initial-access, attack.t1190, attack.lateral-movement, attack.t1210, car.2013-07-002
// Description: Detects a process spawned by the terminal service server process (this could be an indicator for an exploitation of CVE-2019-0708)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessCommandLine contains "\\svchost.exe" and InitiatingProcessCommandLine contains "termsvcs")) and not((((FolderPath endswith "\\rdpclip.exe" or FolderPath endswith ":\\Windows\\System32\\csrss.exe" or FolderPath endswith ":\\Windows\\System32\\wininit.exe" or FolderPath endswith ":\\Windows\\System32\\winlogon.exe")) or ((isempty(FolderPath) or isnull(FolderPath))))))
