// Title: System Information Discovery via Registry Queries
// ID: 0022869c-49f7-4ff2-ba03-85ac42ddac58
// Status: experimental
// Level: low
// Author: lazarg
// Date: 2025-06-12
// Tags: attack.discovery, attack.t1082
// Description: Detects attempts to query system information directly from the Windows Registry.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and (ProcessCommandLine contains "Get-ItemPropertyValue" or ProcessCommandLine contains "gpv")) or (FolderPath endswith "\\reg.exe" and ProcessCommandLine contains "query" and (ProcessCommandLine contains "-v" or ProcessCommandLine contains "/v"))) and ((ProcessCommandLine contains "\\SOFTWARE\\Microsoft\\Windows Defender" or ProcessCommandLine contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion" or ProcessCommandLine contains "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall" or ProcessCommandLine contains "\\SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation" or ProcessCommandLine contains "\\SYSTEM\\CurrentControlSet\\Services")))
