// Title: Potentially Over Permissive Permissions Granted Using Dsacls.EXE
// ID: 01c42d3c-242d-4655-85b2-34f1739632f7
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-20
// Tags: attack.stealth, attack.t1218
// Description: Detects usage of Dsacls to grant over permissive permissions
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains " /G ") and ((FolderPath endswith "\\dsacls.exe") or (ProcessVersionInfoOriginalFileName == "DSACLS.EXE")) and ((ProcessCommandLine contains "GR" or ProcessCommandLine contains "GE" or ProcessCommandLine contains "GW" or ProcessCommandLine contains "GA" or ProcessCommandLine contains "WP" or ProcessCommandLine contains "WD")))
