// Title: Suspicious Schtasks Execution AppData Folder
// ID: c5c00f49-b3f9-45a6-997e-cfdecc6e1967
// Status: test
// Level: high
// Author: pH-T (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-03-15
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053.005, attack.t1059.001
// Description: Detects the creation of a schtask that executes a file from C:\Users\<USER>\AppData\Local
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\schtasks.exe" and (ProcessCommandLine contains "/Create" and ProcessCommandLine contains "/RU" and ProcessCommandLine contains "/TR" and ProcessCommandLine contains "C:\\Users\\" and ProcessCommandLine contains "\\AppData\\Local\\") and (ProcessCommandLine contains "NT AUT" or ProcessCommandLine contains " SYSTEM ")) and not(((InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" and InitiatingProcessFolderPath contains "TeamViewer_.exe") and FolderPath endswith "\\schtasks.exe" and ProcessCommandLine contains "/TN TVInstallRestore")))
