// Title: Exports Critical Registry Keys To a File
// ID: 82880171-b475-4201-b811-e9c826cd5eaa
// Status: test
// Level: high
// Author: Oddvar Moe, Sander Wiebing, oscd.community
// Date: 2020-10-12
// Tags: attack.exfiltration, attack.discovery, attack.t1012
// Description: Detects the export of a crital Registry key to a file.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains " -E ") and ((ProcessCommandLine contains "hklm" or ProcessCommandLine contains "hkey_local_machine")) and ((ProcessCommandLine endswith "\\system" or ProcessCommandLine endswith "\\sam" or ProcessCommandLine endswith "\\security")) and ((FolderPath endswith "\\regedit.exe") or (ProcessVersionInfoOriginalFileName == "REGEDIT.EXE")))
