// Title: Start Windows Service Via Net.EXE
// ID: 2a072a96-a086-49fa-bcb5-15cc5a619093
// Status: test
// Level: low
// Author: Timur Zinniatullin, Daniil Yugoslavskiy, oscd.community
// Date: 2019-10-21
// Tags: attack.execution, attack.t1569.002
// Description: Detects the usage of the "net.exe" command to start a service using the "start" flag
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains " start ") and (((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe")) or ((ProcessVersionInfoOriginalFileName == "net.exe" or ProcessVersionInfoOriginalFileName == "net1.exe"))))
