// Title: Potentially Suspicious Child Process of KeyScrambler.exe
// ID: ca5583e9-8f80-46ac-ab91-7f314d13b984
// Status: test
// Level: medium
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-05-13
// Tags: attack.persistence, attack.execution, attack.privilege-escalation, attack.stealth, attack.t1203, attack.t1574.001
// Description: Detects potentially suspicious child processes of KeyScrambler.exe
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\wscript.exe")) or ((ProcessVersionInfoOriginalFileName == "Cmd.Exe" or ProcessVersionInfoOriginalFileName == "cscript.exe" or ProcessVersionInfoOriginalFileName == "mshta.exe" or ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll" or ProcessVersionInfoOriginalFileName == "regsvr32.exe" or ProcessVersionInfoOriginalFileName == "RUNDLL32.EXE" or ProcessVersionInfoOriginalFileName == "wscript.exe"))) and (InitiatingProcessFolderPath endswith "\\KeyScrambler.exe"))
