// Title: HackTool - KrbRelayUp Execution
// ID: 12827a56-61a4-476a-a9cb-f3068f191073
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-04-26
// Tags: attack.credential-access, attack.t1558.003, attack.lateral-movement, attack.t1550.003
// Description: Detects KrbRelayUp used to perform a universal no-fix local privilege escalation in Windows domain environments where LDAP signing is not enforced
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " relay " and ProcessCommandLine contains " -Domain " and ProcessCommandLine contains " -ComputerName ")) or ((ProcessCommandLine contains " krbscm " and ProcessCommandLine contains " -sc ")) or ((ProcessCommandLine contains " spawn " and ProcessCommandLine contains " -d " and ProcessCommandLine contains " -cn " and ProcessCommandLine contains " -cp ")) or ((FolderPath endswith "\\KrbRelayUp.exe") or (ProcessVersionInfoOriginalFileName == "KrbRelayUp.exe")))
