// Title: Disable Or Stop Services
// ID: de25eeb8-3655-4643-ac3a-b662d3f26b6b
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Tags: attack.defense-impairment, attack.t1685, attack.impact, attack.t1489
// Description: Detects the usage of utilities such as 'systemctl', 'service'...etc to stop or disable tools and services on Linux systems.
// Attackers may stop or disable security tools and services to evade detection, maintain persistence, or disrupt system operations.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "/service" or FolderPath endswith "/systemctl" or FolderPath endswith "/chkconfig") and (ProcessCommandLine contains " stop " or ProcessCommandLine contains " disable ")) and not(((FolderPath endswith "/systemctl" and (ProcessCommandLine contains "--no-reload disable snap-snapd-" or ProcessCommandLine contains " stop snap-snapd-")) or (FolderPath endswith "/systemctl" and InitiatingProcessCommandLine contains "tmp.ci/preinst upgrade" and (ProcessCommandLine contains " stop " and ProcessCommandLine contains "ssh.")) or (InitiatingProcessCommandLine contains "/dpkg/info/ubuntu-pro-client.prerm upgrade" and FolderPath endswith "/systemctl"))) and not((FolderPath endswith "/systemctl" and ProcessCommandLine endswith "snap.amazon-ssm-agent.amazon-ssm-agent.service")))
