// Title: HackTool - KrbRelay Execution
// ID: e96253b8-6b3b-4f90-9e59-3b24b99cf9b4
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-04-27
// Tags: attack.credential-access, attack.t1558.003
// Description: Detects the use of KrbRelay, a Kerberos relaying tool
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " -spn " and ProcessCommandLine contains " -clsid " and ProcessCommandLine contains " -rbcd ")) or ((ProcessCommandLine contains "shadowcred" and ProcessCommandLine contains "clsid" and ProcessCommandLine contains "spn")) or ((ProcessCommandLine contains "spn " and ProcessCommandLine contains "session " and ProcessCommandLine contains "clsid ")) or ((FolderPath endswith "\\KrbRelay.exe") or (ProcessVersionInfoOriginalFileName == "KrbRelay.exe")))
