// Title: Potential Base64 Decoded From Images
// ID: 09a910bf-f71f-4737-9c40-88880ba5913d
// Status: test
// Level: high
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-12-20
// Tags: attack.stealth, attack.t1140
// Description: Detects the use of tail to extract bytes at an offset from an image and then decode the base64 value to create a new file with the decoded content. The detected execution is a bash one-liner.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "base64" and ProcessCommandLine contains "-d" and ProcessCommandLine contains ">")) and ((ProcessCommandLine contains ".avif" or ProcessCommandLine contains ".gif" or ProcessCommandLine contains ".jfif" or ProcessCommandLine contains ".jpeg" or ProcessCommandLine contains ".jpg" or ProcessCommandLine contains ".pjp" or ProcessCommandLine contains ".pjpeg" or ProcessCommandLine contains ".png" or ProcessCommandLine contains ".svg" or ProcessCommandLine contains ".webp")) and (FolderPath endswith "/bash") and ((ProcessCommandLine contains "tail" and ProcessCommandLine contains "-c")))
