// Title: Potentially Suspicious Inline JavaScript Execution via NodeJS Binary
// ID: 8537c866-072e-460d-bfff-aaf39cbd73d3
// Status: experimental
// Level: medium
// Author: Microsoft (idea), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-04-21
// Tags: attack.execution, attack.t1059.007
// Description: Detects potentially suspicious inline JavaScript execution using Node.js with specific keywords in the command line.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "http" and ProcessCommandLine contains "execSync" and ProcessCommandLine contains "spawn" and ProcessCommandLine contains "fs" and ProcessCommandLine contains "path" and ProcessCommandLine contains "zlib")) and ((FolderPath endswith "\\node.exe") or (ProcessVersionInfoOriginalFileName == "node.exe") or (Product == "Node.js")))
