// Title: Potential Privilege Escalation To LOCAL SYSTEM
// ID: 207b0396-3689-42d9-8399-4222658efc99
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-05-22
// Tags: attack.resource-development, attack.t1587.001
// Description: Detects unknown program using commandline flags usually used by tools such as PsExec and PAExec to start programs with SYSTEM Privileges
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " -s cmd" or ProcessCommandLine contains " -s -i cmd" or ProcessCommandLine contains " -i -s cmd" or ProcessCommandLine contains " -s pwsh" or ProcessCommandLine contains " -s -i pwsh" or ProcessCommandLine contains " -i -s pwsh" or ProcessCommandLine contains " -s powershell" or ProcessCommandLine contains " -s -i powershell" or ProcessCommandLine contains " -i -s powershell")) and not(((ProcessCommandLine contains "paexec" or ProcessCommandLine contains "PsExec" or ProcessCommandLine contains "accepteula"))))
