// Title: Potential Recon Activity Using DriverQuery.EXE
// ID: 9fc3072c-dc8f-4bf7-b231-18950000fadd
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-19
// Tags: attack.discovery
// Description: Detect usage of the "driverquery" utility to perform reconnaissance on installed drivers
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "driverquery.exe") or (ProcessVersionInfoOriginalFileName == "drvqry.exe")) and (((InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\regsvr32.exe" or InitiatingProcessFolderPath endswith "\\rundll32.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe")) or ((InitiatingProcessFolderPath contains "\\AppData\\Local\\" or InitiatingProcessFolderPath contains "\\Users\\Public\\" or InitiatingProcessFolderPath contains "\\Windows\\Temp\\"))))
