// Title: Cscript/Wscript Uncommon Script Extension Execution
// ID: 99b7460d-c9f1-40d7-a316-1f36f61d52ee
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Tags: attack.execution, attack.t1059.005, attack.t1059.007
// Description: Detects Wscript/Cscript executing a file with an uncommon (i.e. non-script) extension
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ".csv" or ProcessCommandLine contains ".dat" or ProcessCommandLine contains ".doc" or ProcessCommandLine contains ".gif" or ProcessCommandLine contains ".jpeg" or ProcessCommandLine contains ".jpg" or ProcessCommandLine contains ".png" or ProcessCommandLine contains ".ppt" or ProcessCommandLine contains ".txt" or ProcessCommandLine contains ".xls" or ProcessCommandLine contains ".xml")) and (((ProcessVersionInfoOriginalFileName == "wscript.exe" or ProcessVersionInfoOriginalFileName == "cscript.exe")) or ((FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe"))))
