// Title: HackTool - SharpDPAPI Execution
// ID: c7d33b50-f690-4b51-8cfb-0fb912a31e57
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-06-26
// Tags: attack.privilege-escalation, attack.stealth, attack.t1134.001, attack.t1134.003
// Description: Detects the execution of the SharpDPAPI tool based on CommandLine flags and PE metadata.
// SharpDPAPI is a C# port of some DPAPI functionality from the Mimikatz project.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\SharpDPAPI.exe") or (ProcessVersionInfoOriginalFileName == "SharpDPAPI.exe")) or (((ProcessCommandLine contains " backupkey " or ProcessCommandLine contains " blob " or ProcessCommandLine contains " certificates " or ProcessCommandLine contains " credentials " or ProcessCommandLine contains " keepass " or ProcessCommandLine contains " masterkeys " or ProcessCommandLine contains " rdg " or ProcessCommandLine contains " vaults ")) and (((ProcessCommandLine contains " /file:" or ProcessCommandLine contains " /machine" or ProcessCommandLine contains " /mkfile:" or ProcessCommandLine contains " /password:" or ProcessCommandLine contains " /pvk:" or ProcessCommandLine contains " /server:" or ProcessCommandLine contains " /target:" or ProcessCommandLine contains " /unprotect")) or ((ProcessCommandLine contains " {" and ProcessCommandLine contains "}:")))))
