// Title: MMC Executing Files with Reversed Extensions Using RTLO Abuse
// ID: 9cfe4b27-1e56-48b4-b7a8-d46851c91a44
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-02-05
// Tags: attack.execution, attack.stealth, attack.t1204.002, attack.t1218.014, attack.t1036.002
// Description: Detects malicious behavior where the MMC utility (`mmc.exe`) executes files with reversed extensions caused by Right-to-Left Override (RLO) abuse, disguising them as document formats.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "cod.msc" or ProcessCommandLine contains "fdp.msc" or ProcessCommandLine contains "ftr.msc" or ProcessCommandLine contains "lmth.msc" or ProcessCommandLine contains "slx.msc" or ProcessCommandLine contains "tdo.msc" or ProcessCommandLine contains "xcod.msc" or ProcessCommandLine contains "xslx.msc" or ProcessCommandLine contains "xtpp.msc")) and ((FolderPath endswith "\\mmc.exe") or (ProcessVersionInfoOriginalFileName == "MMC.exe")))
