// Title: Python One-Liners with Base64 Decoding
// ID: 50a0aa3d-ab16-4594-a8aa-5145a6e6792b
// Status: experimental
// Level: high
// Author: Hugh Ryan (HueCodes), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-03-09
// Tags: attack.execution, attack.stealth, attack.t1059.006, attack.t1027.010
// Description: Detects Python one-liners that use base64 decoding functions in command line executions.
// Malicious scripts or attackers often use python one-liners to decode and execute base64-encoded payloads, which is a common technique for obfuscation and evasion.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "import" and ProcessCommandLine contains "base64" and ProcessCommandLine contains " -c") and (ProcessCommandLine contains ".decode" or ProcessCommandLine contains "b16decode" or ProcessCommandLine contains "b32decode" or ProcessCommandLine contains "b32hexdecode" or ProcessCommandLine contains "b64decode" or ProcessCommandLine contains "b85decode" or ProcessCommandLine contains "z85decode")) and ((FolderPath contains "\\python") or (ProcessVersionInfoOriginalFileName contains "python")))
