// Title: Print History File Contents
// ID: d7821ff1-4527-4e33-9f84-d0d57fa2fb66
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-20
// Tags: attack.reconnaissance, attack.t1592.004
// Description: Detects events in which someone prints the contents of history files to the commandline or redirects it to a file for reconnaissance
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "/cat" or FolderPath endswith "/head" or FolderPath endswith "/tail" or FolderPath endswith "/more")) and (((ProcessCommandLine contains "/.bash_history" or ProcessCommandLine contains "/.zsh_history")) or ((ProcessCommandLine endswith "_history" or ProcessCommandLine endswith ".history" or ProcessCommandLine endswith "zhistory"))))
