// Title: PUA - Ngrok Execution
// ID: ee37eb7c-a4e7-4cd5-8fa4-efa27f1c3f31
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2021-05-14
// Tags: attack.command-and-control, attack.t1572
// Description: Detects the use of Ngrok, a utility used for port forwarding and tunneling, often used by threat actors to make local protected services publicly available.
// Involved domains are bin.equinox.io for download and *.ngrok.io for connections.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " tcp 139" or ProcessCommandLine contains " tcp 445" or ProcessCommandLine contains " tcp 3389" or ProcessCommandLine contains " tcp 5985" or ProcessCommandLine contains " tcp 5986")) or ((ProcessCommandLine contains " start " and ProcessCommandLine contains "--all" and ProcessCommandLine contains "--config" and ProcessCommandLine contains ".yml")) or (FolderPath endswith "ngrok.exe" and (ProcessCommandLine contains " tcp " or ProcessCommandLine contains " http " or ProcessCommandLine contains " authtoken ")) or ((ProcessCommandLine contains ".exe authtoken " or ProcessCommandLine contains ".exe start --all")))
