// Title: File Encryption/Decryption Via Gpg4win From Suspicious Locations
// ID: e1e0b7d7-e10b-4ee4-ac49-a4bda05d320d
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), X__Junior (Nextron Systems)
// Date: 2022-11-30
// Tags: attack.execution
// Description: Detects usage of Gpg4win to encrypt/decrypt files located in potentially suspicious locations.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "-passphrase") and (((FolderPath endswith "\\gpg.exe" or FolderPath endswith "\\gpg2.exe")) or (Product == "GNU Privacy Guard (GnuPG)") or (Description == "GnuPG’s OpenPGP tool")) and ((ProcessCommandLine contains ":\\PerfLogs\\" or ProcessCommandLine contains ":\\Temp\\" or ProcessCommandLine contains ":\\Users\\Public\\" or ProcessCommandLine contains ":\\Windows\\Temp\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\AppData\\Roaming\\")))
