// Title: Security Service Disabled Via Reg.EXE
// ID: 5e95028c-5229-4214-afae-d653d573d0ec
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), John Lambert (idea), elhoim
// Date: 2021-07-14
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects execution of "reg.exe" to disable security services such as Windows Defender.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "d 4" and ProcessCommandLine contains "v Start") and (ProcessCommandLine contains "\\AppIDSvc" or ProcessCommandLine contains "\\MsMpSvc" or ProcessCommandLine contains "\\NisSrv" or ProcessCommandLine contains "\\SecurityHealthService" or ProcessCommandLine contains "\\Sense" or ProcessCommandLine contains "\\UsoSvc" or ProcessCommandLine contains "\\WdBoot" or ProcessCommandLine contains "\\WdFilter" or ProcessCommandLine contains "\\WdNisDrv" or ProcessCommandLine contains "\\WdNisSvc" or ProcessCommandLine contains "\\WinDefend" or ProcessCommandLine contains "\\wscsvc" or ProcessCommandLine contains "\\wuauserv")) and ((ProcessCommandLine contains "reg" and ProcessCommandLine contains "add")))
