// Title: PUA - Potential PE Metadata Tamper Using Rcedit
// ID: 0c92f2e6-f08f-4b73-9216-ecb0ca634689
// Status: test
// Level: medium
// Author: Micah Babinski
// Date: 2022-12-11
// Tags: attack.stealth, attack.t1036.003, attack.t1036, attack.t1027.005, attack.t1027
// Description: Detects the use of rcedit to potentially alter executable PE metadata properties, which could conceal efforts to rename system utilities for defense evasion.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "OriginalFileName" or ProcessCommandLine contains "CompanyName" or ProcessCommandLine contains "FileDescription" or ProcessCommandLine contains "ProductName" or ProcessCommandLine contains "ProductVersion" or ProcessCommandLine contains "LegalCopyright")) and (ProcessCommandLine contains "--set-") and (((FolderPath endswith "\\rcedit-x64.exe" or FolderPath endswith "\\rcedit-x86.exe")) or (Description == "Edit resources of exe") or (Product == "rcedit")))
