// Title: Potentially Suspicious Execution Of Regasm/Regsvcs With Uncommon Extension
// ID: e9f8f8cc-07cc-4e81-b724-f387db9175e4
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-13
// Tags: attack.stealth, attack.t1218.009
// Description: Detects potentially suspicious execution of the Regasm/Regsvcs utilities with an uncommon extension.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains ".dat" or ProcessCommandLine contains ".gif" or ProcessCommandLine contains ".jpeg" or ProcessCommandLine contains ".jpg" or ProcessCommandLine contains ".png" or ProcessCommandLine contains ".txt")) and (((FolderPath endswith "\\Regsvcs.exe" or FolderPath endswith "\\Regasm.exe")) or ((ProcessVersionInfoOriginalFileName == "RegSvcs.exe" or ProcessVersionInfoOriginalFileName == "RegAsm.exe"))))
