// Title: Disable Windows Defender AV Security Monitoring
// ID: a7ee1722-c3c5-aeff-3212-c777e4733217
// Status: test
// Level: high
// Author: ok @securonix invrep-de, oscd.community, frack113
// Date: 2020-10-12
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects attackers attempting to disable Windows Defender using Powershell
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or ((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll"))) and ((ProcessCommandLine contains "-DisableBehaviorMonitoring $true" or ProcessCommandLine contains "-DisableRuntimeMonitoring $true"))) or (((FolderPath endswith "\\sc.exe") or (ProcessVersionInfoOriginalFileName == "sc.exe")) and (((ProcessCommandLine contains "delete" and ProcessCommandLine contains "WinDefend")) or ((ProcessCommandLine contains "config" and ProcessCommandLine contains "WinDefend" and ProcessCommandLine contains "start=disabled")) or ((ProcessCommandLine contains "stop" and ProcessCommandLine contains "WinDefend")))))
