// Title: Regsvr32 DLL Execution With Uncommon Extension
// ID: 50919691-7302-437f-8e10-1fe088afa145
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2019-07-17
// Tags: attack.privilege-escalation, attack.persistence, attack.stealth, attack.t1574, attack.execution
// Description: Detects a "regsvr32" execution where the DLL doesn't contain a common file extension.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\regsvr32.exe") or (ProcessVersionInfoOriginalFileName == "REGSVR32.EXE")) and not(((ProcessCommandLine == "") or ((ProcessCommandLine contains ".ax" or ProcessCommandLine contains ".cpl" or ProcessCommandLine contains ".dll" or ProcessCommandLine contains ".ocx")) or ((isempty(ProcessCommandLine) or isnull(ProcessCommandLine))))) and not(((ProcessCommandLine contains ".bav") or (ProcessCommandLine contains ".ppl"))))
