// Title: Suspicious Use of PsLogList
// ID: aae1243f-d8af-40d8-ab20-33fc6d0c55bc
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-18
// Tags: attack.discovery, attack.t1087, attack.t1087.001, attack.t1087.002
// Description: Detects usage of the PsLogList utility to dump event log in order to extract admin accounts and perform account discovery or delete events logs
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " security" or ProcessCommandLine contains " application" or ProcessCommandLine contains " system")) and ((ProcessCommandLine contains " -d" or ProcessCommandLine contains " -x" or ProcessCommandLine contains " -s" or ProcessCommandLine contains " -c" or ProcessCommandLine contains " -g")) and ((ProcessVersionInfoOriginalFileName == "psloglist.exe") or ((FolderPath endswith "\\psloglist.exe" or FolderPath endswith "\\psloglist64.exe" or FolderPath endswith "\\psloglist64a.exe"))))
