// Title: Suspicious Windows Trace ETW Session Tamper Via Logman.EXE
// ID: cd1f961e-0b96-436b-b7c6-38da4583ec00
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2021-02-11
// Tags: attack.defense-impairment, attack.t1685, attack.t1685.005
// Description: Detects the execution of "logman" utility in order to disable or delete Windows trace sessions
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "stop " or ProcessCommandLine contains "delete ")) and ((FolderPath endswith "\\logman.exe") or (ProcessVersionInfoOriginalFileName == "Logman.exe")) and ((ProcessCommandLine contains "Circular Kernel Context Logger" or ProcessCommandLine contains "EventLog-" or ProcessCommandLine contains "SYSMON TRACE" or ProcessCommandLine contains "SysmonDnsEtwSession")))
