// Title: HackTool - Jlaive In-Memory Assembly Execution
// ID: 0a99eb3e-1617-41bd-b095-13dc767f3def
// Status: test
// Level: medium
// Author: Jose Luis Sanchez Martinez (@Joseliyo_Jstnk)
// Date: 2022-05-24
// Tags: attack.execution, attack.t1059.003
// Description: Detects the use of Jlaive to execute assemblies in a copied PowerShell
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\cmd.exe" and InitiatingProcessCommandLine endswith ".bat") and ((FolderPath endswith "\\xcopy.exe" and (ProcessCommandLine contains "powershell.exe" and ProcessCommandLine contains ".bat.exe")) or (FolderPath endswith "\\xcopy.exe" and (ProcessCommandLine contains "pwsh.exe" and ProcessCommandLine contains ".bat.exe")) or (FolderPath endswith "\\attrib.exe" and (ProcessCommandLine contains "+s" and ProcessCommandLine contains "+h" and ProcessCommandLine contains ".bat.exe"))))
