// Title: PowerShell Script Change Permission Via Set-Acl
// ID: bdeb2cff-af74-4094-8426-724dc937f20a
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-18
// Tags: attack.stealth
// Description: Detects PowerShell execution to set the ACL of a file or a folder
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Set-Acl " and ProcessCommandLine contains "-AclObject " and ProcessCommandLine contains "-Path ")) and (((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll")) or ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe"))))
