// Title: RegAsm.EXE Execution Without CommandLine Flags or Files
// ID: 651f87f7-12db-47f9-84c5-f27b081b94b6
// Status: experimental
// Level: low
// Author: frack113
// Date: 2025-06-04
// Tags: attack.stealth, attack.t1218.009
// Description: Detects the execution of "RegAsm.exe" without a commandline flag or file, which might indicate potential process injection activity.
// Usually "RegAsm.exe" should point to a dedicated DLL file or call the help with the "/?" flag.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine endswith "RegAsm" or ProcessCommandLine endswith "RegAsm.exe" or ProcessCommandLine endswith "RegAsm.exe\"" or ProcessCommandLine endswith "RegAsm.exe'")) and ((FolderPath endswith "\\RegAsm.exe") or (ProcessVersionInfoOriginalFileName == "RegAsm.exe")))
