// Title: Control Panel Items
// ID: 0ba863e6-def5-4e50-9cea-4dd8c7dc46a4
// Status: test
// Level: high
// Author: Kyaw Min Thein, Furkan Caliskan (@caliskanfurkan_)
// Date: 2020-06-22
// Tags: attack.privilege-escalation, attack.execution, attack.stealth, attack.t1218.002, attack.persistence, attack.t1546
// Description: Detects the malicious use of a control panel item
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((ProcessCommandLine contains "add" and ProcessCommandLine contains "CurrentVersion\\Control Panel\\CPLs")) and ((FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName == "reg.exe"))) or ((ProcessCommandLine endswith ".cpl") and not((((ProcessCommandLine contains "regsvr32 " and ProcessCommandLine contains " /s " and ProcessCommandLine contains "igfxCPL.cpl")) or ((ProcessCommandLine contains "\\System32\\" or ProcessCommandLine contains "%System%" or ProcessCommandLine contains "|C:\\Windows\\system32|"))))))
