// Title: HackTool - Potential Impacket Lateral Movement Activity
// ID: 10c14723-61c7-4c75-92ca-9af245723ad2
// Status: stable
// Level: high
// Author: Ecco, oscd.community, Jonhnathan Ribeiro, Tim Rauch
// Date: 2019-09-03
// Tags: attack.execution, attack.t1047, attack.lateral-movement, attack.t1021.003
// Description: Detects wmiexec/dcomexec/atexec/smbexec from Impacket framework
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((InitiatingProcessCommandLine contains "svchost.exe -k netsvcs" or InitiatingProcessCommandLine contains "taskeng.exe") and (ProcessCommandLine contains "cmd.exe" and ProcessCommandLine contains "/C" and ProcessCommandLine contains "Windows\\Temp\\" and ProcessCommandLine contains "&1")) or ((InitiatingProcessFolderPath endswith "\\wmiprvse.exe" or InitiatingProcessFolderPath endswith "\\mmc.exe" or InitiatingProcessFolderPath endswith "\\explorer.exe" or InitiatingProcessFolderPath endswith "\\services.exe") and (ProcessCommandLine contains "cmd.exe" and ProcessCommandLine contains "/Q" and ProcessCommandLine contains "/c" and ProcessCommandLine contains "\\\\\\\\127.0.0.1\\\\" and ProcessCommandLine contains "&1")))
