// Title: Suspicious WmiPrvSE Child Process
// ID: 8a582fe2-0882-4b89-a82a-da6b2dc32937
// Status: test
// Level: high
// Author: Vadim Khrykov (ThreatIntel), Cyb3rEng, Florian Roth (Nextron Systems)
// Date: 2021-08-23
// Tags: attack.execution, attack.stealth, attack.t1047, attack.t1204.002, attack.t1218.010
// Description: Detects suspicious and uncommon child processes of WmiPrvSE
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((InitiatingProcessFolderPath endswith "\\wbem\\WmiPrvSE.exe") and (((FolderPath endswith "\\certutil.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\msiexec.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\verclsid.exe" or FolderPath endswith "\\wscript.exe")) or (FolderPath endswith "\\cmd.exe" and (ProcessCommandLine contains "cscript" or ProcessCommandLine contains "mshta" or ProcessCommandLine contains "powershell" or ProcessCommandLine contains "pwsh" or ProcessCommandLine contains "regsvr32" or ProcessCommandLine contains "rundll32" or ProcessCommandLine contains "wscript"))) and not(((FolderPath endswith "\\msiexec.exe" and ProcessCommandLine contains "/i ") or (FolderPath endswith "\\WerFault.exe") or (FolderPath endswith "\\WmiPrvSE.exe"))))
