// Title: Winrs Local Command Execution
// ID: bcfece3d-56fe-4545-9931-3b8e92927db1
// Status: experimental
// Level: high
// Author: Liran Ravich, Nasreddine Bencherchali
// Date: 2025-10-22
// Tags: attack.lateral-movement, attack.stealth, attack.t1021.006, attack.t1218
// Description: Detects the execution of Winrs.exe where it is used to execute commands locally.
// Commands executed this way are launched under Winrshost.exe and can represent proxy execution used for defense evasion or lateral movement.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "\\winrs.exe") or (ProcessVersionInfoOriginalFileName == "winrs.exe")) and ((ProcessCommandLine contains "/r:localhost" or ProcessCommandLine contains "-r:localhost" or ProcessCommandLine contains "/r:127.0.0.1" or ProcessCommandLine contains "-r:127.0.0.1" or ProcessCommandLine contains "/r:[::1]" or ProcessCommandLine contains "-r:[::1]" or ProcessCommandLine contains "/remote:localhost" or ProcessCommandLine contains "-remote:localhost" or ProcessCommandLine contains "/remote:127.0.0.1" or ProcessCommandLine contains "-remote:127.0.0.1" or ProcessCommandLine contains "/remote:[::1]" or ProcessCommandLine contains "-remote:[::1]"))) or (((FolderPath endswith "\\winrs.exe") or (ProcessVersionInfoOriginalFileName == "winrs.exe")) and not(((ProcessCommandLine contains "/r:" or ProcessCommandLine contains "-r:" or ProcessCommandLine contains "/remote:" or ProcessCommandLine contains "-remote:")))))
