// Title: Potential SysInternals ProcDump Evasion
// ID: 79b06761-465f-4f88-9ef2-150e24d3d737
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-11
// Tags: attack.stealth, attack.t1036, attack.t1003.001, attack.credential-access
// Description: Detects uses of the SysInternals ProcDump utility in which ProcDump or its output get renamed, or a dump file is moved or copied to a different name
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "copy procdump" or ProcessCommandLine contains "move procdump")) or ((ProcessCommandLine contains "copy " and ProcessCommandLine contains ".dmp ") and (ProcessCommandLine contains "2.dmp" or ProcessCommandLine contains "lsass" or ProcessCommandLine contains "out.dmp")) or ((ProcessCommandLine contains "copy lsass.exe_" or ProcessCommandLine contains "move lsass.exe_")))
