// Title: Potentially Suspicious Office Document Executed From Trusted Location
// ID: f99abdf0-6283-4e71-bd2b-b5c048a94743
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-21
// Tags: attack.stealth, attack.t1202
// Description: Detects the execution of an Office application that points to a document that is located in a trusted location. Attackers often used this to avoid macro security and execute their malicious code.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((((FolderPath endswith "\\EXCEL.EXE" or FolderPath endswith "\\POWERPNT.EXE" or FolderPath endswith "\\WINWORD.exe")) or ((ProcessVersionInfoOriginalFileName == "Excel.exe" or ProcessVersionInfoOriginalFileName == "POWERPNT.EXE" or ProcessVersionInfoOriginalFileName == "WinWord.exe"))) and ((InitiatingProcessFolderPath endswith "\\explorer.exe" or InitiatingProcessFolderPath endswith "\\dopus.exe")) and ((ProcessCommandLine contains "\\AppData\\Roaming\\Microsoft\\Templates" or ProcessCommandLine contains "\\AppData\\Roaming\\Microsoft\\Word\\Startup\\" or ProcessCommandLine contains "\\Microsoft Office\\root\\Templates\\" or ProcessCommandLine contains "\\Microsoft Office\\Templates\\"))) and not(((ProcessCommandLine endswith ".dotx" or ProcessCommandLine endswith ".xltx" or ProcessCommandLine endswith ".potx"))))
