// Title: Potential Powershell ReverseShell Connection
// ID: edc2f8ae-2412-4dfd-b9d5-0c57727e70be
// Status: stable
// Level: high
// Author: FPT.EagleEye, wagga, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-03-03
// Tags: attack.execution, attack.t1059.001
// Description: Detects usage of the "TcpClient" class. Which can be abused to establish remote connections and reverse-shells. As seen used by the Nishang "Invoke-PowerShellTcpOneLine" reverse shell and other.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains " Net.Sockets.TCPClient" and ProcessCommandLine contains ".GetStream(" and ProcessCommandLine contains ".Write(")) and (((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll")) or ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe"))))
