// Title: Veeam Backup Database Suspicious Query
// ID: 696bfb54-227e-4602-ac5b-30d9d2053312
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-04
// Tags: attack.collection, attack.t1005
// Description: Detects potentially suspicious SQL queries using SQLCmd targeting the Veeam backup databases in order to steal information.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "BackupRepositories" or ProcessCommandLine contains "Backups" or ProcessCommandLine contains "Credentials" or ProcessCommandLine contains "HostCreds" or ProcessCommandLine contains "SmbFileShares" or ProcessCommandLine contains "Ssh_creds" or ProcessCommandLine contains "VSphereInfo")) and (FolderPath endswith "\\sqlcmd.exe" and (ProcessCommandLine contains "VeeamBackup" and ProcessCommandLine contains "From ")))
