// Title: Potential Configuration And Service Reconnaissance Via Reg.EXE
// ID: 970007b7-ce32-49d0-a4a4-fbef016950bd
// Status: test
// Level: medium
// Author: Timur Zinniatullin, oscd.community
// Date: 2019-10-21
// Tags: attack.discovery, attack.t1012, attack.t1007
// Description: Detects the usage of "reg.exe" in order to query reconnaissance information from the registry. Adversaries may interact with the Windows registry to gather information about credentials, the system, configuration, and installed software.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "query") and ((FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName == "reg.exe")) and ((ProcessCommandLine contains "currentVersion\\windows" or ProcessCommandLine contains "winlogon\\" or ProcessCommandLine contains "currentVersion\\shellServiceObjectDelayLoad" or ProcessCommandLine contains "currentVersion\\run" or ProcessCommandLine contains "currentVersion\\policies\\explorer\\run" or ProcessCommandLine contains "currentcontrolset\\services")))
