// Title: Regsvr32 DLL Execution With Suspicious File Extension
// ID: 089fc3d2-71e8-4763-a8a5-c97fbb0a403e
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), frack113
// Date: 2021-11-29
// Tags: attack.stealth, attack.t1218.010
// Description: Detects the execution of REGSVR32.exe with DLL files masquerading as other files
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine endswith ".bin" or ProcessCommandLine endswith ".bmp" or ProcessCommandLine endswith ".cr2" or ProcessCommandLine endswith ".dat" or ProcessCommandLine endswith ".eps" or ProcessCommandLine endswith ".gif" or ProcessCommandLine endswith ".ico" or ProcessCommandLine endswith ".jpeg" or ProcessCommandLine endswith ".jpg" or ProcessCommandLine endswith ".log" or ProcessCommandLine endswith ".nef" or ProcessCommandLine endswith ".orf" or ProcessCommandLine endswith ".png" or ProcessCommandLine endswith ".raw" or ProcessCommandLine endswith ".rtf" or ProcessCommandLine endswith ".sr2" or ProcessCommandLine endswith ".temp" or ProcessCommandLine endswith ".tif" or ProcessCommandLine endswith ".tiff" or ProcessCommandLine endswith ".tmp" or ProcessCommandLine endswith ".txt")) and ((FolderPath endswith "\\regsvr32.exe") or (ProcessVersionInfoOriginalFileName == "REGSVR32.EXE")))
