// Title: Browser Execution In Headless Mode
// ID: ef9dcfed-690c-4c5d-a9d1-482cd422225c
// Status: test
// Level: low
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-12
// Tags: attack.command-and-control, attack.stealth, attack.t1105, attack.t1564.003
// Description: Detects execution of Chromium based browser in headless mode
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\vivaldi.exe") and ProcessCommandLine contains "--headless")
