// Title: Suspicious Service DACL Modification Via Set-Service Cmdlet
// ID: a95b9b42-1308-4735-a1af-abb1c5e6f5ac
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-18
// Tags: attack.privilege-escalation, attack.persistence, attack.t1543.003
// Description: Detects suspicious DACL modifications via the "Set-Service" cmdlet using the "SecurityDescriptorSddl" flag (Only available with PowerShell 7) that can be used to hide services or make them unstopable
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName == "pwsh.dll")) and ((ProcessCommandLine contains "-SecurityDescriptorSddl " or ProcessCommandLine contains "-sd ")) and ((ProcessCommandLine contains "Set-Service " and ProcessCommandLine contains "D;;") and (ProcessCommandLine contains ";;;IU" or ProcessCommandLine contains ";;;SU" or ProcessCommandLine contains ";;;BA" or ProcessCommandLine contains ";;;SY" or ProcessCommandLine contains ";;;WD")))
