// Title: Suspicious Execution via macOS Script Editor
// ID: 6e4dcdd1-e48b-42f7-b2d8-3b413fc58cb4
// Status: test
// Level: medium
// Author: Tim Rauch (rule), Elastic (idea)
// Date: 2022-10-21
// Tags: attack.defense-impairment, attack.t1566, attack.t1566.002, attack.initial-access, attack.t1059, attack.t1059.002, attack.t1204, attack.t1204.001, attack.execution, attack.persistence, attack.t1553
// Description: Detects when the macOS Script Editor utility spawns an unusual child process.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((FolderPath endswith "/curl" or FolderPath endswith "/bash" or FolderPath endswith "/sh" or FolderPath endswith "/zsh" or FolderPath endswith "/dash" or FolderPath endswith "/fish" or FolderPath endswith "/osascript" or FolderPath endswith "/mktemp" or FolderPath endswith "/chmod" or FolderPath endswith "/php" or FolderPath endswith "/nohup" or FolderPath endswith "/openssl" or FolderPath endswith "/plutil" or FolderPath endswith "/PlistBuddy" or FolderPath endswith "/xattr" or FolderPath endswith "/sqlite" or FolderPath endswith "/funzip" or FolderPath endswith "/popen")) or ((FolderPath contains "python" or FolderPath contains "perl"))) and (InitiatingProcessFolderPath endswith "/Script Editor"))
