// Title: System Network Discovery - Linux
// ID: e7bd1cfa-b446-4c88-8afb-403bcd79e3fa
// Status: test
// Level: informational
// Author: Ömer Günal and remotephone, oscd.community
// Date: 2020-10-06
// Tags: attack.discovery, attack.t1016
// Description: Detects enumeration of local network configuration
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((ProcessCommandLine contains "/etc/resolv.conf") or ((FolderPath endswith "/firewall-cmd" or FolderPath endswith "/ufw" or FolderPath endswith "/iptables" or FolderPath endswith "/netstat" or FolderPath endswith "/ss" or FolderPath endswith "/ip" or FolderPath endswith "/ifconfig" or FolderPath endswith "/systemd-resolve" or FolderPath endswith "/route")))
