// Title: PowerShell Set-Acl On Windows Folder
// ID: 0944e002-e3f6-4eb5-bf69-3a3067b53d73
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-18
// Tags: attack.stealth
// Description: Detects PowerShell scripts to set the ACL to a file in the Windows folder
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "Set-Acl " and ProcessCommandLine contains "-AclObject ")) and (((ProcessVersionInfoOriginalFileName == "PowerShell.EXE" or ProcessVersionInfoOriginalFileName == "pwsh.dll")) or ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe"))) and ((ProcessCommandLine contains "-Path \"C:\\Windows" or ProcessCommandLine contains "-Path 'C:\\Windows" or ProcessCommandLine contains "-Path %windir%" or ProcessCommandLine contains "-Path $env:windir")) and ((ProcessCommandLine contains "FullControl" or ProcessCommandLine contains "Allow")))
