// Title: HackTool - CrackMapExec Process Patterns
// ID: f26307d8-14cd-47e3-a26b-4b4769f24af6
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-12
// Tags: attack.credential-access, attack.t1003.001
// Description: Detects suspicious process patterns found in logs when CrackMapExec is used
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((ProcessCommandLine contains "tasklist /fi " and ProcessCommandLine contains "Imagename eq lsass.exe") and (ProcessCommandLine contains "cmd.exe /c " or ProcessCommandLine contains "cmd.exe /r " or ProcessCommandLine contains "cmd.exe /k " or ProcessCommandLine contains "cmd /c " or ProcessCommandLine contains "cmd /r " or ProcessCommandLine contains "cmd /k ") and (AccountName contains "AUTHORI" or AccountName contains "AUTORI")) or ((ProcessCommandLine contains "do rundll32.exe C:\\windows\\System32\\comsvcs.dll, MiniDump" and ProcessCommandLine contains "\\Windows\\Temp\\" and ProcessCommandLine contains " full" and ProcessCommandLine contains "%%B")) or ((ProcessCommandLine contains "tasklist /v /fo csv" and ProcessCommandLine contains "findstr /i \"lsass\"")))
