// Title: DriverQuery.EXE Execution
// ID: a20def93-0709-4eae-9bd2-31206e21e6b2
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-19
// Tags: attack.discovery
// Description: Detect usage of the "driverquery" utility. Which can be used to perform reconnaissance on installed drivers
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "driverquery.exe") or (ProcessVersionInfoOriginalFileName == "drvqry.exe")) and not((((InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\regsvr32.exe" or InitiatingProcessFolderPath endswith "\\rundll32.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe")) or ((InitiatingProcessFolderPath contains "\\AppData\\Local\\" or InitiatingProcessFolderPath contains "\\Users\\Public\\" or InitiatingProcessFolderPath contains "\\Windows\\Temp\\")))))
