// Title: Python Spawning Pretty TTY on Windows
// ID: 480e7e51-e797-47e3-8d72-ebfce65b6d8d
// Status: test
// Level: high
// Author: Nextron Systems
// Date: 2022-06-03
// Tags: attack.execution, attack.t1059
// Description: Detects python spawning a pretty tty
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "python.exe" or FolderPath endswith "python3.exe" or FolderPath endswith "python2.exe")) and (((ProcessCommandLine contains "import pty" and ProcessCommandLine contains ".spawn(")) or (ProcessCommandLine contains "from pty import spawn")))
