// Title: Suspicious Copy From or To System Directory
// ID: fff9d2b7-e11c-4a69-93d3-40ef66189767
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), Markus Neis, Tim Shelton (HAWK.IO), Nasreddine Bencherchali (Nextron Systems)
// Date: 2020-07-03
// Tags: attack.stealth, attack.t1036.003
// Description: Detects a suspicious copy operation that tries to copy a program from system (System32, SysWOW64, WinSxS) directories to another on disk.
// Often used to move LOLBINs such as 'certutil' or 'desktopimgdownldr' to a different location with a different name in order to bypass detections based on locations.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((FolderPath endswith "\\cmd.exe" and ProcessCommandLine contains "copy ") or (((FolderPath endswith "\\robocopy.exe" or FolderPath endswith "\\xcopy.exe")) or ((ProcessVersionInfoOriginalFileName == "robocopy.exe" or ProcessVersionInfoOriginalFileName == "XCOPY.EXE"))) or ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and (ProcessCommandLine contains "copy-item" or ProcessCommandLine contains " copy " or ProcessCommandLine contains "cpi " or ProcessCommandLine contains " cp "))) and (ProcessCommandLine matches regex @"\\s['\"]?C:\\\\Windows\\\\(?:System32|SysWOW64|WinSxS)") and not((FolderPath endswith "\\cmd.exe" and (ProcessCommandLine contains "/c copy" and ProcessCommandLine contains "\\Temp\\" and ProcessCommandLine contains "\\avira_system_speedup.exe") and (ProcessCommandLine contains "C:\\Program Files\\Avira\\" or ProcessCommandLine contains "C:\\Program Files (x86)\\Avira\\"))))
