// Title: Download From Suspicious TLD - Whitelist
// ID: b5de2919-b74a-4805-91a7-5049accbaefe
// Status: test
// Level: low
// Author: Florian Roth (Nextron Systems)
// Date: 2017-03-13
// Tags: attack.initial-access, attack.t1566, attack.execution, attack.t1203, attack.t1204.002
// Description: Detects executable downloads from suspicious remote systems
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (((c-uri-extension == "exe" or c-uri-extension == "vbs" or c-uri-extension == "bat" or c-uri-extension == "rar" or c-uri-extension == "ps1" or c-uri-extension == "doc" or c-uri-extension == "docm" or c-uri-extension == "xls" or c-uri-extension == "xlsm" or c-uri-extension == "pptm" or c-uri-extension == "rtf" or c-uri-extension == "hta" or c-uri-extension == "dll" or c-uri-extension == "ws" or c-uri-extension == "wsf" or c-uri-extension == "sct" or c-uri-extension == "zip")) and not(((cs-host endswith ".com" or cs-host endswith ".org" or cs-host endswith ".net" or cs-host endswith ".edu" or cs-host endswith ".gov" or cs-host endswith ".uk" or cs-host endswith ".ca" or cs-host endswith ".de" or cs-host endswith ".jp" or cs-host endswith ".fr" or cs-host endswith ".au" or cs-host endswith ".us" or cs-host endswith ".ch" or cs-host endswith ".it" or cs-host endswith ".nl" or cs-host endswith ".se" or cs-host endswith ".no" or cs-host endswith ".es"))))
