// Title: Bitsadmin to Uncommon TLD
// ID: 9eb68894-7476-4cd6-8752-23b51f5883a7
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Tim Shelton
// Date: 2019-03-07
// Tags: attack.command-and-control, attack.execution, attack.stealth, attack.t1071.001, attack.persistence, attack.t1197, attack.s0190
// Description: Detects Bitsadmin connections to domains with uncommon TLDs
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((c-useragent startswith "Microsoft BITS/") and not(((cs-host endswith ".com" or cs-host endswith ".microsoft" or cs-host endswith ".net" or cs-host endswith ".org" or cs-host endswith ".scdn.co" or cs-host endswith ".sfx.ms"))))
