// Title: VBScript Payload Stored in Registry
// ID: 46490193-1b22-4c29-bdd6-5bf63907216f
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2021-03-05
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
// Description: Detects VBScript content stored into registry keys as seen being used by UNC2452 group
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "Software\\Microsoft\\Windows\\CurrentVersion" and (RegistryValueData contains "vbscript:" or RegistryValueData contains "jscript:" or RegistryValueData contains "mshtml," or RegistryValueData contains "RunHTMLApplication" or RegistryValueData contains "Execute(" or RegistryValueData contains "CreateObject" or RegistryValueData contains "window.close")) and not(((RegistryKey contains "Software\\Microsoft\\Windows\\CurrentVersion\\Run") or (FolderPath endswith "\\msiexec.exe" and RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Installer\\UserData\\" and (RegistryValueData contains "\\Microsoft.NET\\Primary Interop Assemblies\\Microsoft.mshtml.dll" or RegistryValueData contains "<\\Microsoft.mshtml,fileVersion=" or RegistryValueData contains "_mshtml_dll_" or RegistryValueData contains "<\\Microsoft.mshtml,culture=")))))
