// Title: New Netsh Helper DLL Registered From A Suspicious Location
// ID: e7b18879-676e-4a0e-ae18-27039185a8e7
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-11-28
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.007
// Description: Detects changes to the Netsh registry key to add a new DLL value that is located on a suspicious location. This change might be an indication of a potential persistence attempt by adding a malicious Netsh helper
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\SOFTWARE\\Microsoft\\NetSh") and (((RegistryValueData contains ":\\Perflogs\\" or RegistryValueData contains ":\\Users\\Public\\" or RegistryValueData contains ":\\Windows\\Temp\\" or RegistryValueData contains "\\AppData\\Local\\Temp\\" or RegistryValueData contains "\\Temporary Internet")) or (((RegistryValueData contains ":\\Users\\" and RegistryValueData contains "\\Favorites\\")) or ((RegistryValueData contains ":\\Users\\" and RegistryValueData contains "\\Favourites\\")) or ((RegistryValueData contains ":\\Users\\" and RegistryValueData contains "\\Contacts\\")) or ((RegistryValueData contains ":\\Users\\" and RegistryValueData contains "\\Pictures\\")))))
