// Title: Potentially Suspicious Command Executed Via Run Dialog Box - Registry
// ID: a7df0e9e-91a5-459a-a003-4cde67c2ff5d
// Status: test
// Level: high
// Author: Ahmed Farouk, Nasreddine Bencherchali
// Date: 2024-11-01
// Tags: attack.execution, attack.t1059.001
// Description: Detects execution of commands via the run dialog box on Windows by checking values of the "RunMRU" registry key.
// This technique was seen being abused by threat actors to deceive users into pasting and executing malicious commands, often disguised as CAPTCHA verification steps.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU") and ((((RegistryValueData contains "powershell" or RegistryValueData contains "pwsh")) and ((RegistryValueData contains " -e " or RegistryValueData contains " -ec " or RegistryValueData contains " -en " or RegistryValueData contains " -enc " or RegistryValueData contains " -enco" or RegistryValueData contains "ftp" or RegistryValueData contains "Hidden" or RegistryValueData contains "http" or RegistryValueData contains "iex" or RegistryValueData contains "Invoke-"))) or ((RegistryValueData contains "wmic") and ((RegistryValueData contains "shadowcopy" or RegistryValueData contains "process call create")))))
