// Title: Disabled Windows Defender Eventlog
// ID: fcddca7c-b9c0-4ddf-98da-e1e2d18b0157
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-04
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects the disabling of the Windows Defender eventlog as seen in relation to Lockbit 3.0 infections
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\Microsoft-Windows-Windows Defender/Operational\\Enabled" and RegistryValueData == "DWORD (0x00000000)")
