// Title: Delete Defender Scan ShellEx Context Menu Registry Key
// ID: 72a0369a-2576-4aaf-bfc9-6bb24a574ac6
// Status: experimental
// Level: medium
// Author: Matt Anderson (Huntress)
// Date: 2025-07-11
// Tags: attack.defense-impairment
// Description: Detects deletion of registry key that adds 'Scan with Defender' option in context menu. Attackers may use this to make it harder for users to scan files that are suspicious.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "shellex\\ContextMenuHandlers\\EPP") and not(((FolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" or FolderPath startswith "C:\\Program Files\\Windows Defender\\" or FolderPath startswith "C:\\Program Files (x86)\\Windows Defender\\") and FolderPath endswith "\\MsMpEng.exe")))
