// Title: WinSock2 Autorun Keys Modification
// ID: d6c2ce7e-afb5-4337-9ca4-4b5254ed0565
// Status: test
// Level: medium
// Author: Victor Sergeev, Daniil Yugoslavskiy, Gleb Sukhodolskiy, Timur Zinniatullin, oscd.community, Tim Shelton, frack113 (split)
// Date: 2019-10-25
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
// Description: Detects modification of autostart extensibility point (ASEP) in registry.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\System\\CurrentControlSet\\Services\\WinSock2\\Parameters") and ((RegistryKey contains "\\Protocol_Catalog9\\Catalog_Entries" or RegistryKey contains "\\NameSpace_Catalog5\\Catalog_Entries")) and not(((RegistryValueData == "(Empty)") or (FolderPath == "C:\\Windows\\System32\\MsiExec.exe") or (FolderPath == "C:\\Windows\\syswow64\\MsiExec.exe"))))
