// Title: ScreenSaver Registry Key Set
// ID: 40b6e656-4e11-4c0c-8772-c1cc6dae34ce
// Status: test
// Level: medium
// Author: Jose Luis Sanchez Martinez (@Joseliyo_Jstnk)
// Date: 2022-05-04
// Tags: attack.stealth, attack.t1218.011
// Description: Detects registry key established after masqueraded .scr file execution using Rundll32 through desk.cpl
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((FolderPath endswith "\\rundll32.exe") and (RegistryKey contains "\\Control Panel\\Desktop\\SCRNSAVE.EXE" and RegistryValueData endswith ".scr") and not(((RegistryValueData contains "C:\\Windows\\System32\\" or RegistryValueData contains "C:\\Windows\\SysWOW64\\"))))
