// Title: New ODBC Driver Registered
// ID: 3390fbef-c98d-4bdd-a863-d65ed7c610dd
// Status: test
// Level: low
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-23
// Tags: attack.persistence
// Description: Detects the registration of a new ODBC driver.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\SOFTWARE\\ODBC\\ODBCINST.INI\\" and RegistryKey endswith "\\Driver") and not((RegistryKey contains "\\SQL Server\\" and RegistryValueData == "%WINDIR%\\System32\\SQLSRV32.dll")) and not(((RegistryKey contains "\\Microsoft Access " and RegistryValueData startswith "C:\\Progra" and RegistryValueData endswith "\\ACEODBC.DLL") or (RegistryKey contains "\\Microsoft Excel Driver" and RegistryValueData startswith "C:\\Progra" and RegistryValueData endswith "\\ACEODBC.DLL"))))
