// Title: Microsoft Office Protected View Disabled
// ID: a5c7a43f-6009-4a8c-80c5-32abf1c53ecc
// Status: test
// Level: high
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-06-08
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects changes to Microsoft Office protected view registry keys with which the attacker disables this feature.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey contains "\\SOFTWARE\\Microsoft\\Office\\" and RegistryKey contains "\\Security\\ProtectedView\\")) and ((RegistryValueData == "DWORD (0x00000000)" and (RegistryKey endswith "\\enabledatabasefileprotectedview" or RegistryKey endswith "\\enableforeigntextfileprotectedview")) or (RegistryValueData == "DWORD (0x00000001)" and (RegistryKey endswith "\\DisableAttachementsInPV" or RegistryKey endswith "\\DisableInternetFilesInPV" or RegistryKey endswith "\\DisableIntranetCheck" or RegistryKey endswith "\\DisableUnsafeLocationsInPV"))))
