// Title: IE Change Domain Zone
// ID: 45e112d0-7759-4c2a-aa36-9f8fb79d3393
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-01-22
// Tags: attack.persistence, attack.t1137
// Description: Hides the file extension through modification of the registry
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\Domains\\") and not(((RegistryValueData == "DWORD (0x00000000)" or RegistryValueData == "DWORD (0x00000001)" or RegistryValueData == "(Empty)"))))
