// Title: Suspicious Shell Open Command Registry Modification
// ID: 9e8894c0-0ae0-11ef-9d85-1f2942bec57c
// Status: experimental
// Level: medium
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-01-24
// Tags: attack.privilege-escalation, attack.persistence, attack.t1548.002, attack.t1546.001
// Description: Detects modifications to shell open registry keys that point to suspicious locations typically used by malware for persistence.
// Generally, modifications to the `*\shell\open\command` registry key can indicate an attempt to change the default action for opening files,
// and various UAC bypass or persistence techniques involve modifying these keys to execute malicious scripts or binaries.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (RegistryKey contains "\\shell\\open\\command\\" and (RegistryValueData contains "\\$Recycle.Bin\\" or RegistryValueData contains "\\AppData\\Local\\Temp\\" or RegistryValueData contains "\\Contacts\\" or RegistryValueData contains "\\Music\\" or RegistryValueData contains "\\PerfLogs\\" or RegistryValueData contains "\\Photos\\" or RegistryValueData contains "\\Pictures\\" or RegistryValueData contains "\\Users\\Public\\" or RegistryValueData contains "\\Videos\\" or RegistryValueData contains "\\Windows\\Temp\\" or RegistryValueData contains "%AppData%" or RegistryValueData contains "%LocalAppData%" or RegistryValueData contains "%Temp%" or RegistryValueData contains "%tmp%"))
