// Title: Potential Persistence Via DLLPathOverride
// ID: a1b1fd53-9c4a-444c-bae0-34a330fc7aa8
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-21
// Tags: attack.persistence
// Description: Detects when an attacker adds a new "DLLPathOverride" value to the "Natural Language" key in order to achieve persistence which will get invoked by "SearchIndexer.exe" process
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\SYSTEM\\CurrentControlSet\\Control\\ContentIndex\\Language\\") and ((RegistryKey contains "\\StemmerDLLPathOverride" or RegistryKey contains "\\WBDLLPathOverride" or RegistryKey contains "\\StemmerClass" or RegistryKey contains "\\WBreakerClass")))
