// Title: ETW Logging Disabled In .NET Processes - Sysmon Registry
// ID: bf4fc428-dcc3-4bbd-99fe-2422aeee2544
// Status: test
// Level: high
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-06-05
// Tags: attack.persistence, attack.defense-impairment, attack.t1112, attack.t1685
// Description: Potential adversaries stopping ETW providers recording loaded .NET assemblies.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey endswith "\\COMPlus_ETWEnabled" or RegistryKey endswith "\\COMPlus_ETWFlags") and (RegistryValueData == 0 or RegistryValueData == "DWORD (0x00000000)")) or (RegistryKey endswith "SOFTWARE\\Microsoft\\.NETFramework\\ETWEnabled" and RegistryValueData == "DWORD (0x00000000)"))
