// Title: Potential Persistence Via Event Viewer Events.asp
// ID: a1e11042-a74a-46e6-b07c-c4ce8ecc239b
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-17
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects potential registry persistence technique using the Event Viewer "Events.asp" technique
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey contains "\\Microsoft\\Windows NT\\CurrentVersion\\Event Viewer\\MicrosoftRedirectionProgram" or RegistryKey contains "\\Microsoft\\Windows NT\\CurrentVersion\\Event Viewer\\MicrosoftRedirectionURL")) and not(((RegistryValueData == "(Empty)") or (FolderPath endswith "C:\\WINDOWS\\system32\\svchost.exe" and RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion\\Event Viewer\\MicrosoftRedirectionProgram" and RegistryValueData == "%%SystemRoot%%\\PCHealth\\HelpCtr\\Binaries\\HelpCtr.exe") or (FolderPath endswith "C:\\WINDOWS\\system32\\svchost.exe" and RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion\\Event Viewer\\MicrosoftRedirectionProgramCommandLineParameters" and RegistryValueData == "-url hcp://services/centers/support?topic=%%s") or (RegistryValueData == "http://go.microsoft.com/fwlink/events.asp"))))
