// Title: PowerShell Logging Disabled Via Registry Key Tampering
// ID: fecfd1a1-cc78-4313-a1ea-2ee2e8ec27a7
// Status: test
// Level: high
// Author: frack113
// Date: 2022-04-02
// Tags: attack.stealth, attack.defense-impairment, attack.t1564.001, attack.t1112, attack.persistence
// Description: Detects changes to the registry for the currently logged-in user. In order to disable PowerShell module logging, script block logging or transcription and script execution logging
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\Microsoft\\Windows\\PowerShell\\" or RegistryKey contains "\\Microsoft\\PowerShellCore\\") and (RegistryKey endswith "\\ModuleLogging\\EnableModuleLogging" or RegistryKey endswith "\\ScriptBlockLogging\\EnableScriptBlockLogging" or RegistryKey endswith "\\ScriptBlockLogging\\EnableScriptBlockInvocationLogging" or RegistryKey endswith "\\Transcription\\EnableTranscripting" or RegistryKey endswith "\\Transcription\\EnableInvocationHeader" or RegistryKey endswith "\\EnableScripts") and RegistryValueData == "DWORD (0x00000000)")
