// Title: Macro Enabled In A Potentially Suspicious Document
// ID: a166f74e-bf44-409d-b9ba-ea4b2dd8b3cd
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-21
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects registry changes to Office trust records where the path is located in a potentially suspicious location
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey contains "/AppData/Local/Microsoft/Windows/INetCache/" or RegistryKey contains "/AppData/Local/Temp/" or RegistryKey contains "/PerfLogs/" or RegistryKey contains "C:/Users/Public/" or RegistryKey contains "file:///D:/" or RegistryKey contains "file:///E:/")) and (RegistryKey contains "\\Security\\Trusted Documents\\TrustRecords"))
