// Title: Wow6432Node Windows NT CurrentVersion Autorun Keys Modification
// ID: 480421f9-417f-4d3b-9552-fd2728443ec8
// Status: test
// Level: medium
// Author: Victor Sergeev, Daniil Yugoslavskiy, Gleb Sukhodolskiy, Timur Zinniatullin, oscd.community, Tim Shelton, frack113 (split)
// Date: 2019-10-25
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
// Description: Detects modification of autostart extensibility point (ASEP) in registry.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((((RegistryKey contains "\\Windows\\Appinit_Dlls" or RegistryKey contains "\\Image File Execution Options" or RegistryKey contains "\\Drivers32")) and (RegistryKey contains "\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows NT\\CurrentVersion")) and not(((RegistryValueData == "(Empty)") or (RegistryValueData endswith "\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options") or ((isempty(RegistryValueData) or isnull(RegistryValueData))))))
