// Title: Modify User Shell Folders Startup Value
// ID: 9c226817-8dc9-46c2-a58d-66655aafd7dc
// Status: test
// Level: high
// Author: frack113, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2022-10-01
// Tags: attack.persistence, attack.privilege-escalation, attack.t1547.001
// Description: Detect modification of the User Shell Folders registry values for Startup or Common Startup which could indicate persistence attempts.
// Attackers may modify User Shell Folders registry keys to point to malicious executables or scripts that will be executed during startup.
// This technique is often used to maintain persistence on a compromised system by ensuring that the malicious payload is executed automatically.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey contains "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders" or RegistryKey contains "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders") and (RegistryKey endswith "\\Common Startup" or RegistryKey endswith "\\Startup")) and not((((isempty(RegistryValueData) or isnull(RegistryValueData))) or ((RegistryValueData contains "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup" or RegistryValueData contains "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup")) or ((RegistryValueData contains "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup" or RegistryValueData contains "%%USERPROFILE%%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup")) or ((RegistryValueData contains "C:\\Users\\" and RegistryValueData contains "\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup")))))
