// Title: New TimeProviders Registered With Uncommon DLL Name
// ID: e88a6ddc-74f7-463b-9b26-f69fc0d2ce85
// Status: test
// Level: high
// Author: frack113
// Date: 2022-06-19
// Tags: attack.persistence, attack.privilege-escalation, attack.t1547.003
// Description: Detects processes setting a new DLL in DllName in under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProvider.
// Adversaries may abuse time providers to execute DLLs when the system boots.
// The Windows Time service (W32Time) enables time synchronization across and within domains.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\Services\\W32Time\\TimeProviders" and RegistryKey endswith "\\DllName") and not(((RegistryValueData == "%SystemRoot%\\System32\\vmictimeprovider.dll" or RegistryValueData == "%systemroot%\\system32\\w32time.dll" or RegistryValueData == "C:\\Windows\\SYSTEM32\\w32time.DLL"))))
