// Title: Disable Tamper Protection on Windows Defender
// ID: 93d298a1-d28f-47f1-a468-d971e7796679
// Status: test
// Level: medium
// Author: Austin Songer @austinsonger
// Date: 2021-08-04
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects disabling Windows Defender Tamper Protection
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\Microsoft\\Windows Defender\\Features\\TamperProtection" and RegistryValueData == "DWORD (0x00000000)") and not(((FolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" and FolderPath endswith "\\MsMpEng.exe") or (FolderPath == "C:\\Program Files\\Windows Defender\\MsMpEng.exe"))))
