// Title: Potential SentinelOne Shell Context Menu Scan Command Tampering
// ID: 6c304b02-06e6-402d-8be4-d5833cdf8198
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-03-06
// Tags: attack.persistence
// Description: Detects potentially suspicious changes to the SentinelOne context menu scan command by a process other than SentinelOne.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\shell\\SentinelOneScan\\command\\") and not((((FolderPath endswith "C:\\Program Files\\SentinelOne\\" or FolderPath endswith "C:\\Program Files (x86)\\SentinelOne\\")) or ((RegistryValueData startswith "C:\\Program Files\\SentinelOne\\Sentinel Agent" or RegistryValueData startswith "C:\\Program Files (x86)\\SentinelOne\\Sentinel Agent") and RegistryValueData contains "\\SentinelScanFromContextMenu.exe"))))
