// Title: Potential Attachment Manager Settings Associations Tamper
// ID: a9b6c011-ab69-4ddb-bc0a-c4f21c80ec47
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-01
// Tags: attack.defense-impairment
// Description: Detects tampering with attachment manager settings policies associations to lower the default file type risks (See reference for more information)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Associations\\") and ((RegistryKey endswith "\\DefaultFileTypeRisk" and RegistryValueData == "DWORD (0x00006152)") or (RegistryKey endswith "\\LowRiskFileTypes" and (RegistryValueData contains ".zip;" or RegistryValueData contains ".rar;" or RegistryValueData contains ".exe;" or RegistryValueData contains ".bat;" or RegistryValueData contains ".com;" or RegistryValueData contains ".cmd;" or RegistryValueData contains ".reg;" or RegistryValueData contains ".msi;" or RegistryValueData contains ".htm;" or RegistryValueData contains ".html;"))))
