// Title: Enable Microsoft Dynamic Data Exchange
// ID: 63647769-326d-4dde-a419-b925cc0caf42
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-02-26
// Tags: attack.execution, attack.t1559.002
// Description: Enable Dynamic Data Exchange protocol (DDE) in all supported editions of Microsoft Word or Excel.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey endswith "\\Excel\\Security\\DisableDDEServerLaunch" or RegistryKey endswith "\\Excel\\Security\\DisableDDEServerLookup") and RegistryValueData == "DWORD (0x00000000)") or (RegistryKey endswith "\\Word\\Security\\AllowDDE" and (RegistryValueData == "DWORD (0x00000001)" or RegistryValueData == "DWORD (0x00000002)")))
