// Title: Enable LM Hash Storage
// ID: c420410f-c2d8-4010-856b-dffe21866437
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-12-15
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects changes to the "NoLMHash" registry value in order to allow Windows to store LM Hashes.
// By setting this registry value to "0" (DWORD), Windows will be allowed to store a LAN manager hash of your password in Active Directory and local SAM databases.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (RegistryKey endswith "System\\CurrentControlSet\\Control\\Lsa\\NoLMHash" and RegistryValueData == "DWORD (0x00000000)")
