// Title: Internet Explorer DisableFirstRunCustomize Enabled
// ID: ab567429-1dfb-4674-b6d2-979fd2f9d125
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-16
// Tags: attack.defense-impairment
// Description: Detects changes to the Internet Explorer "DisableFirstRunCustomize" value, which prevents Internet Explorer from running the first run wizard the first time a user starts the browser after installing Internet Explorer or Windows.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((RegistryKey endswith "\\Microsoft\\Internet Explorer\\Main\\DisableFirstRunCustomize" and (RegistryValueData == "DWORD (0x00000001)" or RegistryValueData == "DWORD (0x00000002)")) and not(((FolderPath == "C:\\Windows\\explorer.exe" or FolderPath == "C:\\Windows\\System32\\ie4uinit.exe"))) and not((((FolderPath contains "\\Temp\\" and FolderPath contains "\\.cr\\avira_") and RegistryValueData contains "DWORD (0x00000001)") or ((FolderPath == "C:\\Program Files (x86)\\Foxit Software\\Foxit PDF Reader\\FoxitPDFReader.exe" or FolderPath == "C:\\Program Files\\Foxit Software\\Foxit PDF Reader\\FoxitPDFReader.exe") and RegistryValueData contains "DWORD (0x00000001)"))))
