// Title: Suspicious Camera and Microphone Access
// ID: 62120148-6b7a-42be-8b91-271c04e281a3
// Status: test
// Level: high
// Author: Den Iuzvyk
// Date: 2020-06-07
// Tags: attack.collection, attack.t1125, attack.t1123
// Description: Detects Processes accessing the camera and microphone from suspicious folder
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\" and RegistryKey contains "\\NonPackaged")) and ((RegistryKey contains "microphone" or RegistryKey contains "webcam")) and ((RegistryKey contains ":#Windows#Temp#" or RegistryKey contains ":#$Recycle.bin#" or RegistryKey contains ":#Temp#" or RegistryKey contains ":#Users#Public#" or RegistryKey contains ":#Users#Default#" or RegistryKey contains ":#Users#Desktop#")))
