// Title: ClickOnce Trust Prompt Tampering
// ID: ac9159cc-c364-4304-8f0a-d63fc1a0aabb
// Status: test
// Level: medium
// Author: @SerkinValery, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-12
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects changes to the ClickOnce trust prompt registry key in order to enable an installation from different locations such as the Internet.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (RegistryKey contains "\\SOFTWARE\\MICROSOFT\\.NETFramework\\Security\\TrustManager\\PromptingLevel\\" and (RegistryKey endswith "\\Internet" or RegistryKey endswith "\\LocalIntranet" or RegistryKey endswith "\\MyComputer" or RegistryKey endswith "\\TrustedSites" or RegistryKey endswith "\\UntrustedSites") and RegistryValueData == "Enabled")
