// Title: Potentially Suspicious Desktop Background Change Via Registry
// ID: 85b88e05-dadc-430b-8a9e-53ff1cd30aae
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Stephen Lincoln @slincoln-aiq (AttackIQ)
// Date: 2023-12-21
// Tags: attack.persistence, attack.impact, attack.defense-impairment, attack.t1112, attack.t1491.001
// Description: Detects registry value settings that would replace the user's desktop background.
// This is a common technique used by malware to change the desktop background to a ransom note or other image.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey contains "Control Panel\\Desktop" or RegistryKey contains "CurrentVersion\\Policies\\ActiveDesktop" or RegistryKey contains "CurrentVersion\\Policies\\System")) and ((RegistryKey endswith "NoChangingWallpaper" and RegistryValueData == "DWORD (0x00000001)") or (RegistryKey endswith "\\Wallpaper") or (RegistryKey endswith "\\WallpaperStyle" and RegistryValueData == "2")) and not(((RegistryKey endswith "\\Control Panel\\Desktop\\Wallpaper" and RegistryValueData == "(Empty)") or (FolderPath endswith "C:\\Windows\\Explorer.EXE") or (FolderPath endswith "\\svchost.exe"))) and not(((FolderPath == "C:\\Program Files\\Amazon\\EC2Launch\\EC2Launch.exe" or FolderPath == "C:\\Program Files (x86)\\Amazon\\EC2Launch\\EC2Launch.exe") and RegistryKey endswith "\\Control Panel\\Desktop\\Wallpaper")))
