// Title: Windows Event Log Access Tampering Via Registry
// ID: ba226dcf-d390-4642-b9af-b534872f1156
// Status: experimental
// Level: high
// Author: X__Junior
// Date: 2025-01-16
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-impairment, attack.t1547.001, attack.t1112
// Description: Detects changes to the Windows EventLog channel permission values. It focuses on changes to the Security Descriptor Definition Language (SDDL) string, as modifications to these values can restrict access to specific users or groups, potentially aiding in defense evasion by controlling who can view or modify a event log channel. Upon execution, the user shouldn't be able to access the event log channel via the event viewer or via utilities such as "Get-EventLog" or "wevtutil".
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((RegistryKey contains "\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\" and RegistryKey endswith "\\CustomSD") or ((RegistryKey contains "\\Policies\\Microsoft\\Windows\\EventLog\\" or RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels") and RegistryKey endswith "\\ChannelAccess")) and ((RegistryValueData contains "D:(D;") or ((RegistryValueData contains "D:(" and RegistryValueData contains ")(D;"))) and not(((FolderPath startswith "C:\\Windows\\WinSxS\\" and FolderPath endswith "\\TiWorker.exe") or (FolderPath == "C:\\Windows\\servicing\\TrustedInstaller.exe"))) and not(((FolderPath == "") or ((isempty(FolderPath) or isnull(FolderPath))))))
