// Title: Custom File Open Handler Executes PowerShell
// ID: 7530b96f-ad8e-431d-a04d-ac85cc461fdc
// Status: test
// Level: high
// Author: CD_R0M_
// Date: 2022-06-11
// Tags: attack.stealth, attack.t1202
// Description: Detects the abuse of custom file open handler, executing powershell
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (RegistryKey contains "shell\\open\\command\\" and (RegistryValueData contains "powershell" and RegistryValueData contains "-command"))
