// Title: Remote Registry Recon
// ID: d8ffe17e-04be-4886-beb9-c1dd1944b9a8
// Status: test
// Level: high
// Author: Sagie Dulce, Dekel Paz
// Date: 2022-01-01
// Tags: attack.discovery
// Description: Detects remote RPC calls to collect information
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((EventLog == "RPCFW" and EventID == 3 and InterfaceUuid == "338cd001-2244-31f1-aaaa-900038001003") and not(((OpNum == 6 or OpNum == 7 or OpNum == 8 or OpNum == 13 or OpNum == 18 or OpNum == 19 or OpNum == 21 or OpNum == 22 or OpNum == 23 or OpNum == 35))))
