// Title: Java Payload Strings
// ID: 583aa0a2-30b1-4d62-8bf3-ab73689efe6c
// Status: test
// Level: high
// Author: frack113, Harjot Singh, "@cyb3rjy0t" (update)
// Date: 2022-06-04
// Tags: cve.2022-26134, cve.2021-26084, attack.initial-access, attack.t1190
// Description: Detects possible Java payloads in web access logs
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (* has "%24%7B%28%23a%3D%40" or * has "${(#a=@" or * has "%24%7B%40java" or * has "${@java" or * has "u0022java" or * has "%2F%24%7B%23" or * has "/${#" or * has "new+java." or * has "getRuntime().exec(" or * has "getRuntime%28%29.exec%28")
