// Title: Windows Webshell Strings
// ID: 7ff9db12-1b94-4a79-ba68-a2402c5d6729
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2017-02-19
// Tags: attack.persistence, attack.t1505.003
// Description: Detects common commands used in Windows webshells
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((* has "=whoami" or * has "=net%20user" or * has "=net+user" or * has "=net%2Buser" or * has "=cmd%20/c%" or * has "=cmd+/c+" or * has "=cmd%2B/c%" or * has "=cmd%20/r%" or * has "=cmd+/r+" or * has "=cmd%2B/r%" or * has "=cmd%20/k%" or * has "=cmd+/k+" or * has "=cmd%2B/k%" or * has "=powershell%" or * has "=powershell+" or * has "=tasklist%" or * has "=tasklist+" or * has "=wmic%" or * has "=wmic+" or * has "=ssh%" or * has "=ssh+" or * has "=python%" or * has "=python+" or * has "=python3%" or * has "=python3+" or * has "=ipconfig" or * has "=wget%" or * has "=wget+" or * has "=curl%" or * has "=curl+" or * has "=certutil" or * has "=copy%20%5C%5C" or * has "=dsquery%" or * has "=dsquery+" or * has "=nltest%" or * has "=nltest+") and (cs-method == "GET"))
