// Title: Webshell ReGeorg Detection Via Web Logs
// ID: 2ea44a60-cfda-11ea-87d0-0242ac130003
// Status: test
// Level: high
// Author: Cian Heasley
// Date: 2020-08-04
// Tags: attack.persistence, attack.t1505.003
// Description: Certain strings in the uri_query field when combined with null referer and null user agent can indicate activity associated with the webshell ReGeorg.
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where (((cs-uri-query contains "cmd=read" or cs-uri-query contains "connect&target" or cs-uri-query contains "cmd=connect" or cs-uri-query contains "cmd=disconnect" or cs-uri-query contains "cmd=forward")) and ((isempty(cs-referer) or isnull(cs-referer)) and (isempty(cs-user-agent) or isnull(cs-user-agent)) and cs-method == "POST"))
