// Title: Server Side Template Injection Strings
// ID: ada3bc4f-f0fd-42b9-ba91-e105e8af7342
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-14
// Tags: attack.stealth, attack.t1221
// Description: Detects SSTI attempts sent via GET requests in access logs
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((cs-method == "GET") and (* has "={{" or * has "=%7B%7B" or * has "=${" or * has "=$%7B" or * has "=<%=" or * has "=%3C%25=" or * has "=@(" or * has "freemarker.template.utility.Execute" or * has ".getClass().forName('javax.script.ScriptEngineManager')" or * has "T(org.apache.commons.io.IOUtils)") and not((sc-status == 404)))
