// Title: PsExec Service Installation
// ID: 42c575ea-e41e-41f1-b248-8093c3e82a28
// Status: test
// Level: medium
// Author: Thomas Patzke
// Date: 2017-06-12
// Tags: attack.execution, attack.t1569.002, attack.s0029
// Description: Detects PsExec service installation and execution events
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Provider_Name == "Service Control Manager" and EventID == 7045) and ((ServiceName == "PSEXESVC") or (ImagePath endswith "\\PSEXESVC.exe")))
