// Title: Suspicious Access to Sensitive File Extensions
// ID: 91c945bc-2ad1-4799-a591-4d00198a1215
// Status: test
// Level: medium
// Author: Samir Bousseaden
// Date: 2019-04-03
// Tags: attack.collection, attack.t1039
// Description: Detects known sensitive file extensions accessed on a network share
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (EventID == 5145 and (RelativeTargetName endswith ".bak" or RelativeTargetName endswith ".dmp" or RelativeTargetName endswith ".edb" or RelativeTargetName endswith ".kirbi" or RelativeTargetName endswith ".msg" or RelativeTargetName endswith ".nsf" or RelativeTargetName endswith ".nst" or RelativeTargetName endswith ".oab" or RelativeTargetName endswith ".ost" or RelativeTargetName endswith ".pst" or RelativeTargetName endswith ".rdp"))
