// Title: Restricted Software Access By SRP
// ID: b4c8da4a-1c12-46b0-8a2b-0a8521d03442
// Status: test
// Level: high
// Author: frack113
// Date: 2023-01-12
// Tags: attack.lateral-movement, attack.execution, attack.t1072
// Description: Detects restricted access to applications by the Software Restriction Policies (SRP) policy
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Provider_Name == "Microsoft-Windows-SoftwareRestrictionPolicies" and (EventID == 865 or EventID == 866 or EventID == 867 or EventID == 868 or EventID == 882))
