// Title: Suspicious Application Installed
// ID: 83c161b6-ca67-4f33-8ad0-644a0737cf07
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-14
// Tags: attack.execution
// Description: Detects suspicious application installed by looking at the added shortcut to the app resolver cache
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((EventID == 28115 and (Name contains "Zenmap" or Name contains "AnyDesk" or Name contains "wireshark" or Name contains "openvpn")) or (EventID == 28115 and (AppID contains "zenmap.exe" or AppID contains "prokzult ad" or AppID contains "wireshark" or AppID contains "openvpn")))
