// Title: Kerberos Manipulation
// ID: f7644214-0eb0-4ace-9455-331ec4c09253
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2017-02-10
// Tags: attack.credential-access, attack.t1212
// Description: Detects failed Kerberos TGT issue operation. This can be a sign of manipulations of TGT messages by an attacker.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((EventID == 675 or EventID == 4768 or EventID == 4769 or EventID == 4771) and (Status == "0x9" or Status == "0xA" or Status == "0xB" or Status == "0xF" or Status == "0x10" or Status == "0x11" or Status == "0x13" or Status == "0x14" or Status == "0x1A" or Status == "0x1F" or Status == "0x21" or Status == "0x22" or Status == "0x23" or Status == "0x24" or Status == "0x26" or Status == "0x27" or Status == "0x28" or Status == "0x29" or Status == "0x2C" or Status == "0x2D" or Status == "0x2E" or Status == "0x2F" or Status == "0x31" or Status == "0x32" or Status == "0x3E" or Status == "0x3F" or Status == "0x40" or Status == "0x41" or Status == "0x43" or Status == "0x44"))
