// Title: DPAPI Domain Backup Key Extraction
// ID: 4ac1f50b-3bd0-4968-902d-868b4647937e
// Status: test
// Level: high
// Author: Roberto Rodriguez @Cyb3rWard0g
// Date: 2019-06-20
// Tags: attack.credential-access, attack.t1003.004
// Description: Detects tools extracting LSA secret DPAPI domain backup key from Domain Controllers
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (EventID == 4662 and ObjectType == "SecretObject" and AccessMask == "0x2" and ObjectName contains "BCKUPKEY")
