// Title: Meterpreter or Cobalt Strike Getsystem Service Installation - System
// ID: 843544a7-56e0-4dcc-a44f-5cc266dd97d6
// Status: test
// Level: high
// Author: Teymur Kheirkhabarov, Ecco, Florian Roth (Nextron Systems)
// Date: 2019-10-26
// Tags: attack.privilege-escalation, attack.stealth, attack.t1134.001, attack.t1134.002
// Description: Detects the use of getsystem Meterpreter/Cobalt Strike command by detecting a specific service installation
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Provider_Name == "Service Control Manager" and EventID == 7045) and (((ImagePath contains "/c" and ImagePath contains "echo" and ImagePath contains "\\pipe\\") and (ImagePath contains "cmd" or ImagePath contains "%COMSPEC%")) or ((ImagePath contains "rundll32" and ImagePath contains ".dll,a" and ImagePath contains "/p:")) or (ImagePath startswith "\\\\\\\\127.0.0.1\\\\ADMIN$\\")))
