// Title: Invoke-Obfuscation Via Use Rundll32 - System
// ID: 641a4bfb-c017-44f7-800c-2aee0184ce9b
// Status: test
// Level: high
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-09
// Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
// Description: Detects Obfuscated Powershell via use Rundll32 in Scripts
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Provider_Name == "Service Control Manager" and EventID == 7045 and (ImagePath contains "&&" and ImagePath contains "rundll32" and ImagePath contains "shell32.dll" and ImagePath contains "shellexec_rundll") and (ImagePath contains "value" or ImagePath contains "invoke" or ImagePath contains "comspec" or ImagePath contains "iex"))
