// Title: Active Directory User Backdoors
// ID: 300bac00-e041-4ee2-9c36-e262656a6ecc
// Status: test
// Level: high
// Author: @neu5ron
// Date: 2017-04-13
// Tags: attack.privilege-escalation, attack.t1098, attack.persistence
// Description: Detects scenarios where one can control another users or computers account without having to use their credentials.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((EventID == 4738) and not((((AllowedToDelegateTo == "" or AllowedToDelegateTo == "-")) or ((isempty(AllowedToDelegateTo) or isnull(AllowedToDelegateTo)))))) or ((EventID == 5136 and AttributeLDAPDisplayName == "msDS-AllowedToDelegateTo") or (EventID == 5136 and ObjectClass == "user" and AttributeLDAPDisplayName == "servicePrincipalName") or (EventID == 5136 and AttributeLDAPDisplayName == "msDS-AllowedToActOnBehalfOfOtherIdentity")))
