// Title: All Rules Have Been Deleted From The Windows Firewall Configuration
// ID: 79609c82-a488-426e-abcf-9f341a39365d
// Status: test
// Level: high
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-17
// Tags: attack.defense-impairment, attack.t1686.003
// Description: Detects when a all the rules have been deleted from the Windows Defender Firewall configuration
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((EventID == 2033 or EventID == 2059)) and not((ModifyingApplication endswith ":\\Windows\\System32\\svchost.exe")) and not(((ModifyingApplication contains ":\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" and ModifyingApplication contains "\\MsMpEng.exe"))))
