// Title: Remote Access Tool Services Have Been Installed - System
// ID: 1a31b18a-f00c-4061-9900-f735b96c99fc
// Status: test
// Level: medium
// Author: Connor Martin, Nasreddine Bencherchali
// Date: 2022-12-23
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1543.003, attack.t1569.002
// Description: Detects service installation of different remote access tools software. These software are often abused by threat actors to perform
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Provider_Name == "Service Control Manager" and (EventID == 7045 or EventID == 7036) and (ServiceName contains "AmmyyAdmin" or ServiceName contains "Atera" or ServiceName contains "BASupportExpressSrvcUpdater" or ServiceName contains "BASupportExpressStandaloneService" or ServiceName contains "chromoting" or ServiceName contains "GoToAssist" or ServiceName contains "GoToMyPC" or ServiceName contains "jumpcloud" or ServiceName contains "LMIGuardianSvc" or ServiceName contains "LogMeIn" or ServiceName contains "monblanking" or ServiceName contains "Parsec" or ServiceName contains "RManService" or ServiceName contains "RPCPerformanceService" or ServiceName contains "RPCService" or ServiceName contains "SplashtopRemoteService" or ServiceName contains "SSUService" or ServiceName contains "TeamViewer" or ServiceName contains "TightVNC" or ServiceName contains "vncserver" or ServiceName contains "Zoho"))
