// Title: Credential Dumping Tools Service Execution - System
// ID: 4976aa50-8f41-45c6-8b15-ab3fc10e79ed
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Teymur Kheirkhabarov, Daniil Yugoslavskiy, oscd.community
// Date: 2017-03-05
// Tags: attack.credential-access, attack.execution, attack.t1003.001, attack.t1003.002, attack.t1003.004, attack.t1003.005, attack.t1003.006, attack.t1569.002, attack.s0005
// Description: Detects well-known credential dumping tools execution via service execution events
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Provider_Name == "Service Control Manager" and EventID == 7045 and (ImagePath contains "cachedump" or ImagePath contains "dumpsvc" or ImagePath contains "fgexec" or ImagePath contains "gsecdump" or ImagePath contains "mimidrv" or ImagePath contains "pwdump" or ImagePath contains "servpw"))
