// Title: DiagTrackEoP Default Login Username
// ID: 2111118f-7e46-4fc8-974a-59fd8ec95196
// Status: test
// Level: critical
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-03
// Tags: attack.privilege-escalation
// Description: Detects the default "UserName" used by the DiagTrackEoP POC
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (EventID == 4624 and LogonType == 9 and TargetOutboundUserName == "thisisnotvaliduser")
