// Title: Unsigned or Unencrypted SMB Connection to Share Established
// ID: 8d91f6e4-9f3b-4c21-ae41-2c5b7d9f7a12
// Status: experimental
// Level: medium
// Author: Mohamed Abdelghani
// Date: 2025-10-19
// Tags: attack.lateral-movement, attack.t1021.002
// Description: Detects SMB server connections to shares without signing or encryption enabled.
// This could indicate potential lateral movement activity using unsecured SMB shares.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((EventID == 4000 and (ShareName contains "IPC$" or ShareName contains "ADMIN$" or ShareName contains "C$")) and ((SigningUsed == "false") or (EncyptionUsed == "false"))) and not((((ipv4_is_in_range(ClientAddress, "127.0.0.0/8") or ipv4_is_in_range(ClientAddress, "169.254.0.0/16") or ipv4_is_in_range(ClientAddress, "::1/128") or ipv4_is_in_range(ClientAddress, "fe80::/10") or ipv4_is_in_range(ClientAddress, "fc00::/7"))) or ((ClientAddress contains "00000000000000000000000000000001" or ClientAddress contains "FE80000000000000" or ClientAddress contains "FC00000000000000" or ClientAddress contains "0200????7F" or ClientAddress contains "0200????A9FE")))))
