// Title: Invoke-Obfuscation VAR+ Launcher - Security
// ID: dcf2db1f-f091-425b-a821-c05875b8925a
// Status: test
// Level: high
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-15
// Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
// Description: Detects Obfuscated use of Environment Variables to execute PowerShell
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (EventID == 4697 and (ServiceFileName contains "cmd" and ServiceFileName contains "\"set" and ServiceFileName contains "-f") and (ServiceFileName contains "/c" or ServiceFileName contains "/r"))
