// Title: Anydesk Remote Access Software Service Installation
// ID: 530a6faa-ff3d-4022-b315-50828e77eef5
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2022-08-11
// Tags: attack.persistence
// Description: Detects the installation of the anydesk software service. Which could be an indication of anydesk abuse if you the software isn't already used.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Provider_Name == "Service Control Manager" and EventID == 7045) and (((ServiceName contains "AnyDesk" and ServiceName contains "Service")) or (ImagePath contains "AnyDesk")))
