// Title: MSSQL Destructive Query
// ID: 00321fee-ca72-4cce-b011-5415af3b9960
// Status: experimental
// Level: medium
// Author: Daniel Degasperi '@d4ns4n_'
// Date: 2025-06-04
// Tags: attack.exfiltration, attack.impact, attack.t1485
// Description: Detects the invocation of MS SQL transactions that are destructive towards table or database data, such as "DROP TABLE" or "DROP DATABASE".
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (Provider_Name == "MSSQLSERVER$AUDIT" and EventID == 33205 and (Data contains "statement:TRUNCATE TABLE" or Data contains "statement:DROP TABLE" or Data contains "statement:DROP DATABASE"))
