// Title: Potentially Suspicious Explicit Credential Local Logon
// ID: e3c6d245-7b8f-4e2a-c17f-a9d0e5b38f62
// Status: experimental
// Level: medium
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-07-23
// Tags: attack.privilege-escalation, attack.stealth, attack.t1134, attack.t1134.003
// Description: Detects potentially suspicious explicit credential logon events where the user
// is trying to logon with explicit credentials (username and password) that are
// different from the current user context. It might indicate an attacker attempting
// to escalate privileges after obtaining credentials for a different user account.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (((EventID == 4648) and ((TargetServerName == "localhost") or (TargetInfo == "localhost") or ((IpAddress == "127.0.0.1" or IpAddress == "::1")))) and not(((SubjectUserName endswith "$") or ((ProcessName startswith "C:\\Program Files\\" or ProcessName startswith "C:\\Program Files (x86)\\")) or (SubjectUserName=TargetUserName) or ((ProcessName startswith "C:\\Windows\\System32\\" or ProcessName startswith "C:\\Windows\\SysWOW64\\" or ProcessName startswith "C:\\Windows\\WinSxS\\")))))
