// Title: New Module Module Added To IIS Server
// ID: dd857d3e-0c6e-457b-9b48-e82ae7f86bd7
// Status: test
// Level: medium
// Author: frack113
// Date: 2024-10-06
// Tags: attack.persistence, attack.defense-impairment, attack.t1685.001, attack.t1505.004
// Description: Detects the addition of a new module to an IIS server.
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((EventID == 29 and Configuration contains "/system.webServer/modules/add") and not((((NewValue == "AnonymousAuthenticationModule" or NewValue == "CustomErrorModule" or NewValue == "DefaultDocumentModule" or NewValue == "DirectoryListingModule" or NewValue == "FileCacheModule" or NewValue == "HttpCacheModule" or NewValue == "HttpLoggingModule" or NewValue == "ProtocolSupportModule" or NewValue == "RequestFilteringModule" or NewValue == "StaticCompressionModule" or NewValue == "StaticFileModule" or NewValue == "TokenCacheModule" or NewValue == "UriCacheModule")) or (NewValue == ""))))
