// Title: MSI Installation From Suspicious Locations
// ID: c7c8aa1c-5aff-408e-828b-998e3620b341
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-31
// Tags: attack.execution
// Description: Detects MSI package installation from suspicious locations
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((Provider_Name == "MsiInstaller" and (EventID == 1040 or EventID == 1042) and (Data contains ":\\Windows\\TEMP\\" or Data contains "\\\\\\\\" or Data contains "\\Desktop\\" or Data contains "\\PerfLogs\\" or Data contains "\\Users\\Public\\")) and not(((Data contains "C:\\Windows\\TEMP\\UpdHealthTools.msi") or (Data contains "\\AppData\\Local\\Temp\\WinGet\\"))))
