// Title: Mimikatz Use
// ID: 06d71506-7beb-4f22-8888-e2e5e2ca7fd8
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), David ANDRE (additional keywords)
// Date: 2017-01-10
// Tags: attack.s0002, attack.lateral-movement, attack.credential-access, car.2013-07-001, car.2019-04-004, attack.t1003.002, attack.t1003.004, attack.t1003.001, attack.t1003.006
// Description: This method detects mimikatz keywords in different Eventlogs (some of them only appear in older Mimikatz version that are however still used by different threat groups)
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where ((* has "dpapi::masterkey" or * has "eo.oe.kiwi" or * has "event::clear" or * has "event::drop" or * has "gentilkiwi.com" or * has "kerberos::golden" or * has "kerberos::ptc" or * has "kerberos::ptt" or * has "kerberos::tgt" or * has "Kiwi Legit Printer" or * has "lsadump::" or * has "mimidrv.sys" or * has "\\mimilib.dll" or * has "misc::printnightmare" or * has "misc::shadowcopies" or * has "misc::skeleton" or * has "privilege::backup" or * has "privilege::debug" or * has "privilege::driver" or * has "sekurlsa::") and not((EventID == 15)))
