// Title: NetNTLM Downgrade Attack
// ID: d3abac66-f11c-4ed0-8acb-50cc29c97eed
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), wagga
// Date: 2018-03-20
// Tags: attack.persistence, attack.defense-impairment, attack.t1685, attack.t1112
// Description: Detects NetNTLM downgrade attack
// Converted by: Sigma Universal SIEM/EDR CLI

DeviceProcessEvents | where (EventID == 4657 and (ObjectName contains "\\REGISTRY\\MACHINE\\SYSTEM" and ObjectName contains "ControlSet" and ObjectName contains "\\Control\\Lsa") and (ObjectValueName == "LmCompatibilityLevel" or ObjectValueName == "NtlmMinClientSec" or ObjectValueName == "RestrictSendingNTLMTraffic"))
