// Title: Transferring Files with Credential Data via Network Shares - Zeek
// ID: 2e69f167-47b5-4ae7-a390-47764529eff5
// Status: test
// Level: medium
// Author: @neu5ron, Teymur Kheirkhabarov, oscd.community
// Date: 2020-04-02
// Tags: attack.credential-access, attack.t1003.002, attack.t1003.001, attack.t1003.003
// Description: Transferring files with well-known filenames (sensitive files with credential data) using network shares
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((name == "\\mimidrv" or name == "\\lsass" or name == "\\windows\\minidump\\" or name == "\\hiberfil" or name == "\\sqldmpr" or name == "\\sam" or name == "\\ntds.dit" or name == "\\security"))
