// Title: First Time Seen Remote Named Pipe - Zeek
// ID: 021310d9-30a6-480a-84b7-eaa69aeb92bb
// Status: test
// Level: high
// Author: Samir Bousseaden, @neu5ron, Tim Shelton
// Date: 2020-04-02
// Tags: attack.lateral-movement, attack.t1021.002
// Description: This detection excludes known namped pipes accessible remotely and notify on newly observed ones, may help to detect lateral movement and remote exec using named pipes
// Converted by: Sigma Universal SIEM/EDR CLI

SecurityEvent | where ((path == "\\\\\\\\\\*\\\\IPC$") and not((* has "samr" or * has "lsarpc" or * has "winreg" or * has "netlogon" or * has "srvsvc" or * has "protected_storage" or * has "wkssvc" or * has "browser" or * has "netdfs" or * has "svcctl" or * has "spoolss" or * has "ntsvcs" or * has "LSM_API_service" or * has "HydraLsPipe" or * has "TermSrv_API_service" or * has "MsFteWds")))
