// Title: Creation Of a Suspicious ADS File Outside a Browser Download
// ID: 573df571-a223-43bc-846e-3f98da481eca
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-10-22
// Tags: attack.stealth
// Description: Detects the creation of a suspicious ADS (Alternate Data Stream) file by software other than browsers
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((Contents startswith "[ZoneTransfer]  ZoneId=3" and action_file_path endswith ":Zone.Identifier" and (action_file_path contains ".exe" or action_file_path contains ".scr" or action_file_path contains ".bat" or action_file_path contains ".cmd" or action_file_path contains ".docx" or action_file_path contains ".hta" or action_file_path contains ".jse" or action_file_path contains ".lnk" or action_file_path contains ".pptx" or action_file_path contains ".ps" or action_file_path contains ".reg" or action_file_path contains ".sct" or action_file_path contains ".vb" or action_file_path contains ".wsc" or action_file_path contains ".wsf" or action_file_path contains ".xlsx")) and not (((action_process_image_path endswith "\\brave.exe") or ((action_process_image_path = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" or action_process_image_path = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe")) or ((action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\") or (action_process_image_path endswith "\\WindowsApps\\MicrosoftEdge.exe") or ((action_process_image_path = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" or action_process_image_path = "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe"))) or ((action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft\\EdgeCore\\" or action_process_image_path startswith "C:\\Program Files\\Microsoft\\EdgeCore\\") and (action_process_image_path endswith "\\msedge.exe" or action_process_image_path endswith "\\msedgewebview2.exe")) or ((action_process_image_path = "C:\\Program Files\\Mozilla Firefox\\firefox.exe" or action_process_image_path = "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe")) or ((action_process_image_path = "C:\\Program Files (x86)\\Internet Explorer\\iexplore.exe" or action_process_image_path = "C:\\Program Files\\Internet Explorer\\iexplore.exe")) or (action_process_image_path endswith "\\maxthon.exe") or (action_process_image_path endswith "\\opera.exe") or (action_process_image_path endswith "\\safari.exe") or (action_process_image_path endswith "\\seamonkey.exe") or (action_process_image_path startswith "C:\\Program Files\\WindowsApps\\Microsoft.ScreenSketch_" and action_process_image_path endswith "\\SnippingTool\\SnippingTool.exe" and action_file_path startswith "C:\\Users\\" and (action_file_path contains "\\AppData\\Local\\Packages\\Microsoft.ScreenSketch_" and action_file_path contains "\\TempState\\Screenshot ") and action_file_path endswith ".png:Zone.Identifier") or (action_process_image_path endswith "\\vivaldi.exe") or (action_process_image_path endswith "\\whale.exe"))))
