// Title: Legitimate Application Writing Files In Uncommon Location
// ID: 1cf465a1-2609-4c15-9b66-c32dbe4bfd67
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-12-10
// Tags: attack.stealth, attack.t1218, attack.command-and-control, attack.t1105
// Description: Detects legitimate applications writing any type of file to uncommon or suspicious locations that are not typical for application data storage or execution.
// Adversaries may leverage legitimate applications (Living off the Land Binaries - LOLBins) to drop or download malicious files to uncommon locations on the system to evade detection by security solutions.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_path endswith "\\eqnedt32.exe" or action_process_image_path endswith "\\wordpad.exe" or action_process_image_path endswith "\\wordview.exe" or action_process_image_path endswith "\\cmdl32.exe" or action_process_image_path endswith "\\certutil.exe" or action_process_image_path endswith "\\certoc.exe" or action_process_image_path endswith "\\CertReq.exe" or action_process_image_path endswith "\\bitsadmin.exe" or action_process_image_path endswith "\\Desktopimgdownldr.exe" or action_process_image_path endswith "\\esentutl.exe" or action_process_image_path endswith "\\expand.exe" or action_process_image_path endswith "\\extrac32.exe" or action_process_image_path endswith "\\replace.exe" or action_process_image_path endswith "\\mshta.exe" or action_process_image_path endswith "\\ftp.exe" or action_process_image_path endswith "\\Ldifde.exe" or action_process_image_path endswith "\\RdrCEF.exe" or action_process_image_path endswith "\\hh.exe" or action_process_image_path endswith "\\finger.exe" or action_process_image_path endswith "\\findstr.exe")) and ((action_file_path contains ":\\Perflogs" or action_file_path contains ":\\ProgramData\\" or action_file_path contains ":\\Temp\\" or action_file_path contains ":\\Users\\Public\\" or action_file_path contains ":\\Windows\\" or action_file_path contains "\\$Recycle.Bin\\" or action_file_path contains "\\AppData\\Local\\" or action_file_path contains "\\AppData\\Roaming\\" or action_file_path contains "\\Contacts\\" or action_file_path contains "\\Desktop\\" or action_file_path contains "\\Favorites\\" or action_file_path contains "\\Favourites\\" or action_file_path contains "\\inetpub\\wwwroot\\" or action_file_path contains "\\Music\\" or action_file_path contains "\\Pictures\\" or action_file_path contains "\\Start Menu\\Programs\\Startup\\" or action_file_path contains "\\Users\\Default\\" or action_file_path contains "\\Videos\\")))
