// Title: Windows Binaries Write Suspicious Extensions
// ID: b8fd0e93-ff58-4cbd-8f48-1c114e342e62
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-12
// Tags: attack.stealth, attack.t1036
// Description: Detects Windows executables that write files with suspicious extensions
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_path endswith "\\csrss.exe" or action_process_image_path endswith "\\lsass.exe" or action_process_image_path endswith "\\RuntimeBroker.exe" or action_process_image_path endswith "\\sihost.exe" or action_process_image_path endswith "\\smss.exe" or action_process_image_path endswith "\\wininit.exe" or action_process_image_path endswith "\\winlogon.exe") and (action_file_path endswith ".bat" or action_file_path endswith ".dll" or action_file_path endswith ".exe" or action_file_path endswith ".hta" or action_file_path endswith ".iso" or action_file_path endswith ".ps1" or action_file_path endswith ".txt" or action_file_path endswith ".vbe" or action_file_path endswith ".vbs")) or ((action_process_image_path endswith "\\dllhost.exe" or action_process_image_path endswith "\\rundll32.exe" or action_process_image_path endswith "\\svchost.exe") and (action_file_path endswith ".bat" or action_file_path endswith ".hta" or action_file_path endswith ".iso" or action_file_path endswith ".ps1" or action_file_path endswith ".vbe" or action_file_path endswith ".vbs"))) and not (((action_process_image_path = "C:\\Windows\\System32\\dllhost.exe" and (action_file_path contains ":\\Users\\" and action_file_path contains "\\AppData\\Local\\Temp\\__PSScriptPolicyTest_") and action_file_path endswith ".ps1") or (action_process_image_path = "C:\\Windows\\system32\\svchost.exe" and (action_file_path contains "C:\\Program Files\\WindowsApps\\Clipchamp" and action_file_path contains ".ps1")) or ((action_process_image_path = "C:\\Windows\\system32\\svchost.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\svchost.exe") and (action_file_path startswith "C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview" or action_file_path startswith "C:\\Program Files (x86)\\WindowsApps\\Microsoft.PowerShellPreview") and action_file_path endswith ".ps1") or (action_process_image_path = "C:\\Windows\\system32\\svchost.exe" and (action_file_path contains "C:\\Windows\\System32\\GroupPolicy\\DataStore\\" and action_file_path contains "\\sysvol\\" and action_file_path contains "\\Policies\\" and action_file_path contains "\\Machine\\Scripts\\Startup\\") and (action_file_path endswith ".ps1" or action_file_path endswith ".bat")))))
