// Title: PSScriptPolicyTest Creation By Uncommon Process
// ID: 1027d292-dd87-4a1a-8701-2abe04d7783c
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-01
// Tags: attack.stealth
// Description: Detects the creation of the "PSScriptPolicyTest" PowerShell script by an uncommon process. This file is usually generated by Microsoft Powershell to test against Applocker.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((action_file_path contains "__PSScriptPolicyTest_") and not ((((action_process_image_path = "C:\\Windows\\System32\\dsac.exe" or action_process_image_path = "C:\\Windows\\System32\\sdiagnhost.exe" or action_process_image_path = "C:\\Windows\\System32\\ServerManager.exe" or action_process_image_path = "C:\\Windows\\System32\\wsmprovhost.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\sdiagnhost.exe")) or ((action_process_image_path = "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe" or action_process_image_path = "C:\\Program Files\\PowerShell\\7\\pwsh.exe" or action_process_image_path = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe" or action_process_image_path = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell_ise.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe")) or ((action_process_image_path contains "C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview" or action_process_image_path contains "\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShellPreview") and action_process_image_path endswith "\\pwsh.exe"))) and not ((action_process_image_path startswith "C:\\Program Files\\WindowsApps\\Microsoft.GetHelp_" and action_process_image_path endswith "\\GetHelp.exe")))
