// Title: Suspicious WSMAN Provider Image Loads
// ID: ad1f4bb9-8dfb-4765-adb6-2a7cfb6c0f94
// Status: test
// Level: medium
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-06-24
// Tags: attack.execution, attack.t1059.001, attack.lateral-movement, attack.t1021.003
// Description: Detects signs of potential use of the WSMAN provider from uncommon processes locally and remote execution.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((((ImageLoaded endswith "\\WsmSvc.dll" or ImageLoaded endswith "\\WsmAuto.dll" or ImageLoaded endswith "\\Microsoft.WSMan.Management.ni.dll")) or ((action_process_image_name = "WsmSvc.dll" or action_process_image_name = "WSMANAUTOMATION.DLL" or action_process_image_name = "Microsoft.WSMan.Management.dll"))) or (action_process_image_path endswith "\\svchost.exe" and action_process_image_name = "WsmWmiPl.dll")) and not (((action_process_image_path startswith "C:\\Program Files\\Citrix\\") or ((action_process_image_path = "C:\\Program Files (x86)\\PowerShell\\6\\pwsh.exe" or action_process_image_path = "C:\\Program Files (x86)\\PowerShell\\7\\pwsh.exe" or action_process_image_path = "C:\\Program Files\\PowerShell\\6\\pwsh.exe" or action_process_image_path = "C:\\Program Files\\PowerShell\\7\\pwsh.exe" or action_process_image_path = "C:\\Windows\\System32\\sdiagnhost.exe" or action_process_image_path = "C:\\Windows\\System32\\services.exe" or action_process_image_path = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe" or action_process_image_path = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe")) or (action_process_image_path startswith "C:\\Program Files\\WindowsApps\\Microsoft.GetHelp_" and action_process_image_path endswith "\\GetHelp.exe") or (action_process_image_path endswith "\\mmc.exe") or ((action_process_image_path startswith "C:\\Windows\\Microsoft.NET\\Framework64\\v" or action_process_image_path startswith "C:\\Windows\\Microsoft.NET\\Framework\\v" or action_process_image_path startswith "C:\\Windows\\Microsoft.NET\\FrameworkArm\\v" or action_process_image_path startswith "C:\\Windows\\Microsoft.NET\\FrameworkArm64\\v") and action_process_image_path endswith "\\mscorsvw.exe") or (action_process_image_path startswith "C:\\Windows\\Temp\\asgard2-agent\\") or ((action_process_image_command_line contains "svchost.exe -k netsvcs -p -s BITS" or action_process_image_command_line contains "svchost.exe -k GraphicsPerfSvcGroup -s GraphicsPerfSvc" or action_process_image_command_line contains "svchost.exe -k NetworkService -p -s Wecsvc" or action_process_image_command_line contains "svchost.exe -k netsvcs")) or ((action_process_image_path = "C:\\Windows\\System32\\Configure-SMRemoting.exe" or action_process_image_path = "C:\\Windows\\System32\\ServerManager.exe")) or (action_process_image_path startswith "C:\\$WINDOWS.~BT\\Sources\\"))) and not (((action_process_image_path endswith "\\svchost.exe") and (action_process_image_command_line = null))))
