// Title: Outbound RDP Connections Over Non-Standard Tools
// ID: ed74fe75-7594-4b4b-ae38-e38e3fd2eb23
// Status: test
// Level: high
// Author: Markus Neis
// Date: 2019-05-15
// Tags: attack.lateral-movement, attack.t1021.001, car.2013-07-002
// Description: Detects Non-Standard tools initiating a connection over port 3389 indicating possible lateral movement.
// An initial baseline is required before using this utility to exclude third party RDP tooling that you might use.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((action_remote_port = 3389 and Initiated = "true") and not (((action_process_image_path = "C:\\Windows\\System32\\mstsc.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\mstsc.exe"))) and not ((((action_process_image_path endswith "\\Avast Software\\Avast\\AvastSvc.exe" or action_process_image_path endswith "\\Avast\\AvastSvc.exe")) or (action_process_image_path = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe") or (action_process_image_path = "C:\\Windows\\System32\\dns.exe" and action_local_port = 53 and Protocol = "udp") or (action_process_image_path = "") or (action_process_image_path = "C:\\Program Files\\Mozilla Firefox\\firefox.exe") or (action_process_image_path = null) or (action_process_image_path endswith "\\Ranger\\SentinelRanger.exe") or (action_process_image_path startswith "C:\\Program Files\\SplunkUniversalForwarder\\bin\\") or (action_process_image_path endswith "\\RDCMan.exe") or ((action_process_image_path endswith "\\FSAssessment.exe" or action_process_image_path endswith "\\FSDiscovery.exe" or action_process_image_path endswith "\\MobaRTE.exe" or action_process_image_path endswith "\\mRemote.exe" or action_process_image_path endswith "\\mRemoteNG.exe" or action_process_image_path endswith "\\Passwordstate.exe" or action_process_image_path endswith "\\RemoteDesktopManager.exe" or action_process_image_path endswith "\\RemoteDesktopManager64.exe" or action_process_image_path endswith "\\RemoteDesktopManagerFree.exe" or action_process_image_path endswith "\\RSSensor.exe" or action_process_image_path endswith "\\RTS2App.exe" or action_process_image_path endswith "\\RTSApp.exe" or action_process_image_path endswith "\\spiceworks-finder.exe" or action_process_image_path endswith "\\Terminals.exe" or action_process_image_path endswith "\\ws_TunnelService.exe")) or ((action_process_image_path endswith "\\thor.exe" or action_process_image_path endswith "\\thor64.exe")) or ((action_process_image_path = "C:\\Program Files\\TSplus\\Java\\bin\\HTML5service.exe" or action_process_image_path = "C:\\Program Files (x86)\\TSplus\\Java\\bin\\HTML5service.exe")) or (action_process_image_path = "<unknown process>"))))
