// Title: Network Communication Initiated To File Sharing Domains From Process Located In Suspicious Folder
// ID: e0f8ab85-0ac9-423b-a73a-81b3c7b1aa97
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2018-08-30
// Tags: attack.command-and-control, attack.t1105
// Description: Detects executables located in potentially suspicious directories initiating network connections towards file sharing domains.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((Initiated = "true" and (DestinationHostname endswith ".githubusercontent.com" or DestinationHostname endswith "0x0.st" or DestinationHostname endswith "anonfiles.com" or DestinationHostname endswith "bashupload.com" or DestinationHostname endswith "cdn.discordapp.com" or DestinationHostname endswith "chunk.io" or DestinationHostname endswith "ddns.net" or DestinationHostname endswith "dl.dropboxusercontent.com" or DestinationHostname endswith "ghostbin.co" or DestinationHostname endswith "github.com" or DestinationHostname endswith "glitch.me" or DestinationHostname endswith "gofile.io" or DestinationHostname endswith "hastebin.com" or DestinationHostname endswith "mediafire.com" or DestinationHostname endswith "mega.co.nz" or DestinationHostname endswith "mega.nz" or DestinationHostname endswith "onrender.com" or DestinationHostname endswith "pages.dev" or DestinationHostname endswith "paste.ee" or DestinationHostname endswith "pastebin.com" or DestinationHostname endswith "pastebin.pl" or DestinationHostname endswith "pastetext.net" or DestinationHostname endswith "pixeldrain.com" or DestinationHostname endswith "privatlab.com" or DestinationHostname endswith "privatlab.net" or DestinationHostname endswith "send.exploit.in" or DestinationHostname endswith "sendspace.com" or DestinationHostname endswith "storage.googleapis.com" or DestinationHostname endswith "storjshare.io" or DestinationHostname endswith "supabase.co" or DestinationHostname endswith "temp.sh" or DestinationHostname endswith "transfer.sh" or DestinationHostname endswith "trycloudflare.com" or DestinationHostname endswith "ufile.io" or DestinationHostname endswith "w3spaces.com" or DestinationHostname endswith "workers.dev" or DestinationHostname endswith "x0.at")) and ((action_process_image_path contains ":\\$Recycle.bin" or action_process_image_path contains ":\\Perflogs\\" or action_process_image_path contains ":\\Temp\\" or action_process_image_path contains ":\\Users\\Default\\" or action_process_image_path contains ":\\Users\\Public\\" or action_process_image_path contains ":\\Windows\\Fonts\\" or action_process_image_path contains ":\\Windows\\IME\\" or action_process_image_path contains ":\\Windows\\System32\\Tasks\\" or action_process_image_path contains ":\\Windows\\Tasks\\" or action_process_image_path contains ":\\Windows\\Temp\\" or action_process_image_path contains "\\AppData\\Temp\\" or action_process_image_path contains "\\config\\systemprofile\\" or action_process_image_path contains "\\Windows\\addins\\")))
