// Title: Suspicious Non-Browser Network Communication With Google API
// ID: 7e9cf7b6-e827-11ed-a05b-0242ac120003
// Status: experimental
// Level: medium
// Author: Gavin Knapp
// Date: 2023-05-01
// Tags: attack.command-and-control, attack.t1102
// Description: Detects a non-browser process interacting with the Google API which could indicate the use of a covert C2 such as Google Sheet C2 (GC2-sheet)
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((DestinationHostname contains "drive.googleapis.com" or DestinationHostname contains "oauth2.googleapis.com" or DestinationHostname contains "sheets.googleapis.com" or DestinationHostname contains "www.googleapis.com")) and not (((action_process_image_path = "") or (action_process_image_path = null))) and not (((action_process_image_path endswith "\\brave.exe") or ((action_process_image_path endswith ":\\Program Files\\Google\\Chrome\\Application\\chrome.exe" or action_process_image_path endswith ":\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe")) or ((action_process_image_path contains ":\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\") or ((action_process_image_path endswith ":\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" or action_process_image_path endswith ":\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe" or action_process_image_path endswith "\\WindowsApps\\MicrosoftEdge.exe"))) or ((action_process_image_path contains ":\\Program Files (x86)\\Microsoft\\EdgeCore\\" or action_process_image_path contains ":\\Program Files\\Microsoft\\EdgeCore\\") and (action_process_image_path endswith "\\msedge.exe" or action_process_image_path endswith "\\msedgewebview2.exe")) or ((action_process_image_path endswith ":\\Program Files\\Mozilla Firefox\\firefox.exe" or action_process_image_path endswith ":\\Program Files (x86)\\Mozilla Firefox\\firefox.exe")) or (action_process_image_path contains ":\\Program Files\\Google\\Drive File Stream\\" and action_process_image_path endswith "\\GoogleDriveFS.exe") or (action_process_image_path endswith "\\GoogleUpdate.exe") or ((action_process_image_path endswith ":\\Program Files (x86)\\Internet Explorer\\iexplore.exe" or action_process_image_path endswith ":\\Program Files\\Internet Explorer\\iexplore.exe")) or (action_process_image_path endswith "\\maxthon.exe") or (action_process_image_path endswith "\\opera.exe") or (action_process_image_path endswith "\\outlook.exe") or (action_process_image_path endswith "\\safari.exe") or (action_process_image_path endswith "\\seamonkey.exe") or (action_process_image_path endswith "\\vivaldi.exe") or (action_process_image_path endswith "\\whale.exe"))))
