// Title: Alternate PowerShell Hosts Pipe
// ID: 58cb02d5-78ce-4692-b3e1-dce850aae41a
// Status: test
// Level: medium
// Author: Roberto Rodriguez @Cyb3rWard0g, Tim Shelton
// Date: 2019-09-12
// Tags: attack.execution, attack.t1059.001
// Description: Detects alternate PowerShell hosts potentially bypassing detections looking for powershell.exe
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((PipeName startswith "\\PSHost") and not (((((action_process_image_path contains ":\\Program Files\\PowerShell\\7-preview\\pwsh.exe" or action_process_image_path contains ":\\Program Files\\PowerShell\\7\\pwsh.exe" or action_process_image_path contains ":\\Windows\\system32\\dsac.exe" or action_process_image_path contains ":\\Windows\\system32\\inetsrv\\w3wp.exe" or action_process_image_path contains ":\\Windows\\System32\\sdiagnhost.exe" or action_process_image_path contains ":\\Windows\\system32\\ServerManager.exe" or action_process_image_path contains ":\\Windows\\system32\\wbem\\wmiprvse.exe" or action_process_image_path contains ":\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe" or action_process_image_path contains ":\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" or action_process_image_path contains ":\\Windows\\System32\\wsmprovhost.exe" or action_process_image_path contains ":\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell_ise.exe" or action_process_image_path contains ":\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe")) or ((action_process_image_path contains "C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview" and action_process_image_path contains "\\pwsh.exe")) or ((action_process_image_path contains "\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShellPreview" and action_process_image_path contains "\\pwsh.exe"))) or (action_process_image_path = null))) and not (((action_process_image_path startswith "C:\\Program Files\\AzureConnectedMachineAgent\\GCArcService" and action_process_image_path endswith "\\GC\\gc_worker.exe") or (action_process_image_path startswith "C:\\Program Files\\Citrix\\") or (action_process_image_path startswith "C:\\Program Files\\Microsoft\\Exchange Server\\") or ((action_process_image_path startswith "C:\\Program Files (x86)\\" or action_process_image_path startswith "C:\\Program Files\\") and action_process_image_path contains "\\Microsoft SQL Server\\" and action_process_image_path endswith "\\Tools\\Binn\\SQLPS.exe"))))
