// Title: Cmd Launched with Hidden Start Flags to Suspicious Targets
// ID: 5a6b7c8d-9e0f-1a2b-3c4d-5e6f7a8b9c0d
// Status: experimental
// Level: medium
// Author: Vladan Sekulic, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-01-24
// Tags: attack.stealth, attack.t1564.003
// Description: Detects cmd.exe executing commands with the "start" utility using "/b" (no window) or "/min" (minimized) flags.
// To reduce false positives from standard background tasks, detection is restricted to scenarios where the target is a known script extension or located in suspicious temporary/public directories.
// This technique was observed in Chaos, DarkSide, and Emotet malware campaigns.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "start " or action_process_image_command_line contains "start/b" or action_process_image_command_line contains "start/min")) and ((action_process_image_command_line contains "/b " or action_process_image_command_line contains "-b " or action_process_image_command_line contains "/b\"" or action_process_image_command_line contains "-b\"" or action_process_image_command_line contains "/min " or action_process_image_command_line contains "-min " or action_process_image_command_line contains "/min\"" or action_process_image_command_line contains "-min\"")) and ((action_process_image_path endswith "\\cmd.exe") or (action_process_image_name = "Cmd.Exe"))) and (((action_process_image_command_line contains ".bat" or action_process_image_command_line contains ".cmd" or action_process_image_command_line contains ".cpl" or action_process_image_command_line contains ".hta" or action_process_image_command_line contains ".js" or action_process_image_command_line contains ".ps1" or action_process_image_command_line contains ".scr" or action_process_image_command_line contains ".vbe" or action_process_image_command_line contains ".vbs")) or ((action_process_image_command_line contains " -nop " or action_process_image_command_line contains " -sta " or action_process_image_command_line contains ".downloadfile(" or action_process_image_command_line contains ".downloadstring(" or action_process_image_command_line contains "-noni " or action_process_image_command_line contains "-w hidden ")) or ((action_process_image_command_line contains ":\\Perflogs\\" or action_process_image_command_line contains ":\\Temp\\" or action_process_image_command_line contains ":\\Users\\Default\\" or action_process_image_command_line contains ":\\Windows\\Temp\\" or action_process_image_command_line contains "\\AppData\\Roaming\\" or action_process_image_command_line contains "\\Contacts\\" or action_process_image_command_line contains "\\Documents\\" or action_process_image_command_line contains "\\Downloads\\" or action_process_image_command_line contains "\\Favorites\\" or action_process_image_command_line contains "\\Favourites\\" or action_process_image_command_line contains "\\inetpub\\" or action_process_image_command_line contains "\\Music\\" or action_process_image_command_line contains "\\Photos\\" or action_process_image_command_line contains "\\Temporary Internet\\" or action_process_image_command_line contains "\\Users\\Public\\" or action_process_image_command_line contains "\\Videos\\"))))
