// Title: Suspicious Modification Of Scheduled Tasks
// ID: 1c0e41cd-21bb-4433-9acc-4a2cd6367b9b
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-28
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1053.005
// Description: Detects when an attacker tries to modify an already existing scheduled tasks to run from a suspicious location
// Attackers can create a simple looking task in order to avoid detection on creation as it's often the most focused on
// Instead they modify the task after creation to include their malicious payload
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((action_process_image_path endswith "\\schtasks.exe" and (action_process_image_command_line contains " /Change " and action_process_image_command_line contains " /TN ")) and ((action_process_image_command_line contains "regsvr32" or action_process_image_command_line contains "rundll32" or action_process_image_command_line contains "cmd /c " or action_process_image_command_line contains "cmd /k " or action_process_image_command_line contains "cmd /r " or action_process_image_command_line contains "cmd.exe /c " or action_process_image_command_line contains "cmd.exe /k " or action_process_image_command_line contains "cmd.exe /r " or action_process_image_command_line contains "powershell" or action_process_image_command_line contains "mshta" or action_process_image_command_line contains "wscript" or action_process_image_command_line contains "cscript" or action_process_image_command_line contains "certutil" or action_process_image_command_line contains "bitsadmin" or action_process_image_command_line contains "bash.exe" or action_process_image_command_line contains "bash " or action_process_image_command_line contains "scrcons" or action_process_image_command_line contains "wmic " or action_process_image_command_line contains "wmic.exe" or action_process_image_command_line contains "forfiles" or action_process_image_command_line contains "scriptrunner" or action_process_image_command_line contains "hh.exe" or action_process_image_command_line contains "hh ")) and ((action_process_image_command_line contains "\\AppData\\Local\\Temp" or action_process_image_command_line contains "\\AppData\\Roaming\\" or action_process_image_command_line contains "\\Users\\Public\\" or action_process_image_command_line contains "\\WINDOWS\\Temp\\" or action_process_image_command_line contains "\\Desktop\\" or action_process_image_command_line contains "\\Downloads\\" or action_process_image_command_line contains "\\Temporary Internet" or action_process_image_command_line contains "C:\\ProgramData\\" or action_process_image_command_line contains "C:\\Perflogs\\" or action_process_image_command_line contains "%ProgramData%" or action_process_image_command_line contains "%appdata%" or action_process_image_command_line contains "%comspec%" or action_process_image_command_line contains "%localappdata%")))
