// Title: Suspicious Process By Web Server Process
// ID: 8202070f-edeb-4d31-a010-a26c72ac5600
// Status: test
// Level: high
// Author: Thomas Patzke, Florian Roth (Nextron Systems), Zach Stanford @svch0st, Tim Shelton, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-01-16
// Tags: attack.persistence, attack.initial-access, attack.t1505.003, attack.t1190
// Description: Detects potentially suspicious processes being spawned by a web server process which could be the result of a successfully placed web shell or exploitation
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((actor_process_image_path endswith "\\java.exe" or actor_process_image_path endswith "\\javaw.exe") and (actor_process_image_path contains "-tomcat-" or actor_process_image_path contains "\\tomcat")) or ((actor_process_image_path endswith "\\java.exe" or actor_process_image_path endswith "\\javaw.exe") and (actor_process_command_line contains "CATALINA_HOME" or actor_process_command_line contains "catalina.home" or actor_process_command_line contains "catalina.jar")) or ((actor_process_image_path endswith "\\caddy.exe" or actor_process_image_path endswith "\\httpd.exe" or actor_process_image_path endswith "\\nginx.exe" or actor_process_image_path endswith "\\php-cgi.exe" or actor_process_image_path endswith "\\php.exe" or actor_process_image_path endswith "\\tomcat.exe" or actor_process_image_path endswith "\\UMWorkerProcess.exe" or actor_process_image_path endswith "\\w3wp.exe" or actor_process_image_path endswith "\\ws_TomcatService.exe"))) and ((action_process_image_path endswith "\\arp.exe" or action_process_image_path endswith "\\at.exe" or action_process_image_path endswith "\\bash.exe" or action_process_image_path endswith "\\bitsadmin.exe" or action_process_image_path endswith "\\certutil.exe" or action_process_image_path endswith "\\cmd.exe" or action_process_image_path endswith "\\cscript.exe" or action_process_image_path endswith "\\dsget.exe" or action_process_image_path endswith "\\hostname.exe" or action_process_image_path endswith "\\nbtstat.exe" or action_process_image_path endswith "\\net.exe" or action_process_image_path endswith "\\net1.exe" or action_process_image_path endswith "\\netdom.exe" or action_process_image_path endswith "\\netsh.exe" or action_process_image_path endswith "\\nltest.exe" or action_process_image_path endswith "\\ntdsutil.exe" or action_process_image_path endswith "\\powershell_ise.exe" or action_process_image_path endswith "\\powershell.exe" or action_process_image_path endswith "\\pwsh.exe" or action_process_image_path endswith "\\qprocess.exe" or action_process_image_path endswith "\\query.exe" or action_process_image_path endswith "\\qwinsta.exe" or action_process_image_path endswith "\\reg.exe" or action_process_image_path endswith "\\rundll32.exe" or action_process_image_path endswith "\\sc.exe" or action_process_image_path endswith "\\sh.exe" or action_process_image_path endswith "\\wmic.exe" or action_process_image_path endswith "\\wscript.exe" or action_process_image_path endswith "\\wusa.exe")) and not (((actor_process_image_path endswith "\\java.exe" and action_process_image_command_line endswith "Windows\\system32\\cmd.exe /c C:\\ManageEngine\\ADManager \"Plus\\ES\\bin\\elasticsearch.bat -Enode.name=RMP-NODE1 -pelasticsearch-pid.txt") or (actor_process_image_path endswith "\\java.exe" and (action_process_image_command_line contains "sc query" and action_process_image_command_line contains "ADManager Plus")))))
