// Title: Suspicious Spool Service Child Process
// ID: dcdbc940-0bff-46b2-95f3-2d73f848e33b
// Status: test
// Level: high
// Author: Justin C. (@endisphotic), @dreadphones (detection), Thomas Patzke (Sigma rule)
// Date: 2021-07-11
// Tags: attack.execution, attack.t1203, attack.privilege-escalation, attack.t1068
// Description: Detects suspicious print spool service (spoolsv.exe) child processes.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((actor_process_image_path endswith "\\spoolsv.exe" and (IntegrityLevel = "System" or IntegrityLevel = "S-1-16-16384")) and (((action_process_image_path endswith "\\gpupdate.exe" or action_process_image_path endswith "\\whoami.exe" or action_process_image_path endswith "\\nltest.exe" or action_process_image_path endswith "\\taskkill.exe" or action_process_image_path endswith "\\wmic.exe" or action_process_image_path endswith "\\taskmgr.exe" or action_process_image_path endswith "\\sc.exe" or action_process_image_path endswith "\\findstr.exe" or action_process_image_path endswith "\\curl.exe" or action_process_image_path endswith "\\wget.exe" or action_process_image_path endswith "\\certutil.exe" or action_process_image_path endswith "\\bitsadmin.exe" or action_process_image_path endswith "\\accesschk.exe" or action_process_image_path endswith "\\wevtutil.exe" or action_process_image_path endswith "\\bcdedit.exe" or action_process_image_path endswith "\\fsutil.exe" or action_process_image_path endswith "\\cipher.exe" or action_process_image_path endswith "\\schtasks.exe" or action_process_image_path endswith "\\write.exe" or action_process_image_path endswith "\\wuauclt.exe" or action_process_image_path endswith "\\systeminfo.exe" or action_process_image_path endswith "\\reg.exe" or action_process_image_path endswith "\\query.exe")) or (((action_process_image_path endswith "\\net.exe" or action_process_image_path endswith "\\net1.exe")) and not ((action_process_image_command_line contains "start"))) or ((action_process_image_path endswith "\\cmd.exe") and not (((action_process_image_command_line contains ".spl" or action_process_image_command_line contains "route add" or action_process_image_command_line contains "program files")))) or ((action_process_image_path endswith "\\netsh.exe") and not (((action_process_image_command_line contains "add portopening" or action_process_image_command_line contains "rule name")))) or (((action_process_image_path endswith "\\powershell.exe" or action_process_image_path endswith "\\pwsh.exe")) and not ((action_process_image_command_line contains ".spl"))) or ((action_process_image_command_line endswith "rundll32.exe") and ((action_process_image_path endswith "\\rundll32.exe") or (action_process_image_name = "RUNDLL32.EXE")))))
