// Title: Webshell Hacking Activity Patterns
// ID: 4ebc877f-4612-45cb-b3a5-8e3834db36c9
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-17
// Tags: attack.persistence, attack.discovery, attack.t1505.003, attack.t1018, attack.t1033, attack.t1087
// Description: Detects certain parent child patterns found in cases in which a web shell is used to perform certain credential dumping or exfiltration activities on a compromised system
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((actor_process_image_path endswith "\\java.exe" or actor_process_image_path endswith "\\javaw.exe") and (actor_process_image_path contains "-tomcat-" or actor_process_image_path contains "\\tomcat")) or ((actor_process_image_path endswith "\\java.exe" or actor_process_image_path endswith "\\javaw.exe") and (action_process_image_command_line contains "catalina.jar" or action_process_image_command_line contains "CATALINA_HOME")) or ((actor_process_image_path endswith "\\caddy.exe" or actor_process_image_path endswith "\\httpd.exe" or actor_process_image_path endswith "\\nginx.exe" or actor_process_image_path endswith "\\php-cgi.exe" or actor_process_image_path endswith "\\w3wp.exe" or actor_process_image_path endswith "\\ws_tomcatservice.exe"))) and (((action_process_image_command_line contains "rundll32" and action_process_image_command_line contains "comsvcs")) or ((action_process_image_command_line contains " -hp" and action_process_image_command_line contains " a " and action_process_image_command_line contains " -m")) or ((action_process_image_command_line contains "net" and action_process_image_command_line contains " user " and action_process_image_command_line contains " /add")) or ((action_process_image_command_line contains "net" and action_process_image_command_line contains " localgroup " and action_process_image_command_line contains " administrators " and action_process_image_command_line contains "/add")) or ((action_process_image_path endswith "\\ntdsutil.exe" or action_process_image_path endswith "\\ldifde.exe" or action_process_image_path endswith "\\adfind.exe" or action_process_image_path endswith "\\procdump.exe" or action_process_image_path endswith "\\Nanodump.exe" or action_process_image_path endswith "\\vssadmin.exe" or action_process_image_path endswith "\\fsutil.exe")) or ((action_process_image_command_line contains " -decode " or action_process_image_command_line contains " -NoP " or action_process_image_command_line contains " -W Hidden " or action_process_image_command_line contains " /decode " or action_process_image_command_line contains " /ticket:" or action_process_image_command_line contains " sekurlsa" or action_process_image_command_line contains ".dmp full" or action_process_image_command_line contains ".downloadfile(" or action_process_image_command_line contains ".downloadstring(" or action_process_image_command_line contains "FromBase64String" or action_process_image_command_line contains "process call create" or action_process_image_command_line contains "reg save " or action_process_image_command_line contains "whoami /priv"))))
