// Title: Execution of Suspicious File Type Extension
// ID: c09dad97-1c78-4f71-b127-7edb2b8e491a
// Status: test
// Level: medium
// Author: Max Altgelt (Nextron Systems)
// Date: 2021-12-09
// Tags: attack.stealth
// Description: Detects whether the image specified in a process creation event doesn't refer to an ".exe" (or other known executable extension) file. This can be caused by process ghosting or other unorthodox methods to start a process.
// This rule might require some initial baselining to align with some third party tooling in the user environment.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (not (((action_process_image_path endswith ".bin" or action_process_image_path endswith ".cgi" or action_process_image_path endswith ".com" or action_process_image_path endswith ".exe" or action_process_image_path endswith ".scr" or action_process_image_path endswith ".tmp"))) and not (((action_process_image_path contains ":\\$Extend\\$Deleted\\") or (action_process_image_path contains ":\\Windows\\System32\\DriverStore\\FileRepository\\") or ((action_process_image_path = "-" or action_process_image_path = "")) or ((action_process_image_path = "System" or action_process_image_path = "Registry" or action_process_image_path = "MemCompression" or action_process_image_path = "vmmem")) or (action_process_image_path contains ":\\Windows\\Installer\\MSI") or (action_process_image_path contains ":\\Config.Msi\\" and (action_process_image_path endswith ".rbf" or action_process_image_path endswith ".rbs")) or (action_process_image_path = null) or ((actor_process_image_path contains ":\\Windows\\Temp\\") or (action_process_image_path contains ":\\Windows\\Temp\\")))) and not (((actor_process_image_path contains ":\\ProgramData\\Avira\\") or (actor_process_image_path = "C:\\Windows\\System32\\services.exe" and action_process_image_path endswith "com.docker.service") or (action_process_image_path contains ":\\Program Files\\Mozilla Firefox\\") or (action_process_image_path endswith "\\LZMA_EXE") or ((action_process_image_path endswith ":\\Program Files (x86)\\MyQ\\Server\\pcltool.dll" or action_process_image_path endswith ":\\Program Files\\MyQ\\Server\\pcltool.dll")) or (action_process_image_path contains "NVIDIA\\NvBackend\\" and action_process_image_path endswith ".dat") or ((action_process_image_path contains ":\\Program Files (x86)\\WINPAKPRO\\" or action_process_image_path contains ":\\Program Files\\WINPAKPRO\\") and action_process_image_path endswith ".ngn") or ((action_process_image_path contains "\\AppData\\Local\\Packages\\" and action_process_image_path contains "\\LocalState\\rootfs\\")))))
