// Title: Syslog Clearing or Removal Via System Utilities
// ID: 3fcc9b35-39e4-44c0-a2ad-9e82b6902b31
// Status: test
// Level: high
// Author: Max Altgelt (Nextron Systems), Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research), MSTIC
// Date: 2021-10-15
// Tags: attack.defense-impairment, attack.t1685.006
// Description: Detects specific commands commonly used to remove or empty the syslog. Which is a technique often used by attacker as a method to hide their tracks
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "/var/log/syslog") and ((action_process_image_path endswith "/cp" and action_process_image_command_line contains "/dev/null") or (action_process_image_path endswith "/ln" and (action_process_image_command_line contains "/dev/null " and action_process_image_command_line contains "/var/log/syslog") and (action_process_image_command_line contains "-sf " or action_process_image_command_line contains "-sfn " or action_process_image_command_line contains "-sfT ")) or (action_process_image_path endswith "/mv") or (action_process_image_path endswith "/rm" and (action_process_image_command_line contains " -r " or action_process_image_command_line contains " -f " or action_process_image_command_line contains " -rf " or action_process_image_command_line contains "/var/log/syslog")) or (action_process_image_path endswith "/shred" and action_process_image_command_line contains "-u ") or (action_process_image_path endswith "/truncate" and (action_process_image_command_line contains "0 " and action_process_image_command_line contains "/var/log/syslog") and (action_process_image_command_line contains "-s " or action_process_image_command_line contains "-c " or action_process_image_command_line contains "--size")) or (action_process_image_path endswith "/unlink"))) or (((action_process_image_command_line contains "journalctl --vacuum" or action_process_image_command_line contains "journalctl --rotate")) or ((action_process_image_command_line contains " > /var/log/syslog" or action_process_image_command_line contains " >/var/log/syslog" or action_process_image_command_line contains " >| /var/log/syslog" or action_process_image_command_line contains ": > /var/log/syslog" or action_process_image_command_line contains ":> /var/log/syslog" or action_process_image_command_line contains ":>/var/log/syslog" or action_process_image_command_line contains ">|/var/log/syslog"))))
