// Title: Potential Data Exfiltration Activity Via CommandLine Tools
// ID: 7d1aaf3d-4304-425c-b7c3-162055e0b3ab
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-02
// Tags: attack.execution, attack.t1059.001
// Description: Detects the use of various CLI utilities exfiltrating data via web requests
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_path endswith "\\powershell_ise.exe" or action_process_image_path endswith "\\powershell.exe" or action_process_image_path endswith "\\pwsh.exe" or action_process_image_path endswith "\\cmd.exe") and (action_process_image_command_line contains "curl " or action_process_image_command_line contains "Invoke-RestMethod" or action_process_image_command_line contains "Invoke-WebRequest" or action_process_image_command_line contains "irm " or action_process_image_command_line contains "iwr " or action_process_image_command_line contains "wget ") and (action_process_image_command_line contains " -ur" and action_process_image_command_line contains " -me" and action_process_image_command_line contains " -b" and action_process_image_command_line contains " POST ")) or ((action_process_image_path endswith "\\curl.exe" and action_process_image_command_line contains "--ur") and ((action_process_image_command_line contains " -d " or action_process_image_command_line contains " --data "))) or (action_process_image_path endswith "\\wget.exe" and (action_process_image_command_line contains "--post-data" or action_process_image_command_line contains "--post-file"))) and (((action_process_image_command_line ~= "net\\s+view" or action_process_image_command_line ~= "sc\\s+query")) or ((action_process_image_command_line contains "Get-Content" or action_process_image_command_line contains "GetBytes" or action_process_image_command_line contains "hostname" or action_process_image_command_line contains "ifconfig" or action_process_image_command_line contains "ipconfig" or action_process_image_command_line contains "netstat" or action_process_image_command_line contains "nltest" or action_process_image_command_line contains "qprocess" or action_process_image_command_line contains "systeminfo" or action_process_image_command_line contains "tasklist" or action_process_image_command_line contains "ToBase64String" or action_process_image_command_line contains "whoami")) or ((action_process_image_command_line contains "type " and action_process_image_command_line contains " > " and action_process_image_command_line contains " C:\\"))))
