// Title: File Download From IP URL Via Curl.EXE
// ID: 9cc85849-3b02-4cb5-b371-3a1ff54f2218
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-18
// Tags: attack.execution
// Description: Detects file downloads directly from IP address URL using curl.exe
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains " -O" or action_process_image_command_line contains "--remote-name" or action_process_image_command_line contains "--output")) and (action_process_image_command_line contains "http") and ((action_process_image_path endswith "\\curl.exe") or (action_process_image_name = "curl.exe")) and (action_process_image_command_line ~= "://[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}")) and not (((action_process_image_command_line endswith ".bat" or action_process_image_command_line endswith ".bat\"" or action_process_image_command_line endswith ".dat" or action_process_image_command_line endswith ".dat\"" or action_process_image_command_line endswith ".dll" or action_process_image_command_line endswith ".dll\"" or action_process_image_command_line endswith ".exe" or action_process_image_command_line endswith ".exe\"" or action_process_image_command_line endswith ".gif" or action_process_image_command_line endswith ".gif\"" or action_process_image_command_line endswith ".hta" or action_process_image_command_line endswith ".hta\"" or action_process_image_command_line endswith ".jpeg" or action_process_image_command_line endswith ".jpeg\"" or action_process_image_command_line endswith ".log" or action_process_image_command_line endswith ".log\"" or action_process_image_command_line endswith ".msi" or action_process_image_command_line endswith ".msi\"" or action_process_image_command_line endswith ".png" or action_process_image_command_line endswith ".png\"" or action_process_image_command_line endswith ".ps1" or action_process_image_command_line endswith ".ps1\"" or action_process_image_command_line endswith ".psm1" or action_process_image_command_line endswith ".psm1\"" or action_process_image_command_line endswith ".vbe" or action_process_image_command_line endswith ".vbe\"" or action_process_image_command_line endswith ".vbs" or action_process_image_command_line endswith ".vbs\"" or action_process_image_command_line endswith ".bat'" or action_process_image_command_line endswith ".dat'" or action_process_image_command_line endswith ".dll'" or action_process_image_command_line endswith ".exe'" or action_process_image_command_line endswith ".gif'" or action_process_image_command_line endswith ".hta'" or action_process_image_command_line endswith ".jpeg'" or action_process_image_command_line endswith ".log'" or action_process_image_command_line endswith ".msi'" or action_process_image_command_line endswith ".png'" or action_process_image_command_line endswith ".ps1'" or action_process_image_command_line endswith ".psm1'" or action_process_image_command_line endswith ".vbe'" or action_process_image_command_line endswith ".vbs'"))))
