// Title: Suspicious File Downloaded From File-Sharing Website Via Certutil.EXE
// ID: 42a5f1e7-9603-4f6d-97ae-3f37d130d794
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-15
// Tags: attack.stealth, attack.t1027, attack.command-and-control, attack.t1105
// Description: Detects the execution of certutil with certain flags that allow the utility to download files from file-sharing websites.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "urlcache " or action_process_image_command_line contains "verifyctl " or action_process_image_command_line contains "URL ")) and ((action_process_image_command_line contains ".githubusercontent.com" or action_process_image_command_line contains "0x0.st" or action_process_image_command_line contains "anonfiles.com" or action_process_image_command_line contains "bashupload.com" or action_process_image_command_line contains "cdn.discordapp.com" or action_process_image_command_line contains "chunk.io" or action_process_image_command_line contains "ddns.net" or action_process_image_command_line contains "dl.dropboxusercontent.com" or action_process_image_command_line contains "ghostbin.co" or action_process_image_command_line contains "github.com" or action_process_image_command_line contains "glitch.me" or action_process_image_command_line contains "gofile.io" or action_process_image_command_line contains "hastebin.com" or action_process_image_command_line contains "mediafire.com" or action_process_image_command_line contains "mega.nz" or action_process_image_command_line contains "onrender.com" or action_process_image_command_line contains "pages.dev" or action_process_image_command_line contains "paste.ee" or action_process_image_command_line contains "pastebin.com" or action_process_image_command_line contains "pastebin.pl" or action_process_image_command_line contains "pastetext.net" or action_process_image_command_line contains "privatlab.com" or action_process_image_command_line contains "privatlab.net" or action_process_image_command_line contains "send.exploit.in" or action_process_image_command_line contains "sendspace.com" or action_process_image_command_line contains "storage.googleapis.com" or action_process_image_command_line contains "storjshare.io" or action_process_image_command_line contains "supabase.co" or action_process_image_command_line contains "temp.sh" or action_process_image_command_line contains "transfer.sh" or action_process_image_command_line contains "trycloudflare.com" or action_process_image_command_line contains "ufile.io" or action_process_image_command_line contains "w3spaces.com" or action_process_image_command_line contains "workers.dev" or action_process_image_command_line contains "x0.at")) and ((action_process_image_path endswith "\\certutil.exe") or (action_process_image_name = "CertUtil.exe")))
