// Title: Disabling Security Tools
// ID: e3a8a052-111f-4606-9aee-f28ebeb76776
// Status: test
// Level: medium
// Author: Ömer Günal, Alejandro Ortuno, oscd.community
// Date: 2020-06-17
// Tags: attack.defense-impairment, attack.t1686
// Description: Detects disabling security tools
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((action_process_image_path endswith "/service" and (action_process_image_command_line contains "cbdaemon" and action_process_image_command_line contains "stop")) or (action_process_image_path endswith "/chkconfig" and (action_process_image_command_line contains "cbdaemon" and action_process_image_command_line contains "off")) or (action_process_image_path endswith "/systemctl" and (action_process_image_command_line contains "cbdaemon" and action_process_image_command_line contains "stop")) or (action_process_image_path endswith "/systemctl" and (action_process_image_command_line contains "cbdaemon" and action_process_image_command_line contains "disable")) or (action_process_image_path endswith "/systemctl" and (action_process_image_command_line contains "stop" and action_process_image_command_line contains "falcon-sensor")) or (action_process_image_path endswith "/systemctl" and (action_process_image_command_line contains "disable" and action_process_image_command_line contains "falcon-sensor")) or (action_process_image_path endswith "/systemctl" and (action_process_image_command_line contains "firewalld" and action_process_image_command_line contains "stop")) or (action_process_image_path endswith "/systemctl" and (action_process_image_command_line contains "firewalld" and action_process_image_command_line contains "disable")) or (action_process_image_path endswith "/service" and (action_process_image_command_line contains "iptables" and action_process_image_command_line contains "stop")) or (action_process_image_path endswith "/service" and (action_process_image_command_line contains "ip6tables" and action_process_image_command_line contains "stop")) or (action_process_image_path endswith "/chkconfig" and (action_process_image_command_line contains "iptables" and action_process_image_command_line contains "stop")) or (action_process_image_path endswith "/chkconfig" and (action_process_image_command_line contains "ip6tables" and action_process_image_command_line contains "stop")) or (action_process_image_path endswith "/setenforce" and action_process_image_command_line contains "0"))
