// Title: Suspicious Autorun Registry Modified via WMI
// ID: c80e66d8-1780-48a9-b412-46663fd21ac0
// Status: experimental
// Level: high
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-02-17
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1547.001, attack.t1047
// Description: Detects suspicious activity where the WMIC process is used to create an autorun registry entry via reg.exe, which is often indicative of persistence mechanisms employed by malware.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "reg" and action_process_image_command_line contains " add ") and (action_process_image_command_line contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" or action_process_image_command_line contains "\\Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Run" or action_process_image_command_line contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\Run")) and ((action_process_image_path endswith "\\wmic.exe") or (action_process_image_name = "wmic.exe") or (actor_process_image_path endswith "\\wmiprvse.exe"))) and (((action_process_image_command_line contains ":\\Perflogs" or action_process_image_command_line contains ":\\ProgramData'" or action_process_image_command_line contains ":\\Windows\\Temp" or action_process_image_command_line contains ":\\Temp" or action_process_image_command_line contains "\\AppData\\Local\\Temp" or action_process_image_command_line contains "\\AppData\\Roaming" or action_process_image_command_line contains ":\\$Recycle.bin" or action_process_image_command_line contains ":\\Users\\Default" or action_process_image_command_line contains ":\\Users\\public" or action_process_image_command_line contains "%temp%" or action_process_image_command_line contains "%tmp%" or action_process_image_command_line contains "%Public%" or action_process_image_command_line contains "%AppData%")) or ((action_process_image_command_line contains ":\\Users\\") and ((action_process_image_command_line contains "\\Favorites" or action_process_image_command_line contains "\\Favourites" or action_process_image_command_line contains "\\Contacts" or action_process_image_command_line contains "\\Music" or action_process_image_command_line contains "\\Pictures" or action_process_image_command_line contains "\\Documents" or action_process_image_command_line contains "\\Photos")))))
