// Title: Suspicious Windows Defender Registry Key Tampering Via Reg.EXE
// ID: 452bce90-6fb0-43cc-97a5-affc283139b3
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Swachchhanda Shrawan Poudel, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-03-22
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects the usage of "reg.exe" to tamper with different Windows Defender registry keys in order to disable some important features related to protection and detection
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_path endswith "\\reg.exe") or (action_process_image_name = "reg.exe")) and ((action_process_image_command_line contains "SOFTWARE\\Microsoft\\Windows Defender\\" or action_process_image_command_line contains "SOFTWARE\\Policies\\Microsoft\\Windows Defender Security Center" or action_process_image_command_line contains "SOFTWARE\\Policies\\Microsoft\\Windows Defender\\"))) and (((action_process_image_command_line contains " add " and action_process_image_command_line contains "d 0") and (action_process_image_command_line contains "DisallowExploitProtectionOverride" or action_process_image_command_line contains "EnableControlledFolderAccess" or action_process_image_command_line contains "MpEnablePus" or action_process_image_command_line contains "PUAProtection" or action_process_image_command_line contains "SpynetReporting" or action_process_image_command_line contains "SubmitSamplesConsent" or action_process_image_command_line contains "TamperProtection")) or ((action_process_image_command_line contains " add " and action_process_image_command_line contains "d 1") and (action_process_image_command_line contains "DisableAccess" or action_process_image_command_line contains "DisableAntiSpyware" or action_process_image_command_line contains "DisableAntiSpywareRealtimeProtection" or action_process_image_command_line contains "DisableAntiVirus" or action_process_image_command_line contains "DisableAntiVirusSignatures" or action_process_image_command_line contains "DisableArchiveScanning" or action_process_image_command_line contains "DisableBehaviorMonitoring" or action_process_image_command_line contains "DisableBlockAtFirstSeen" or action_process_image_command_line contains "DisableCloudProtection" or action_process_image_command_line contains "DisableConfig" or action_process_image_command_line contains "DisableEnhancedNotifications" or action_process_image_command_line contains "DisableIntrusionPreventionSystem" or action_process_image_command_line contains "DisableIOAVProtection" or action_process_image_command_line contains "DisableNetworkProtection" or action_process_image_command_line contains "DisableOnAccessProtection" or action_process_image_command_line contains "DisablePrivacyMode" or action_process_image_command_line contains "DisableRealtimeMonitoring" or action_process_image_command_line contains "DisableRoutinelyTakingAction" or action_process_image_command_line contains "DisableScanOnRealtimeEnable" or action_process_image_command_line contains "DisableScriptScanning" or action_process_image_command_line contains "DisableSecurityCenter" or action_process_image_command_line contains "Notification_Suppress" or action_process_image_command_line contains "SignatureDisableUpdateOnStartupWithoutEngine"))))
