// Title: Schedule Task Creation From Env Variable Or Potentially Suspicious Path Via Schtasks.EXE
// ID: 81325ce1-be01-4250-944f-b4789644556f
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2022-02-21
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1053.005
// Description: Detects Schtask creations that point to a suspicious folder or an environment variable often used by malware
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((((action_process_image_command_line contains ":\\Perflogs" or action_process_image_command_line contains ":\\Users\\All Users\\" or action_process_image_command_line contains ":\\Users\\Default\\" or action_process_image_command_line contains ":\\Users\\Public" or action_process_image_command_line contains ":\\Windows\\Temp" or action_process_image_command_line contains "\\AppData\\Local\\" or action_process_image_command_line contains "\\AppData\\Roaming\\" or action_process_image_command_line contains "%AppData%" or action_process_image_command_line contains "%Public%")) and (action_process_image_path endswith "\\schtasks.exe" and action_process_image_command_line contains " /create ")) or ((actor_process_command_line endswith "\\svchost.exe -k netsvcs -p -s Schedule") and ((action_process_image_command_line contains ":\\Perflogs" or action_process_image_command_line contains ":\\Windows\\Temp" or action_process_image_command_line contains "\\Users\\Public" or action_process_image_command_line contains "%Public%")))) and not ((((action_process_image_command_line contains "/Create /Xml " and action_process_image_command_line contains "\\Temp\\.CR." and action_process_image_command_line contains "\\Avira_Security_Installation.xml")) or ((action_process_image_command_line contains "/Create /F /TN" and action_process_image_command_line contains "/Xml " and action_process_image_command_line contains "\\Temp\\" and action_process_image_command_line contains "Avira_") and (action_process_image_command_line contains ".tmp\\UpdateFallbackTask.xml" or action_process_image_command_line contains ".tmp\\WatchdogServiceControlManagerTimeout.xml" or action_process_image_command_line contains ".tmp\\SystrayAutostart.xml" or action_process_image_command_line contains ".tmp\\MaintenanceTask.xml")) or ((action_process_image_command_line contains "\\Temp\\" and action_process_image_command_line contains "/Create /TN \"klcp_update\" /XML " and action_process_image_command_line contains "\\klcp_update_task.xml")) or ((actor_process_command_line contains "unattended.ini") or (action_process_image_command_line contains "update_task.xml")) or (action_process_image_command_line contains "/Create /TN TVInstallRestore /TR"))))
