// Title: Script Interpreter Execution From Suspicious Folder
// ID: 1228c958-e64e-4e71-92ad-7d429f4138ba
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-02-08
// Tags: attack.execution, attack.t1059
// Description: Detects suspicious script execution from suspicious directories or folders accessible by environment variables that may indicate malware activity.
// Script interpreters (cscript, wscript, mshta, powershell) executing from folders like Temp, Public, or user profile directories may suggest attempts to evade detection or execute malicious scripts.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains " -ep bypass " or action_process_image_command_line contains " -ExecutionPolicy bypass " or action_process_image_command_line contains " -w hidden " or action_process_image_command_line contains "/e:javascript " or action_process_image_command_line contains "/e:Jscript " or action_process_image_command_line contains "/e:vbscript ")) or ((action_process_image_path endswith "\\cscript.exe" or action_process_image_path endswith "\\mshta.exe" or action_process_image_path endswith "\\wscript.exe")) or ((action_process_image_name = "cscript.exe" or action_process_image_name = "mshta.exe" or action_process_image_name = "wscript.exe"))) and (((action_process_image_command_line contains ":\\Perflogs\\" or action_process_image_command_line contains ":\\Users\\Public\\" or action_process_image_command_line contains "\\%Public%" or action_process_image_command_line contains "\\AppData\\Local\\Temp" or action_process_image_command_line contains "\\AppData\\Roaming\\Temp" or action_process_image_command_line contains "\\Temporary Internet" or action_process_image_command_line contains "\\Windows\\Temp" or action_process_image_command_line contains "\\Start Menu\\Programs\\Startup\\" or action_process_image_command_line contains "%TEMP%" or action_process_image_command_line contains "%TMP%" or action_process_image_command_line contains "%LocalAppData%\\Temp")) or (((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Favorites\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Favourites\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Contacts\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Documents\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Music\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Pictures\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Videos\\")))) and not (((actor_process_image_path = "C:\\Windows\\System32\\Msiexec.exe" or actor_process_image_path = "C:\\Windows\\SysWOW64\\Msiexec.exe") and action_process_image_path endswith "\\powershell.exe" and (action_process_image_command_line contains "-NoProfile -ExecutionPolicy Bypass -Command" and action_process_image_command_line contains "AppData\\Local\\Temp\\" and action_process_image_command_line contains "Install-Chocolatey.ps1"))))
