// Title: Csc.EXE Execution Form Potentially Suspicious Parent
// ID: b730a276-6b63-41b8-bcf8-55930c8fc6ee
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems), X__Junior (Nextron Systems)
// Date: 2019-02-11
// Tags: attack.execution, attack.stealth, attack.t1059.005, attack.t1059.007, attack.t1218.005, attack.t1027.004
// Description: Detects a potentially suspicious parent of "csc.exe", which could be a sign of payload delivery.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_path endswith "\\csc.exe") or (action_process_image_name = "csc.exe")) and (((actor_process_image_path endswith "\\cscript.exe" or actor_process_image_path endswith "\\excel.exe" or actor_process_image_path endswith "\\mshta.exe" or actor_process_image_path endswith "\\onenote.exe" or actor_process_image_path endswith "\\outlook.exe" or actor_process_image_path endswith "\\powerpnt.exe" or actor_process_image_path endswith "\\winword.exe" or actor_process_image_path endswith "\\wscript.exe")) or ((actor_process_image_path endswith "\\powershell.exe" or actor_process_image_path endswith "\\pwsh.exe") and (actor_process_command_line contains "-Encoded " or actor_process_command_line contains "FromBase64String")) or ((actor_process_command_line ~= "(?:[Pp]rogram[Dd]ata|%(?:[Ll]ocal)?[Aa]pp[Dd]ata%|\\\\[Aa]pp[Dd]ata\\\\(?:[Ll]ocal(?:[Ll]ow)?|[Rr]oaming))\\\\[^\\\\]{1,256}$") or ((actor_process_command_line contains ":\\PerfLogs\\" or actor_process_command_line contains ":\\Users\\Public\\" or actor_process_command_line contains ":\\Windows\\Temp\\" or actor_process_command_line contains "\\Temporary Internet")) or ((actor_process_command_line contains ":\\Users\\" and actor_process_command_line contains "\\Favorites\\")) or ((actor_process_command_line contains ":\\Users\\" and actor_process_command_line contains "\\Favourites\\")) or ((actor_process_command_line contains ":\\Users\\" and actor_process_command_line contains "\\Contacts\\")) or ((actor_process_command_line contains ":\\Users\\" and actor_process_command_line contains "\\Pictures\\")))) and not ((((actor_process_image_path startswith "C:\\Program Files (x86)\\" or actor_process_image_path startswith "C:\\Program Files\\")) or (actor_process_image_path = "C:\\Windows\\System32\\sdiagnhost.exe") or (actor_process_image_path = "C:\\Windows\\System32\\inetsrv\\w3wp.exe"))) and not ((((actor_process_command_line contains "JwB7ACIAZgBhAGkAbABlAGQAIgA6AHQAcgB1AGUALAAiAG0AcwBnACIAOgAiAEEAbgBzAGkAYgBsAGUAIAByAGUAcQB1AGkAcgBlAHMAIABQAG8AdwBlAHIAUwBoAGUAbABsACAAdgAzAC4AMAAgAG8AcgAgAG4AZQB3AGUAcgAiAH0AJw" or actor_process_command_line contains "cAewAiAGYAYQBpAGwAZQBkACIAOgB0AHIAdQBlACwAIgBtAHMAZwAiADoAIgBBAG4AcwBpAGIAbABlACAAcgBlAHEAdQBpAHIAZQBzACAAUABvAHcAZQByAFMAaABlAGwAbAAgAHYAMwAuADAAIABvAHIAIABuAGUAdwBlAHIAIgB9ACcA" or actor_process_command_line contains "nAHsAIgBmAGEAaQBsAGUAZAAiADoAdAByAHUAZQAsACIAbQBzAGcAIgA6ACIAQQBuAHMAaQBiAGwAZQAgAHIAZQBxAHUAaQByAGUAcwAgAFAAbwB3AGUAcgBTAGgAZQBsAGwAIAB2ADMALgAwACAAbwByACAAbgBlAHcAZQByACIAfQAnA")) or (actor_process_image_path = "C:\\ProgramData\\chocolatey\\choco.exe") or (actor_process_command_line contains "\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection"))))
