// Title: Process Proxy Execution Via Squirrel.EXE
// ID: 45239e6a-b035-4aaf-b339-8ad379fcb67e
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems), Karneades / Markus Neis, Jonhnathan Ribeiro, oscd.community
// Date: 2022-06-09
// Tags: attack.execution, attack.stealth, attack.t1218
// Description: Detects the usage of the "Squirrel.exe" binary to execute arbitrary processes. This binary is part of multiple Electron based software installations (Slack, Teams, Discord, etc.)
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "--processStart" or action_process_image_command_line contains "--processStartAndWait" or action_process_image_command_line contains "--createShortcut")) and ((action_process_image_path endswith "\\squirrel.exe" or action_process_image_path endswith "\\update.exe"))) and not ((((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\AppData\\Local\\Discord\\Update.exe" and action_process_image_command_line contains "Discord.exe") and (action_process_image_command_line contains "--createShortcut" or action_process_image_command_line contains "--processStart")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\AppData\\Local\\GitHubDesktop\\Update.exe" and action_process_image_command_line contains "GitHubDesktop.exe") and (action_process_image_command_line contains "--createShortcut" or action_process_image_command_line contains "--processStartAndWait")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\AppData\\Local\\Microsoft\\Teams\\Update.exe" and action_process_image_command_line contains "Teams.exe") and (action_process_image_command_line contains "--processStart" or action_process_image_command_line contains "--createShortcut")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\AppData\\Local\\yammerdesktop\\Update.exe" and action_process_image_command_line contains "Yammer.exe") and (action_process_image_command_line contains "--processStart" or action_process_image_command_line contains "--createShortcut")))))
