// Title: Potential Defense Evasion Via Rename Of Highly Relevant Binaries
// ID: 0ba1da6d-b6ce-4366-828c-18826c9de23e
// Status: test
// Level: high
// Author: Matthew Green - @mgreen27, Florian Roth (Nextron Systems), frack113
// Date: 2019-06-15
// Tags: attack.stealth, attack.t1036.003, car.2013-05-009
// Description: Detects the execution of a renamed binary often used by attackers or malware leveraging new Sysmon OriginalFileName datapoint.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((Description = "Execute processes remotely") or (Product = "Sysinternals PsExec") or ((Description startswith "Windows PowerShell" or Description startswith "pwsh")) or ((action_process_image_name = "certutil.exe" or action_process_image_name = "cmstp.exe" or action_process_image_name = "cscript.exe" or action_process_image_name = "IE4UINIT.EXE" or action_process_image_name = "finger.exe" or action_process_image_name = "mshta.exe" or action_process_image_name = "msiexec.exe" or action_process_image_name = "msxsl.exe" or action_process_image_name = "powershell_ise.exe" or action_process_image_name = "powershell.exe" or action_process_image_name = "psexec.c" or action_process_image_name = "psexec.exe" or action_process_image_name = "psexesvc.exe" or action_process_image_name = "pwsh.dll" or action_process_image_name = "reg.exe" or action_process_image_name = "regsvr32.exe" or action_process_image_name = "rundll32.exe" or action_process_image_name = "WerMgr" or action_process_image_name = "wmic.exe" or action_process_image_name = "wscript.exe"))) and not (((action_process_image_path endswith "\\certutil.exe" or action_process_image_path endswith "\\cmstp.exe" or action_process_image_path endswith "\\cscript.exe" or action_process_image_path endswith "\\ie4uinit.exe" or action_process_image_path endswith "\\finger.exe" or action_process_image_path endswith "\\mshta.exe" or action_process_image_path endswith "\\msiexec.exe" or action_process_image_path endswith "\\msxsl.exe" or action_process_image_path endswith "\\powershell_ise.exe" or action_process_image_path endswith "\\powershell.exe" or action_process_image_path endswith "\\psexec.exe" or action_process_image_path endswith "\\psexec64.exe" or action_process_image_path endswith "\\psexec64a.exe" or action_process_image_path endswith "\\PSEXESVC.exe" or action_process_image_path endswith "\\pwsh.exe" or action_process_image_path endswith "\\reg.exe" or action_process_image_path endswith "\\regsvr32.exe" or action_process_image_path endswith "\\rundll32.exe" or action_process_image_path endswith "\\wermgr.exe" or action_process_image_path endswith "\\wmic.exe" or action_process_image_path endswith "\\wscript.exe"))))
