// Title: Suspicious File Download From IP Via Wget.EXE
// ID: 17f0c0a8-8bd5-4ee0-8c5f-a342c0199f35
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-27
// Tags: attack.execution
// Description: Detects potentially suspicious file downloads directly from IP addresses using Wget.exe
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line endswith ".ps1" or action_process_image_command_line endswith ".ps1'" or action_process_image_command_line endswith ".ps1\"" or action_process_image_command_line endswith ".dat" or action_process_image_command_line endswith ".dat'" or action_process_image_command_line endswith ".dat\"" or action_process_image_command_line endswith ".msi" or action_process_image_command_line endswith ".msi'" or action_process_image_command_line endswith ".msi\"" or action_process_image_command_line endswith ".bat" or action_process_image_command_line endswith ".bat'" or action_process_image_command_line endswith ".bat\"" or action_process_image_command_line endswith ".exe" or action_process_image_command_line endswith ".exe'" or action_process_image_command_line endswith ".exe\"" or action_process_image_command_line endswith ".vbs" or action_process_image_command_line endswith ".vbs'" or action_process_image_command_line endswith ".vbs\"" or action_process_image_command_line endswith ".vbe" or action_process_image_command_line endswith ".vbe'" or action_process_image_command_line endswith ".vbe\"" or action_process_image_command_line endswith ".hta" or action_process_image_command_line endswith ".hta'" or action_process_image_command_line endswith ".hta\"" or action_process_image_command_line endswith ".dll" or action_process_image_command_line endswith ".dll'" or action_process_image_command_line endswith ".dll\"" or action_process_image_command_line endswith ".psm1" or action_process_image_command_line endswith ".psm1'" or action_process_image_command_line endswith ".psm1\"")) and ((action_process_image_command_line ~= "\\s-O\\s") or (action_process_image_command_line contains "--output-document")) and (action_process_image_command_line contains "http") and ((action_process_image_path endswith "\\wget.exe") or (action_process_image_name = "wget.exe")) and (action_process_image_command_line ~= "://[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"))
