// Title: Uncommon  Assistive Technology Applications Execution Via AtBroker.EXE
// ID: f24bcaea-0cd1-11eb-adc1-0242ac120002
// Status: test
// Level: medium
// Author: Mateusz Wydra, oscd.community
// Date: 2020-10-12
// Tags: attack.stealth, attack.t1218
// Description: Detects the start of a non built-in assistive technology applications via "Atbroker.EXE".
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "start") and ((action_process_image_path endswith "\\AtBroker.exe") or (action_process_image_name = "AtBroker.exe"))) and not (((action_process_image_command_line contains "animations" or action_process_image_command_line contains "audiodescription" or action_process_image_command_line contains "caretbrowsing" or action_process_image_command_line contains "caretwidth" or action_process_image_command_line contains "colorfiltering" or action_process_image_command_line contains "cursorindicator" or action_process_image_command_line contains "cursorscheme" or action_process_image_command_line contains "filterkeys" or action_process_image_command_line contains "focusborderheight" or action_process_image_command_line contains "focusborderwidth" or action_process_image_command_line contains "highcontrast" or action_process_image_command_line contains "keyboardcues" or action_process_image_command_line contains "keyboardpref" or action_process_image_command_line contains "livecaptions" or action_process_image_command_line contains "magnifierpane" or action_process_image_command_line contains "messageduration" or action_process_image_command_line contains "minimumhitradius" or action_process_image_command_line contains "mousekeys" or action_process_image_command_line contains "Narrator" or action_process_image_command_line contains "osk" or action_process_image_command_line contains "overlappedcontent" or action_process_image_command_line contains "showsounds" or action_process_image_command_line contains "soundsentry" or action_process_image_command_line contains "speechreco" or action_process_image_command_line contains "stickykeys" or action_process_image_command_line contains "togglekeys" or action_process_image_command_line contains "voiceaccess" or action_process_image_command_line contains "windowarranging" or action_process_image_command_line contains "windowtracking" or action_process_image_command_line contains "windowtrackingtimeout" or action_process_image_command_line contains "windowtrackingzorder"))) and not ((action_process_image_command_line contains "Oracle_JavaAccessBridge")))
