// Title: File Download with Headless Browser
// ID: 0e8cfe08-02c9-4815-a2f8-0d157b7ed33e
// Status: test
// Level: high
// Author: Sreeman, Florian Roth (Nextron Systems)
// Date: 2022-01-04
// Tags: attack.command-and-control, attack.stealth, attack.t1105, attack.t1564.003
// Description: Detects execution of chromium based browser in headless mode using the "dump-dom" command line to download files
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_path endswith "\\brave.exe" or action_process_image_path endswith "\\chrome.exe" or action_process_image_path endswith "\\msedge.exe" or action_process_image_path endswith "\\opera.exe" or action_process_image_path endswith "\\vivaldi.exe") and (action_process_image_command_line contains "--headless" and action_process_image_command_line contains "dump-dom" and action_process_image_command_line contains "http")) and not ((((action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\" or action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft\\EdgeCore\\" or action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\" or action_process_image_path startswith "C:\\Program Files\\Microsoft\\Edge\\Application\\" or action_process_image_path startswith "C:\\Program Files\\Microsoft\\EdgeCore\\" or action_process_image_path startswith "C:\\Program Files\\Microsoft\\EdgeWebView\\" or action_process_image_path startswith "C:\\Program Files\\WindowsApps\\Microsoft.MicrosoftEdge") and (action_process_image_path endswith "\\msedge.exe" or action_process_image_path endswith "\\msedgewebview2.exe" or action_process_image_path endswith "\\MicrosoftEdge.exe") and action_process_image_command_line contains "--headless --disable-gpu --disable-extensions --disable-plugins --mute-audio --no-first-run --incognito --aggressive-cache-discard --dump-dom") or ((action_process_image_path contains "\\AppData\\Local\\Microsoft\\WindowsApps\\" or action_process_image_path contains "\\Windows\\SystemApps\\Microsoft.MicrosoftEdge") and (action_process_image_path endswith "\\msedge.exe" or action_process_image_path endswith "\\MicrosoftEdge.exe") and action_process_image_command_line contains "--headless --disable-gpu --disable-extensions --disable-plugins --mute-audio --no-first-run --incognito --aggressive-cache-discard --dump-dom"))))
