// Title: Powershell Base64 Encoded MpPreference Cmdlet
// ID: c6fb44c6-71f5-49e6-9462-1425d328aee3
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-04
// Tags: attack.defense-impairment, attack.t1685
// Description: Detects base64 encoded "MpPreference" PowerShell cmdlet code that tries to modifies or tamper with Windows Defender AV
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "QWRkLU1wUHJlZmVyZW5jZS" or action_process_image_command_line contains "FkZC1NcFByZWZlcmVuY2Ug" or action_process_image_command_line contains "BZGQtTXBQcmVmZXJlbmNlI" or action_process_image_command_line contains "U2V0LU1wUHJlZmVyZW5jZS" or action_process_image_command_line contains "NldC1NcFByZWZlcmVuY2Ug" or action_process_image_command_line contains "TZXQtTXBQcmVmZXJlbmNlI" or action_process_image_command_line contains "YWRkLW1wcHJlZmVyZW5jZS" or action_process_image_command_line contains "FkZC1tcHByZWZlcmVuY2Ug" or action_process_image_command_line contains "hZGQtbXBwcmVmZXJlbmNlI" or action_process_image_command_line contains "c2V0LW1wcHJlZmVyZW5jZS" or action_process_image_command_line contains "NldC1tcHByZWZlcmVuY2Ug" or action_process_image_command_line contains "zZXQtbXBwcmVmZXJlbmNlI")) or ((action_process_image_command_line contains "QQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgA" or action_process_image_command_line contains "EAZABkAC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIA" or action_process_image_command_line contains "BAGQAZAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAA" or action_process_image_command_line contains "UwBlAHQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgA" or action_process_image_command_line contains "MAZQB0AC0ATQBwAFAAcgBlAGYAZQByAGUAbgBjAGUAIA" or action_process_image_command_line contains "TAGUAdAAtAE0AcABQAHIAZQBmAGUAcgBlAG4AYwBlACAA" or action_process_image_command_line contains "YQBkAGQALQBtAHAAcAByAGUAZgBlAHIAZQBuAGMAZQAgA" or action_process_image_command_line contains "EAZABkAC0AbQBwAHAAcgBlAGYAZQByAGUAbgBjAGUAIA" or action_process_image_command_line contains "hAGQAZAAtAG0AcABwAHIAZQBmAGUAcgBlAG4AYwBlACAA" or action_process_image_command_line contains "cwBlAHQALQBtAHAAcAByAGUAZgBlAHIAZQBuAGMAZQAgA" or action_process_image_command_line contains "MAZQB0AC0AbQBwAHAAcgBlAGYAZQByAGUAbgBjAGUAIA" or action_process_image_command_line contains "zAGUAdAAtAG0AcABwAHIAZQBmAGUAcgBlAG4AYwBlACAA")))
