// Title: Regsvr32 Execution From Highly Suspicious Location
// ID: 327ff235-94eb-4f06-b9de-aaee571324be
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-26
// Tags: attack.stealth, attack.t1218.010
// Description: Detects execution of regsvr32 where the DLL is located in a highly suspicious locations
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_path endswith "\\regsvr32.exe") or (action_process_image_name = "REGSVR32.EXE")) and (((action_process_image_command_line contains ":\\PerfLogs\\" or action_process_image_command_line contains ":\\Temp\\" or action_process_image_command_line contains "\\Windows\\Registration\\CRMLog" or action_process_image_command_line contains "\\Windows\\System32\\com\\dmp\\" or action_process_image_command_line contains "\\Windows\\System32\\FxsTmp\\" or action_process_image_command_line contains "\\Windows\\System32\\Microsoft\\Crypto\\RSA\\MachineKeys\\" or action_process_image_command_line contains "\\Windows\\System32\\spool\\drivers\\color\\" or action_process_image_command_line contains "\\Windows\\System32\\spool\\PRINTERS\\" or action_process_image_command_line contains "\\Windows\\System32\\spool\\SERVERS\\" or action_process_image_command_line contains "\\Windows\\System32\\Tasks_Migrated\\" or action_process_image_command_line contains "\\Windows\\System32\\Tasks\\Microsoft\\Windows\\SyncCenter\\" or action_process_image_command_line contains "\\Windows\\SysWOW64\\com\\dmp\\" or action_process_image_command_line contains "\\Windows\\SysWOW64\\FxsTmp\\" or action_process_image_command_line contains "\\Windows\\SysWOW64\\Tasks\\Microsoft\\Windows\\PLA\\System\\" or action_process_image_command_line contains "\\Windows\\SysWOW64\\Tasks\\Microsoft\\Windows\\SyncCenter\\" or action_process_image_command_line contains "\\Windows\\Tasks\\" or action_process_image_command_line contains "\\Windows\\Tracing\\")) or (((action_process_image_command_line contains " \"C:\\" or action_process_image_command_line contains " C:\\" or action_process_image_command_line contains " 'C:\\" or action_process_image_command_line contains "D:\\")) and not (((action_process_image_command_line contains "C:\\Program Files (x86)\\" or action_process_image_command_line contains "C:\\Program Files\\" or action_process_image_command_line contains "C:\\ProgramData\\" or action_process_image_command_line contains "C:\\Users\\" or action_process_image_command_line contains " C:\\Windows\\" or action_process_image_command_line contains " \"C:\\Windows\\" or action_process_image_command_line contains " 'C:\\Windows\\"))))) and not (((action_process_image_command_line = "") or (action_process_image_command_line = null))))
