// Title: Cmd.EXE Missing Space Characters Execution Anomaly
// ID: a16980c2-0c56-4de0-9a79-17971979efdd
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-23
// Tags: attack.execution, attack.t1059.001
// Description: Detects Windows command lines that miss a space before or after the /c flag when running a command using the cmd.exe.
// This could be a sign of obfuscation of a fat finger problem (typo by the developer).
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "cmd.exe/c" or action_process_image_command_line contains "\\cmd/c" or action_process_image_command_line contains "\"cmd/c" or action_process_image_command_line contains "cmd.exe/k" or action_process_image_command_line contains "\\cmd/k" or action_process_image_command_line contains "\"cmd/k" or action_process_image_command_line contains "cmd.exe/r" or action_process_image_command_line contains "\\cmd/r" or action_process_image_command_line contains "\"cmd/r")) or ((action_process_image_command_line contains "/cwhoami" or action_process_image_command_line contains "/cpowershell" or action_process_image_command_line contains "/cschtasks" or action_process_image_command_line contains "/cbitsadmin" or action_process_image_command_line contains "/ccertutil" or action_process_image_command_line contains "/kwhoami" or action_process_image_command_line contains "/kpowershell" or action_process_image_command_line contains "/kschtasks" or action_process_image_command_line contains "/kbitsadmin" or action_process_image_command_line contains "/kcertutil")) or ((action_process_image_command_line contains "cmd.exe /c" or action_process_image_command_line contains "cmd /c" or action_process_image_command_line contains "cmd.exe /k" or action_process_image_command_line contains "cmd /k" or action_process_image_command_line contains "cmd.exe /r" or action_process_image_command_line contains "cmd /r"))) and not ((((action_process_image_command_line contains "AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\node_modules") or (action_process_image_command_line endswith "cmd.exe/c .") or (action_process_image_command_line = "cmd.exe /c") or (action_process_image_command_line = "cmd /c")) or ((action_process_image_command_line contains "cmd.exe /c " or action_process_image_command_line contains "cmd /c " or action_process_image_command_line contains "cmd.exe /k " or action_process_image_command_line contains "cmd /k " or action_process_image_command_line contains "cmd.exe /r " or action_process_image_command_line contains "cmd /r ")))))
