// Title: Linux HackTool Execution
// ID: a015e032-146d-4717-8944-7a1884122111
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems), Georg Lauenstein (sure[secure])
// Date: 2023-01-03
// Tags: attack.execution, attack.resource-development, attack.t1587
// Description: Detects known hacktool execution based on image name.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_path contains "/cobaltstrike" or action_process_image_path contains "/teamserver")) or ((action_process_image_path endswith "/crackmapexec" or action_process_image_path endswith "/havoc" or action_process_image_path endswith "/merlin-agent" or action_process_image_path endswith "/merlinServer-Linux-x64" or action_process_image_path endswith "/msfconsole" or action_process_image_path endswith "/msfvenom" or action_process_image_path endswith "/ps-empire server" or action_process_image_path endswith "/ps-empire" or action_process_image_path endswith "/sliver-client" or action_process_image_path endswith "/sliver-server" or action_process_image_path endswith "/Villain.py")) or ((action_process_image_path endswith "/aircrack-ng" or action_process_image_path endswith "/bloodhound-python" or action_process_image_path endswith "/bpfdos" or action_process_image_path endswith "/ebpfki" or action_process_image_path endswith "/evil-winrm" or action_process_image_path endswith "/hashcat" or action_process_image_path endswith "/hoaxshell.py" or action_process_image_path endswith "/hydra" or action_process_image_path endswith "/john" or action_process_image_path endswith "/ncrack" or action_process_image_path endswith "/nxc-ubuntu-latest" or action_process_image_path endswith "/pidhide" or action_process_image_path endswith "/pspy32" or action_process_image_path endswith "/pspy32s" or action_process_image_path endswith "/pspy64" or action_process_image_path endswith "/pspy64s" or action_process_image_path endswith "/setoolkit" or action_process_image_path endswith "/sqlmap" or action_process_image_path endswith "/writeblocker")) or (action_process_image_path contains "/linpeas") or ((action_process_image_path endswith "/autorecon" or action_process_image_path endswith "/httpx" or action_process_image_path endswith "/legion" or action_process_image_path endswith "/naabu" or action_process_image_path endswith "/netdiscover" or action_process_image_path endswith "/nuclei" or action_process_image_path endswith "/recon-ng")) or (action_process_image_path contains "/sniper") or ((action_process_image_path endswith "/dirb" or action_process_image_path endswith "/dirbuster" or action_process_image_path endswith "/eyewitness" or action_process_image_path endswith "/feroxbuster" or action_process_image_path endswith "/ffuf" or action_process_image_path endswith "/gobuster" or action_process_image_path endswith "/wfuzz" or action_process_image_path endswith "/whatweb")) or ((action_process_image_path endswith "/joomscan" or action_process_image_path endswith "/nikto" or action_process_image_path endswith "/wpscan")))
