// Title: File With Suspicious Extension Downloaded Via Bitsadmin
// ID: 5b80a791-ad9b-4b75-bcc1-ad4e1e89c200
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-28
// Tags: attack.persistence, attack.execution, attack.stealth, attack.t1197, attack.s0190, attack.t1036.003, attack.command-and-control, attack.t1105
// Description: Detects usage of bitsadmin downloading a file with a suspicious extension
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains ".7z" or action_process_image_command_line contains ".asax" or action_process_image_command_line contains ".ashx" or action_process_image_command_line contains ".asmx" or action_process_image_command_line contains ".asp" or action_process_image_command_line contains ".aspx" or action_process_image_command_line contains ".bat" or action_process_image_command_line contains ".cfm" or action_process_image_command_line contains ".cgi" or action_process_image_command_line contains ".chm" or action_process_image_command_line contains ".cmd" or action_process_image_command_line contains ".dll" or action_process_image_command_line contains ".gif" or action_process_image_command_line contains ".jpeg" or action_process_image_command_line contains ".jpg" or action_process_image_command_line contains ".jsp" or action_process_image_command_line contains ".jspx" or action_process_image_command_line contains ".log" or action_process_image_command_line contains ".png" or action_process_image_command_line contains ".ps1" or action_process_image_command_line contains ".psm1" or action_process_image_command_line contains ".rar" or action_process_image_command_line contains ".scf" or action_process_image_command_line contains ".sct" or action_process_image_command_line contains ".txt" or action_process_image_command_line contains ".vbe" or action_process_image_command_line contains ".vbs" or action_process_image_command_line contains ".war" or action_process_image_command_line contains ".wsf" or action_process_image_command_line contains ".wsh" or action_process_image_command_line contains ".xll" or action_process_image_command_line contains ".zip")) and ((action_process_image_command_line contains " /transfer " or action_process_image_command_line contains " /create " or action_process_image_command_line contains " /addfile ")) and ((action_process_image_path endswith "\\bitsadmin.exe") or (action_process_image_name = "bitsadmin.exe")))
