// Title: Suspicious Program Location Whitelisted In Firewall Via Netsh.EXE
// ID: a35f5a72-f347-4e36-8895-9869b0d5fc6d
// Status: test
// Level: high
// Author: Sander Wiebing, Jonhnathan Ribeiro, Daniil Yugoslavskiy, oscd.community
// Date: 2020-05-25
// Tags: attack.defense-impairment, attack.t1686.003
// Description: Detects Netsh command execution that whitelists a program located in a suspicious location in the Windows Firewall
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "firewall" and action_process_image_command_line contains "add" and action_process_image_command_line contains "allowedprogram")) or ((action_process_image_command_line contains "advfirewall" and action_process_image_command_line contains "firewall" and action_process_image_command_line contains "add" and action_process_image_command_line contains "rule" and action_process_image_command_line contains "action=allow" and action_process_image_command_line contains "program="))) and ((action_process_image_path endswith "\\netsh.exe") or (action_process_image_name = "netsh.exe")) and ((action_process_image_command_line contains ":\\$Recycle.bin\\" or action_process_image_command_line contains ":\\RECYCLER.BIN\\" or action_process_image_command_line contains ":\\RECYCLERS.BIN\\" or action_process_image_command_line contains ":\\SystemVolumeInformation\\" or action_process_image_command_line contains ":\\Temp\\" or action_process_image_command_line contains ":\\Users\\Default\\" or action_process_image_command_line contains ":\\Users\\Desktop\\" or action_process_image_command_line contains ":\\Users\\Public\\" or action_process_image_command_line contains ":\\Windows\\addins\\" or action_process_image_command_line contains ":\\Windows\\cursors\\" or action_process_image_command_line contains ":\\Windows\\debug\\" or action_process_image_command_line contains ":\\Windows\\drivers\\" or action_process_image_command_line contains ":\\Windows\\fonts\\" or action_process_image_command_line contains ":\\Windows\\help\\" or action_process_image_command_line contains ":\\Windows\\system32\\tasks\\" or action_process_image_command_line contains ":\\Windows\\Tasks\\" or action_process_image_command_line contains ":\\Windows\\Temp\\" or action_process_image_command_line contains "\\Downloads\\" or action_process_image_command_line contains "\\Local Settings\\Temporary Internet Files\\" or action_process_image_command_line contains "\\Temporary Internet Files\\Content.Outlook\\" or action_process_image_command_line contains "%Public%\\" or action_process_image_command_line contains "%TEMP%" or action_process_image_command_line contains "%TMP%")))
