// Title: Suspicious Download From File-Sharing Website Via Bitsadmin
// ID: 8518ed3d-f7c9-4601-a26c-f361a4256a0c
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-28
// Tags: attack.persistence, attack.execution, attack.stealth, attack.t1197, attack.s0190, attack.t1036.003, attack.command-and-control, attack.t1105
// Description: Detects usage of bitsadmin downloading a file from a suspicious domain
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains ".githubusercontent.com" or action_process_image_command_line contains "0x0.st" or action_process_image_command_line contains "anonfiles.com" or action_process_image_command_line contains "bashupload.com" or action_process_image_command_line contains "cdn.discordapp.com" or action_process_image_command_line contains "chunk.io" or action_process_image_command_line contains "ddns.net" or action_process_image_command_line contains "dl.dropboxusercontent.com" or action_process_image_command_line contains "ghostbin.co" or action_process_image_command_line contains "github.com" or action_process_image_command_line contains "glitch.me" or action_process_image_command_line contains "gofile.io" or action_process_image_command_line contains "hastebin.com" or action_process_image_command_line contains "mediafire.com" or action_process_image_command_line contains "mega.nz" or action_process_image_command_line contains "onrender.com" or action_process_image_command_line contains "pages.dev" or action_process_image_command_line contains "paste.ee" or action_process_image_command_line contains "pastebin.com" or action_process_image_command_line contains "pastebin.pl" or action_process_image_command_line contains "pastetext.net" or action_process_image_command_line contains "privatlab.com" or action_process_image_command_line contains "privatlab.net" or action_process_image_command_line contains "send.exploit.in" or action_process_image_command_line contains "sendspace.com" or action_process_image_command_line contains "storage.googleapis.com" or action_process_image_command_line contains "storjshare.io" or action_process_image_command_line contains "supabase.co" or action_process_image_command_line contains "temp.sh" or action_process_image_command_line contains "transfer.sh" or action_process_image_command_line contains "trycloudflare.com" or action_process_image_command_line contains "ufile.io" or action_process_image_command_line contains "w3spaces.com" or action_process_image_command_line contains "workers.dev" or action_process_image_command_line contains "x0.at")) and ((action_process_image_command_line contains " /transfer " or action_process_image_command_line contains " /create " or action_process_image_command_line contains " /addfile ")) and ((action_process_image_path endswith "\\bitsadmin.exe") or (action_process_image_name = "bitsadmin.exe")))
