// Title: AADInternals PowerShell Cmdlets Execution - ProccessCreation
// ID: c86500e9-a645-4680-98d7-f882c70c1ea3
// Status: test
// Level: high
// Author: Austin Songer (@austinsonger), Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2022-12-23
// Tags: attack.execution, attack.reconnaissance, attack.discovery, attack.credential-access, attack.impact
// Description: Detects ADDInternals Cmdlet execution. A tool for administering Azure AD and Office 365. Which can be abused by threat actors to attack Azure AD or Office 365.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "Add-AADInt" or action_process_image_command_line contains "ConvertTo-AADInt" or action_process_image_command_line contains "Disable-AADInt" or action_process_image_command_line contains "Enable-AADInt" or action_process_image_command_line contains "Export-AADInt" or action_process_image_command_line contains "Find-AADInt" or action_process_image_command_line contains "Get-AADInt" or action_process_image_command_line contains "Grant-AADInt" or action_process_image_command_line contains "Initialize-AADInt" or action_process_image_command_line contains "Install-AADInt" or action_process_image_command_line contains "Invoke-AADInt" or action_process_image_command_line contains "Join-AADInt" or action_process_image_command_line contains "New-AADInt" or action_process_image_command_line contains "Open-AADInt" or action_process_image_command_line contains "Read-AADInt" or action_process_image_command_line contains "Register-AADInt" or action_process_image_command_line contains "Remove-AADInt" or action_process_image_command_line contains "Reset-AADInt" or action_process_image_command_line contains "Resolve-AADInt" or action_process_image_command_line contains "Restore-AADInt" or action_process_image_command_line contains "Save-AADInt" or action_process_image_command_line contains "Search-AADInt" or action_process_image_command_line contains "Send-AADInt" or action_process_image_command_line contains "Set-AADInt" or action_process_image_command_line contains "Start-AADInt" or action_process_image_command_line contains "Unprotect-AADInt" or action_process_image_command_line contains "Update-AADInt")) and (((action_process_image_path endswith "\\powershell.exe" or action_process_image_path endswith "\\powershell_ise.exe" or action_process_image_path endswith "\\pwsh.exe")) or ((action_process_image_name = "PowerShell.Exe" or action_process_image_name = "pwsh.dll"))))
