// Title: PowerShell Base64 Encoded WMI Classes
// ID: 1816994b-42e1-4fb1-afd2-134d88184f71
// Status: test
// Level: high
// Author: Christian Burkard (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-30
// Tags: attack.execution, attack.stealth, attack.t1059.001, attack.t1027
// Description: Detects calls to base64 encoded WMI class such as "Win32_ShadowCopy", "Win32_ScheduledJob", etc.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_path endswith "\\powershell.exe" or action_process_image_path endswith "\\pwsh.exe")) or ((action_process_image_name = "PowerShell.EXE" or action_process_image_name = "pwsh.dll"))) and (((action_process_image_command_line contains "VwBpAG4AMwAyAF8ATABvAGcAZwBlAGQATwBuAFUAcwBlAHIA" or action_process_image_command_line contains "cAaQBuADMAMgBfAEwAbwBnAGcAZQBkAE8AbgBVAHMAZQByA" or action_process_image_command_line contains "XAGkAbgAzADIAXwBMAG8AZwBnAGUAZABPAG4AVQBzAGUAcg" or action_process_image_command_line contains "V2luMzJfTG9nZ2VkT25Vc2Vy" or action_process_image_command_line contains "dpbjMyX0xvZ2dlZE9uVXNlc" or action_process_image_command_line contains "XaW4zMl9Mb2dnZWRPblVzZX")) or ((action_process_image_command_line contains "VwBpAG4AMwAyAF8AUAByAG8AYwBlAHMAcw" or action_process_image_command_line contains "cAaQBuADMAMgBfAFAAcgBvAGMAZQBzAHMA" or action_process_image_command_line contains "XAGkAbgAzADIAXwBQAHIAbwBjAGUAcwBzA" or action_process_image_command_line contains "V2luMzJfUHJvY2Vzc" or action_process_image_command_line contains "dpbjMyX1Byb2Nlc3" or action_process_image_command_line contains "XaW4zMl9Qcm9jZXNz")) or ((action_process_image_command_line contains "VwBpAG4AMwAyAF8AUwBjAGgAZQBkAHUAbABlAGQASgBvAGIA" or action_process_image_command_line contains "cAaQBuADMAMgBfAFMAYwBoAGUAZAB1AGwAZQBkAEoAbwBiA" or action_process_image_command_line contains "XAGkAbgAzADIAXwBTAGMAaABlAGQAdQBsAGUAZABKAG8AYg" or action_process_image_command_line contains "V2luMzJfU2NoZWR1bGVkSm9i" or action_process_image_command_line contains "dpbjMyX1NjaGVkdWxlZEpvY" or action_process_image_command_line contains "XaW4zMl9TY2hlZHVsZWRKb2")) or ((action_process_image_command_line contains "VwBpAG4AMwAyAF8AUwBoAGEAZABvAHcAYwBvAHAAeQ" or action_process_image_command_line contains "cAaQBuADMAMgBfAFMAaABhAGQAbwB3AGMAbwBwAHkA" or action_process_image_command_line contains "XAGkAbgAzADIAXwBTAGgAYQBkAG8AdwBjAG8AcAB5A" or action_process_image_command_line contains "V2luMzJfU2hhZG93Y29we" or action_process_image_command_line contains "dpbjMyX1NoYWRvd2NvcH" or action_process_image_command_line contains "XaW4zMl9TaGFkb3djb3B5")) or ((action_process_image_command_line contains "VwBpAG4AMwAyAF8AVQBzAGUAcgBBAGMAYwBvAHUAbgB0A" or action_process_image_command_line contains "cAaQBuADMAMgBfAFUAcwBlAHIAQQBjAGMAbwB1AG4AdA" or action_process_image_command_line contains "XAGkAbgAzADIAXwBVAHMAZQByAEEAYwBjAG8AdQBuAHQA" or action_process_image_command_line contains "V2luMzJfVXNlckFjY291bn" or action_process_image_command_line contains "dpbjMyX1VzZXJBY2NvdW50" or action_process_image_command_line contains "XaW4zMl9Vc2VyQWNjb3Vud"))))
