// Title: Suspicious Program Names
// ID: efdd8dd5-cee8-4e59-9390-7d4d5e4dd6f6
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-02-11
// Tags: attack.execution, attack.t1059
// Description: Detects suspicious patterns in program names or folders that are often found in malicious samples or hacktools
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "inject.ps1" or action_process_image_command_line contains "Invoke-CVE" or action_process_image_command_line contains "pupy.ps1" or action_process_image_command_line contains "payload.ps1" or action_process_image_command_line contains "beacon.ps1" or action_process_image_command_line contains "PowerView.ps1" or action_process_image_command_line contains "bypass.ps1" or action_process_image_command_line contains "obfuscated.ps1" or action_process_image_command_line contains "obfusc.ps1" or action_process_image_command_line contains "obfus.ps1" or action_process_image_command_line contains "obfs.ps1" or action_process_image_command_line contains "evil.ps1" or action_process_image_command_line contains "MiniDogz.ps1" or action_process_image_command_line contains "_enc.ps1" or action_process_image_command_line contains "\\shell.ps1" or action_process_image_command_line contains "\\rshell.ps1" or action_process_image_command_line contains "revshell.ps1" or action_process_image_command_line contains "\\av.ps1" or action_process_image_command_line contains "\\av_test.ps1" or action_process_image_command_line contains "adrecon.ps1" or action_process_image_command_line contains "mimikatz.ps1" or action_process_image_command_line contains "\\PowerUp_" or action_process_image_command_line contains "powerup.ps1" or action_process_image_command_line contains "\\Temp\\a.ps1" or action_process_image_command_line contains "\\Temp\\p.ps1" or action_process_image_command_line contains "\\Temp\\1.ps1" or action_process_image_command_line contains "Hound.ps1" or action_process_image_command_line contains "encode.ps1" or action_process_image_command_line contains "powercat.ps1")) or (((action_process_image_path contains "\\CVE-202" or action_process_image_path contains "\\CVE202")) or ((action_process_image_path endswith "\\poc.exe" or action_process_image_path endswith "\\artifact.exe" or action_process_image_path endswith "\\artifact64.exe" or action_process_image_path endswith "\\artifact_protected.exe" or action_process_image_path endswith "\\artifact32.exe" or action_process_image_path endswith "\\artifact32big.exe" or action_process_image_path endswith "obfuscated.exe" or action_process_image_path endswith "obfusc.exe" or action_process_image_path endswith "\\meterpreter"))))
