// Title: Windows Shell/Scripting Processes Spawning Suspicious Programs
// ID: 3a6586ad-127a-4d3b-a677-1e6eacdf8fde
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems), Tim Shelton
// Date: 2018-04-06
// Tags: attack.execution, attack.stealth, attack.t1059.005, attack.t1059.001, attack.t1218
// Description: Detects suspicious child processes of a Windows shell and scripting processes such as wscript, rundll32, powershell, mshta...etc.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((actor_process_image_path endswith "\\mshta.exe" or actor_process_image_path endswith "\\powershell.exe" or actor_process_image_path endswith "\\pwsh.exe" or actor_process_image_path endswith "\\rundll32.exe" or actor_process_image_path endswith "\\cscript.exe" or actor_process_image_path endswith "\\wscript.exe" or actor_process_image_path endswith "\\wmiprvse.exe" or actor_process_image_path endswith "\\regsvr32.exe") and (action_process_image_path endswith "\\schtasks.exe" or action_process_image_path endswith "\\nslookup.exe" or action_process_image_path endswith "\\certutil.exe" or action_process_image_path endswith "\\bitsadmin.exe" or action_process_image_path endswith "\\mshta.exe")) and not ((((actor_process_command_line contains "\\Program Files\\Amazon\\WorkSpacesConfig\\Scripts\\setup-scheduledtask.ps1" or actor_process_command_line contains "\\Program Files\\Amazon\\WorkSpacesConfig\\Scripts\\set-selfhealing.ps1" or actor_process_command_line contains "\\Program Files\\Amazon\\WorkSpacesConfig\\Scripts\\check-workspacehealth.ps1" or actor_process_command_line contains "\\nessus_")) or (CurrentDirectory contains "\\ccmcache\\") or (action_process_image_command_line contains "\\nessus_") or (actor_process_image_path endswith "\\mshta.exe" and action_process_image_path endswith "\\mshta.exe" and (actor_process_command_line contains "C:\\MEM_Configmgr_" and actor_process_command_line contains "\\splash.hta" and actor_process_command_line contains "{1E460BD7-F1C3-4B2E-88BF-4E770A288AF5}") and (action_process_image_command_line contains "C:\\MEM_Configmgr_" and action_process_image_command_line contains "\\SMSSETUP\\BIN\\" and action_process_image_command_line contains "\\autorun.hta" and action_process_image_command_line contains "{1E460BD7-F1C3-4B2E-88BF-4E770A288AF5}")))))
