// Title: Suspicious Browser Child Process - MacOS
// ID: 0250638a-2b28-4541-86fc-ea4c558fa0c6
// Status: test
// Level: medium
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-04-05
// Tags: attack.initial-access, attack.execution, attack.t1189, attack.t1203, attack.t1059
// Description: Detects suspicious child processes spawned from browsers. This could be a result of a potential web browser exploitation.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((actor_process_image_path contains "com.apple.WebKit.WebContent" or actor_process_image_path contains "firefox" or actor_process_image_path contains "Google Chrome Helper" or actor_process_image_path contains "Google Chrome" or actor_process_image_path contains "Microsoft Edge" or actor_process_image_path contains "Opera" or actor_process_image_path contains "Safari" or actor_process_image_path contains "Tor Browser") and (action_process_image_path endswith "/bash" or action_process_image_path endswith "/curl" or action_process_image_path endswith "/dash" or action_process_image_path endswith "/ksh" or action_process_image_path endswith "/osascript" or action_process_image_path endswith "/perl" or action_process_image_path endswith "/php" or action_process_image_path endswith "/pwsh" or action_process_image_path endswith "/python" or action_process_image_path endswith "/sh" or action_process_image_path endswith "/tcsh" or action_process_image_path endswith "/wget" or action_process_image_path endswith "/zsh")) and not ((((actor_process_image_path contains "Google Chrome Helper" or actor_process_image_path contains "Google Chrome") and (action_process_image_command_line contains "/Volumes/Google Chrome/Google Chrome.app/Contents/Frameworks/*/Resources/install.sh" or action_process_image_command_line contains "/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/*/Resources/keystone_promote_preflight.sh" or action_process_image_command_line contains "/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/*/Resources/keystone_promote_postflight.sh")) or ((actor_process_image_path contains "Google Chrome Helper" or actor_process_image_path contains "Google Chrome") and (action_process_image_command_line contains "/Users/" and action_process_image_command_line contains "/Library/Application Support/Google/Chrome/recovery/" and action_process_image_command_line contains "/ChromeRecovery")) or (action_process_image_command_line contains "--defaults-torrc") or (action_process_image_command_line contains "/Library/Application Support/Microsoft/MAU*/Microsoft AutoUpdate.app/Contents/MacOS/msupdate") or (actor_process_image_path contains "Microsoft Edge" and (action_process_image_command_line contains "IOPlatformExpertDevice" or action_process_image_command_line contains "hw.model")))) and not (((action_process_image_command_line = "") or (action_process_image_command_line = null))))
