// Title: Dynamic .NET Compilation Via Csc.EXE
// ID: dcaa3f04-70c3-427a-80b4-b870d73c94c4
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems), X__Junior (Nextron Systems)
// Date: 2019-08-24
// Tags: attack.stealth, attack.t1027.004
// Description: Detects execution of "csc.exe" to compile .NET code. Attackers often leverage this to compile code on the fly and use it in other stages.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((action_process_image_path endswith "\\csc.exe") and (((action_process_image_command_line contains ":\\Perflogs\\" or action_process_image_command_line contains ":\\Users\\Public\\" or action_process_image_command_line contains "\\AppData\\Local\\Temp\\" or action_process_image_command_line contains "\\Temporary Internet" or action_process_image_command_line contains "\\Windows\\Temp\\")) or (((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Favorites\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Favourites\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Contacts\\")) or ((action_process_image_command_line contains ":\\Users\\" and action_process_image_command_line contains "\\Pictures\\"))) or (action_process_image_command_line ~= "(?:[Pp]rogram[Dd]ata|%(?:[Ll]ocal)?[Aa]pp[Dd]ata%|\\\\[Aa]pp[Dd]ata\\\\(?:[Ll]ocal(?:[Ll]ow)?|[Rr]oaming))\\\\[^\\\\]{1,256}$")) and not ((((actor_process_image_path startswith "C:\\Program Files (x86)\\" or actor_process_image_path startswith "C:\\Program Files\\")) or (actor_process_image_path = "C:\\Windows\\System32\\sdiagnhost.exe") or (actor_process_image_path = "C:\\Windows\\System32\\inetsrv\\w3wp.exe"))) and not ((((actor_process_command_line contains "JwB7ACIAZgBhAGkAbABlAGQAIgA6AHQAcgB1AGUALAAiAG0AcwBnACIAOgAiAEEAbgBzAGkAYgBsAGUAIAByAGUAcQB1AGkAcgBlAHMAIABQAG8AdwBlAHIAUwBoAGUAbABsACAAdgAzAC4AMAAgAG8AcgAgAG4AZQB3AGUAcgAiAH0AJw" or actor_process_command_line contains "cAewAiAGYAYQBpAGwAZQBkACIAOgB0AHIAdQBlACwAIgBtAHMAZwAiADoAIgBBAG4AcwBpAGIAbABlACAAcgBlAHEAdQBpAHIAZQBzACAAUABvAHcAZQByAFMAaABlAGwAbAAgAHYAMwAuADAAIABvAHIAIABuAGUAdwBlAHIAIgB9ACcA" or actor_process_command_line contains "nAHsAIgBmAGEAaQBsAGUAZAAiADoAdAByAHUAZQAsACIAbQBzAGcAIgA6ACIAQQBuAHMAaQBiAGwAZQAgAHIAZQBxAHUAaQByAGUAcwAgAFAAbwB3AGUAcgBTAGgAZQBsAGwAIAB2ADMALgAwACAAbwByACAAbgBlAHcAZQByACIAfQAnA")) or ((actor_process_image_path = "C:\\ProgramData\\chocolatey\\choco.exe" or actor_process_image_path = "C:\\ProgramData\\chocolatey\\tools\\shimgen.exe")) or (actor_process_command_line contains "\\ProgramData\\Microsoft\\Windows Defender Advanced Threat Protection"))))
