// Title: Invoke-Obfuscation Obfuscated IEX Invocation
// ID: 4bf943c6-5146-4273-98dd-e958fd1e3abf
// Status: test
// Level: high
// Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
// Date: 2019-11-08
// Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
// Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the following code block
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((action_process_image_command_line ~= "\\$PSHome\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$PSHome\\[") or (action_process_image_command_line ~= "\\$ShellId\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$ShellId\\[") or (action_process_image_command_line ~= "\\$env:Public\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$env:Public\\[") or (action_process_image_command_line ~= "\\$env:ComSpec\\[(?:\\s*\\d{1,3}\\s*,){2}") or (action_process_image_command_line ~= "\\*mdr\\*\\W\\s*\\)\\.Name") or (action_process_image_command_line ~= "\\$VerbosePreference\\.ToString\\(") or (action_process_image_command_line ~= "\\[String\\]\\s*\\$VerbosePreference"))
