// Title: HackTool - Impacket Tools Execution
// ID: 4627c6ae-6899-46e2-aa0c-6ebcb1becd19
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2021-07-24
// Tags: attack.collection, attack.execution, attack.credential-access, attack.t1557.001
// Description: Detects the execution of different compiled Windows binaries of the impacket toolset (based on names or part of their names - could lead to false positives)
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_path contains "\\goldenPac" or action_process_image_path contains "\\karmaSMB" or action_process_image_path contains "\\kintercept" or action_process_image_path contains "\\ntlmrelayx" or action_process_image_path contains "\\rpcdump" or action_process_image_path contains "\\samrdump" or action_process_image_path contains "\\secretsdump" or action_process_image_path contains "\\smbexec" or action_process_image_path contains "\\smbrelayx" or action_process_image_path contains "\\wmiexec" or action_process_image_path contains "\\wmipersist")) or ((action_process_image_path endswith "\\atexec_windows.exe" or action_process_image_path endswith "\\dcomexec_windows.exe" or action_process_image_path endswith "\\dpapi_windows.exe" or action_process_image_path endswith "\\findDelegation_windows.exe" or action_process_image_path endswith "\\GetADUsers_windows.exe" or action_process_image_path endswith "\\GetNPUsers_windows.exe" or action_process_image_path endswith "\\getPac_windows.exe" or action_process_image_path endswith "\\getST_windows.exe" or action_process_image_path endswith "\\getTGT_windows.exe" or action_process_image_path endswith "\\GetUserSPNs_windows.exe" or action_process_image_path endswith "\\ifmap_windows.exe" or action_process_image_path endswith "\\mimikatz_windows.exe" or action_process_image_path endswith "\\netview_windows.exe" or action_process_image_path endswith "\\nmapAnswerMachine_windows.exe" or action_process_image_path endswith "\\opdump_windows.exe" or action_process_image_path endswith "\\psexec_windows.exe" or action_process_image_path endswith "\\rdp_check_windows.exe" or action_process_image_path endswith "\\sambaPipe_windows.exe" or action_process_image_path endswith "\\smbclient_windows.exe" or action_process_image_path endswith "\\smbserver_windows.exe" or action_process_image_path endswith "\\sniff_windows.exe" or action_process_image_path endswith "\\sniffer_windows.exe" or action_process_image_path endswith "\\split_windows.exe" or action_process_image_path endswith "\\ticketer_windows.exe")))
