// Title: Potential Browser Data Stealing
// ID: 47147b5b-9e17-4d76-b8d2-7bac24c5ce1b
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-23
// Tags: attack.credential-access, attack.t1555.003
// Description: Adversaries may acquire credentials from web browsers by reading files specific to the target browser.
// Web browsers commonly save credentials such as website usernames and passwords so that they do not need to be entered manually in the future.
// Web browsers typically store the credentials in an encrypted format within a credential store.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "copy-item" or action_process_image_command_line contains "copy " or action_process_image_command_line contains "cpi " or action_process_image_command_line contains " cp " or action_process_image_command_line contains "move " or action_process_image_command_line contains "move-item" or action_process_image_command_line contains " mi " or action_process_image_command_line contains " mv ")) or ((action_process_image_path endswith "\\esentutl.exe" or action_process_image_path endswith "\\xcopy.exe" or action_process_image_path endswith "\\robocopy.exe")) or ((action_process_image_name = "esentutl.exe" or action_process_image_name = "XCOPY.EXE" or action_process_image_name = "robocopy.exe"))) and ((action_process_image_command_line contains "\\Amigo\\User Data" or action_process_image_command_line contains "\\BraveSoftware\\Brave-Browser\\User Data" or action_process_image_command_line contains "\\CentBrowser\\User Data" or action_process_image_command_line contains "\\Chromium\\User Data" or action_process_image_command_line contains "\\CocCoc\\Browser\\User Data" or action_process_image_command_line contains "\\Comodo\\Dragon\\User Data" or action_process_image_command_line contains "\\Elements Browser\\User Data" or action_process_image_command_line contains "\\Epic Privacy Browser\\User Data" or action_process_image_command_line contains "\\Google\\Chrome Beta\\User Data" or action_process_image_command_line contains "\\Google\\Chrome SxS\\User Data" or action_process_image_command_line contains "\\Google\\Chrome\\User Data\\" or action_process_image_command_line contains "\\Kometa\\User Data" or action_process_image_command_line contains "\\Maxthon5\\Users" or action_process_image_command_line contains "\\Microsoft\\Edge\\User Data" or action_process_image_command_line contains "\\Mozilla\\Firefox\\Profiles" or action_process_image_command_line contains "\\Nichrome\\User Data" or action_process_image_command_line contains "\\Opera Software\\Opera GX Stable\\" or action_process_image_command_line contains "\\Opera Software\\Opera Neon\\User Data" or action_process_image_command_line contains "\\Opera Software\\Opera Stable\\" or action_process_image_command_line contains "\\Orbitum\\User Data" or action_process_image_command_line contains "\\QIP Surf\\User Data" or action_process_image_command_line contains "\\Sputnik\\User Data" or action_process_image_command_line contains "\\Torch\\User Data" or action_process_image_command_line contains "\\uCozMedia\\Uran\\User Data" or action_process_image_command_line contains "\\Vivaldi\\User Data")))
