// Title: Suspicious File Download From IP Via Curl.EXE
// ID: 5cb299fc-5fb1-4d07-b989-0644c68b6043
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-27
// Tags: attack.execution
// Description: Detects potentially suspicious file downloads directly from IP addresses using curl.exe
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line endswith ".bat" or action_process_image_command_line endswith ".bat\"" or action_process_image_command_line endswith ".dat" or action_process_image_command_line endswith ".dat\"" or action_process_image_command_line endswith ".dll" or action_process_image_command_line endswith ".dll\"" or action_process_image_command_line endswith ".exe" or action_process_image_command_line endswith ".exe\"" or action_process_image_command_line endswith ".gif" or action_process_image_command_line endswith ".gif\"" or action_process_image_command_line endswith ".hta" or action_process_image_command_line endswith ".hta\"" or action_process_image_command_line endswith ".jpeg" or action_process_image_command_line endswith ".jpeg\"" or action_process_image_command_line endswith ".log" or action_process_image_command_line endswith ".log\"" or action_process_image_command_line endswith ".msi" or action_process_image_command_line endswith ".msi\"" or action_process_image_command_line endswith ".png" or action_process_image_command_line endswith ".png\"" or action_process_image_command_line endswith ".ps1" or action_process_image_command_line endswith ".ps1\"" or action_process_image_command_line endswith ".psm1" or action_process_image_command_line endswith ".psm1\"" or action_process_image_command_line endswith ".vbe" or action_process_image_command_line endswith ".vbe\"" or action_process_image_command_line endswith ".vbs" or action_process_image_command_line endswith ".vbs\"" or action_process_image_command_line endswith ".bat'" or action_process_image_command_line endswith ".dat'" or action_process_image_command_line endswith ".dll'" or action_process_image_command_line endswith ".exe'" or action_process_image_command_line endswith ".gif'" or action_process_image_command_line endswith ".hta'" or action_process_image_command_line endswith ".jpeg'" or action_process_image_command_line endswith ".log'" or action_process_image_command_line endswith ".msi'" or action_process_image_command_line endswith ".png'" or action_process_image_command_line endswith ".ps1'" or action_process_image_command_line endswith ".psm1'" or action_process_image_command_line endswith ".vbe'" or action_process_image_command_line endswith ".vbs'")) and ((action_process_image_command_line contains " -O" or action_process_image_command_line contains "--remote-name" or action_process_image_command_line contains "--output")) and (action_process_image_command_line contains "http") and ((action_process_image_path endswith "\\curl.exe") or (action_process_image_name = "curl.exe")) and (action_process_image_command_line ~= "://[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"))
