// Title: Potentially Suspicious File Download From File Sharing Domain Via PowerShell.EXE
// ID: b6e04788-29e1-4557-bb14-77f761848ab8
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-02-23
// Tags: attack.execution
// Description: Detects potentially suspicious file downloads from file sharing domains using PowerShell.exe
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains ".DownloadString(" or action_process_image_command_line contains ".DownloadFile(" or action_process_image_command_line contains "Invoke-WebRequest " or action_process_image_command_line contains "iwr " or action_process_image_command_line contains "wget ")) and (((action_process_image_path endswith "\\powershell.exe" or action_process_image_path endswith "\\pwsh.exe")) or ((action_process_image_name = "PowerShell.EXE" or action_process_image_name = "pwsh.dll"))) and ((action_process_image_command_line contains "0x0.st" or action_process_image_command_line contains "anonfiles.com" or action_process_image_command_line contains "bashupload.com" or action_process_image_command_line contains "cdn.discordapp.com" or action_process_image_command_line contains "chunk.io" or action_process_image_command_line contains "ddns.net" or action_process_image_command_line contains "dl.dropboxusercontent.com" or action_process_image_command_line contains "ghostbin.co" or action_process_image_command_line contains "glitch.me" or action_process_image_command_line contains "gofile.io" or action_process_image_command_line contains "hastebin.com" or action_process_image_command_line contains "mediafire.com" or action_process_image_command_line contains "mega.nz" or action_process_image_command_line contains "onrender.com" or action_process_image_command_line contains "pages.dev" or action_process_image_command_line contains "paste.ee" or action_process_image_command_line contains "pastebin.com" or action_process_image_command_line contains "pastebin.pl" or action_process_image_command_line contains "pastetext.net" or action_process_image_command_line contains "pixeldrain.com" or action_process_image_command_line contains "privatlab.com" or action_process_image_command_line contains "privatlab.net" or action_process_image_command_line contains "send.exploit.in" or action_process_image_command_line contains "sendspace.com" or action_process_image_command_line contains "storage.googleapis.com" or action_process_image_command_line contains "storjshare.io" or action_process_image_command_line contains "supabase.co" or action_process_image_command_line contains "temp.sh" or action_process_image_command_line contains "transfer.sh" or action_process_image_command_line contains "trycloudflare.com" or action_process_image_command_line contains "ufile.io" or action_process_image_command_line contains "w3spaces.com" or action_process_image_command_line contains "workers.dev" or action_process_image_command_line contains "x0.at")))
