// Title: Suspicious PowerShell Invocations - Specific - ProcessCreation
// ID: 536e2947-3729-478c-9903-745aaffe60d2
// Status: test
// Level: medium
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-05
// Tags: attack.stealth
// Description: Detects suspicious PowerShell invocation command parameters
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "-nop" and action_process_image_command_line contains " -w " and action_process_image_command_line contains "hidden" and action_process_image_command_line contains " -c " and action_process_image_command_line contains "[Convert]::FromBase64String")) or ((action_process_image_command_line contains " -w " and action_process_image_command_line contains "hidden" and action_process_image_command_line contains "-ep" and action_process_image_command_line contains "bypass" and action_process_image_command_line contains "-Enc")) or ((action_process_image_command_line contains " -w " and action_process_image_command_line contains "hidden" and action_process_image_command_line contains "-noni" and action_process_image_command_line contains "-nop" and action_process_image_command_line contains " -c " and action_process_image_command_line contains "iex" and action_process_image_command_line contains "New-Object")) or ((action_process_image_command_line contains "iex" and action_process_image_command_line contains "New-Object" and action_process_image_command_line contains "Net.WebClient" and action_process_image_command_line contains ".Download")) or ((action_process_image_command_line contains "powershell" and action_process_image_command_line contains "reg" and action_process_image_command_line contains "add" and action_process_image_command_line contains "\\software\\")) or ((action_process_image_command_line contains "bypass" and action_process_image_command_line contains "-noprofile" and action_process_image_command_line contains "-windowstyle" and action_process_image_command_line contains "hidden" and action_process_image_command_line contains "new-object" and action_process_image_command_line contains "system.net.webclient" and action_process_image_command_line contains ".download"))) and not (((action_process_image_command_line contains "(New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1" or action_process_image_command_line contains "Write-ChocolateyWarning"))))
