// Title: Suspicious Manipulation Of Default Accounts Via Net.EXE
// ID: 5b768e71-86f2-4879-b448-81061cbae951
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-01
// Tags: attack.collection, attack.t1560.001
// Description: Detects suspicious manipulations of default accounts such as 'administrator' and 'guest'. For example 'enable' or 'disable' accounts or change the password...etc
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((((action_process_image_path endswith "\\net.exe" or action_process_image_path endswith "\\net1.exe")) or ((action_process_image_name = "net.exe" or action_process_image_name = "net1.exe"))) and (action_process_image_command_line contains " user ") and ((action_process_image_command_line contains " Järjestelmänvalvoja " or action_process_image_command_line contains " Rendszergazda " or action_process_image_command_line contains " Администратор " or action_process_image_command_line contains " Administrateur " or action_process_image_command_line contains " Administrador " or action_process_image_command_line contains " Administratör " or action_process_image_command_line contains " Administrator " or action_process_image_command_line contains " guest " or action_process_image_command_line contains " DefaultAccount " or action_process_image_command_line contains " \"Järjestelmänvalvoja\" " or action_process_image_command_line contains " \"Rendszergazda\" " or action_process_image_command_line contains " \"Администратор\" " or action_process_image_command_line contains " \"Administrateur\" " or action_process_image_command_line contains " \"Administrador\" " or action_process_image_command_line contains " \"Administratör\" " or action_process_image_command_line contains " \"Administrator\" " or action_process_image_command_line contains " \"guest\" " or action_process_image_command_line contains " \"DefaultAccount\" " or action_process_image_command_line contains " 'Järjestelmänvalvoja' " or action_process_image_command_line contains " 'Rendszergazda' " or action_process_image_command_line contains " 'Администратор' " or action_process_image_command_line contains " 'Administrateur' " or action_process_image_command_line contains " 'Administrador' " or action_process_image_command_line contains " 'Administratör' " or action_process_image_command_line contains " 'Administrator' " or action_process_image_command_line contains " 'guest' " or action_process_image_command_line contains " 'DefaultAccount' "))) and not (((action_process_image_command_line contains "guest" and action_process_image_command_line contains "/active no"))))
