// Title: Potential Netcat Reverse Shell Execution
// ID: 7f734ed0-4f47-46c0-837f-6ee62505abd9
// Status: test
// Level: high
// Author: @d4ns4n_, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-07
// Tags: attack.execution, attack.t1059
// Description: Detects execution of netcat with the "-e" or "-c" flags followed by common shells, which are commonly used to spawn reverse shells.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains " -c " or action_process_image_command_line contains " -e ")) and ((action_process_image_path endswith "/nc.openbsd" or action_process_image_path endswith "/nc.traditional" or action_process_image_path endswith "/nc" or action_process_image_path endswith "/ncat" or action_process_image_path endswith "/netcat.openbsd" or action_process_image_path endswith "/netcat.traditional" or action_process_image_path endswith "/netcat")) and ((action_process_image_command_line contains " ash" or action_process_image_command_line contains " bash" or action_process_image_command_line contains " bsh" or action_process_image_command_line contains " csh" or action_process_image_command_line contains " ksh" or action_process_image_command_line contains " pdksh" or action_process_image_command_line contains " sh" or action_process_image_command_line contains " tcsh" or action_process_image_command_line contains "/bin/ash" or action_process_image_command_line contains "/bin/bash" or action_process_image_command_line contains "/bin/bsh" or action_process_image_command_line contains "/bin/csh" or action_process_image_command_line contains "/bin/ksh" or action_process_image_command_line contains "/bin/pdksh" or action_process_image_command_line contains "/bin/sh" or action_process_image_command_line contains "/bin/tcsh" or action_process_image_command_line contains "/bin/zsh" or action_process_image_command_line contains "$IFSash" or action_process_image_command_line contains "$IFSbash" or action_process_image_command_line contains "$IFSbsh" or action_process_image_command_line contains "$IFScsh" or action_process_image_command_line contains "$IFSksh" or action_process_image_command_line contains "$IFSpdksh" or action_process_image_command_line contains "$IFSsh" or action_process_image_command_line contains "$IFStcsh" or action_process_image_command_line contains "$IFSzsh")))
