// Title: PowerShell Base64 Encoded IEX Cmdlet
// ID: 88f680b8-070e-402c-ae11-d2914f2257f1
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2019-08-23
// Tags: attack.execution, attack.t1059.001
// Description: Detects usage of a base64 encoded "IEX" cmdlet in a process command line
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "SUVYIChb" or action_process_image_command_line contains "lFWCAoW" or action_process_image_command_line contains "JRVggKF" or action_process_image_command_line contains "aWV4IChb" or action_process_image_command_line contains "lleCAoW" or action_process_image_command_line contains "pZXggKF" or action_process_image_command_line contains "aWV4IChOZX" or action_process_image_command_line contains "lleCAoTmV3" or action_process_image_command_line contains "pZXggKE5ld" or action_process_image_command_line contains "SUVYIChOZX" or action_process_image_command_line contains "lFWCAoTmV3" or action_process_image_command_line contains "JRVggKE5ld" or action_process_image_command_line contains "SUVYKF" or action_process_image_command_line contains "lFWChb" or action_process_image_command_line contains "JRVgoW" or action_process_image_command_line contains "aWV4KF" or action_process_image_command_line contains "lleChb" or action_process_image_command_line contains "pZXgoW" or action_process_image_command_line contains "aWV4KE5ld" or action_process_image_command_line contains "lleChOZX" or action_process_image_command_line contains "pZXgoTmV3" or action_process_image_command_line contains "SUVYKE5ld" or action_process_image_command_line contains "lFWChOZX" or action_process_image_command_line contains "JRVgoTmV3" or action_process_image_command_line contains "SUVYKCgn" or action_process_image_command_line contains "lFWCgoJ" or action_process_image_command_line contains "JRVgoKC" or action_process_image_command_line contains "aWV4KCgn" or action_process_image_command_line contains "lleCgoJ" or action_process_image_command_line contains "pZXgoKC")) or ((action_process_image_command_line contains "SQBFAFgAIAAoAFsA" or action_process_image_command_line contains "kARQBYACAAKABbA" or action_process_image_command_line contains "JAEUAWAAgACgAWw" or action_process_image_command_line contains "aQBlAHgAIAAoAFsA" or action_process_image_command_line contains "kAZQB4ACAAKABbA" or action_process_image_command_line contains "pAGUAeAAgACgAWw" or action_process_image_command_line contains "aQBlAHgAIAAoAE4AZQB3A" or action_process_image_command_line contains "kAZQB4ACAAKABOAGUAdw" or action_process_image_command_line contains "pAGUAeAAgACgATgBlAHcA" or action_process_image_command_line contains "SQBFAFgAIAAoAE4AZQB3A" or action_process_image_command_line contains "kARQBYACAAKABOAGUAdw" or action_process_image_command_line contains "JAEUAWAAgACgATgBlAHcA")))
