// Title: Potential Homoglyph Attack Using Lookalike Characters
// ID: 32e280f1-8ad4-46ef-9e80-910657611fbc
// Status: test
// Level: medium
// Author: Micah Babinski, @micahbabinski
// Date: 2023-05-07
// Tags: attack.stealth, attack.t1036, attack.t1036.003
// Description: Detects the presence of unicode characters which are homoglyphs, or identical in appearance, to ASCII letter characters.
// This is used as an obfuscation and masquerading techniques. Only "perfect" homoglyphs are included; these are characters that
// are indistinguishable from ASCII characters and thus may make excellent candidates for homoglyph attack characters.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((action_process_image_command_line contains "а" or action_process_image_command_line contains "е" or action_process_image_command_line contains "о" or action_process_image_command_line contains "р" or action_process_image_command_line contains "с" or action_process_image_command_line contains "х" or action_process_image_command_line contains "ѕ" or action_process_image_command_line contains "і" or action_process_image_command_line contains "ӏ" or action_process_image_command_line contains "ј" or action_process_image_command_line contains "һ" or action_process_image_command_line contains "ԁ" or action_process_image_command_line contains "ԛ" or action_process_image_command_line contains "ԝ" or action_process_image_command_line contains "ο")) or ((action_process_image_command_line contains "А" or action_process_image_command_line contains "В" or action_process_image_command_line contains "Е" or action_process_image_command_line contains "К" or action_process_image_command_line contains "М" or action_process_image_command_line contains "Н" or action_process_image_command_line contains "О" or action_process_image_command_line contains "Р" or action_process_image_command_line contains "С" or action_process_image_command_line contains "Т" or action_process_image_command_line contains "Х" or action_process_image_command_line contains "Ѕ" or action_process_image_command_line contains "І" or action_process_image_command_line contains "Ј" or action_process_image_command_line contains "Ү" or action_process_image_command_line contains "Ӏ" or action_process_image_command_line contains "Ԍ" or action_process_image_command_line contains "Ԛ" or action_process_image_command_line contains "Ԝ" or action_process_image_command_line contains "Α" or action_process_image_command_line contains "Β" or action_process_image_command_line contains "Ε" or action_process_image_command_line contains "Ζ" or action_process_image_command_line contains "Η" or action_process_image_command_line contains "Ι" or action_process_image_command_line contains "Κ" or action_process_image_command_line contains "Μ" or action_process_image_command_line contains "Ν" or action_process_image_command_line contains "Ο" or action_process_image_command_line contains "Ρ" or action_process_image_command_line contains "Τ" or action_process_image_command_line contains "Υ" or action_process_image_command_line contains "Χ")))
