// Title: Suspicious Command Patterns In Scheduled Task Creation
// ID: f2c64357-b1d2-41b7-849f-34d2682c0fad
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-02-23
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1053.005
// Description: Detects scheduled task creation using "schtasks" that contain potentially suspicious or uncommon commands
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((action_process_image_path endswith "\\schtasks.exe" and action_process_image_command_line contains "/Create ") and ((((action_process_image_command_line contains "/sc minute " or action_process_image_command_line contains "/ru system ")) and ((action_process_image_command_line contains "cmd /c" or action_process_image_command_line contains "cmd /k" or action_process_image_command_line contains "cmd /r" or action_process_image_command_line contains "cmd.exe /c " or action_process_image_command_line contains "cmd.exe /k " or action_process_image_command_line contains "cmd.exe /r "))) or ((action_process_image_command_line contains " -decode " or action_process_image_command_line contains " -enc " or action_process_image_command_line contains " -w hidden " or action_process_image_command_line contains " bypass " or action_process_image_command_line contains " IEX" or action_process_image_command_line contains ".DownloadData" or action_process_image_command_line contains ".DownloadFile" or action_process_image_command_line contains ".DownloadString" or action_process_image_command_line contains "/c start /min " or action_process_image_command_line contains "FromBase64String" or action_process_image_command_line contains "mshta http" or action_process_image_command_line contains "mshta.exe http")) or (((action_process_image_command_line contains ":\\ProgramData\\" or action_process_image_command_line contains ":\\Temp\\" or action_process_image_command_line contains ":\\Tmp\\" or action_process_image_command_line contains ":\\Users\\Public\\" or action_process_image_command_line contains ":\\Windows\\Temp\\" or action_process_image_command_line contains "\\AppData\\" or action_process_image_command_line contains "%AppData%" or action_process_image_command_line contains "%Temp%" or action_process_image_command_line contains "%tmp%")) and ((action_process_image_command_line contains "cscript" or action_process_image_command_line contains "curl" or action_process_image_command_line contains "wscript")))))
