// Title: Renamed AdFind Execution
// ID: df55196f-f105-44d3-a675-e9dfb6cc2f2b
// Status: test
// Level: high
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-21
// Tags: attack.discovery, attack.t1018, attack.t1087.002, attack.t1482, attack.t1069.002
// Description: Detects the use of a renamed Adfind.exe. AdFind continues to be seen across majority of breaches. It is used to domain trust discovery to plan out subsequent steps in the attack chain.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((((action_process_image_command_line contains "domainlist" or action_process_image_command_line contains "trustdmp" or action_process_image_command_line contains "dcmodes" or action_process_image_command_line contains "adinfo" or action_process_image_command_line contains " dclist " or action_process_image_command_line contains "computer_pwdnotreqd" or action_process_image_command_line contains "objectcategory=" or action_process_image_command_line contains "-subnets -f" or action_process_image_command_line contains "name=\"Domain Admins\"" or action_process_image_command_line contains "-sc u:" or action_process_image_command_line contains "domainncs" or action_process_image_command_line contains "dompol" or action_process_image_command_line contains " oudmp " or action_process_image_command_line contains "subnetdmp" or action_process_image_command_line contains "gpodmp" or action_process_image_command_line contains "fspdmp" or action_process_image_command_line contains "users_noexpire" or action_process_image_command_line contains "computers_active" or action_process_image_command_line contains "computers_pwdnotreqd")) or ((Hashes contains "IMPHASH=BCA5675746D13A1F246E2DA3C2217492" or Hashes contains "IMPHASH=53E117A96057EAF19C41380D0E87F1C2" or Hashes contains "IMPHASH=d144de8117df2beceaba2201ad304764" or Hashes contains "IMPHASH=12ce1c0f3f5837ecc18a3782408fa975" or Hashes contains "IMPHASH=4fbf3f084fbbb2470b80b2013134df35" or Hashes contains "IMPHASH=49b639b4acbecc49d72a01f357aa4930" or Hashes contains "IMPHASH=680dad9e300346e05a85023965867201" or Hashes contains "IMPHASH=21aa085d54992511b9f115355e468782")) or (action_process_image_name = "AdFind.exe")) and not ((action_process_image_path endswith "\\AdFind.exe")))
