// Title: Download from Suspicious Dyndns Hosts
// ID: 195c1119-ef07-4909-bb12-e66f5e07bf3c
// Status: test
// Level: medium
// Author: Florian Roth (Nextron Systems)
// Date: 2017-11-08
// Tags: attack.command-and-control, attack.t1105, attack.t1568
// Description: Detects download of certain file types from hosts with dynamic DNS names (selected list)
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((c-uri-extension = "exe" or c-uri-extension = "vbs" or c-uri-extension = "bat" or c-uri-extension = "rar" or c-uri-extension = "ps1" or c-uri-extension = "doc" or c-uri-extension = "docm" or c-uri-extension = "xls" or c-uri-extension = "xlsm" or c-uri-extension = "pptm" or c-uri-extension = "rtf" or c-uri-extension = "hta" or c-uri-extension = "dll" or c-uri-extension = "ws" or c-uri-extension = "wsf" or c-uri-extension = "sct" or c-uri-extension = "zip") and (cs-host endswith ".hopto.org" or cs-host endswith ".no-ip.org" or cs-host endswith ".no-ip.info" or cs-host endswith ".no-ip.biz" or cs-host endswith ".no-ip.com" or cs-host endswith ".noip.com" or cs-host endswith ".ddns.name" or cs-host endswith ".myftp.org" or cs-host endswith ".myftp.biz" or cs-host endswith ".serveblog.net" or cs-host endswith ".servebeer.com" or cs-host endswith ".servemp3.com" or cs-host endswith ".serveftp.com" or cs-host endswith ".servequake.com" or cs-host endswith ".servehalflife.com" or cs-host endswith ".servehttp.com" or cs-host endswith ".servegame.com" or cs-host endswith ".servepics.com" or cs-host endswith ".myvnc.com" or cs-host endswith ".ignorelist.com" or cs-host endswith ".jkub.com" or cs-host endswith ".dlinkddns.com" or cs-host endswith ".jumpingcrab.com" or cs-host endswith ".ddns.info" or cs-host endswith ".mooo.com" or cs-host endswith ".dns-dns.com" or cs-host endswith ".strangled.net" or cs-host endswith ".adultdns.net" or cs-host endswith ".craftx.biz" or cs-host endswith ".ddns01.com" or cs-host endswith ".dns53.biz" or cs-host endswith ".dnsapi.info" or cs-host endswith ".dnsd.info" or cs-host endswith ".dnsdynamic.com" or cs-host endswith ".dnsdynamic.net" or cs-host endswith ".dnsget.org" or cs-host endswith ".fe100.net" or cs-host endswith ".flashserv.net" or cs-host endswith ".ftp21.net" or cs-host endswith ".http01.com" or cs-host endswith ".http80.info" or cs-host endswith ".https443.com" or cs-host endswith ".imap01.com" or cs-host endswith ".kadm5.com" or cs-host endswith ".mysq1.net" or cs-host endswith ".ns360.info" or cs-host endswith ".ntdll.net" or cs-host endswith ".ole32.com" or cs-host endswith ".proxy8080.com" or cs-host endswith ".sql01.com" or cs-host endswith ".ssh01.com" or cs-host endswith ".ssh22.net" or cs-host endswith ".tempors.com" or cs-host endswith ".tftpd.net" or cs-host endswith ".ttl60.com" or cs-host endswith ".ttl60.org" or cs-host endswith ".user32.com" or cs-host endswith ".voip01.com" or cs-host endswith ".wow64.net" or cs-host endswith ".x64.me" or cs-host endswith ".xns01.com" or cs-host endswith ".dyndns.org" or cs-host endswith ".dyndns.info" or cs-host endswith ".dyndns.tv" or cs-host endswith ".dyndns-at-home.com" or cs-host endswith ".dnsomatic.com" or cs-host endswith ".zapto.org" or cs-host endswith ".webhop.net" or cs-host endswith ".25u.com" or cs-host endswith ".slyip.net"))
