// Title: Potential Defense Evasion Via Raw Disk Access By Uncommon Tools
// ID: db809f10-56ce-4420-8c86-d6a7d793c79c
// Status: test
// Level: low
// Author: Teymur Kheirkhabarov, oscd.community
// Date: 2019-10-22
// Tags: attack.stealth, attack.t1006
// Description: Detects raw disk access using uncommon tools or tools that are located in suspicious locations (heavy filtering is required), which could indicate possible defense evasion attempts
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (not (((Device contains "floppy") or ((action_process_image_path startswith "C:\\$WINDOWS.~BT\\" or action_process_image_path startswith "C:\\Program Files (x86)\\" or action_process_image_path startswith "C:\\Program Files\\" or action_process_image_path startswith "C:\\Windows\\CCM\\" or action_process_image_path startswith "C:\\Windows\\explorer.exe" or action_process_image_path startswith "C:\\Windows\\servicing\\" or action_process_image_path startswith "C:\\Windows\\SoftwareDistribution\\" or action_process_image_path startswith "C:\\Windows\\System32\\" or action_process_image_path startswith "C:\\Windows\\SystemApps\\" or action_process_image_path startswith "C:\\Windows\\SysWOW64\\" or action_process_image_path startswith "C:\\Windows\\uus\\" or action_process_image_path startswith "C:\\Windows\\WinSxS\\")) or (action_process_image_path startswith "C:\\Users\\" and (action_process_image_path contains "\\AppData\\" and action_process_image_path contains "\\Microsoft\\")) or (action_process_image_path = null) or (action_process_image_path startswith "C:\\Windows\\Temp\\" and (action_process_image_path endswith "\\Executables\\SSDUpdate.exe" or action_process_image_path endswith "\\HostMetadata\\NVMEHostmetadata.exe")) or ((action_process_image_path = "Registry" or action_process_image_path = "System")) or (action_process_image_path = "C:\\Windows\\ImmersiveControlPanel\\SystemSettings.exe") or (action_process_image_path startswith "C:\\$WinREAgent\\Scratch\\") or (action_process_image_path startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" and (action_process_image_path endswith "\\MsMpEng.exe" or action_process_image_path endswith "\\MpDefenderCoreService.exe")))) and not (((action_process_image_path startswith "C:\\Users\\" and action_process_image_path contains "\\AppData\\Local\\Keybase\\upd.exe") or (action_process_image_path startswith "C:\\Users\\" and action_process_image_path contains "\\AppData\\Local\\GitHubDesktop\\app-" and action_process_image_path endswith "\\resources\\app\\git\\mingw64\\bin\\git.exe") or (action_process_image_path startswith "C:\\Windows\\Temp\\asgard2-agent\\" and action_process_image_path endswith "\\thor.exe"))))
