// Title: Removal of Potential COM Hijacking Registry Keys
// ID: 96f697b0-b499-4e5d-9908-a67bec11cdb6
// Status: test
// Level: medium
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects any deletion of entries in ".*\shell\open\command" registry keys.
// These registry keys might have been used for COM hijacking activities by a threat actor or an attacker and the deletion could indicate steps to remove its tracks.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((TargetObject endswith "\\shell\\open\\command") and not (((action_process_image_path endswith "C:\\Windows\\explorer.exe") or ((action_process_image_path startswith "C:\\Program Files\\" or action_process_image_path startswith "C:\\Program Files (x86)\\")) or ((action_process_image_path = "C:\\Windows\\System32\\msiexec.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\msiexec.exe")) or (action_process_image_path = "C:\\Windows\\System32\\OpenWith.exe") or (action_process_image_path = "C:\\Windows\\system32\\svchost.exe"))) and not ((((action_process_image_path = "C:\\Program Files (x86)\\Avira\\Antivirus\\" or action_process_image_path = "C:\\Program Files\\Avira\\Antivirus\\") and (TargetObject endswith "\\CLSID\\{305CA226-D286-468e-B848-2B2E8E697B74}\\Shell\\Open\\Command" or TargetObject endswith "\\AntiVir.Keyfile\\shell\\open\\command")) or (action_process_image_path endswith "\\reg.exe" and TargetObject endswith "\\Discord\\shell\\open\\command") or (action_process_image_path endswith "\\Dropbox.exe" and TargetObject contains "\\Dropbox.") or (action_process_image_path endswith "C:\\eclipse\\eclipse.exe" and TargetObject contains "_Classes\\eclipse+") or (action_process_image_path contains "\\Microsoft\\EdgeUpdate\\Install") or (action_process_image_path endswith "\\Everything.exe" and TargetObject contains "\\Everything.") or (((action_process_image_path contains "AppData\\Local\\Temp" and action_process_image_path contains "\\setup.exe")) or ((action_process_image_path contains "\\Temp\\is-" and action_process_image_path contains "\\target.tmp"))) or (action_process_image_path startswith "C:\\Program Files (x86)\\Java\\" and action_process_image_path endswith "\\installer.exe" and TargetObject contains "\\Classes\\WOW6432Node\\CLSID\\{4299124F-F2C3-41b4-9C73-9236B2AD0E8F}") or (action_process_image_path endswith "\\ninite.exe") or (action_process_image_path contains "peazip" and TargetObject contains "\\PeaZip.") or (action_process_image_path endswith "\\Spotify.exe" and TargetObject endswith "\\Spotify\\shell\\open\\command") or ((action_process_image_path contains "\\Temp" and action_process_image_path contains "\\TeamViewer")) or (action_process_image_path startswith "C:\\Windows\\Installer\\MSI") or (action_process_image_path endswith "\\AppData\\Local\\Temp\\Wireshark_uninstaller.exe" and TargetObject contains "\\wireshark-capture-file\\"))))
