// Title: Disable Internal Tools or Feature in Registry
// ID: e2482f8d-3443-4237-b906-cc145d87a076
// Status: test
// Level: medium
// Author: frack113, Nasreddine Bencherchali (Nextron Systems), CrimpSec
// Date: 2022-03-18
// Tags: attack.persistence, attack.defense-impairment, attack.t1112
// Description: Detects registry modifications that change features of internal Windows tools (malware like Agent Tesla uses this technique)
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\ConsentPromptBehaviorAdmin" or TargetObject endswith "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\InactivityTimeoutSecs" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\shutdownwithoutlogon" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\PushNotifications\\ToastEnabled" or TargetObject endswith "SYSTEM\\CurrentControlSet\\Control\\Storage\\Write Protection" or TargetObject endswith "SYSTEM\\CurrentControlSet\\Control\\StorageDevicePolicies\\WriteProtect") and Details = "DWORD (0x00000000)") or ((TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\DisableCMD" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\NoControlPanel" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\NoRun" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\StartMenuLogOff" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\DisableChangePassword" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\DisableLockWorkstation" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\DisableRegistryTools" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\DisableTaskmgr" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\NoDispBackgroundPage" or TargetObject endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\NoDispCPL" or TargetObject endswith "SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer\\DisableNotificationCenter" or TargetObject endswith "SOFTWARE\\Policies\\Microsoft\\Windows\\System\\DisableCMD") and Details = "DWORD (0x00000001)"))
