// Title: Suspicious Execution Of Renamed Sysinternals Tools - Registry
// ID: f50f3c09-557d-492d-81db-9064a8d4e211
// Status: test
// Level: high
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-24
// Tags: attack.resource-development, attack.t1588.002
// Description: Detects the creation of the "accepteula" key related to the Sysinternals tools being created from executables with the wrong name (e.g. a renamed Sysinternals tool)
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((TargetObject contains "\\Active Directory Explorer" or TargetObject contains "\\Handle" or TargetObject contains "\\LiveKd" or TargetObject contains "\\ProcDump" or TargetObject contains "\\Process Explorer" or TargetObject contains "\\PsExec" or TargetObject contains "\\PsLoggedon" or TargetObject contains "\\PsLoglist" or TargetObject contains "\\PsPasswd" or TargetObject contains "\\PsPing" or TargetObject contains "\\PsService" or TargetObject contains "\\SDelete") and TargetObject endswith "\\EulaAccepted") and not (((action_process_image_path endswith "\\ADExplorer.exe" or action_process_image_path endswith "\\ADExplorer64.exe" or action_process_image_path endswith "\\ADExplorer64a.exe" or action_process_image_path endswith "\\handle.exe" or action_process_image_path endswith "\\handle64.exe" or action_process_image_path endswith "\\handle64a.exe" or action_process_image_path endswith "\\livekd.exe" or action_process_image_path endswith "\\livekd64.exe" or action_process_image_path endswith "\\procdump.exe" or action_process_image_path endswith "\\procdump64.exe" or action_process_image_path endswith "\\procdump64a.exe" or action_process_image_path endswith "\\procexp.exe" or action_process_image_path endswith "\\procexp64.exe" or action_process_image_path endswith "\\procexp64a.exe" or action_process_image_path endswith "\\PsExec.exe" or action_process_image_path endswith "\\PsExec64.exe" or action_process_image_path endswith "\\PsExec64a.exe" or action_process_image_path endswith "\\PsLoggedon.exe" or action_process_image_path endswith "\\PsLoggedon64.exe" or action_process_image_path endswith "\\psloglist.exe" or action_process_image_path endswith "\\psloglist64.exe" or action_process_image_path endswith "\\psloglist64a.exe" or action_process_image_path endswith "\\pspasswd.exe" or action_process_image_path endswith "\\pspasswd64.exe" or action_process_image_path endswith "\\pspasswd64a.exe" or action_process_image_path endswith "\\PsPing.exe" or action_process_image_path endswith "\\PsPing64.exe" or action_process_image_path endswith "\\PsPing64a.exe" or action_process_image_path endswith "\\PsService.exe" or action_process_image_path endswith "\\PsService64.exe" or action_process_image_path endswith "\\PsService64a.exe" or action_process_image_path endswith "\\sdelete.exe"))))
