// Title: Potential Persistence Via Visual Studio Tools for Office
// ID: 9d15044a-7cfe-4d23-8085-6ebc11df7685
// Status: test
// Level: medium
// Author: Bhabesh Raj
// Date: 2021-01-10
// Tags: attack.t1137.006, attack.persistence
// Description: Detects persistence via Visual Studio Tools for Office (VSTO) add-ins in Office applications.
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((TargetObject contains "\\Software\\Microsoft\\Office\\Outlook\\Addins\\" or TargetObject contains "\\Software\\Microsoft\\Office\\Word\\Addins\\" or TargetObject contains "\\Software\\Microsoft\\Office\\Excel\\Addins\\" or TargetObject contains "\\Software\\Microsoft\\Office\\Powerpoint\\Addins\\" or TargetObject contains "\\Software\\Microsoft\\VSTO\\Security\\Inclusion\\")) and not ((((action_process_image_path = "C:\\Program Files (x86)\\Microsoft Office\\root\\integration\\integrator.exe" or action_process_image_path = "C:\\Program Files\\Microsoft Office\\root\\integration\\integrator.exe")) or ((action_process_image_path startswith "C:\\Program Files\\Microsoft Office\\OFFICE" or action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft Office\\OFFICE" or action_process_image_path startswith "C:\\Program Files\\Microsoft Office\\Root\\OFFICE" or action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft Office\\Root\\OFFICE" or action_process_image_path startswith "C:\\PROGRA~2\\MICROS~2\\Office") and (action_process_image_path endswith "\\excel.exe" or action_process_image_path endswith "\\Integrator.exe" or action_process_image_path endswith "\\OneNote.exe" or action_process_image_path endswith "\\outlook.exe" or action_process_image_path endswith "\\powerpnt.exe" or action_process_image_path endswith "\\Teams.exe" or action_process_image_path endswith "\\visio.exe" or action_process_image_path endswith "\\winword.exe")) or ((action_process_image_path startswith "C:\\Program Files\\Common Files (x86)\\Microsoft Shared\\ClickToRun\\" or action_process_image_path startswith "C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\") and action_process_image_path endswith "\\OfficeClickToRun.exe") or ((action_process_image_path = "C:\\Windows\\System32\\msiexec.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\msiexec.exe" or action_process_image_path = "C:\\Windows\\System32\\regsvr32.exe" or action_process_image_path = "C:\\Windows\\SysWOW64\\regsvr32.exe")) or ((action_process_image_path startswith "C:\\Program Files\\Common Files\\Microsoft Shared\\VSTO\\" or action_process_image_path startswith "C:\\Program Files (x86)\\Microsoft Shared\\VSTO\\") and action_process_image_path endswith "\\VSTOInstaller.exe"))) and not ((((action_process_image_path = "C:\\Program Files\\Avast Software\\Avast\\RegSvr.exe" or action_process_image_path = "C:\\Program Files (x86)\\Avast Software\\Avast\\RegSvr.exe") and TargetObject contains "\\Microsoft\\Office\\Outlook\\Addins\\Avast.AsOutExt\\") or ((action_process_image_path = "C:\\Program Files\\AVG\\Antivirus\\RegSvr.exe" or action_process_image_path = "C:\\Program Files (x86)\\AVG\\Antivirus\\RegSvr.exe") and TargetObject contains "\\Microsoft\\Office\\Outlook\\Addins\\Antivirus.AsOutExt\\"))))
