// Title: Scheduled TaskCache Change by Uncommon Program
// ID: 4720b7df-40c3-48fd-bbdf-fd4b3c464f0d
// Status: test
// Level: high
// Author: Syed Hasan (@syedhasan009)
// Date: 2021-06-18
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053, attack.t1053.005
// Description: Monitor the creation of a new key under 'TaskCache' when a new scheduled task is registered by a process that is not svchost.exe, which is suspicious
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((TargetObject contains "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\") and not (((Details = "(Empty)") or (action_process_image_path = "C:\\Windows\\explorer.exe" and TargetObject contains "\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree\\Microsoft\\Windows\\PLA\\Server Manager Performance Monitor\\") or (action_process_image_path endswith "C:\\Windows\\System32\\MoUsoCoreWorker.exe") or (action_process_image_path = "C:\\Windows\\System32\\msiexec.exe") or (action_process_image_path startswith "C:\\Windows\\Microsoft.NET\\Framework" and action_process_image_path endswith "\\ngen.exe" and (TargetObject contains "\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tasks\\{B66B135D-DA06-4FC4-95F8-7458E1D10129}" or TargetObject contains "\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree\\Microsoft\\Windows\\.NET Framework\\.NET Framework NGEN")) or (Details = null) or ((action_process_image_path = "C:\\Program Files\\Microsoft Office\\root\\Integration\\Integrator.exe" or action_process_image_path = "C:\\Program Files (x86)\\Microsoft Office\\root\\Integration\\Integrator.exe" or action_process_image_path = "C:\\Program Files\\Common Files\\microsoft shared\\ClickToRun\\OfficeC2RClient.exe" or action_process_image_path = "C:\\Program Files (x86)\\Common Files\\microsoft shared\\ClickToRun\\OfficeC2RClient.exe")) or ((TargetObject contains "Microsoft\\Windows\\UpdateOrchestrator" or TargetObject contains "Microsoft\\Windows\\SoftwareProtectionPlatform\\SvcRestartTask\\Index" or TargetObject contains "Microsoft\\Windows\\Flighting\\OneSettings\\RefreshCache\\Index")) or (action_process_image_path = "C:\\Windows\\System32\\RuntimeBroker.exe") or (action_process_image_path endswith "C:\\Windows\\System32\\services.exe") or (action_process_image_path = "C:\\WINDOWS\\system32\\svchost.exe") or (action_process_image_path = "System") or (action_process_image_path startswith "C:\\Windows\\" and action_process_image_path endswith "\\TiWorker.exe"))) and not ((((action_process_image_path = "C:\\Program Files (x86)\\Dropbox\\Update\\DropboxUpdate.exe" or action_process_image_path = "C:\\Program Files\\Dropbox\\Update\\DropboxUpdate.exe")) or ((action_process_image_path endswith "C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\MicrosoftEdgeUpdate.exe" or action_process_image_path endswith "C:\\Program Files\\Microsoft\\EdgeUpdate\\MicrosoftEdgeUpdate.exe")) or ((action_process_image_path endswith "C:\\Program Files (x86)\\Microsoft OneDrive\\OneDrive.exe" or action_process_image_path endswith "C:\\Program Files\\Microsoft OneDrive\\OneDrive.exe")))))
