// Title: Uncommon New Firewall Rule Added In Windows Firewall Exception List
// ID: cde0a575-7d3d-4a49-9817-b8004a7bf105
// Status: test
// Level: medium
// Author: frack113
// Date: 2022-02-19
// Tags: attack.defense-impairment, attack.t1686.003
// Description: Detects when a rule has been added to the Windows Firewall exception list
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter (((EventID = 2004 or EventID = 2071 or EventID = 2097)) and not (((Action = 2) or ((ApplicationPath contains "C:\\PerfLogs\\" or ApplicationPath contains "C:\\Temp\\" or ApplicationPath contains "C:\\Tmp\\" or ApplicationPath contains "C:\\Users\\Public\\" or ApplicationPath contains "C:\\Windows\\Tasks\\" or ApplicationPath contains "C:\\Windows\\Temp\\" or ApplicationPath contains "\\AppData\\Local\\Temp\\")) or (ApplicationPath startswith "C:\\Windows\\ehome\\" and ModifyingApplication = "C:\\Windows\\System32\\oobe\\Setup.exe") or ((ApplicationPath startswith "C:\\Program Files (x86)\\" or ApplicationPath startswith "C:\\Program Files\\" or ApplicationPath startswith "C:\\Windows\\System32\\" or ApplicationPath startswith "C:\\Windows\\SysWOW64\\" or ApplicationPath startswith "C:\\Windows\\WinSxS\\")) or (ApplicationPath = null) or (ApplicationPath = "SYSTEM" and (ModifyingApplication = "C:\\Windows\\System32\\dllhost.exe" or ModifyingApplication = "C:\\Windows\\System32\\oobe\\Setup.exe" or ModifyingApplication = "C:\\Windows\\System32\\svchost.exe")) or (ModifyingApplication startswith "C:\\Windows\\WinSxS\\" and ModifyingApplication endswith "\\TiWorker.exe"))) and not (((((ModifyingApplication startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" or ModifyingApplication startswith "C:\\Program Files\\Windows Defender\\") and ModifyingApplication endswith "\\MsMpEng.exe") or ((ApplicationPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" or ApplicationPath startswith "C:\\Program Files\\Windows Defender\\") and ApplicationPath endswith "\\MsMpEng.exe")) or ((ModifyingApplication = "C:\\Windows\\System32\\svchost.exe" or ModifyingApplication = "C:\\Windows\\System32\\dllhost.exe") and ApplicationPath = "") or (ApplicationPath startswith "C:\\Windows\\SystemApps\\" and ModifyingApplication = "C:\\Windows\\System32\\svchost.exe"))))
