// Title: Invoke-Obfuscation Obfuscated IEX Invocation - System
// ID: 51aa9387-1c53-4153-91cc-d73c59ae1ca9
// Status: test
// Level: high
// Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
// Date: 2019-11-08
// Tags: attack.stealth, attack.t1027
// Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the code block linked in the references
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((EventID = 7045) and ((ImagePath ~= "\\$PSHome\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$PSHome\\[") or (ImagePath ~= "\\$ShellId\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$ShellId\\[") or (ImagePath ~= "\\$env:Public\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$env:Public\\[") or (ImagePath ~= "\\$env:ComSpec\\[(\\s*\\d{1,3}\\s*,){2}") or (ImagePath ~= "\\\\*mdr\\*\\W\\s*\\)\\.Name") or (ImagePath ~= "\\$VerbosePreference\\.ToString\\(") or (ImagePath ~= "\\String\\]\\s*\\$VerbosePreference")))
