// Title: Invoke-Obfuscation Obfuscated IEX Invocation - Security
// ID: fd0f5778-d3cb-4c9a-9695-66759d04702a
// Status: test
// Level: high
// Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
// Date: 2019-11-08
// Tags: attack.stealth, attack.t1027
// Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the code block linked in the references
// Converted by: Sigma Universal SIEM/EDR CLI

dataset = xdr_data | filter ((EventID = 4697) and ((ServiceFileName ~= "\\$PSHome\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$PSHome\\[") or (ServiceFileName ~= "\\$ShellId\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$ShellId\\[") or (ServiceFileName ~= "\\$env:Public\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$env:Public\\[") or (ServiceFileName ~= "\\$env:ComSpec\\[(\\s*\\d{1,3}\\s*,){2}") or (ServiceFileName ~= "\\\\*mdr\\*\\W\\s*\\)\\.Name") or (ServiceFileName ~= "\\$VerbosePreference\\.ToString\\(") or (ServiceFileName ~= "\\String\\]\\s*\\$VerbosePreference")))
