# Title: HackTool - SafetyKatz Dump Indicator
# ID: e074832a-eada-4fd7-94a1-10642b130e16
# Status: test
# Level: high
# Author: Markus Neis
# Date: 2018-07-24
# Tags: attack.credential-access, attack.t1003.001
# Description: Detects default lsass dump filename generated by SafetyKatz.
# Converted by: Sigma Universal SIEM/EDR CLI

# Panther Detection Rule: HackTool - SafetyKatz Dump Indicator
def rule(event):
    # Detection Logic:
    # (TargetFilename="*\\Temp\\debug.bin")
    return True

def title(event):
    return "HackTool - SafetyKatz Dump Indicator"

