# Title: Invoke-Obfuscation Obfuscated IEX Invocation - PowerShell Module
# ID: 2f211361-7dce-442d-b78a-c04039677378
# Status: test
# Level: high
# Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
# Date: 2019-11-08
# Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
# Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the code block cited in the reference section below
# Converted by: Sigma Universal SIEM/EDR CLI

# Panther Detection Rule: Invoke-Obfuscation Obfuscated IEX Invocation - PowerShell Module
def rule(event):
    # Detection Logic:
    # ((Payload=regex("\\$PSHome\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$PSHome\\[")) OR (Payload=regex("\\$ShellId\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$ShellId\\[")) OR (Payload=regex("\\$env:Public\\[\\s*\\d{1,3}\\s*\\]\\s*\\+\\s*\\$env:Public\\[")) OR (Payload=regex("\\$env:ComSpec\\[(\\s*\\d{1,3}\\s*,){2}")) OR (Payload=regex("\\*mdr\\*\\W\\s*\\)\\.Name")) OR (Payload=regex("\\$VerbosePreference\\.ToString\\(")) OR (Payload=regex("\\[String\\]\\s*\\$VerbosePreference")))
    return True

def title(event):
    return "Invoke-Obfuscation Obfuscated IEX Invocation - PowerShell Module"

