// Title: PowerView PowerShell Cmdlets - ScriptBlock
// ID: dcd74b95-3f36-4ed9-9598-0490951643aa
// Status: test
// Level: high
// Author: Bhabesh Raj
// Date: 2021-05-18
// Tags: attack.execution, attack.t1059.001
// Description: Detects Cmdlet names from PowerView of the PowerSploit exploitation framework.
// Converted by: Sigma Universal SIEM/EDR CLI

((ScriptBlockText: "*Export-PowerViewCSV*" OR ScriptBlockText: "*Find-DomainLocalGroupMember*" OR ScriptBlockText: "*Find-DomainObjectPropertyOutlier*" OR ScriptBlockText: "*Find-DomainProcess*" OR ScriptBlockText: "*Find-DomainShare*" OR ScriptBlockText: "*Find-DomainUserEvent*" OR ScriptBlockText: "*Find-DomainUserLocation*" OR ScriptBlockText: "*Find-ForeignGroup*" OR ScriptBlockText: "*Find-ForeignUser*" OR ScriptBlockText: "*Find-GPOComputerAdmin*" OR ScriptBlockText: "*Find-GPOLocation*" OR ScriptBlockText: "*Find-InterestingDomain*" OR ScriptBlockText: "*Find-InterestingFile*" OR ScriptBlockText: "*Find-LocalAdminAccess*" OR ScriptBlockText: "*Find-ManagedSecurityGroups*" OR ScriptBlockText: "*Get-CachedRDPConnection*" OR ScriptBlockText: "*Get-DFSshare*" OR ScriptBlockText: "*Get-DomainDFSShare*" OR ScriptBlockText: "*Get-DomainDNSRecord*" OR ScriptBlockText: "*Get-DomainDNSZone*" OR ScriptBlockText: "*Get-DomainFileServer*" OR ScriptBlockText: "*Get-DomainGPOComputerLocalGroupMapping*" OR ScriptBlockText: "*Get-DomainGPOLocalGroup*" OR ScriptBlockText: "*Get-DomainGPOUserLocalGroupMapping*" OR ScriptBlockText: "*Get-LastLoggedOn*" OR ScriptBlockText: "*Get-LoggedOnLocal*" OR ScriptBlockText: "*Get-NetFileServer*" OR ScriptBlockText: "*Get-NetForest*" OR ScriptBlockText: "*Get-NetGPOGroup*" OR ScriptBlockText: "*Get-NetProcess*" OR ScriptBlockText: "*Get-NetRDPSession*" OR ScriptBlockText: "*Get-RegistryMountedDrive*" OR ScriptBlockText: "*Get-RegLoggedOn*" OR ScriptBlockText: "*Get-WMIRegCachedRDPConnection*" OR ScriptBlockText: "*Get-WMIRegLastLoggedOn*" OR ScriptBlockText: "*Get-WMIRegMountedDrive*" OR ScriptBlockText: "*Get-WMIRegProxy*" OR ScriptBlockText: "*Invoke-ACLScanner*" OR ScriptBlockText: "*Invoke-CheckLocalAdminAccess*" OR ScriptBlockText: "*Invoke-EnumerateLocalAdmin*" OR ScriptBlockText: "*Invoke-EventHunter*" OR ScriptBlockText: "*Invoke-FileFinder*" OR ScriptBlockText: "*Invoke-Kerberoast*" OR ScriptBlockText: "*Invoke-MapDomainTrust*" OR ScriptBlockText: "*Invoke-ProcessHunter*" OR ScriptBlockText: "*Invoke-RevertToSelf*" OR ScriptBlockText: "*Invoke-ShareFinder*" OR ScriptBlockText: "*Invoke-UserHunter*" OR ScriptBlockText: "*Invoke-UserImpersonation*" OR ScriptBlockText: "*Remove-RemoteConnection*" OR ScriptBlockText: "*Request-SPNTicket*" OR ScriptBlockText: "*Resolve-IPAddress*"))
