// Title: Potentially Suspicious AccessMask Requested From LSASS
// ID: 4a1b6da0-d94f-4fc3-98fc-2d9cb9e5ee76
// Status: test
// Level: medium
// Author: Roberto Rodriguez, Teymur Kheirkhabarov, Dimitrios Slamaris, Mark Russinovich, Aleksey Potapov, oscd.community (update)
// Date: 2019-11-01
// Tags: attack.credential-access, car.2019-04-004, attack.t1003.001
// Description: Detects process handle on LSASS process with certain access mask
// Converted by: Sigma Universal SIEM/EDR CLI

(((EventID: "4656" AND ObjectName="*\\lsass.exe" AND (AccessMask: "*0x40*" OR AccessMask: "*0x1400*" OR AccessMask: "*0x100000*" OR AccessMask: "*0x1410*" OR AccessMask: "*0x1010*" OR AccessMask: "*0x1438*" OR AccessMask: "*0x143a*" OR AccessMask: "*0x1418*" OR AccessMask: "*0x1f0fff*" OR AccessMask: "*0x1f1fff*" OR AccessMask: "*0x1f2fff*" OR AccessMask: "*0x1f3fff*")) OR (EventID: "4663" AND ObjectName="*\\lsass.exe" AND (AccessList: "*4484*" OR AccessList: "*4416*"))) AND NOT (((ProcessName: "*:\\Windows\\Temp\\asgard2-agent-sc\\aurora\\*" AND ProcessName="*\\aurora-agent-64.exe" AND AccessList: "*%%4484*") OR ((ProcessName: "*:\\Users\\*" AND ProcessName: "*\\AppData\\Local\\Temp\\is-*") AND ProcessName="*\\avira_system_speedup.tmp" AND AccessList: "*%%4484*") OR (ProcessName: "*:\\Windows\\Temp\\*" AND ProcessName="*\\avira_speedup_setup_update.tmp" AND AccessList: "*%%4484*") OR ((ProcessName="*:\\Windows\\System32\\taskhostw.exe" OR ProcessName="*:\\Windows\\System32\\msiexec.exe" OR ProcessName="*:\\Windows\\CCM\\CcmExec.exe")) OR (ProcessName: "*:\\Program Files*") OR (ProcessName: "*:\\Windows\\SystemTemp\\*" AND ProcessName="*\\GoogleUpdate.exe" AND AccessList: "*%%4484*") OR (ProcessName="*\\x64\\SCENARIOENGINE.EXE" AND AccessList: "*%%4484*") OR (ProcessName="*:\\Windows\\System32\\snmp.exe" AND AccessList: "*%%4484*") OR ((ProcessName="*\\csrss.exe" OR ProcessName="*\\GamingServices.exe" OR ProcessName="*\\lsm.exe" OR ProcessName="*\\MicrosoftEdgeUpdate.exe" OR ProcessName="*\\minionhost.exe" OR ProcessName="*\\MRT.exe" OR ProcessName="*\\MsMpEng.exe" OR ProcessName="*\\perfmon.exe" OR ProcessName="*\\procexp.exe" OR ProcessName="*\\procexp64.exe" OR ProcessName="*\\procexp64a.exe" OR ProcessName="*\\svchost.exe" OR ProcessName="*\\taskmgr.exe" OR ProcessName="*\\thor.exe" OR ProcessName="*\\thor64.exe" OR ProcessName="*\\vmtoolsd.exe" OR ProcessName="*\\VsTskMgr.exe" OR ProcessName="*\\wininit.exe" OR ProcessName="*\\wmiprvse.exe" OR ProcessName="*RtkAudUService64") AND (ProcessName: "*:\\Program Files (x86)\\*" OR ProcessName: "*:\\Program Files\\*" OR ProcessName: "*:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\*" OR ProcessName: "*:\\Windows\\SysNative\\*" OR ProcessName: "*:\\Windows\\System32\\*" OR ProcessName: "*:\\Windows\\SysWow64\\*" OR ProcessName: "*:\\Windows\\Temp\\asgard2-agent\\*")) OR ((ProcessName="*:\\Windows\\Sysmon64.exe" OR ProcessName="*:\\Windows\\Sysmon64a.exe") AND AccessList: "*%%4484*"))) AND NOT (((ProcessName="*\\procmon64.exe" OR ProcessName="*\\procmon64a.exe" OR ProcessName="*\\procmon.exe") AND AccessList: "*%%4484*")))
