-- Title: Antivirus - APT Malware Signature
-- ID: 101a1877-2cf4-474d-abfd-7f6ac4788d1a
-- Status: experimental
-- Level: critical
-- Author: Arnim Rupp (Nextron Systems)
-- Date: 2026-06-15
-- Tags: attack.execution, attack.t1203, attack.command-and-control, attack.t1219.002
-- Description: Detects a highly relevant Antivirus alert that reports APT malware.
-- This event must not be ignored just because the AV has blocked the malware but investigate, how it came there in the first place.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE (((REGEXP_LIKE(Signature, 'APT\d') OR REGEXP_LIKE(Signature, 'ATK\d') OR REGEXP_LIKE(Signature, 'UNC\d') OR REGEXP_LIKE(Signature, 'UAC\d'))) OR ((Signature ILIKE '%[APT]%' OR Signature ILIKE '%APT_%' OR Signature ILIKE '%APT-%' OR Signature ILIKE '%BackOrder%' OR Signature ILIKE '%BlindingCan%' OR Signature ILIKE '%Blizzard%' OR Signature ILIKE '%Chollima%' OR Signature ILIKE '%Cleaver%' OR Signature ILIKE '%Cobra%' OR Signature ILIKE '%DarkHotel%' OR Signature ILIKE '%Dragon%' OR Signature ILIKE '%DTrack%' OR Signature ILIKE '%Equation%' OR Signature ILIKE '%GiftedCrook%' OR Signature ILIKE '%GraphSteel%' OR Signature ILIKE '%GreyEnergy%' OR Signature ILIKE '%GEnergy%' OR Signature ILIKE '%GrimPlant%' OR Signature ILIKE '%Hydra%' OR Signature ILIKE '%Jackal%' OR Signature ILIKE '%Kitten%' OR Signature ILIKE '%Kimsuky%' OR Signature ILIKE '%Lazar%' OR Signature ILIKE '%LightRail%' OR Signature ILIKE '%Lotus%' OR Signature ILIKE '%Luminous%' OR Signature ILIKE '%LumiMoth%' OR Signature ILIKE '%Nimbus%' OR Signature ILIKE '%Manticore%' OR Signature ILIKE '%MiniBike%' OR Signature ILIKE '%MiniBrowse%' OR Signature ILIKE '%MiniBus%' OR Signature ILIKE '%MiniFast%' OR Signature ILIKE '%MiniJuke%' OR Signature ILIKE '%MiniUpdate%' OR Signature ILIKE '%MuddyWater%' OR Signature ILIKE '%NukeSped%' OR Signature ILIKE '%OilRig%' OR Signature ILIKE '%Panda%' OR Signature ILIKE '%Sandstorm%' OR Signature ILIKE '%SandWorm%' OR Signature ILIKE '%Seamonkey%' OR Signature ILIKE '%Sleet%' OR Signature ILIKE '%SlugResin%' OR Signature ILIKE '%SnailResin%' OR Signature ILIKE '%Snake%' OR Signature ILIKE '%Tempest%' OR Signature ILIKE '%Tsunami%' OR Signature ILIKE '%Turla%' OR Signature ILIKE '%Typhoon%' OR Signature ILIKE '%UAC_%' OR Signature ILIKE '%UAC-%' OR Signature ILIKE '%UNC_%' OR Signature ILIKE '%UNC-%' OR Signature ILIKE '%VinoSiren%' OR Signature ILIKE '%Winnti%')))
