-- Title: Rare Remote Thread Creation By Uncommon Source Image
-- ID: 02d1d718-dd13-41af-989d-ea85c7fab93f
-- Status: test
-- Level: high
-- Author: Perez Diego (@darkquassar), oscd.community
-- Date: 2019-10-27
-- Tags: attack.privilege-escalation, attack.stealth, attack.t1055
-- Description: Detects uncommon processes creating remote threads.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE (((SourceImage ILIKE '%\\bash.exe' OR SourceImage ILIKE '%\\cscript.exe' OR SourceImage ILIKE '%\\cvtres.exe' OR SourceImage ILIKE '%\\defrag.exe' OR SourceImage ILIKE '%\\dialer.exe' OR SourceImage ILIKE '%\\dnx.exe' OR SourceImage ILIKE '%\\esentutl.exe' OR SourceImage ILIKE '%\\excel.exe' OR SourceImage ILIKE '%\\expand.exe' OR SourceImage ILIKE '%\\find.exe' OR SourceImage ILIKE '%\\findstr.exe' OR SourceImage ILIKE '%\\forfiles.exe' OR SourceImage ILIKE '%\\gpupdate.exe' OR SourceImage ILIKE '%\\hh.exe' OR SourceImage ILIKE '%\\installutil.exe' OR SourceImage ILIKE '%\\lync.exe' OR SourceImage ILIKE '%\\makecab.exe' OR SourceImage ILIKE '%\\mDNSResponder.exe' OR SourceImage ILIKE '%\\monitoringhost.exe' OR SourceImage ILIKE '%\\msbuild.exe' OR SourceImage ILIKE '%\\mshta.exe' OR SourceImage ILIKE '%\\mspaint.exe' OR SourceImage ILIKE '%\\outlook.exe' OR SourceImage ILIKE '%\\ping.exe' OR SourceImage ILIKE '%\\provtool.exe' OR SourceImage ILIKE '%\\python.exe' OR SourceImage ILIKE '%\\regsvr32.exe' OR SourceImage ILIKE '%\\robocopy.exe' OR SourceImage ILIKE '%\\runonce.exe' OR SourceImage ILIKE '%\\sapcimc.exe' OR SourceImage ILIKE '%\\smartscreen.exe' OR SourceImage ILIKE '%\\spoolsv.exe' OR SourceImage ILIKE '%\\tstheme.exe' OR SourceImage ILIKE '%\\userinit.exe' OR SourceImage ILIKE '%\\vssadmin.exe' OR SourceImage ILIKE '%\\vssvc.exe' OR SourceImage ILIKE '%\\w3wp.exe' OR SourceImage ILIKE '%\\winscp.exe' OR SourceImage ILIKE '%\\winword.exe' OR SourceImage ILIKE '%\\wmic.exe' OR SourceImage ILIKE '%\\wscript.exe')) AND NOT ((((SourceImage = 'C:\\Windows\\System32\\Defrag.exe' OR SourceImage = 'C:\\Windows\\System32\\makecab.exe') AND TargetImage = 'C:\\Windows\\System32\\conhost.exe') OR ((SourceImage ILIKE 'C:\\Program Files\\Microsoft Office\\%' OR SourceImage ILIKE 'C:\\Program Files (x86)\\Microsoft Office\\%') AND TargetImage = 'System') OR (SourceImage = 'C:\\Windows\\System32\\provtool.exe' AND TargetImage = 'C:\\Windows\\System32\\svchost.exe') OR (SourceImage = 'C:\\Windows\\System32\\provtool.exe' AND TargetImage = 'System') OR (SourceImage = 'C:\\Windows\\System32\\userinit.exe' AND TargetImage = 'C:\\Windows\\explorer.exe') OR (SourceImage ILIKE '%\\WINWORD.EXE' AND (TargetImage ILIKE 'C:\\Program Files (x86)\\%' OR TargetImage ILIKE 'C:\\Program Files\\%')))) AND NOT ((SourceImage ILIKE '%\\SysWOW64\\explorer.exe' AND (TargetImage = 'C:\\Program Files (x86)\\VMware\\VMware Tools\\vmtoolsd.exe' OR TargetImage = 'C:\\Program Files\\VMware\\VMware Tools\\vmtoolsd.exe'))))
