-- Title: Invoke-Obfuscation Obfuscated IEX Invocation - PowerShell
-- ID: 1b9dc62e-6e9e-42a3-8990-94d7a10007f7
-- Status: test
-- Level: high
-- Author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
-- Date: 2019-11-08
-- Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
-- Description: Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the following code block \u2014
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE ((REGEXP_LIKE(ScriptBlockText, '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\[')) OR (REGEXP_LIKE(ScriptBlockText, '\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\[')) OR (REGEXP_LIKE(ScriptBlockText, '\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\[')) OR (REGEXP_LIKE(ScriptBlockText, '\$env:ComSpec\[(\s*\d{1,3}\s*,){2}')) OR (REGEXP_LIKE(ScriptBlockText, '\*mdr\*\W\s*\)\.Name')) OR (REGEXP_LIKE(ScriptBlockText, '\$VerbosePreference\.ToString\(')))
