-- Title: PowerView PowerShell Cmdlets - ScriptBlock
-- ID: dcd74b95-3f36-4ed9-9598-0490951643aa
-- Status: test
-- Level: high
-- Author: Bhabesh Raj
-- Date: 2021-05-18
-- Tags: attack.execution, attack.t1059.001
-- Description: Detects Cmdlet names from PowerView of the PowerSploit exploitation framework.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE ((ScriptBlockText ILIKE '%Export-PowerViewCSV%' OR ScriptBlockText ILIKE '%Find-DomainLocalGroupMember%' OR ScriptBlockText ILIKE '%Find-DomainObjectPropertyOutlier%' OR ScriptBlockText ILIKE '%Find-DomainProcess%' OR ScriptBlockText ILIKE '%Find-DomainShare%' OR ScriptBlockText ILIKE '%Find-DomainUserEvent%' OR ScriptBlockText ILIKE '%Find-DomainUserLocation%' OR ScriptBlockText ILIKE '%Find-ForeignGroup%' OR ScriptBlockText ILIKE '%Find-ForeignUser%' OR ScriptBlockText ILIKE '%Find-GPOComputerAdmin%' OR ScriptBlockText ILIKE '%Find-GPOLocation%' OR ScriptBlockText ILIKE '%Find-InterestingDomain%' OR ScriptBlockText ILIKE '%Find-InterestingFile%' OR ScriptBlockText ILIKE '%Find-LocalAdminAccess%' OR ScriptBlockText ILIKE '%Find-ManagedSecurityGroups%' OR ScriptBlockText ILIKE '%Get-CachedRDPConnection%' OR ScriptBlockText ILIKE '%Get-DFSshare%' OR ScriptBlockText ILIKE '%Get-DomainDFSShare%' OR ScriptBlockText ILIKE '%Get-DomainDNSRecord%' OR ScriptBlockText ILIKE '%Get-DomainDNSZone%' OR ScriptBlockText ILIKE '%Get-DomainFileServer%' OR ScriptBlockText ILIKE '%Get-DomainGPOComputerLocalGroupMapping%' OR ScriptBlockText ILIKE '%Get-DomainGPOLocalGroup%' OR ScriptBlockText ILIKE '%Get-DomainGPOUserLocalGroupMapping%' OR ScriptBlockText ILIKE '%Get-LastLoggedOn%' OR ScriptBlockText ILIKE '%Get-LoggedOnLocal%' OR ScriptBlockText ILIKE '%Get-NetFileServer%' OR ScriptBlockText ILIKE '%Get-NetForest%' OR ScriptBlockText ILIKE '%Get-NetGPOGroup%' OR ScriptBlockText ILIKE '%Get-NetProcess%' OR ScriptBlockText ILIKE '%Get-NetRDPSession%' OR ScriptBlockText ILIKE '%Get-RegistryMountedDrive%' OR ScriptBlockText ILIKE '%Get-RegLoggedOn%' OR ScriptBlockText ILIKE '%Get-WMIRegCachedRDPConnection%' OR ScriptBlockText ILIKE '%Get-WMIRegLastLoggedOn%' OR ScriptBlockText ILIKE '%Get-WMIRegMountedDrive%' OR ScriptBlockText ILIKE '%Get-WMIRegProxy%' OR ScriptBlockText ILIKE '%Invoke-ACLScanner%' OR ScriptBlockText ILIKE '%Invoke-CheckLocalAdminAccess%' OR ScriptBlockText ILIKE '%Invoke-EnumerateLocalAdmin%' OR ScriptBlockText ILIKE '%Invoke-EventHunter%' OR ScriptBlockText ILIKE '%Invoke-FileFinder%' OR ScriptBlockText ILIKE '%Invoke-Kerberoast%' OR ScriptBlockText ILIKE '%Invoke-MapDomainTrust%' OR ScriptBlockText ILIKE '%Invoke-ProcessHunter%' OR ScriptBlockText ILIKE '%Invoke-RevertToSelf%' OR ScriptBlockText ILIKE '%Invoke-ShareFinder%' OR ScriptBlockText ILIKE '%Invoke-UserHunter%' OR ScriptBlockText ILIKE '%Invoke-UserImpersonation%' OR ScriptBlockText ILIKE '%Remove-RemoteConnection%' OR ScriptBlockText ILIKE '%Request-SPNTicket%' OR ScriptBlockText ILIKE '%Resolve-IPAddress%'))
