-- Title: PUA - PingCastle Execution From Potentially Suspicious Parent
-- ID: b37998de-a70b-4f33-b219-ec36bf433dc0
-- Status: test
-- Level: high
-- Author: Nasreddine Bencherchali (Nextron Systems), X__Junior (Nextron Systems)
-- Date: 2024-01-11
-- Tags: attack.reconnaissance, attack.t1595
-- Description: Detects the execution of PingCastle, a tool designed to quickly assess the Active Directory security level via a script located in a potentially suspicious or uncommon location.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE ((((ParentCommandLine ILIKE '%.bat%' OR ParentCommandLine ILIKE '%.chm%' OR ParentCommandLine ILIKE '%.cmd%' OR ParentCommandLine ILIKE '%.hta%' OR ParentCommandLine ILIKE '%.htm%' OR ParentCommandLine ILIKE '%.html%' OR ParentCommandLine ILIKE '%.js%' OR ParentCommandLine ILIKE '%.lnk%' OR ParentCommandLine ILIKE '%.ps1%' OR ParentCommandLine ILIKE '%.vbe%' OR ParentCommandLine ILIKE '%.vbs%' OR ParentCommandLine ILIKE '%.wsf%')) OR ((ParentCommandLine ILIKE '%:\\Perflogs\\%' OR ParentCommandLine ILIKE '%:\\Temp\\%' OR ParentCommandLine ILIKE '%:\\Users\\Public\\%' OR ParentCommandLine ILIKE '%:\\Windows\\Temp\\%' OR ParentCommandLine ILIKE '%\\AppData\\Local\\Temp%' OR ParentCommandLine ILIKE '%\\AppData\\Roaming\\%' OR ParentCommandLine ILIKE '%\\Temporary Internet%')) OR (((ParentCommandLine ILIKE '%:\\Users\\%' AND ParentCommandLine ILIKE '%\\Favorites\\%')) OR ((ParentCommandLine ILIKE '%:\\Users\\%' AND ParentCommandLine ILIKE '%\\Favourites\\%')) OR ((ParentCommandLine ILIKE '%:\\Users\\%' AND ParentCommandLine ILIKE '%\\Contacts\\%')))) AND ((ParentCommandLine ILIKE '%.bat%' OR ParentCommandLine ILIKE '%.chm%' OR ParentCommandLine ILIKE '%.cmd%' OR ParentCommandLine ILIKE '%.hta%' OR ParentCommandLine ILIKE '%.htm%' OR ParentCommandLine ILIKE '%.html%' OR ParentCommandLine ILIKE '%.js%' OR ParentCommandLine ILIKE '%.lnk%' OR ParentCommandLine ILIKE '%.ps1%' OR ParentCommandLine ILIKE '%.vbe%' OR ParentCommandLine ILIKE '%.vbs%' OR ParentCommandLine ILIKE '%.wsf%')) AND ((Image ILIKE '%\\PingCastle.exe') OR (OriginalFileName = 'PingCastle.exe') OR (Product = 'Ping Castle') OR ((CommandLine ILIKE '%--scanner aclcheck%' OR CommandLine ILIKE '%--scanner antivirus%' OR CommandLine ILIKE '%--scanner computerversion%' OR CommandLine ILIKE '%--scanner foreignusers%' OR CommandLine ILIKE '%--scanner laps_bitlocker%' OR CommandLine ILIKE '%--scanner localadmin%' OR CommandLine ILIKE '%--scanner nullsession%' OR CommandLine ILIKE '%--scanner nullsession-trust%' OR CommandLine ILIKE '%--scanner oxidbindings%' OR CommandLine ILIKE '%--scanner remote%' OR CommandLine ILIKE '%--scanner share%' OR CommandLine ILIKE '%--scanner smb%' OR CommandLine ILIKE '%--scanner smb3querynetwork%' OR CommandLine ILIKE '%--scanner spooler%' OR CommandLine ILIKE '%--scanner startup%' OR CommandLine ILIKE '%--scanner zerologon%')) OR (CommandLine ILIKE '%--no-enum-limit%') OR ((CommandLine ILIKE '%--healthcheck%' AND CommandLine ILIKE '%--level Full%')) OR ((CommandLine ILIKE '%--healthcheck%' AND CommandLine ILIKE '%--server %'))))
