-- Title: Suspicious Browser Child Process - MacOS
-- ID: 0250638a-2b28-4541-86fc-ea4c558fa0c6
-- Status: test
-- Level: medium
-- Author: Sohan G (D4rkCiph3r)
-- Date: 2023-04-05
-- Tags: attack.initial-access, attack.execution, attack.t1189, attack.t1203, attack.t1059
-- Description: Detects suspicious child processes spawned from browsers. This could be a result of a potential web browser exploitation.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE (((ParentImage ILIKE '%com.apple.WebKit.WebContent%' OR ParentImage ILIKE '%firefox%' OR ParentImage ILIKE '%Google Chrome Helper%' OR ParentImage ILIKE '%Google Chrome%' OR ParentImage ILIKE '%Microsoft Edge%' OR ParentImage ILIKE '%Opera%' OR ParentImage ILIKE '%Safari%' OR ParentImage ILIKE '%Tor Browser%') AND (Image ILIKE '%/bash' OR Image ILIKE '%/curl' OR Image ILIKE '%/dash' OR Image ILIKE '%/ksh' OR Image ILIKE '%/osascript' OR Image ILIKE '%/perl' OR Image ILIKE '%/php' OR Image ILIKE '%/pwsh' OR Image ILIKE '%/python' OR Image ILIKE '%/sh' OR Image ILIKE '%/tcsh' OR Image ILIKE '%/wget' OR Image ILIKE '%/zsh')) AND NOT ((((ParentImage ILIKE '%Google Chrome Helper%' OR ParentImage ILIKE '%Google Chrome%') AND (CommandLine ILIKE '%/Volumes/Google Chrome/Google Chrome.app/Contents/Frameworks/*/Resources/install.sh%' OR CommandLine ILIKE '%/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/*/Resources/keystone_promote_preflight.sh%' OR CommandLine ILIKE '%/Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/*/Resources/keystone_promote_postflight.sh%')) OR ((ParentImage ILIKE '%Google Chrome Helper%' OR ParentImage ILIKE '%Google Chrome%') AND (CommandLine ILIKE '%/Users/%' AND CommandLine ILIKE '%/Library/Application Support/Google/Chrome/recovery/%' AND CommandLine ILIKE '%/ChromeRecovery%')) OR (CommandLine ILIKE '%--defaults-torrc%') OR (CommandLine ILIKE '%/Library/Application Support/Microsoft/MAU*/Microsoft AutoUpdate.app/Contents/MacOS/msupdate%') OR (ParentImage ILIKE '%Microsoft Edge%' AND (CommandLine ILIKE '%IOPlatformExpertDevice%' OR CommandLine ILIKE '%hw.model%')))) AND NOT (((CommandLine = '') OR (CommandLine IS NULL))))
