-- Title: Suspicious Microsoft Office Child Process
-- ID: 438025f9-5856-4663-83f7-52f878a70a50
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), Markus Neis, FPT.EagleEye Team, Vadim Khrykov, Cyb3rEng, Michael Haag, Christopher Peacock @securepeacock, @scythe_io
-- Date: 2018-04-06
-- Tags: attack.execution, attack.stealth, attack.t1047, attack.t1204.002, attack.t1218.010
-- Description: Detects a suspicious process spawning from one of the Microsoft Office suite products (Word, Excel, PowerPoint, Publisher, Visio, etc.)
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE (((ParentImage ILIKE '%\\EQNEDT32.EXE' OR ParentImage ILIKE '%\\EXCEL.EXE' OR ParentImage ILIKE '%\\MSACCESS.EXE' OR ParentImage ILIKE '%\\MSPUB.exe' OR ParentImage ILIKE '%\\ONENOTE.EXE' OR ParentImage ILIKE '%\\POWERPNT.exe' OR ParentImage ILIKE '%\\VISIO.exe' OR ParentImage ILIKE '%\\WINWORD.EXE' OR ParentImage ILIKE '%\\wordpad.exe' OR ParentImage ILIKE '%\\wordview.exe')) AND ((((OriginalFileName = 'bitsadmin.exe' OR OriginalFileName = 'CertOC.exe' OR OriginalFileName = 'CertUtil.exe' OR OriginalFileName = 'Cmd.Exe' OR OriginalFileName = 'CMSTP.EXE' OR OriginalFileName = 'cscript.exe' OR OriginalFileName = 'curl.exe' OR OriginalFileName = 'HH.exe' OR OriginalFileName = 'IEExec.exe' OR OriginalFileName = 'InstallUtil.exe' OR OriginalFileName = 'javaw.exe' OR OriginalFileName = 'Microsoft.Workflow.Compiler.exe' OR OriginalFileName = 'msdt.exe' OR OriginalFileName = 'MSHTA.EXE' OR OriginalFileName = 'msiexec.exe' OR OriginalFileName = 'Msxsl.exe' OR OriginalFileName = 'odbcconf.exe' OR OriginalFileName = 'pcalua.exe' OR OriginalFileName = 'PowerShell.EXE' OR OriginalFileName = 'RegAsm.exe' OR OriginalFileName = 'RegSvcs.exe' OR OriginalFileName = 'REGSVR32.exe' OR OriginalFileName = 'RUNDLL32.exe' OR OriginalFileName = 'schtasks.exe' OR OriginalFileName = 'ScriptRunner.exe' OR OriginalFileName = 'wmic.exe' OR OriginalFileName = 'WorkFolders.exe' OR OriginalFileName = 'wscript.exe')) OR ((Image ILIKE '%\\AppVLP.exe' OR Image ILIKE '%\\bash.exe' OR Image ILIKE '%\\bitsadmin.exe' OR Image ILIKE '%\\certoc.exe' OR Image ILIKE '%\\certutil.exe' OR Image ILIKE '%\\cmd.exe' OR Image ILIKE '%\\cmstp.exe' OR Image ILIKE '%\\control.exe' OR Image ILIKE '%\\cscript.exe' OR Image ILIKE '%\\curl.exe' OR Image ILIKE '%\\forfiles.exe' OR Image ILIKE '%\\hh.exe' OR Image ILIKE '%\\ieexec.exe' OR Image ILIKE '%\\installutil.exe' OR Image ILIKE '%\\javaw.exe' OR Image ILIKE '%\\mftrace.exe' OR Image ILIKE '%\\Microsoft.Workflow.Compiler.exe' OR Image ILIKE '%\\msbuild.exe' OR Image ILIKE '%\\msdt.exe' OR Image ILIKE '%\\mshta.exe' OR Image ILIKE '%\\msidb.exe' OR Image ILIKE '%\\msiexec.exe' OR Image ILIKE '%\\msxsl.exe' OR Image ILIKE '%\\odbcconf.exe' OR Image ILIKE '%\\pcalua.exe' OR Image ILIKE '%\\powershell.exe' OR Image ILIKE '%\\pwsh.exe' OR Image ILIKE '%\\regasm.exe' OR Image ILIKE '%\\regsvcs.exe' OR Image ILIKE '%\\regsvr32.exe' OR Image ILIKE '%\\rundll32.exe' OR Image ILIKE '%\\schtasks.exe' OR Image ILIKE '%\\scrcons.exe' OR Image ILIKE '%\\scriptrunner.exe' OR Image ILIKE '%\\sh.exe' OR Image ILIKE '%\\svchost.exe' OR Image ILIKE '%\\verclsid.exe' OR Image ILIKE '%\\wmic.exe' OR Image ILIKE '%\\workfolders.exe' OR Image ILIKE '%\\wscript.exe'))) OR ((Image ILIKE '%\\AppData\\%' OR Image ILIKE '%\\Users\\Public\\%' OR Image ILIKE '%\\ProgramData\\%' OR Image ILIKE '%\\Windows\\Tasks\\%' OR Image ILIKE '%\\Windows\\Temp\\%' OR Image ILIKE '%\\Windows\\System32\\Tasks\\%'))))
