-- Title: System File Execution Location Anomaly
-- ID: e4a6b256-3e47-40fc-89d2-7a477edd6915
-- Status: test
-- Level: high
-- Author: Florian Roth (Nextron Systems), Patrick Bareiss, Anton Kutepov, oscd.community, Nasreddine Bencherchali (Nextron Systems)
-- Date: 2017-11-27
-- Tags: attack.stealth, attack.t1036
-- Description: Detects the execution of a Windows system binary that is usually located in the system folder from an uncommon location.
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE (((Image ILIKE '%\\atbroker.exe' OR Image ILIKE '%\\audiodg.exe' OR Image ILIKE '%\\bcdedit.exe' OR Image ILIKE '%\\bitsadmin.exe' OR Image ILIKE '%\\certreq.exe' OR Image ILIKE '%\\certutil.exe' OR Image ILIKE '%\\cmstp.exe' OR Image ILIKE '%\\conhost.exe' OR Image ILIKE '%\\consent.exe' OR Image ILIKE '%\\cscript.exe' OR Image ILIKE '%\\csrss.exe' OR Image ILIKE '%\\dashost.exe' OR Image ILIKE '%\\defrag.exe' OR Image ILIKE '%\\dfrgui.exe' OR Image ILIKE '%\\dism.exe' OR Image ILIKE '%\\dllhost.exe' OR Image ILIKE '%\\dllhst3g.exe' OR Image ILIKE '%\\dwm.exe' OR Image ILIKE '%\\eventvwr.exe' OR Image ILIKE '%\\fsquirt.exe' OR Image ILIKE '%\\finger.exe' OR Image ILIKE '%\\logonui.exe' OR Image ILIKE '%\\LsaIso.exe' OR Image ILIKE '%\\lsass.exe' OR Image ILIKE '%\\lsm.exe' OR Image ILIKE '%\\msiexec.exe' OR Image ILIKE '%\\ntoskrnl.exe' OR Image ILIKE '%\\powershell_ise.exe' OR Image ILIKE '%\\powershell.exe' OR Image ILIKE '%\\pwsh.exe' OR Image ILIKE '%\\regsvr32.exe' OR Image ILIKE '%\\rundll32.exe' OR Image ILIKE '%\\runonce.exe' OR Image ILIKE '%\\RuntimeBroker.exe' OR Image ILIKE '%\\schtasks.exe' OR Image ILIKE '%\\services.exe' OR Image ILIKE '%\\sihost.exe' OR Image ILIKE '%\\smartscreen.exe' OR Image ILIKE '%\\smss.exe' OR Image ILIKE '%\\spoolsv.exe' OR Image ILIKE '%\\svchost.exe' OR Image ILIKE '%\\taskhost.exe' OR Image ILIKE '%\\taskhostw.exe' OR Image ILIKE '%\\Taskmgr.exe' OR Image ILIKE '%\\userinit.exe' OR Image ILIKE '%\\werfault.exe' OR Image ILIKE '%\\werfaultsecure.exe' OR Image ILIKE '%\\wininit.exe' OR Image ILIKE '%\\winlogon.exe' OR Image ILIKE '%\\winver.exe' OR Image ILIKE '%\\wlanext.exe' OR Image ILIKE '%\\wmic.exe' OR Image ILIKE '%\\wscript.exe' OR Image ILIKE '%\\wsl.exe' OR Image ILIKE '%\\wsmprovhost.exe')) AND NOT ((((Image ILIKE 'C:\\$WINDOWS.~BT\\%' OR Image ILIKE 'C:\\$WinREAgent\\%' OR Image ILIKE 'C:\\Windows\\SoftwareDistribution\\%' OR Image ILIKE 'C:\\Windows\\System32\\%' OR Image ILIKE 'C:\\Windows\\SystemTemp\\%' OR Image ILIKE 'C:\\Windows\\SysWOW64\\%' OR Image ILIKE 'C:\\Windows\\uus\\%' OR Image ILIKE 'C:\\Windows\\WinSxS\\%')) OR ((Image ILIKE '%C:\\Program Files\\PowerShell\\7\\%' OR Image ILIKE '%C:\\Program Files\\PowerShell\\7-preview\\%' OR Image ILIKE '%C:\\Program Files\\WindowsApps\\Microsoft.PowerShellPreview%' OR Image ILIKE '%\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShellPreview%') AND Image ILIKE '%\\pwsh.exe') OR (Image ILIKE 'C:\\Users\\%' AND Image ILIKE '%\\AppData\\Local\\Microsoft\\WindowsApps\\%' AND Image ILIKE '%\\wsl.exe') OR ((Image ILIKE 'C:\\Program Files\\WindowsApps\\MicrosoftCorporationII.WindowsSubsystemForLinux%' OR Image ILIKE 'C:\\Program Files\\WSL\\%') AND Image ILIKE '%\\wsl.exe'))) AND NOT ((Image ILIKE '%\\SystemRoot\\System32\\%')))
