-- Title: Malicious Base64 Encoded PowerShell Keywords in Command Lines
-- ID: f26c6093-6f14-4b12-800f-0fcb46f5ffd0
-- Status: test
-- Level: high
-- Author: John Lambert (rule)
-- Date: 2019-01-16
-- Tags: attack.execution, attack.t1059.001
-- Description: Detects base64 encoded strings used in hidden malicious PowerShell command lines
-- Converted by: Sigma Universal SIEM/EDR CLI

SELECT * FROM process_journal WHERE (((CommandLine ILIKE '%AGkAdABzAGEAZABtAGkAbgAgAC8AdAByAGEAbgBzAGYAZQByA%' OR CommandLine ILIKE '%aXRzYWRtaW4gL3RyYW5zZmVy%' OR CommandLine ILIKE '%IAaQB0AHMAYQBkAG0AaQBuACAALwB0AHIAYQBuAHMAZgBlAHIA%' OR CommandLine ILIKE '%JpdHNhZG1pbiAvdHJhbnNmZX%' OR CommandLine ILIKE '%YgBpAHQAcwBhAGQAbQBpAG4AIAAvAHQAcgBhAG4AcwBmAGUAcg%' OR CommandLine ILIKE '%Yml0c2FkbWluIC90cmFuc2Zlc%' OR CommandLine ILIKE '%AGMAaAB1AG4AawBfAHMAaQB6AGUA%' OR CommandLine ILIKE '%JABjAGgAdQBuAGsAXwBzAGkAegBlA%' OR CommandLine ILIKE '%JGNodW5rX3Npem%' OR CommandLine ILIKE '%QAYwBoAHUAbgBrAF8AcwBpAHoAZQ%' OR CommandLine ILIKE '%RjaHVua19zaXpl%' OR CommandLine ILIKE '%Y2h1bmtfc2l6Z%' OR CommandLine ILIKE '%AE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4A%' OR CommandLine ILIKE '%kATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8Abg%' OR CommandLine ILIKE '%lPLkNvbXByZXNzaW9u%' OR CommandLine ILIKE '%SQBPAC4AQwBvAG0AcAByAGUAcwBzAGkAbwBuA%' OR CommandLine ILIKE '%SU8uQ29tcHJlc3Npb2%' OR CommandLine ILIKE '%Ty5Db21wcmVzc2lvb%' OR CommandLine ILIKE '%AE8ALgBNAGUAbQBvAHIAeQBTAHQAcgBlAGEAbQ%' OR CommandLine ILIKE '%kATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtA%' OR CommandLine ILIKE '%lPLk1lbW9yeVN0cmVhb%' OR CommandLine ILIKE '%SQBPAC4ATQBlAG0AbwByAHkAUwB0AHIAZQBhAG0A%' OR CommandLine ILIKE '%SU8uTWVtb3J5U3RyZWFt%' OR CommandLine ILIKE '%Ty5NZW1vcnlTdHJlYW%' OR CommandLine ILIKE '%4ARwBlAHQAQwBoAHUAbgBrA%' OR CommandLine ILIKE '%5HZXRDaHVua%' OR CommandLine ILIKE '%AEcAZQB0AEMAaAB1AG4Aaw%' OR CommandLine ILIKE '%LgBHAGUAdABDAGgAdQBuAGsA%' OR CommandLine ILIKE '%LkdldENodW5r%' OR CommandLine ILIKE '%R2V0Q2h1bm%' OR CommandLine ILIKE '%AEgAUgBFAEEARABfAEkATgBGAE8ANgA0A%' OR CommandLine ILIKE '%QASABSAEUAQQBEAF8ASQBOAEYATwA2ADQA%' OR CommandLine ILIKE '%RIUkVBRF9JTkZPNj%' OR CommandLine ILIKE '%SFJFQURfSU5GTzY0%' OR CommandLine ILIKE '%VABIAFIARQBBAEQAXwBJAE4ARgBPADYANA%' OR CommandLine ILIKE '%VEhSRUFEX0lORk82N%' OR CommandLine ILIKE '%AHIAZQBhAHQAZQBSAGUAbQBvAHQAZQBUAGgAcgBlAGEAZA%' OR CommandLine ILIKE '%cmVhdGVSZW1vdGVUaHJlYW%' OR CommandLine ILIKE '%MAcgBlAGEAdABlAFIAZQBtAG8AdABlAFQAaAByAGUAYQBkA%' OR CommandLine ILIKE '%NyZWF0ZVJlbW90ZVRocmVhZ%' OR CommandLine ILIKE '%Q3JlYXRlUmVtb3RlVGhyZWFk%' OR CommandLine ILIKE '%QwByAGUAYQB0AGUAUgBlAG0AbwB0AGUAVABoAHIAZQBhAGQA%' OR CommandLine ILIKE '%0AZQBtAG0AbwB2AGUA%' OR CommandLine ILIKE '%1lbW1vdm%' OR CommandLine ILIKE '%AGUAbQBtAG8AdgBlA%' OR CommandLine ILIKE '%bQBlAG0AbQBvAHYAZQ%' OR CommandLine ILIKE '%bWVtbW92Z%' OR CommandLine ILIKE '%ZW1tb3Zl%')) AND (CommandLine ILIKE '% hidden %') AND (((Image ILIKE '%\\powershell.exe' OR Image ILIKE '%\\pwsh.exe')) OR ((OriginalFileName = 'PowerShell.EXE' OR OriginalFileName = 'pwsh.dll'))))
