# Title: AWS Config Disabling Channel/Recorder
# ID: 07330162-dba1-4746-8121-a9647d49d297
# Status: test
# Level: high
# Author: vitaliy0x1
# Date: 2020-01-21
# Tags: attack.defense-impairment, attack.t1685.002
# Description: Detects AWS Config Service disabling
# Converted by: Sigma Universal SIEM/EDR CLI

# LimaCharlie Detection & Response Rule
# Name: AWS Config Disabling Channel/Recorder
detect:
  event: NEW_PROCESS
  op: and
  rules:
    # Filter logic:
    # (eventSource="config.amazonaws.com" AND (eventName="DeleteDeliveryChannel" OR eventName="StopConfigurationRecorder"))
respond:
  - action: report
    name: AWS Config Disabling Channel/Recorder

