# Title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - Security
# ID: 4c54ba8f-73d2-4d40-8890-d9cf1dca3d30
# Status: test
# Level: high
# Author: Timur Zinniatullin, oscd.community
# Date: 2020-10-13
# Tags: attack.stealth, attack.t1027, attack.execution, attack.t1059.001
# Description: Detects Obfuscated Powershell via VAR++ LAUNCHER
# Converted by: Sigma Universal SIEM/EDR CLI

# LimaCharlie Detection & Response Rule
# Name: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - Security
detect:
  event: NEW_PROCESS
  op: and
  rules:
    # Filter logic:
    # (EventID="4697" AND (ServiceFileName="*&&set*" AND ServiceFileName="*cmd*" AND ServiceFileName="*/c*" AND ServiceFileName="*-f*") AND (ServiceFileName="*{0}*" OR ServiceFileName="*{1}*" OR ServiceFileName="*{2}*" OR ServiceFileName="*{3}*" OR ServiceFileName="*{4}*" OR ServiceFileName="*{5}*"))
respond:
  - action: report
    name: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - Security

