# Title: Application Uninstalled
# ID: 570ae5ec-33dc-427c-b815-db86228ad43e
# Status: test
# Level: low
# Author: frack113
# Date: 2022-01-28
# Tags: attack.impact, attack.t1489
# Description: An application has been removed. Check if it is critical.
# Converted by: Sigma Universal SIEM/EDR CLI

# LimaCharlie Detection & Response Rule
# Name: Application Uninstalled
detect:
  event: NEW_PROCESS
  op: and
  rules:
    # Filter logic:
    # (Provider_Name="MsiInstaller" AND (EventID="1034" OR EventID="11724"))
respond:
  - action: report
    name: Application Uninstalled

